begin;
select plan(8);
select ok((select count(*)=0 from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace where con.contype='f' and n.nspname='public' and not exists(select 1 from pg_index i where i.indrelid=con.conrelid and i.indpred is null and i.indexprs is null and (select array_agg(x.attnum order by x.ord) from unnest(i.indkey) with ordinality x(attnum,ord) where x.ord<=array_length(con.conkey,1))=con.conkey)),'all public foreign keys are indexed');
select ok((select count(*)=0 from pg_publication_tables where pubname='supabase_realtime' and tablename in('chat_messages','chat_message_receipts','chat_message_reactions','chat_conversation_members') ) is false,'chat tables are present in realtime publication');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename in('chat_messages','chat_message_receipts','chat_message_user_states','chat_user_focus','operational_reminders','push_subscriptions','notification_preferences','reminder_deliveries','ai_operator_commands') and (qual like '%auth.uid()%' or with_check like '%auth.uid()%') and qual not like '%( SELECT auth.uid()%' and with_check not like '%( SELECT auth.uid()%'),'target RLS policies are initplan wrapped');
select ok((select count(*)=0 from pg_policies p where p.schemaname='public' and p.policyname like 'owner_console%'),'owner_console overlay policies removed from public tables');
select ok((select count(*)=0 from (select tablename,cmd,roles,count(*) n from pg_policies where schemaname='public' and permissive='PERMISSIVE' group by tablename,cmd,roles having count(*)>1) x),'no duplicate permissive policy groups remain');
select ok((select count(*)=0 from pg_policies where schemaname='realtime' and tablename='messages' and policyname in('chat_realtime_select','chat_realtime_insert')) is false,'realtime authorization policies exist');
select has_function('public','claim_chat_notification_outbox','chat push claim RPC exists');
select has_function('public','crm_sales_funnel','CRM funnel RPC exists');
select * from finish();
rollback;
