export type JalaliDate = { year:number; month:number; day:number };
export const JALALI_MONTHS=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'] as const;
export const WEEK_DAYS=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'] as const;
const PERSIAN_DIGITS='۰۱۲۳۴۵۶۷۸۹'; const ARABIC_DIGITS='٠١٢٣٤٥٦٧٨٩'; const TZ='Asia/Tehran';
const calendarFormatter=new Intl.DateTimeFormat('en-US-u-ca-persian',{timeZone:'UTC',year:'numeric',month:'numeric',day:'numeric'});
const dateFormatter=new Intl.DateTimeFormat('fa-IR-u-ca-persian',{timeZone:TZ,year:'numeric',month:'long',day:'numeric',weekday:'long'});
const timeFormatter=new Intl.DateTimeFormat('fa-IR',{timeZone:TZ,hour:'2-digit',minute:'2-digit'});
const parts=(date:Date)=>{const p=calendarFormatter.formatToParts(date);const get=(t:string)=>Number(p.find(x=>x.type===t)?.value??0);return {year:get('year'),month:get('month'),day:get('day')} as JalaliDate;};
export const normalizeDigits=(value:string)=>value.replace(/[۰-۹]/g,c=>String(PERSIAN_DIGITS.indexOf(c))).replace(/[٠-٩]/g,c=>String(ARABIC_DIGITS.indexOf(c)));
export const normalizeFaText=(value:string)=>normalizeDigits(value).normalize('NFKC').replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[\u200c\u200d]+/g,'‌').replace(/\s+/g,' ').trim();
function findGregorian(target:JalaliDate){let lo=Date.UTC(target.year+620,0,1),hi=Date.UTC(target.year+623,11,31);const key=target.year*10000+target.month*100+target.day;for(let i=0;i<22&&lo<=hi;i++){const mid=lo+Math.floor((hi-lo)/2);const j=parts(new Date(mid));const k=j.year*10000+j.month*100+j.day;if(k<key)lo=mid+86400000;else hi=mid-86400000;}for(let ts=Math.max(Date.UTC(target.year+620,0,1),lo-86400000);ts<=Math.min(Date.UTC(target.year+623,11,31),hi+2*86400000);ts+=86400000){const d=new Date(ts),j=parts(d);if(j.year===target.year&&j.month===target.month&&j.day===target.day)return {gy:d.getUTCFullYear(),gm:d.getUTCMonth()+1,gd:d.getUTCDate()};}throw new RangeError('تاریخ جلالی خارج از محدوده است');}
export function isJalaliLeap(year:number){if(!Number.isInteger(year)||year<1||year>3176)throw new RangeError('سال جلالی نامعتبر است');const a=findGregorian({year,month:1,day:1}),b=findGregorian({year:year+1,month:1,day:1});return (Date.UTC(b.gy,b.gm-1,b.gd)-Date.UTC(a.gy,a.gm-1,a.gd))/86400000===366;}
export function jalaliMonthLength(year:number,month:number){if(!Number.isInteger(year)||month<1||month>12)throw new RangeError('ماه جلالی نامعتبر است');if(month<=6)return 31;if(month<=11)return 30;return isJalaliLeap(year)?30:29;}
export function toJalali(date:Date):JalaliDate{return parts(date);}
export function toGregorian(year:number,month:number,day:number){if(!Number.isInteger(year)||!Number.isInteger(month)||!Number.isInteger(day)||year<1||year>3177||month<1||month>12||day<1||day>jalaliMonthLength(year,month))throw new RangeError('تاریخ جلالی نامعتبر است');return findGregorian({year,month,day});}
function tzOffsetMinutes(ts:number,timeZone:string){const f=new Intl.DateTimeFormat('en-US',{timeZone,hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).formatToParts(new Date(ts));const get=(t:string)=>Number(f.find(x=>x.type===t)?.value??0);return (Date.UTC(get('year'),get('month')-1,get('day'),get('hour'),get('minute'),get('second'))-ts)/60000;}
export function zonedJalaliToDate(year:number,month:number,day:number,hour=0,minute=0,second=0,timeZone=TZ){const g=toGregorian(year,month,day);const guess=Date.UTC(g.gy,g.gm-1,g.gd,hour,minute,second);const a=tzOffsetMinutes(guess,timeZone);let ts=guess-a*60000;const b=tzOffsetMinutes(ts,timeZone);if(a!==b)ts=guess-b*60000;return new Date(ts);}
export function addJalaliDays(date:Date,days:number,timeZone=TZ){const j=toJalali(date),g=toGregorian(j.year,j.month,j.day);const d=new Date(Date.UTC(g.gy,g.gm-1,g.gd)+days*86400000);const j2=toJalali(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),12)));const p=new Intl.DateTimeFormat('en-US',{timeZone,hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}).formatToParts(date);const get=(t:string)=>Number(p.find(x=>x.type===t)?.value??0);return zonedJalaliToDate(j2.year,j2.month,j2.day,get('hour'),get('minute'),get('second'),timeZone);}
export function formatJalali(date:Date){return dateFormatter.format(date);}
export function formatJalaliTime(date:Date){return timeFormatter.format(date);}
export function formatJalaliDateTime(date:Date){return formatJalali(date)+' · '+formatJalaliTime(date);}
export function jalaliWeekday(date:Date){const j=toJalali(date),g=toGregorian(j.year,j.month,j.day);return (new Date(Date.UTC(g.gy,g.gm-1,g.gd)).getUTCDay()+1)%7;}
export function startOfTehranDay(date=new Date()){const j=toJalali(date);return zonedJalaliToDate(j.year,j.month,j.day,0,0,0,TZ);}
export function tomorrowAt(hour:number,minute=0,date=new Date()){const j=toJalali(addJalaliDays(date,1));return zonedJalaliToDate(j.year,j.month,j.day,hour,minute);}
export function formatRelativeFa(due:Date,now=new Date()){const ms=due.getTime()-now.getTime(),a=Math.abs(ms),mins=Math.round(a/60000),hrs=Math.round(a/3600000),days=Math.round(a/86400000),n=(v:number)=>normalizeDigits(String(v));if(a<45000)return 'همین الان';if(a<3600000)return n(mins)+' دقیقه '+(ms>=0?'دیگر':'پیش');if(a<86400000)return n(hrs)+' ساعت '+(ms>=0?'دیگر':'پیش');if(days===1)return ms>=0?'فردا':'دیروز';return n(days)+' روز '+(ms>=0?'دیگر':'پیش');}
export function groupDayLabel(date:Date,now=new Date()){const d=Math.round((startOfTehranDay(date).getTime()-startOfTehranDay(now).getTime())/86400000);if(d===0)return 'امروز';if(d===1)return 'فردا';if(d===-1)return 'دیروز';return formatJalali(date);}
