import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'npm:@supabase/supabase-js@2';
const cors=(o:string)=>({'Access-Control-Allow-Origin':o||'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'});
const out=(x:unknown,s=200,o='')=>new Response(JSON.stringify(x),{status:s,headers:{...cors(o),'Content-Type':'application/json','Cache-Control':'no-store'}});
const fields=['vesselType','regNumber','regDate','packageCount','warehouseReceiptNo','warehouseReceiptDate','cargoDescription','originCountry','transactionCountry','deliveryTerm','invoiceAmount','invoiceCurrency','bankBranchCode','bankName','bankBranch','lcNumber','dutyRate','tariffCode','netWeight','grossWeight','billOfLading','insuranceIrr','requiredDocuments'];
const shipFields=['ownerName','shippingLine','vesselName','imo','count','unit','net','gross','billOfLading'];
const strip=(s:string)=>s.replace(/^data:[^;]+;base64,/,'');
const clip=(s:string,n:number)=>{const x=String(s||'');return x.length<=n?x:x.slice(0,n)+'\\n[context clipped]';};
const geminiSchema=(keys:string[])=>({type:'object',properties:Object.fromEntries(keys.map(k=>[k,{type:'string'}])),required:keys});
const openaiSchema=(keys:string[])=>({type:'object',properties:Object.fromEntries(keys.map(k=>[k,{type:'string'}])),required:keys,additionalProperties:false});
const text=(d:any)=>d?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').filter(Boolean).join('\n').trim()||d?.output_text||'';
const limited=(s:number,m:string)=>s===429||/rate.?limit|quota|too many|resource.?exhausted|limit exceeded/i.test(m);
const loadOperationalContext=async(sb:any,organizationId:string)=>{
  const [sh,cl,ca,de,sc,docsRes,checksRes,inv,pay,req,vessels]=await Promise.all([
    sb.from('shipments').select('id,case_id,client_id,display_name,bill_of_lading_no,cargo_count,cargo_count_unit,net_weight_kg,gross_weight_kg,current_status,release_status,release_invoice_payment_status,finance_status').eq('organization_id',organizationId).order('updated_at',{ascending:false}).limit(300),
    sb.from('clients').select('id,name').eq('organization_id',organizationId).limit(300),
    sb.from('cases').select('id,client_id,case_number,display_name,registration_order_no,warehouse_receipt_no,warehouse_receipt_date,cargo_count,cargo_count_unit,cargo_description,net_weight_kg,gross_weight_kg,status,release_status').eq('organization_id',organizationId).limit(300),
    sb.from('customs_declarations').select('id,shipment_id,case_id,kottaj_number,declaration_date,customs_path,payment_reference,workflow_stage').eq('organization_id',organizationId).limit(300),
    sb.from('shipment_customs_data').select('shipment_id,registration_order_no,warehouse_receipt_no,warehouse_receipt_date_shamsi,cargo_description,tariff_code,net_weight_kg,gross_weight_kg,bill_of_lading').eq('organization_id',organizationId).limit(300),
    sb.from('shipment_documents').select('shipment_id,document_name,original_file_name,extraction_status').eq('organization_id',organizationId).limit(500),
    sb.from('case_checklist_items').select('case_id,stage_no,item_key,completed').eq('organization_id',organizationId).limit(1000),
    sb.from('finance_invoice_shipments').select('shipment_id,invoice_id').eq('organization_id',organizationId).limit(500),
    sb.from('finance_payments').select('shipment_id,case_id,amount,currency,amount_irr,payment_type,description,payment_date').eq('organization_id',organizationId).limit(500),
    sb.from('finance_payment_requests').select('shipment_id,request_no,requested_amount,currency,status,subject').eq('organization_id',organizationId).limit(500),
    sb.from('vessels').select('id,name,imo_number,flag,last_latitude,last_longitude,last_position_at,last_position_source,last_speed_knots,last_course_deg').eq('organization_id',organizationId).limit(300)
  ]);
  const clients=cl.data||[],cases=ca.data||[],declarations=de.data||[],customs=sc.data||[],docs=docsRes.data||[],checks=checksRes.data||[],invoices=inv.data||[],payments=pay.data||[],requests=req.data||[],vessels=vessels.data||[];
  const cm=new Map(clients.map((x:any)=>[x.id,x])); const km=new Map(cases.map((x:any)=>[x.id,x]));
  const usable=(v:any)=>{const s=String(v??'').trim();return !!s&&!/^x{2,}$/i.test(s)&&s!=='—'&&s!=='-'};const dm=new Map<string,any>();for(const x of declarations){if(!x.shipment_id)continue;const prev=dm.get(x.shipment_id);if(!prev||(!usable(prev.kottaj_number)&&usable(x.kottaj_number))||(prev.kottaj_number===x.kottaj_number&&new Date(x.declaration_date||0)>new Date(prev.declaration_date||0)))dm.set(x.shipment_id,x);}
  const sm=new Map<string,any>();for(const x of customs){if(x.shipment_id&&!sm.has(x.shipment_id))sm.set(x.shipment_id,x);}const vm=new Map(vessels.map((x:any)=>[x.id,x]));const docsBy=new Map<string,any[]>();for(const x of docs){const a=docsBy.get(x.shipment_id)||[];a.push(x);docsBy.set(x.shipment_id,a);}const checksBy=new Map<string,any[]>();for(const x of checks){const a=checksBy.get(x.case_id)||[];a.push(x);checksBy.set(x.case_id,a);}const invIdsBy=new Map<string,string[]>();for(const x of invoices){const a=invIdsBy.get(x.shipment_id)||[];a.push(x.invoice_id);invIdsBy.set(x.shipment_id,a);}const payBy=new Map<string,any[]>();for(const x of payments){const a=payBy.get(x.shipment_id)||[];a.push(x);payBy.set(x.shipment_id,a);}const reqBy=new Map<string,any[]>();for(const x of requests){const a=reqBy.get(x.shipment_id)||[];a.push(x);reqBy.set(x.shipment_id,a);}
  const rows=(sh.data||[]).map((s:any)=>{const ca=km.get(s.case_id)||null,cl=cm.get(s.client_id||ca?.client_id)||null,de=dm.get(s.id)||null,sc=sm.get(s.id)||null;return {shipment_id:s.id,client_name:cl?.name||null,case_number:ca?.case_number||null,shipment_name:s.display_name||null,cargo_count:s.cargo_count??ca?.cargo_count??null,cargo_unit:s.cargo_count_unit??ca?.cargo_count_unit??null,bill_of_lading:s.bill_of_lading_no||sc?.bill_of_lading||null,kottaj_number:de?.kottaj_number||null,warehouse_receipt_no:sc?.warehouse_receipt_no||ca?.warehouse_receipt_no||null,warehouse_receipt_date:sc?.warehouse_receipt_date_shamsi||ca?.warehouse_receipt_date||null,registration_order_no:sc?.registration_order_no||ca?.registration_order_no||null,net_weight_kg:s.net_weight_kg??sc?.net_weight_kg??ca?.net_weight_kg??null,gross_weight_kg:s.gross_weight_kg??sc?.gross_weight_kg??ca?.gross_weight_kg??null,cargo_description:sc?.cargo_description||ca?.cargo_description||null,status:s.current_status||ca?.status||null,release_status:s.release_status||ca?.release_status||null,release_invoice_payment_status:s.release_invoice_payment_status||null,finance_status:s.finance_status||null,workflow_stage:de?.workflow_stage??null,customs_path:de?.customs_path||null,vessel:(vm.get(s.vessel_id)||null),documents:docsBy.get(s.id)||[],checklist:checksBy.get(s.case_id)||[],invoice_ids:invIdsBy.get(s.id)||[],payments:payBy.get(s.id)||[],payment_requests:reqBy.get(s.id)||[]};});
  return JSON.stringify(rows).slice(0,70000);
};
Deno.serve(async(req)=>{const o=req.headers.get('Origin')||'';if(req.method==='OPTIONS')return new Response('ok',{headers:cors(o)});if(req.method!=='POST')return out({error:'Method not allowed.'},405,o);try{const a=req.headers.get('Authorization')||'',token=a.startsWith('Bearer ')?a.slice(7):'';if(!token)return out({error:'Unauthorized'},401,o);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,sb=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}}});const{data:{user}}=await sb.auth.getUser(token);if(!user)return out({error:'Unauthorized'},401,o);const{data:profile}=await sb.from('profiles').select('role,is_active,organization_id').eq('id',user.id).maybeSingle();if(!profile||profile.is_active===false)return out({error:'پروفایل کاربر معتبر یا فعال نیست.'},403,o);const b=await req.json().catch(()=>({}));const q=String(b.query||'').slice(0,12000),dt=String(b.document_text||'').slice(0,30000);let dd=strip(String(b.document_data||''));const dm=String(b.document_mime_type||'').toLowerCase(),documentStoragePath=String(b.document_storage_path||'').trim(),docs=Array.isArray(b.documents)?b.documents:[],ex=!!b.extract_fields,voice=!!b.voice_transcription,sh=!!b.shipment_extract||q.includes('اطلاعات محموله کشتیرانی');
 if(!dd&&documentStoragePath){try{if(documentStoragePath.length>500||documentStoragePath.includes('..')||documentStoragePath.startsWith('/'))return out({error:'مسیر سند نامعتبر است.'},400,o);const {data:file,error:fileError}=await sb.storage.from('customs_documents').download(documentStoragePath);if(fileError||!file)throw new Error(fileError?.message||'سند از Storage قابل دریافت نیست.');if(file.size>30*1024*1024)return out({error:'حجم سند برای استخراج هوش مصنوعی بیش از ۳۰MB است.'},413,o);const bytes=new Uint8Array(await file.arrayBuffer());let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));dd=btoa(binary);}catch(e){return out({error:`دریافت سند از Storage ناموفق بود: ${e instanceof Error?e.message:String(e)}`},502,o);}}
 if(!q&&!dt&&!dd&&!docs.length)return out({error:'No query or document was supplied.'},400,o);const commandMode=!!b.command_mode;let operationalContext='';if(commandMode&&!ex&&!sh&&q&&profile.organization_id){try{operationalContext=await loadOperationalContext(sb,profile.organization_id)}catch{operationalContext=''}}console.log(JSON.stringify({event:'ai_request',extract_fields:ex,has_document_data:!!dd,has_storage_path:!!documentStoragePath,mime:dm,document_bytes_base64:dd.length}));const prompt=voice?'این فایل صوتی را به متن دقیق فارسی تبدیل کن. فقط همان کلمات گفته‌شده را برگردان؛ هیچ خلاصه، توضیح، ترجمه، حدس یا قالب‌بندی اضافه نکن.':sh?'فقط این فیلدها را استخراج کن: ownerName, shippingLine, vesselName, imo, count, unit, net, gross, billOfLading. حدس نزن؛ مقدار ناموجود یا ناخوانا xxxx. خروجی JSON.':ex?'فقط از همین سند/فایل ورودی اطلاعات استخراج کن. از حافظه، پیام‌های قبلی، context، اسناد قبلی یا حدس استفاده نکن. همه صفحات و جدول‌ها را بخوان. اعداد، تعداد بسته/رول، واحد، نام شرکت، شماره سند و شناسه‌های رسمی را دقیقاً همان‌طور که در سند آمده حفظ کن. اگر یک مقدار در سند نیست یا ناخواناست، xxxx قرار بده. هیچ مقدار جایگزین یا تخمینی نساز. خروجی فقط JSON و شامل همه فیلدهای موردنیاز باشد.':commandMode?'تو دستیار عملیاتی Customs OS هستی. پرسش را فقط بر اساس داده واقعی زیر پاسخ بده. برای «۲۲ رول شرکت آبتین» تعداد و صاحب کالا را تطبیق بده. شماره کوتاژ فقط از kottaj_number، قبض انبار فقط از warehouse_receipt_no و ثبت سفارش فقط از registration_order_no. اگر چند مورد است همه را جدا کن؛ اگر نیست صریحاً ثبت نشده بگو؛ هرگز حدس نزن. پاسخ کوتاه و فارسی باشد. داده عملیاتی:\n'+operationalContext:q||'اسناد را برای عملیات گمرکی تحلیل کن.';const keys=sh?shipFields:(ex?fields:[]);const input=clip(prompt+'\n'+(dt?dt:''),22000);const errors:string[]=[];
 const toBytes=(b64:string)=>{const bin=atob(b64);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;};
 const providers=[
 {name:'Gemini',key:Deno.env.get('GEMINI_API_KEY'),run:async(k:string)=>{const pp:any=[{text:input}];if(dd)pp.push({inlineData:{mimeType:dm,data:dd}});const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent',{method:'POST',headers:{'x-goog-api-key':k,'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:pp}],generationConfig:keys.length?{responseMimeType:'application/json'}:undefined})});const raw=await r.text();let d:any={};try{d=JSON.parse(raw)}catch{};return {r,d,t:text(d)}}},
 {name:'Cloudflare',key:Deno.env.get('CLOUDFLARE_API_TOKEN')||Deno.env.get('CLOUDFLARE_AI_TOKEN'),run:async(k:string)=>{const account=Deno.env.get('CLOUDFLARE_ACCOUNT_ID');if(!account)throw new Error('CLOUDFLARE_ACCOUNT_ID missing');const model=voice?'@cf/openai/whisper':'@cf/meta/llama-3.1-8b-instruct';const headers:any={Authorization:'Bearer '+k};let body:any;if(voice){body=toBytes(dd);headers['Content-Type']='application/octet-stream';}else{headers['Content-Type']='application/json';body=JSON.stringify({messages:[{role:'user',content:input}]});}const r=await fetch('https://api.cloudflare.com/client/v4/accounts/'+account+'/ai/run/'+model,{method:'POST',headers,body});const raw=await r.text();let d:any={};try{d=JSON.parse(raw)}catch{};return {r,d,t:voice?(d?.result?.text||''):(d?.result?.response||'')}}},
 {name:'Groq',key:Deno.env.get('GROQ_API_KEY'),run:async(k:string)=>{if(voice){const form=new FormData();form.append('file',new Blob([toBytes(dd)],{type:dm||'audio/mp4'}),'voice.'+(dm.includes('webm')?'webm':'mp4'));form.append('model','whisper-large-v3');form.append('language','fa');form.append('response_format','json');form.append('temperature','0');const r=await fetch('https://api.groq.com/openai/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${k}`},body:form});const raw=await r.text();let d:any={};try{d=JSON.parse(raw)}catch{};return {r,d,t:d?.text||''};}const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${k}`,'Content-Type':'application/json'},body:JSON.stringify({model:'openai/gpt-oss-120b',messages:[{role:'user',content:clip(input,20000)}],temperature:0,max_tokens:900,response_format:keys.length?{type:'json_object'}:undefined})});const raw=await r.text();let d:any={};try{d=JSON.parse(raw)}catch{};return {r,d,t:d?.choices?.[0]?.message?.content||''}}},
 {name:'OpenRouter',key:Deno.env.get('OPENROUTER_API_KEY'),run:async(k:string)=>{const content:any[]=voice?[{type:'text',text:input},{type:'input_audio',input_audio:{data:dd,format:dm.includes('webm')?'webm':'mp4'}}]:[{type:'text',text:input}];const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+k,'Content-Type':'application/json','HTTP-Referer':'https://customs.mohsen-darbandi.workers.dev','X-Title':'Customs OS'},body:JSON.stringify({model:'google/gemini-2.5-flash',messages:[{role:'user',content}],response_format:keys.length?{type:'json_object'}:undefined})});const raw=await r.text();let d:any={};try{d=JSON.parse(raw)}catch{};return {r,d,t:d?.choices?.[0]?.message?.content||''}}},
 {name:'OpenAI',key:Deno.env.get('OPENAI_API_KEY'),run:async(k:string)=>{if(voice){const form=new FormData();form.append('file',new Blob([toBytes(dd)],{type:dm||'audio/mp4'}),'voice.'+(dm.includes('webm')?'webm':'mp4'));form.append('model','gpt-4o-mini-transcribe');form.append('language','fa');const r=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${k}`},body:form});const raw=await r.text();let d:any={};try{d=JSON.parse(raw)}catch{};return {r,d,t:d?.text||''};}const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${k}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-4.1-mini',input:input,text:keys.length?{format:{type:'json_schema',name:'extraction',schema:openaiSchema(keys),strict:true}}:undefined})});const raw=await r.text();let d:any={};try{d=JSON.parse(raw)}catch{};return {r,d,t:d?.output_text||''}}}
 ];for(const p of providers){for(const key of providerKeys(p.name,p.key)){try{const z=await p.run(key),msg=String(z.d?.error?.message||z.d?.error||`HTTP ${z.r.status}`);if(z.r.ok&&String(z.t||'').trim())return out({answer:String(z.t).trim(),provider:p.name,status:'completed'},200,o);errors.push(`${p.name}: ${msg}`);continue}catch(e){errors.push(`${p.name}: ${e instanceof Error?e.message:String(e)}`)}}}console.error(JSON.stringify({event:'ai_provider_failure',errors}));return out({error:`همه سرویس‌های هوش مصنوعی در دسترس نبودند. ${errors.join(' | ')}`},502,o)}catch(e){return out({error:e instanceof Error?e.message:'AI request failed'},500,o)}});