// Deployed Edge Function: scan-chat-file. Static defense-in-depth scanner; no external AV dependency.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "jsr:@supabase/supabase-js@2";
const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const secret=async()=>{const {data,error}=await admin.rpc("internal_get_reminder_secret",{p_name:"file_scan_cron_secret"});if(error)throw error;return data as string|null};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json"}});
const ext=(n:string)=>(n.toLowerCase().match(/\.([a-z0-9]{1,12})$/)?.[1]??"");
const blocked=new Set(["exe","dll","com","scr","msi","msix","apk","ipa","jar","class","wasm","js","mjs","cjs","ts","tsx","jsx","php","phtml","asp","aspx","jsp","jspx","cgi","pl","py","rb","sh","bash","bat","cmd","ps1","vbs","vbe","wsf","hta","html","htm","svg"]);
const txt=(b:Uint8Array)=>new TextDecoder("latin1").decode(b);
const u16=(b:Uint8Array,o:number)=>new DataView(b.buffer,b.byteOffset,b.byteLength).getUint16(o,true);
const u32=(b:Uint8Array,o:number)=>new DataView(b.buffer,b.byteOffset,b.byteLength).getUint32(o,true);
function magic(b:Uint8Array){if(b[0]===0x4d&&b[1]===0x5a)return"exe";if(b[0]===0x7f&&b[1]===0x45&&b[2]===0x4c&&b[3]===0x46)return"elf";if(txt(b.slice(0,5))==="%PDF-")return"pdf";if(b[0]===0x50&&b[1]===0x4b&&b[2]===0x03&&b[3]===0x04)return"zip";if(b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47)return"png";if(b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return"jpeg";return"unknown"}
function scan(b:Uint8Array,name:string,mime:string){const reasons:string[]=[],e=ext(name),m=magic(b);if(b.length===0)reasons.push("empty");if(b.length>50*1024*1024)reasons.push("size");if(blocked.has(e)||["exe","elf"].includes(m))reasons.push("executable");if(m==="pdf"){const h=txt(b.slice(0,2*1024*1024));for(const x of ["/JavaScript","/JS","/OpenAction","/AA","/Launch","/EmbeddedFile"])if(h.includes(x))reasons.push("pdf_active:"+x)}if(m==="zip"){const end=Math.max(0,b.length-65557);let at=-1;for(let i=b.length-22;i>=end;i--)if(u32(b,i)===0x06054b50){at=i;break}if(at<0)reasons.push("invalid_zip");else{const n=u16(b,at+10),size=u32(b,at+12),off=u32(b,at+16);if(n>100||off+size>b.length)reasons.push("archive_limit");else{let p=off,total=0;for(let i=0;i<n;i++){if(u32(b,p)!==0x02014b50){reasons.push("invalid_entry");break}const flags=u16(b,p+8),un=u32(b,p+24),fn=u16(b,p+28),ex=u16(b,p+30),co=u16(b,p+32),name0=txt(b.slice(p+46,p+46+fn));if(flags&1)reasons.push("encrypted");if(name0.includes("..")||name0.startsWith("/")||name0.includes("\\")||name0.includes(":"))reasons.push("path_traversal");if(/vbaProject\.bin$/i.test(name0))reasons.push("office_macro");total+=un;if(total>250*1024*1024)reasons.push("decompression_limit");p+=46+fn+ex+co}}}}if(["docm","xlsm","pptm","xlam","xltm","potm"].includes(e))reasons.push("office_macro");return{clean:reasons.length===0,magic:m,extension:e,mime,reasons}}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const expected=await secret();if(!expected||req.headers.get("x-file-scan-cron-secret")!==expected)return json({error:"unauthorized"},401);try{const {data,error}=await admin.from("file_scans").select("id,attachment_id").eq("status","scanning").order("created_at").limit(25);if(error)throw error;let processed=0;for(const s of data??[]){const {data:a}=await admin.from("chat_attachments").select("id,storage_path,original_name,mime_type").eq("id",s.attachment_id).maybeSingle();if(!a)continue;const parts=String(a.storage_path||"").split("/"),bucket=parts.shift(),path=parts.join("/");if(!bucket||!path)continue;const {data:file}=await admin.storage.from(bucket).download(path);if(!file)continue;const b=new Uint8Array(await file.arrayBuffer()),dig=await crypto.subtle.digest("SHA-256",b),sha=Array.from(new Uint8Array(dig)).map(x=>x.toString(16).padStart(2,"0")).join(""),r=scan(b,a.original_name,a.mime_type);await admin.from("file_scans").update({status:r.clean?"clean":"blocked",sha256:sha,provider:"local_static",local_result:r,completed_at:new Date().toISOString()}).eq("id",s.id);await admin.from("chat_attachments").update({security_status:r.clean?"clean":"blocked",security_checked_at:new Date().toISOString(),security_error:r.clean?null:JSON.stringify(r.reasons)}).eq("id",a.id);processed++}return json({ok:true,processed})}catch(e){return json({ok:false,error:e instanceof Error?e.message:"scanner_failed"},500)}});