import React,{useEffect,useState}from'react';
import{registerSW}from'virtual:pwa-register';
const isIos=()=>/iphone|ipad|ipod/i.test(navigator.userAgent)&&!/android/i.test(navigator.userAgent);
const standalone=()=>window.matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone);
export const PwaLifecycle:React.FC=()=>{
 const[installEvent,setInstallEvent]=useState<BeforeInstallPromptEvent|null>(null),[update,setUpdate]=useState(false),[iosGuide,setIosGuide]=useState(false),[online,setOnline]=useState(()=>navigator.onLine);
 useEffect(()=>{const updateSW=registerSW({immediate:true,onNeedRefresh:()=>setUpdate(true),onOfflineReady:()=>undefined});const onInstall=(e:Event)=>{e.preventDefault();setInstallEvent(e as BeforeInstallPromptEvent)},onOnline=()=>setOnline(true),onOffline=()=>setOnline(false);window.addEventListener('beforeinstallprompt',onInstall);window.addEventListener('online',onOnline);window.addEventListener('offline',onOffline);return()=>{window.removeEventListener('beforeinstallprompt',onInstall);window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline)}} ,[]);
 useEffect(()=>{const vv=window.visualViewport;if(!vv)return;const set=()=>document.documentElement.style.setProperty('--reminder-keyboard-height',Math.max(0,window.innerHeight-vv.height)+'px');set();vv.addEventListener('resize',set);vv.addEventListener('scroll',set);return()=>{vv.removeEventListener('resize',set);vv.removeEventListener('scroll',set)}},[]);
 useEffect(()=>{if(isIos()&&!standalone()&&localStorage.getItem('customs-os-ios-install-dismissed')!=='1')setIosGuide(true)},[]);
 const install=async()=>{if(!installEvent)return;await installEvent.prompt();setInstallEvent(null)};
 const dismissIos=()=>{localStorage.setItem('customs-os-ios-install-dismissed','1');setIosGuide(false)};
 const [updateSW,setUpdateSW]=useState<((reloadPage?:boolean)=>Promise<void>)|null>(null);
 useEffect(()=>{setUpdateSW(()=>registerSW({immediate:false,onNeedRefresh:()=>setUpdate(true)}))},[]);
 return <>{installEvent&&!standalone()&&<div dir="rtl" className="fixed bottom-4 right-4 left-4 md:left-auto md:w-[380px] z-[500] rounded-2xl border app-border bg-[var(--surface)] p-4 shadow-2xl"><b>نصب برنامه</b><p className="text-xs app-muted mt-1">برای اعلان‌های واقعی و دسترسی سریع، برنامه را روی گوشی نصب کنید.</p><div className="flex gap-2 mt-3"><button onClick={()=>void install()} className="min-h-11 flex-1 rounded-xl bg-[var(--primary)] text-white font-bold">نصب برنامه</button><button onClick={()=>setInstallEvent(null)} className="min-h-11 px-4 rounded-xl border app-border">بعداً</button></div></div>}
 {iosGuide&&!standalone()&&<div dir="rtl" className="fixed inset-x-3 bottom-3 z-[500] rounded-2xl border app-border bg-[var(--surface)] p-4 shadow-2xl"><b>نصب در آیفون</b><ol className="text-xs app-muted mt-2 space-y-1 pr-4 list-decimal"><li>دکمه «اشتراک‌گذاری» را در Safari بزنید.</li><li>گزینه «افزودن به صفحه اصلی» را انتخاب کنید.</li><li>برنامه را از صفحه اصلی باز کنید؛ بعد اعلان‌ها فعال می‌شوند.</li></ol><div className="flex gap-2 mt-3"><button onClick={dismissIos} className="min-h-11 flex-1 rounded-xl bg-[var(--primary)] text-white font-bold">متوجه شدم</button><button onClick={()=>setIosGuide(false)} className="min-h-11 px-4 rounded-xl border app-border">بستن</button></div></div>}
 {!online&&<div dir="rtl" className="fixed top-[calc(66px+env(safe-area-inset-top))] inset-x-3 z-[300] rounded-xl bg-[var(--surface)] border app-border px-3 py-2 text-xs shadow-lg">اتصال اینترنت قطع است؛ یادآورهای جدید روی دستگاه شما صف می‌شوند.</div>}
 {update&&<div dir="rtl" className="fixed bottom-4 left-4 z-[500] rounded-2xl border app-border bg-[var(--surface)] p-3 shadow-2xl"><div className="text-sm font-bold">نسخه جدید آماده است</div><button onClick={()=>void updateSW?.(true)} className="mt-2 min-h-10 rounded-xl bg-[var(--primary)] px-4 text-white font-bold">به‌روزرسانی</button></div>}</>;
};
export const isPwaInstalled=standalone;
type BeforeInstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed';platform:string}>};
