import React,{useEffect,useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useSearchParams} from 'react-router-dom';
import {Bell,CalendarDays,Check,ChevronLeft,ChevronRight,Clock3,MoreHorizontal,Plus,RefreshCw,Search,Trash2,Undo2,X,Users,Repeat2,ListChecks,Mic,MicOff} from 'lucide-react';
import {supabase} from '../../lib/supabase';
import {rpcWithOfflineQueue} from '../../lib/offlineQueue';
import {useAuth} from '../../context/AuthContext';
import {addJalaliDays,formatJalaliDateTime,formatRelativeFa,groupDayLabel,startOfTehranDay,toJalali,zonedJalaliToDate} from '../../lib/jalali';
import {JalaliDateTimePicker} from './JalaliDateTimePicker';
import {disablePush,enablePush,listPushDevices,setNotificationPreferences,testPush} from './push';
import {parseReminder,resolveAssignee,resolveLink,type Reminder,type ReminderKind,type ReminderPriority,ReminderEntityType} from './reminderCore';

type Filter='today'|'scheduled'|'overdue'|'all'|'done'|'assigned';
type QueryResult={rows:Reminder[];count:number};
const PAGE_SIZE=50;
const kinds:[ReminderKind,string][]=[['document','اسناد'],['shipment','محموله / پرونده'],['finance','مالی'],['other','سایر']];
const priorityLabel:Record<ReminderPriority,string>={low:'کم',normal:'عادی',high:'زیاد',urgent:'فوری'};
const filterLabel:Record<Filter,string>={today:'امروز',scheduled:'برنامه‌ریزی‌شده',overdue:'معوق',all:'همه',done:'انجام‌شده',assigned:'به من واگذار شده'};
const fa=(n:number)=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[Number(d)]);
const todayRange=()=>{const s=startOfTehranDay();return [s,addJalaliDays(s,1)] as const;};
const emptyForm={title:'',notes:'',dueAt:new Date(Date.now()+3600000),priority:'normal' as ReminderPriority,kind:'other' as ReminderKind,allDay:false,offsets:[0],recurrence:null as string|null,visibility:'private' as 'private'|'team',tags:''};

function errorFa(error:unknown){const m=error instanceof Error?error.message:String(error??'');const replacements:[[string,string]]=[['permission denied','دسترسی مجاز نیست'],['row-level security','دسترسی این یادآور مجاز نیست'],['violates','اطلاعات ثبت‌شده معتبر نیست'],['invalid','اطلاعات واردشده معتبر نیست']];for(const [a,b] of replacements)if(m.toLowerCase().includes(a))return b;return 'عملیات یادآور انجام نشد';}

type SpeechRecognitionLike={lang:string;interimResults:boolean;resultIndex:number;onresult:(event:SpeechRecognitionEventLike)=>void;onerror:()=>void;onend:()=>void;start:()=>void;stop:()=>void};type SpeechRecognitionEventLike={resultIndex:number;results:ArrayLike<{0:{transcript?:string}} & ArrayLike<{transcript?:string}>>};
export const RemindersPage:React.FC=()=>{
 const {profile,user}=useAuth();const qc=useQueryClient();const [params,setParams]=useSearchParams();const [filter,setFilter]=useState<Filter>((params.get('view') as Filter)||'today');const [kind,setKind]=useState<ReminderKind|null>(null);const [search,setSearch]=useState('');const [page,setPage]=useState(0);const [composer,setComposer]=useState('');const [selected,setSelected]=useState<string[]>([]);const [editor,setEditor]=useState<Reminder|null>(null);const [showPicker,setShowPicker]=useState(false);const [toast,setToast]=useState<{text:string;undo?:()=>void}|null>(null);const [pushOpen,setPushOpen]=useState(false);const [pushDevices,setPushDevices]=useState<Array<{id:string;platform:string|null;user_agent:string|null;last_seen_at:string;is_active:boolean;failure_count:number}>>([]);const [pushBusy,setPushBusy]=useState(false);
 const pushAllowed=profile?.role!=='client';
 const [recording,setRecording]=useState(false);
 const [menuId,setMenuId]=useState<string|null>(null);
 const preview=useMemo(()=>composer.trim()?parseReminder(composer):null,[composer]);

 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const target=e.target as HTMLElement|null;if(e.key.toLowerCase()==='n'&&target&&![HTMLInputElement,HTMLTextAreaElement].some(C=>target instanceof C)){e.preventDefault();document.getElementById('reminder-quick-input')?.focus();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 useEffect(()=>{if(params.get('new')==='1'){setTimeout(()=>document.getElementById('reminder-quick-input')?.focus(),50);setParams({}, {replace:true});}},[params,setParams]);
 useEffect(()=>{const rid=params.get('rid'),act=params.get('act');if(!rid||!act)return;setParams(p=>{p.delete('rid');p.delete('act');return p},{replace:true});if(!user)return;const run=async()=>{if(act==='done'){await supabase.from('operational_reminders').update({status:'done',completed_at:new Date().toISOString(),completed_by:user.id}).eq('id',rid);}else if(act==='snooze10'){await supabase.from('operational_reminders').update({snoozed_until:new Date(Date.now()+600000).toISOString(),snooze_count:1}).eq('id',rid);}else if(act==='tomorrow9'){const d=new Date();const j=toJalali(addJalaliDays(d,1));const at=zonedJalaliToDate(j.year,j.month,j.day,9,0);await supabase.from('operational_reminders').update({snoozed_until:at.toISOString(),snooze_count:1}).eq('id',rid);}await qc.invalidateQueries({queryKey:['reminders']});};void run();},[params,qc,setParams,user]);

 const query=useQuery<QueryResult>({
  queryKey:['reminders',filter,kind,search,page,user?.id],
  queryFn:async()=>{
   if(!profile?.organization_id)return{rows:[],count:0};let q=supabase.from('operational_reminders').select('*',{count:'exact'}).order('due_at',{ascending:true}).range(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE-1);
   q=q.eq('organization_id',profile.organization_id);
   if(filter==='today'){const[r1,r2]=todayRange();q=q.gte('due_at',r1.toISOString()).lt('due_at',r2.toISOString()).eq('status','open');}
   if(filter==='scheduled')q=q.eq('status','open').gte('due_at',new Date().toISOString());
   if(filter==='overdue')q=q.eq('status','open').lt('due_at',new Date().toISOString());
   if(filter==='done')q=q.eq('status','done');
   if(filter==='assigned')q=q.eq('assignee_id',user?.id??'00000000-0000-0000-0000-000000000000').eq('status','open');
   if(kind)q=q.eq('kind',kind);
   if(search.trim()){const s=search.trim().replace(/[,()]/g,' ');q=q.or('title.ilike.%'+s+'%,description.ilike.%'+s+'%,notes.ilike.%'+s+'%');}
   const {data,error,count}=await q;if(error)throw error;return{rows:(data??[]) as Reminder[],count:count??0};
  },enabled:Boolean(profile?.organization_id),staleTime:15000,placeholderData:(old)=>old
 });
 const reminders=query.data?.rows??[];
 const upsertVisible=(fn:(rows:Reminder[])=>Reminder[])=>{qc.setQueriesData<QueryResult>({queryKey:['reminders']},old=>old?{...old,rows:fn(old.rows)}:old);};
 const create=useMutation({
  mutationFn:async({parsed,clientUuid}:{parsed:ReturnType<typeof parseReminder>;clientUuid:string})=>{
   const payload={title:parsed.title,due_at:parsed.dueAt.toISOString(),priority:parsed.priority,kind:parsed.kind,recurrence_rule:parsed.recurrenceRule,alarm_offsets_min:parsed.alarmOffsets,visibility:'private',all_day:false,timezone:'Asia/Tehran',client_uuid:clientUuid};
   const result=await rpcWithOfflineQueue('create_operational_reminder',{p_payload:payload}) as {data:Reminder|null;error:{message:string}|null;queued?:boolean};
   if(result.error)throw new Error(result.error.message);
   if(result.data){const link=await resolveLink(parsed.linkQuery,parsed.kind).catch(()=>null);const assignee=await resolveAssignee(parsed.assigneeName).catch(()=>null);if(link||assignee){await supabase.from('operational_reminders').update({...link,...(assignee?{assignee_id:assignee}: {})}).eq('id',result.data.id);}}
   return result;
  },
  onMutate:async({parsed,clientUuid})=>{await qc.cancelQueries({queryKey:['reminders']});const temp={id:'local-'+clientUuid,organization_id:profile?.organization_id??null,case_id:null,shipment_id:null,title:parsed.title,description:null,due_at:parsed.dueAt.toISOString(),priority:parsed.priority,status:'open',created_by:user?.id??null,completed_at:null,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),due_precision:'day',source_key:null,is_system:false,kind:parsed.kind,entity_type:null,entity_id:null,assignee_id:user?.id??null,visibility:'private',all_day:false,timezone:'Asia/Tehran',alarm_offsets_min:parsed.alarmOffsets,recurrence_rule:parsed.recurrenceRule,recurrence_until:null,series_id:null,occurrence_key:null,snoozed_until:null,snooze_count:0,tags:[],notes:null,client_uuid:clientUuid,deleted_at:null,completed_by:null} as Reminder;upsertVisible(rows=>[temp,...rows]);return{tempId:temp.id};},
  onError:(e,_v,ctx)=>{if(ctx?.tempId)upsertVisible(rows=>rows.filter(x=>x.id!==ctx.tempId));setToast({text:errorFa(e)});},
  onSettled:()=>{void qc.invalidateQueries({queryKey:['reminders']});}
 });
 const update=useMutation({
  mutationFn:async(v:{id:string;patch:Partial<Reminder>})=>{const {error}=await supabase.from('operational_reminders').update(v.patch).eq('id',v.id);if(error)throw error;},
  onMutate:async(v)=>{await qc.cancelQueries({queryKey:['reminders']});const old=reminders.find(x=>x.id===v.id);upsertVisible(rows=>rows.map(x=>x.id===v.id?{...x,...v.patch,updated_at:new Date().toISOString()}:x));return{old};},
  onError:(e,v,ctx)=>{if(ctx?.old)upsertVisible(rows=>rows.map(x=>x.id===v.id?ctx.old!:x));setToast({text:errorFa(e)});},
  onSettled:()=>{void qc.invalidateQueries({queryKey:['reminders']});}
 });
 const createQuick=async(text:string)=>{const parsed=parseReminder(text);const clientUuid=crypto.randomUUID();setComposer('');await create.mutateAsync({parsed,clientUuid}).catch(()=>{});};
 const toggleDone=(r:Reminder)=>{if(r.id.startsWith('local-'))return;update.mutate({id:r.id,patch:r.status==='done'?{status:'open',completed_at:null,completed_by:null}:{status:'done',completed_at:new Date().toISOString(),completed_by:user?.id??null}});};
 const softDelete=(r:Reminder)=>{const deletedAt=new Date().toISOString();update.mutate({id:r.id,patch:{deleted_at:deletedAt,status:'dismissed'}});setToast({text:'یادآور به سطل پنهان منتقل شد.',undo:()=>update.mutate({id:r.id,patch:{deleted_at:null,status:'open'}})});};
 const snooze=(r:Reminder,minutes:number)=>update.mutate({id:r.id,patch:{snoozed_until:new Date(Date.now()+minutes*60000).toISOString(),snooze_count:r.snooze_count+1}});
 const tomorrow=()=>{const j=toJalali(addJalaliDays(new Date(),1));return zonedJalaliToDate(j.year,j.month,j.day,9,0);};
 const bulkDone=()=>{for(const id of selected)if(!id.startsWith('local-'))update.mutate({id,patch:{status:'done',completed_at:new Date().toISOString(),completed_by:user?.id??null}});setSelected([]);};
 const bulkSnooze=()=>{for(const id of selected)if(!id.startsWith('local-'))update.mutate({id,patch:{snoozed_until:new Date(Date.now()+600000).toISOString(),snooze_count:(reminders.find(r=>r.id===id)?.snooze_count??0)+1}});setSelected([]);};
 const bulkDismiss=()=>{for(const id of selected)if(!id.startsWith('local-'))update.mutate({id,patch:{status:'dismissed'}});setSelected([]);};
 const openPush=async()=>{setPushOpen(true);if(pushAllowed){try{setPushDevices(await listPushDevices())}catch{setPushDevices([])}}};
 useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(null),5000);return()=>window.clearTimeout(t);},[toast]);
 useEffect(()=>{const onOnline=()=>void qc.invalidateQueries({queryKey:['reminders']});window.addEventListener('online',onOnline);return()=>window.removeEventListener('online',onOnline);},[qc]);
 useEffect(()=>{const nav=navigator as Navigator & {setAppBadge?:(contents?:number)=>Promise<void>;clearAppBadge?:()=>Promise<void>};const badger=async()=>{try{const [{data:over}] = await Promise.all([supabase.from('operational_reminders').select('id',{count:'exact',head:true}).eq('status','open').lt('due_at',new Date().toISOString())]);if(nav.setAppBadge)await nav.setAppBadge(over?.length??0);}catch{}};void badger();},[reminders.length]);
 useEffect(()=>{const channel=supabase.channel('reminders-live').on('postgres_changes',{event:'*',schema:'public',table:'operational_reminders'},()=>{void qc.invalidateQueries({queryKey:['reminders']});}).subscribe();return()=>{void supabase.removeChannel(channel);};},[qc]);

 const groups=useMemo(()=>{const out:Array<{label:string;rows:Reminder[]}>=[];for(const r of reminders){const label=groupDayLabel(new Date(r.due_at));const existing=out.find(x=>x.label===label);if(existing)existing.rows.push(r);else out.push({label,rows:[r]});}return out;},[reminders]);
 const totalPages=Math.max(1,Math.ceil((query.data?.count??0)/PAGE_SIZE));
 const startDictation=()=>{const w=window as Window & {SpeechRecognition?:new()=>SpeechRecognitionLike;webkitSpeechRecognition?:new()=>SpeechRecognitionLike};const C=w.SpeechRecognition??w.webkitSpeechRecognition;if(!C){setToast({text:'تشخیص گفتار در این مرورگر پشتیبانی نمی‌شود.'});return;}const recognition=new C();recognition.lang='fa-IR';recognition.interimResults=true;recognition.onresult=(event)=>{let value='';for(let i=event.resultIndex;i<event.results.length;i++)value+=event.results[i][0]?.transcript??'';setComposer(value);};recognition.onerror=()=>{setRecording(false);setToast({text:'تشخیص گفتار انجام نشد.'});};recognition.onend=()=>setRecording(false);setRecording(true);recognition.start();};
 const submitComposer=(e:React.FormEvent)=>{e.preventDefault();const lines=composer.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(lines.length>1){setComposer('');for(const line of lines)void createQuick(line);}else if(composer.trim())void createQuick(composer.trim());};
 const onCardPointerDown=(id:string,e:React.PointerEvent)=>{if(e.pointerType==='mouse')return;const timer=window.setTimeout(()=>{setSelected(s=>s.includes(id)?s:[...s,id]);},550);(e.currentTarget as HTMLElement).dataset.longPress=String(timer);};
 const onCardPointerUp=(id:string,e:React.PointerEvent)=>{const el=e.currentTarget as HTMLElement;const timer=Number(el.dataset.longPress??0);if(timer)window.clearTimeout(timer);};
 const performSwipe=(r:Reminder,e:React.PointerEvent,start:{x:number})=>{const dx=e.clientX-start.x;if(Math.abs(dx)>70){if(dx>70)toggleDone(r);else snooze(r,10);}};
 const [pointerStart,setPointerStart]=useState<{x:number}|null>(null);

 return <main dir="rtl" className="min-h-[calc(100vh-64px)] pb-28">
  <section className="mx-auto max-w-6xl px-2 sm:px-4 pt-2 sm:pt-5">
   <header className="sticky top-0 z-20 rounded-3xl border app-border bg-[color-mix(in_srgb,var(--surface)_90%,transparent)] backdrop-blur-xl px-3 py-3 shadow-sm">
    <div className="flex items-center gap-2"><div className="flex-1 min-w-0"><h1 className="text-2xl sm:text-3xl font-black">یادآورها</h1><div className="text-xs app-muted mt-1">{fa(query.data?.count??0)} مورد · سریع، شمسی و متصل به عملیات</div></div><button onClick={()=>void openPush()} className="min-w-11 min-h-11 rounded-xl border app-border bg-[var(--surface-2)]" title="اعلان‌ها"><Bell size={18}/></button><button onClick={()=>void query.refetch()} className="min-w-11 min-h-11 rounded-xl border app-border bg-[var(--surface-2)]" title="تازه‌سازی"><RefreshCw size={17} className={query.isFetching?'animate-spin':''}/></button></div>
    <div className="mt-3 relative"><Search size={16} className="absolute right-3 top-3.5 app-muted"/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="جستجو در یادآورها..." className="w-full min-h-12 rounded-2xl border app-border bg-[var(--surface-2)] pr-10 pl-3 outline-none focus:ring-2 focus:ring-[var(--primary)]/30"/></div>
    <div className="flex gap-2 overflow-x-auto mt-3 pb-1">{(Object.keys(filterLabel) as Filter[]).map(f=><button key={f} onClick={()=>{setFilter(f);setPage(0)}} className={'shrink-0 min-h-10 rounded-xl px-3 text-xs font-bold '+(filter===f?'bg-[var(--primary)] text-white':'bg-[var(--surface-2)] border app-border')}>{filterLabel[f]}</button>)}</div>
    <div className="flex gap-2 overflow-x-auto mt-2 pb-1">{kinds.map(([k,label])=><button key={k} onClick={()=>{setKind(kind===k?null:k);setPage(0)}} className={'shrink-0 min-h-9 rounded-full px-3 text-xs '+(kind===k?'bg-[var(--text)] text-[var(--surface)]':'border app-border bg-[var(--surface)]')}>{label}</button>)}</div>
   </header>

   {selected.length>0&&<div className="sticky top-[178px] z-10 mt-2 rounded-2xl border app-border bg-[var(--surface)] p-2 flex items-center gap-2 shadow-lg"><span className="text-xs font-bold flex-1">{fa(selected.length)} انتخاب شده</span><button onClick={bulkDone} className="min-h-10 px-3 rounded-xl bg-emerald-600 text-white text-xs font-bold">انجام شد</button><button onClick={bulkSnooze} className="min-h-10 px-3 rounded-xl border app-border text-xs">۱۰ دقیقه</button><button onClick={bulkDismiss} className="min-h-10 px-3 rounded-xl border app-border text-xs">پنهان‌کردن</button><button onClick={()=>setSelected([])} className="min-h-10 px-3 rounded-xl border app-border text-xs">لغو</button></div>}

   {query.isPending&&<div className="space-y-2 mt-3">{Array.from({length:5},(_,i)=><div key={i} className="h-24 rounded-2xl bg-[var(--surface-2)] animate-pulse border app-border"/>)}</div>}
   {query.isError&&<div className="mt-3 rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm">{errorFa(query.error)}</div>}

   <div className="mt-3 space-y-5">
    {groups.map(group=><section key={group.label}><div className="px-2 mb-2 text-sm font-black">{group.label}</div><div className="space-y-2">{group.rows.map(r=><article key={r.id} onPointerDown={e=>{onCardPointerDown(r.id,e);setPointerStart({x:e.clientX})}} onPointerUp={e=>{onCardPointerUp(r.id,e);if(pointerStart){performSwipe(r,e,pointerStart);setPointerStart(null)}}} className={'relative overflow-hidden rounded-2xl border app-border bg-[var(--surface)] p-3 transition '+(selected.includes(r.id)?'ring-2 ring-[var(--primary)] ':'')} style={{contentVisibility:'auto',containIntrinsicSize:'0 96px'}}>
      <div className="flex items-start gap-3"><button aria-label={r.status==='done'?'بازگرداندن':'انجام شد'} onClick={()=>toggleDone(r)} className={'min-w-11 min-h-11 rounded-xl grid place-items-center border app-border '+(r.status==='done'?'bg-emerald-600 text-white':'bg-[var(--surface-2)]')}>{r.status==='done'?<Check size={18}/>:<span className="w-5 h-5 rounded-full border-2 border-current"/>}</button>
       <div className="flex-1 min-w-0"><div className={'font-black text-sm leading-6 '+(r.status==='done'?'line-through opacity-60':'')}>{r.title}</div><div className="flex flex-wrap gap-x-3 gap-y-1 mt-1 text-[11px] app-muted"><span><Clock3 size={12} className="inline ml-1"/>{formatRelativeFa(new Date(r.due_at))} · {formatJalaliDateTime(new Date(r.due_at))}</span><span>{priorityLabel[r.priority]}</span><span>{kinds.find(x=>x[0]===r.kind)?.[1]??'سایر'}</span>{r.assignee_id&&r.assignee_id===user?.id&&<span>به من</span>}</div>{(r.case_id||r.shipment_id)&&<div className="text-[11px] mt-1 text-[var(--primary)]">{r.case_id?'پرونده مرتبط':'محموله مرتبط'}</div>}{r.notes&&<div className="text-xs app-muted mt-1 line-clamp-2">{r.notes}</div>}</div>
       <button onClick={()=>setMenuId(menuId===r.id?null:r.id)} className="min-w-11 min-h-11 rounded-xl border app-border bg-[var(--surface-2)]"><MoreHorizontal size={18}/></button>{menuId===r.id&&<div className="absolute left-3 top-14 z-20 w-44 rounded-2xl border app-border bg-[var(--surface)] p-2 shadow-xl"><button onClick={()=>{snooze(r,10);setMenuId(null)}} className="w-full min-h-10 rounded-xl text-right px-3 text-xs">۱۰ دقیقه بعد</button><button onClick={()=>{snooze(r,60);setMenuId(null)}} className="w-full min-h-10 rounded-xl text-right px-3 text-xs">۱ ساعت بعد</button><button onClick={()=>{update.mutate({id:r.id,patch:{snoozed_until:tomorrow().toISOString(),snooze_count:r.snooze_count+1}});setMenuId(null)}} className="w-full min-h-10 rounded-xl text-right px-3 text-xs">فردا ۹ صبح</button><button onClick={()=>{softDelete(r);setMenuId(null)}} className="w-full min-h-10 rounded-xl text-right px-3 text-xs text-red-500">پنهان‌کردن</button><button onClick={()=>{setEditor(r);setMenuId(null)}} className="w-full min-h-10 rounded-xl text-right px-3 text-xs">ویرایش</button></div>}
      </div>
     </article>)}</div></section>)}
   </div>
   {!query.isPending&&!groups.length&&<div className="mt-8 rounded-3xl border app-border bg-[var(--surface)] p-12 text-center"><Bell size={30} className="mx-auto app-muted"/><div className="mt-3 font-black">یادآوری پیدا نشد</div><div className="text-xs app-muted mt-1">از نوار پایین، اولین یادآور را در یک خط بنویسید.</div></div>}
   <div className="flex items-center justify-between mt-5 pb-10"><button disabled={page===0} onClick={()=>setPage(x=>x-1)} className="min-h-11 px-3 rounded-xl border app-border disabled:opacity-40"><ChevronRight size={17}/></button><span className="text-xs app-muted">{fa(page+1)} از {fa(totalPages)}</span><button disabled={page+1>=totalPages} onClick={()=>setPage(x=>x+1)} className="min-h-11 px-3 rounded-xl border app-border disabled:opacity-40"><ChevronLeft size={17}/></button></div>
  </section>

  <form onSubmit={submitComposer} className="fixed bottom-0 inset-x-0 z-30 px-3 pb-[calc(10px+env(safe-area-inset-bottom))] pt-2 bg-gradient-to-t from-[var(--bg)] via-[var(--bg)]/95 to-transparent"><div className="max-w-6xl mx-auto flex items-end gap-2"><button type="button" onClick={()=>document.getElementById('reminder-quick-input')?.focus()} className="min-w-12 min-h-12 rounded-2xl bg-[var(--primary)] text-white grid place-items-center shadow-xl" aria-label="یادآور جدید"><Plus size={21}/></button><button type="button" onClick={()=>{if(!recording)startDictation()}} className="min-w-12 min-h-12 rounded-2xl border app-border bg-[var(--surface)] grid place-items-center" aria-label="دیکته صوتی">{recording?<MicOff size={18}/>:<Mic size={18}/>}</button><input id="reminder-quick-input" value={composer} onChange={e=>setComposer(e.target.value)} onKeyDown={e=>{if(e.key==='n'&&e.metaKey)setComposer('')}} placeholder="مثلاً: فردا ساعت ۹ صبح پیگیری ترخیص کوتاژ ۱۲۳" className="flex-1 min-h-14 rounded-2xl border app-border bg-[var(--surface)] shadow-xl px-4 outline-none focus:ring-2 focus:ring-[var(--primary)]/30" enterKeyHint="done"/><button type="submit" disabled={!composer.trim()||create.isPending} className="min-w-12 min-h-12 rounded-2xl bg-[var(--text)] text-[var(--surface)] disabled:opacity-40 grid place-items-center"><Plus size={20}/></button></div></form>

  {editor&&<ReminderEditor reminder={editor} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);void qc.invalidateQueries({queryKey:['reminders']})}} onPicker={()=>setShowPicker(true)}/>}
  {showPicker&&editor&&<JalaliDateTimePicker value={new Date(editor.due_at)} onChange={d=>setEditor({...editor,due_at:d.toISOString()})} allDay={editor.all_day} onAllDayChange={v=>setEditor({...editor,all_day:v})} onClose={()=>setShowPicker(false)}/>}
  {pushOpen&&<PushSettings allowed={pushAllowed} devices={pushDevices} busy={pushBusy} onClose={()=>setPushOpen(false)} setBusy={setPushBusy} reloadDevices={async()=>setPushDevices(await listPushDevices())}/>}
  {toast&&<div className="fixed bottom-24 left-3 right-3 md:left-auto md:right-6 md:w-[360px] z-[200] rounded-2xl border app-border bg-[var(--surface)] p-3 shadow-2xl flex items-center gap-2"><div className="text-sm flex-1">{toast.text}</div>{toast.undo&&<button onClick={()=>{toast.undo?.();setToast(null)}} className="min-h-10 px-3 rounded-xl bg-[var(--primary)] text-white text-xs font-bold"><Undo2 size={14} className="inline ml-1"/>برگردان</button>}{<button onClick={()=>setToast(null)} className="min-w-10 min-h-10 rounded-xl border app-border"><X size={15}/></button>}</div>}
 </main>
};

const ReminderEditor:React.FC<{reminder:Reminder;onClose:()=>void;onSaved:()=>void;onPicker:()=>void}>=({reminder,onClose,onSaved,onPicker})=>{
 const [title,setTitle]=useState(reminder.title),[notes,setNotes]=useState(reminder.notes??''),[priority,setPriority]=useState(reminder.priority),[kind,setKind]=useState(reminder.kind),[visibility,setVisibility]=useState(reminder.visibility),[recurrence,setRecurrence]=useState(reminder.recurrence_rule??''),[offsets,setOffsets]=useState<number[]>(reminder.alarm_offsets_min?.length?reminder.alarm_offsets_min:[0]),[tagText,setTagText]=useState(reminder.tags.join(' ')),[items,setItems]=useState<Array<{id:string;title:string;is_done:boolean}>>([]),[check,setCheck]=useState(''),[saving,setSaving]=useState(false),[assigneeId,setAssigneeId]=useState(reminder.assignee_id??''),[people,setPeople]=useState<Array<{id:string;full_name:string;role:string}>>([]),[entitySearch,setEntitySearch]=useState(''),[entity,setEntity]=useState<{type:ReminderEntityType;id:string;label:string}|null>(reminder.entity_type&&reminder.entity_id?{type:reminder.entity_type,id:reminder.entity_id,label:'موجودیت پیوندشده'}:null),[entityResults,setEntityResults]=useState<Array<{type:ReminderEntityType;id:string;label:string}>>([]);
 useEffect(()=>{void (async()=>{const {data}=await supabase.from('profiles').select('id,full_name,role').eq('is_active',true).neq('role','client').order('full_name');setPeople((data??[]) as Array<{id:string;full_name:string;role:string}>);})();if(!reminder.id)return;void (async()=>{const {data}=await supabase.from('reminder_checklist_items').select('id,title,is_done').eq('reminder_id',reminder.id).order('position');setItems((data??[]) as Array<{id:string;title:string;is_done:boolean}>);})();},[reminder.id]);
 const save=async()=>{if(!reminder.id){onClose();return;}setSaving(true);const {error}=await supabase.from('operational_reminders').update({title:title.trim()||'یادآور جدید',notes:notes.trim()||null,priority,kind,visibility,assignee_id:assigneeId||null,entity_type:entity?.type??null,entity_id:entity?.id??null,alarm_offsets_min:offsets,recurrence_rule:recurrence.trim()?recurrence.trim():null,tags:tagText.split(/\s+/).filter(Boolean)}).eq('id',reminder.id);setSaving(false);if(error)return;onSaved();};
 const addCheck=async()=>{if(!check.trim()||!reminder.id)return;const {data,error}=await supabase.from('reminder_checklist_items').insert({reminder_id:reminder.id,title:check.trim(),position:items.length}).select('id,title,is_done').single();if(!error&&data){setItems(x=>[...x,data as {id:string;title:string;is_done:boolean}]);setCheck('');}};
 const toggleCheck=async(item:{id:string;title:string;is_done:boolean})=>{const next=!item.is_done;setItems(x=>x.map(i=>i.id===item.id?{...i,is_done:next}:i));await supabase.from('reminder_checklist_items').update({is_done:next}).eq('id',item.id);};
 const removeCheck=async(id:string)=>{setItems(x=>x.filter(i=>i.id!==id));await supabase.from('reminder_checklist_items').delete().eq('id',id);};
 return <div className="fixed inset-0 z-[160] bg-black/55 flex items-end md:items-center justify-center" dir="rtl"><div className="w-full md:max-w-lg max-h-[94vh] overflow-auto rounded-t-[28px] md:rounded-[28px] border app-border bg-[var(--surface)] p-4 pb-[calc(18px+env(safe-area-inset-bottom))] shadow-2xl"><div className="flex items-center justify-between gap-3 mb-3"><div><b className="text-lg">ویرایش یادآور</b><div className="text-xs app-muted mt-1">{formatJalaliDateTime(new Date(reminder.due_at))}</div></div><button onClick={onClose} className="min-w-11 min-h-11 rounded-xl border app-border"><X size={17}/></button></div>
  <div className="space-y-3">
   <input value={title} onChange={e=>setTitle(e.target.value)} className="w-full min-h-12 rounded-xl border app-border bg-[var(--surface-2)] px-3 outline-none"/><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="یادداشت" className="w-full min-h-24 rounded-xl border app-border bg-[var(--surface-2)] p-3 outline-none"/>
   <button onClick={onPicker} className="w-full min-h-12 rounded-xl border app-border bg-[var(--surface-2)] text-right px-3 flex items-center gap-2"><CalendarDays size={16}/><span className="flex-1">{formatJalaliDateTime(new Date(reminder.due_at))}</span><span className="text-xs app-muted">تغییر</span></button>
   <div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold">اولویت<select value={priority} onChange={e=>setPriority(e.target.value as ReminderPriority)} className="min-h-12 rounded-xl border app-border bg-[var(--surface-2)] px-3"><option value="low">کم</option><option value="normal">عادی</option><option value="high">زیاد</option><option value="urgent">فوری</option></select></label><label className="text-xs font-bold">دسته<select value={kind} onChange={e=>setKind(e.target.value as ReminderKind)} className="min-h-12 rounded-xl border app-border bg-[var(--surface-2)] px-3">{kinds.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label className="block text-xs font-bold mt-3">مسئول<select value={assigneeId} onChange={e=>setAssigneeId(e.target.value)} className="w-full mt-1 min-h-12 rounded-xl border app-border bg-[var(--surface-2)] px-3"><option value="">من</option>{people.map(p=><option key={p.id} value={p.id}>{p.full_name} · {p.role}</option>)}</select></label><div className="rounded-xl border app-border p-3"><div className="text-xs font-bold mb-2 flex items-center gap-1"><Bell size={14}/>هشدارها</div><div className="flex flex-wrap gap-2">{[[0,'سر وقت'],[10,'۱۰ دقیقه قبل'],[60,'۱ ساعت قبل'],[1440,'۱ روز قبل']].map(([v,l])=>{const n=Number(v);const on=offsets.includes(n);return <button key={n} onClick={()=>setOffsets(x=>on?x.filter(i=>i!==n):[...x,n].sort((a,b)=>a-b))} className={'min-h-9 px-3 rounded-full text-xs '+(on?'bg-[var(--primary)] text-white':'border app-border')}>{l}</button>})}</div></div>
   <div className="grid grid-cols-2 gap-2"><button onClick={()=>setRecurrence('RRULE:FREQ=DAILY')} className="min-h-11 rounded-xl border app-border flex items-center justify-center gap-1"><Repeat2 size={15}/>هر روز</button><button onClick={()=>setRecurrence('RRULE:FREQ=WEEKLY')} className="min-h-11 rounded-xl border app-border flex items-center justify-center gap-1"><Repeat2 size={15}/>هر هفته</button><button onClick={()=>setRecurrence('RRULE:FREQ=MONTHLY;X-JALALI=1')} className="min-h-11 rounded-xl border app-border">هر ماه</button><button onClick={()=>setRecurrence('RRULE:FREQ=YEARLY;X-JALALI=1')} className="min-h-11 rounded-xl border app-border">هر سال</button></div>
   <div className="rounded-xl border app-border p-3"><div className="text-xs font-bold mb-2">پیوند به موجودیت</div><input value={entitySearch} onChange={e=>{const q=e.target.value.trim();setEntitySearch(q);if(q.length<2){setEntityResults([]);return;}void (async()=>{const [s,d]=await Promise.all([supabase.from('shipments').select('id,display_name,bill_of_lading_no').or('display_name.ilike.%'+q+'%,bill_of_lading_no.ilike.%'+q+'%').limit(5),supabase.from('customs_documents').select('id,display_name,original_name,document_number').or('display_name.ilike.%'+q+'%,original_name.ilike.%'+q+'%,document_number.ilike.%'+q+'%').limit(5)]);const results:Array<{type:ReminderEntityType;id:string;label:string}>=[];for(const x of (s.data??[]) as Array<{id:string;display_name:string|null;bill_of_lading_no:string|null}>)results.push({type:'shipments',id:x.id,label:x.display_name??x.bill_of_lading_no??'محموله'});for(const x of (d.data??[]) as Array<{id:string;display_name:string|null;original_name:string;document_number:string|null}>)results.push({type:'customs_documents',id:x.id,label:x.display_name??x.original_name});setEntityResults(results);})();}}} placeholder="جستجوی محموله یا سند" className="w-full min-h-11 rounded-xl border app-border bg-[var(--surface-2)] px-3"/>{entity&&<div className="text-[11px] mt-2 text-[var(--primary)]">انتخاب‌شده: {entity.label}<button onClick={()=>setEntity(null)} className="mr-2 underline">حذف</button></div>}{entityResults.length>0&&<div className="mt-2 space-y-1">{entityResults.map(x=><button key={x.type+x.id} onClick={()=>{setEntity(x);setEntitySearch('');setEntityResults([])}} className="w-full min-h-10 rounded-lg border app-border px-3 text-right text-xs">{x.label}</button>)}</div>}</div><input value={tagText} onChange={e=>setTagText(e.target.value)} placeholder="برچسب‌ها با فاصله" className="w-full min-h-11 rounded-xl border app-border bg-[var(--surface-2)] px-3"/>
   <div className="rounded-xl border app-border p-3"><div className="text-xs font-bold flex items-center gap-1"><ListChecks size={14}/>چک‌لیست</div>{items.map(item=><div key={item.id} className="flex items-center gap-2 mt-2"><button onClick={()=>void toggleCheck(item)} className={'min-w-9 min-h-9 rounded-lg border app-border '+(item.is_done?'bg-emerald-600 text-white':'')}>{item.is_done?<Check size={15}/>:''}</button><span className={'text-xs flex-1 '+(item.is_done?'line-through opacity-50':'')}>{item.title}</span><button onClick={()=>void removeCheck(item.id)} className="min-w-9 min-h-9"><Trash2 size={14}/></button></div>)}<div className="flex gap-2 mt-3"><input value={check} onChange={e=>setCheck(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void addCheck()}}} placeholder="مورد جدید" className="flex-1 min-h-10 rounded-lg border app-border bg-[var(--surface-2)] px-3"/><button onClick={()=>void addCheck()} className="min-w-10 min-h-10 rounded-lg bg-[var(--primary)] text-white"><Plus size={15}/></button></div></div>
   <div className="grid grid-cols-2 gap-2"><button onClick={save} disabled={saving} className="min-h-12 rounded-xl bg-[var(--primary)] text-white font-black">{saving?'در حال ذخیره…':'ذخیره تغییرات'}</button><button onClick={onClose} className="min-h-12 rounded-xl border app-border">انصراف</button></div>
  </div>
 </div></div>;
};

const PushSettings:React.FC<{allowed:boolean;devices:Array<{id:string;platform:string|null;user_agent:string|null;last_seen_at:string;is_active:boolean;failure_count:number}>;busy:boolean;onClose:()=>void;setBusy:(v:boolean)=>void;reloadDevices:()=>Promise<void>}>=({allowed,devices,busy,onClose,setBusy,reloadDevices})=>{
 const [permission,setPermission]=useState<NotificationPermission>(typeof Notification==='undefined'?'default':Notification.permission);
 const [hide,setHide]=useState(false);
 const toggle=async()=>{setBusy(true);try{if(permission==='granted'){await disablePush();setPermission('default');}else{const r=await enablePush();setPermission(r.status==='granted'?'granted':r.status as NotificationPermission);}}catch(e){alert(errorFa(e));}finally{setBusy(false);void reloadDevices();}};
 const test=async()=>{setBusy(true);try{await testPush();}catch(e){alert(errorFa(e));}finally{setBusy(false);}};
 const saveHide=async(v:boolean)=>{setHide(v);try{await setNotificationPreferences({hide_content:v})}catch{}};
 return <div className="fixed inset-0 z-[180] bg-black/55 flex items-end md:items-center justify-center" dir="rtl"><div className="w-full md:max-w-lg max-h-[90vh] overflow-auto rounded-t-[28px] md:rounded-[28px] border app-border bg-[var(--surface)] p-4 pb-[calc(18px+env(safe-area-inset-bottom))]"><div className="flex items-center justify-between"><div><b className="text-lg">اعلان‌ها</b><div className="text-xs app-muted mt-1">اعلان واقعی دستگاه‌های شما</div></div><button onClick={onClose} className="min-w-11 min-h-11 border app-border rounded-xl"><X size={17}/></button></div>
  {!allowed?<div className="mt-4 rounded-xl bg-amber-500/10 border border-amber-500/20 p-3 text-sm">برای حساب صاحب کالا اعلان داخلی فعال نمی‌شود.</div>:<><div className="mt-4 rounded-2xl border app-border p-3"><div className="flex items-center gap-3"><div className="flex-1"><div className="font-bold text-sm">وضعیت اعلان</div><div className="text-xs app-muted mt-1">{permission==='granted'?'فعال':'فعال نیست'}</div></div><button disabled={busy} onClick={()=>void toggle()} className={'min-h-11 px-4 rounded-xl font-bold '+(permission==='granted'?'border app-border':'bg-[var(--primary)] text-white')}>{permission==='granted'?'غیرفعال‌سازی':'فعال‌سازی'}</button></div><button disabled={busy||permission!=='granted'} onClick={()=>void test()} className="w-full min-h-11 rounded-xl border app-border mt-2 disabled:opacity-40">ارسال اعلان آزمایشی</button></div>
   <label className="flex items-center gap-3 mt-3 p-3 rounded-2xl border app-border"><input type="checkbox" checked={hide} onChange={e=>void saveHide(e.target.checked)} className="w-5 h-5"/><span><b className="block text-sm">پنهان کردن متن اعلان</b><span className="text-xs app-muted">به‌جای عنوان، متن عمومی نمایش داده می‌شود.</span></span></label>
   <div className="mt-4"><div className="font-bold text-sm mb-2 flex items-center gap-1"><Users size={15}/>دستگاه‌ها</div>{devices.length?devices.map(d=><div key={d.id} className="rounded-xl border app-border p-3 mb-2"><div className="text-sm font-bold">{d.platform==='ios'?'آیفون':d.platform==='android'?'اندروید':'رایانه'}</div><div className="text-[11px] app-muted mt-1">{new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'medium',timeZone:'Asia/Tehran'}).format(new Date(d.last_seen_at))}</div></div>):<div className="text-xs app-muted border app-border rounded-xl p-4">هنوز دستگاهی ثبت نشده است.</div>}</div></>}
 </div></div>;
};
