import React,{useState}from'react';
import{Check,Eye,FileText,Image as ImageIcon,Plus,RefreshCw,Save,Send,Trash2,UploadCloud,X,XCircle}from'lucide-react';
import{supabase}from'../../lib/supabase';
import{formatJalali}from'../../lib/jalali';
import{formatMoney}from'../../lib/finance';
import{ALL_SHIPMENT_COST_STAGES,createReceiptPath,displayReceiptName,formatIrr,jalaliInputToIso,isoToJalaliInput,parseAmount,SHIPMENT_COST_STAGES,ShipmentCost,ShipmentCostCategory,ShipmentCostStage,ShipmentCostType,STAGE_LABELS,sumApprovedByStage,todayIso,toReceiptMetadata,validateCostDraft,validateReceiptFile,WORKFLOW_LABELS}from'./shipmentCosts';
type Props={shipment:any;profile:any;onChanged:()=>Promise<void>|void;fixedStage?:ShipmentCostStage};
type Filter={stage:''|ShipmentCostType;status:''|ShipmentCost['workflow_status'];from:string;to:string;min:string;max:string;query:string};
type Draft={clientId:string;stage:ShipmentCostType;categoryId:string;categoryName:string;description:string;amount:string;currency:'IRR'|'USD'|'EUR';exchangeRate:string;paymentDate:string;paidBy:'our_company'|'client_direct';notes:string};
const roleCanWrite=(role:string)=>['owner','admin','broker','warehouse','accountant'].includes(role);
const roleCanManage=(role:string)=>['owner','admin'].includes(role);
const initialDraft=(shipment:any,fixedStage?:ShipmentCostStage):Draft=>({clientId:shipment.client_id||'',stage:fixedStage||'STAGE_1_SHIPMENT',categoryId:'',categoryName:'متفرقه',description:'',amount:'',currency:'IRR',exchangeRate:'1',paymentDate:todayIso(),paidBy:'our_company',notes:''});
const JalaliDateInput=({value,onChange,label,placeholder='۱۴۰۵/۰۷/۱۳'}:{value:string;onChange:(iso:string)=>void;label:string;placeholder?:string})=>{
 const[text,setText]=useState(isoToJalaliInput(value));const[invalid,setInvalid]=useState(false);
 React.useEffect(()=>setText(isoToJalaliInput(value)),[value]);
 const commit=()=>{if(!text.trim()){setInvalid(true);return}try{const iso=jalaliInputToIso(text);if(!iso)throw new Error();onChange(iso);setInvalid(false)}catch{setInvalid(true)}};
 return <label className="text-xs app-muted">{label}<div className="relative mt-1"><input className="input" dir="ltr" inputMode="numeric" value={text} placeholder={placeholder} onChange={e=>{setText(e.target.value);setInvalid(false)}} onBlur={commit}/><span className="absolute left-3 top-3 text-[10px] app-muted">جلالی</span></div>{invalid&&<span className="text-[10px] text-red-700">تاریخ جلالی معتبر نیست.</span>}</label>;
};
export const ShipmentCostsPanel:React.FC<Props>=({shipment,profile,onChanged,fixedStage})=>{
 const[costs,setCosts]=useState<ShipmentCost[]>([]),[categories,setCategories]=useState<ShipmentCostCategory[]>([]),[canApprove,setCanApprove]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState('');
 const[filter,setFilter]=useState<Filter>({stage:fixedStage||'',status:'',from:'',to:'',min:'',max:'',query:''});
 const[open,setOpen]=useState(false),[draft,setDraft]=useState<Draft>(initialDraft(shipment,fixedStage)),[files,setFiles]=useState<File[]>([]),[drag,setDrag]=useState(false),[saving,setSaving]=useState(false),[editing,setEditing]=useState<ShipmentCost|null>(null),[decision,setDecision]=useState<ShipmentCost|null>(null),[decisionReason,setDecisionReason]=useState(''),[busyId,setBusyId]=useState(''),[preview,setPreview]=useState<{url:string;type:string;name:string}|null>(null);
 const inputRef=React.useRef<HTMLInputElement|null>(null);
 const load=async()=>{
  if(!shipment?.id||!profile?.organization_id)return;setLoading(true);setError('');
  const[{data:rows,error:re},{data:cats,error:ce},{data:perm}]=await Promise.all([
   supabase.from('finance_cost_items').select('*').eq('shipment_id',shipment.id).eq('organization_id',profile.organization_id).order('payment_date',{ascending:false}).order('created_at',{ascending:false}),
   supabase.from('finance_cost_categories').select('id,code,name_fa,is_active').eq('organization_id',profile.organization_id).eq('is_active',true).order('sort_order').order('name_fa'),
   supabase.from('financial_permissions').select('approve_other_expenses').eq('organization_id',profile.organization_id).eq('user_id',profile.id).maybeSingle(),
  ]);
  if(re)setError(re.message);if(ce)setError(ce.message);setCosts((rows||[]) as ShipmentCost[]);setCategories((cats||[]) as ShipmentCostCategory[]);setCanApprove(Boolean(perm?.approve_other_expenses)||roleCanManage(profile.role));setLoading(false);
 };
 React.useEffect(()=>{void load()},[shipment?.id,profile?.organization_id,profile?.id]);
 React.useEffect(()=>{setFilter(f=>({...f,stage:fixedStage||''}));setDraft(d=>({...d,stage:fixedStage||d.stage}))},[fixedStage]);
 const visible=React.useMemo(()=>costs.filter(x=>{if(x.deleted_at)return false;if(filter.stage&&x.cost_type!==filter.stage)return false;if(filter.status&&x.workflow_status!==filter.status)return false;if(filter.from&&x.payment_date<filter.from)return false;if(filter.to&&x.payment_date>filter.to)return false;const total=Number(x.amount_irr||0)+Number(x.vat_amount||0);if(filter.min&&total<parseAmount(filter.min))return false;if(filter.max&&total>parseAmount(filter.max))return false;if(filter.query&&!(x.cost_category+' '+x.description).toLowerCase().includes(filter.query.trim().toLowerCase()))return false;return true}),[costs,filter]);
 const stageTotals=sumApprovedByStage(costs);const grandTotal=Object.values(stageTotals).reduce((a,b)=>a+b,0);
 const canWrite=roleCanWrite(profile?.role||'');const canManage=roleCanManage(profile?.role||'')||canApprove;
 const resetForm=()=>{setDraft(initialDraft(shipment,fixedStage));setFiles([]);setEditing(null);setError('')};
 const chooseCategory=(id:string)=>{const cat=categories.find(c=>c.id===id);setDraft(d=>({...d,categoryId:id,categoryName:cat?.name_fa||d.categoryName}))};
 const addFiles=async(incoming:File[])=>{const next=[...files];for(const file of incoming){if(next.some(f=>f.name===file.name&&f.size===file.size&&f.lastModified===file.lastModified))continue;const checked=await validateReceiptFile(file);if(!checked.ok){setError(checked.error);continue}next.push(file)}setFiles(next)};
 const removeNewFile=(i:number)=>setFiles(v=>v.filter((_,index)=>index!==i));
 const previewLocal=(file:File)=>{const url=URL.createObjectURL(file);setPreview({url,type:file.type,name:file.name})};
 const uploadReceiptFiles=async()=>{
  const uploadedPaths:string[]=[];const metadata:ReturnType<typeof toReceiptMetadata>[]=[];
  try{for(const file of files){const extension=file.name.toLowerCase().endsWith('.jpeg')?'jpg':file.name.split('.').pop()!.toLowerCase();const path=createReceiptPath(profile.organization_id,profile.id,extension);const{error:e}=await supabase.storage.from('finance-receipts').upload(path,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(e)throw e;uploadedPaths.push(path);metadata.push(toReceiptMetadata(file,path,profile.id))}return{uploadedPaths,metadata}}catch(e){if(uploadedPaths.length)await supabase.storage.from('finance-receipts').remove(uploadedPaths);throw e}
 };
 const openEdit=(cost:ShipmentCost)=>{if(!canWrite||cost.workflow_status==='APPROVED'||cost.created_by!==profile.id)return;setEditing(cost);setDraft({clientId:cost.client_id,stage:cost.cost_type,categoryId:cost.category_id,categoryName:cost.cost_category,description:cost.description,amount:String(cost.amount),currency:(['IRR','USD','EUR'].includes(cost.currency)?cost.currency:'IRR') as Draft['currency'],exchangeRate:String(cost.exchange_rate||1),paymentDate:cost.payment_date,paidBy:cost.paid_by,notes:String((cost as any).notes||'')});setFiles([]);setOpen(true)};
 const saveDraft=async(submitAfter:boolean)=>{
  setMessage('');setError('');const validation=validateCostDraft(draft);if(validation){setError(validation);return}
  const hasExistingReceipt=(editing?.receipt_files||[]).length>0||Boolean(editing?.receipt_file_url);if(submitAfter&&!files.length&&!hasExistingReceipt){setError('برای ارسال هزینه، حداقل یک فیش پرداختی لازم است.');return}
  setSaving(true);let persisted=false;const newUploads:{uploadedPaths:string[];metadata:ReturnType<typeof toReceiptMetadata>[]}={uploadedPaths:[],metadata:[]};
  try{
   if(editing){
    const amount=parseAmount(draft.amount),rate=parseAmount(draft.exchangeRate),receiptFiles=[...(editing.receipt_files||[])];
    if(files.length){const uploaded=await uploadReceiptFiles();newUploads.uploadedPaths=uploaded.uploadedPaths;newUploads.metadata=uploaded.metadata;receiptFiles.push(...uploaded.metadata)}
    const payload:any={cost_type:draft.stage,cost_category:draft.categoryName.trim(),category_id:draft.categoryId,description:draft.description.trim(),amount,unit_price:amount,currency:draft.currency,exchange_rate:rate,amount_irr:Math.round(amount*rate*100)/100,payment_date:draft.paymentDate,paid_by:draft.paidBy,notes:draft.notes.trim()||null,receipt_files:receiptFiles,receipt_file_url:receiptFiles[0]?.path||editing.receipt_file_url||null,updated_by:profile.id,updated_at:new Date().toISOString()};
    const{error:e}=await supabase.from('finance_cost_items').update(payload).eq('id',editing.id).eq('organization_id',profile.organization_id);if(e)throw e;
    persisted=true;if(submitAfter){const{error:e2}=await supabase.rpc('submit_finance_shipment_cost',{p_cost_id:editing.id});if(e2)throw e2}
   }else{
    const uploaded=await uploadReceiptFiles();newUploads.uploadedPaths=uploaded.uploadedPaths;newUploads.metadata=uploaded.metadata;
    const{data:created,error:e}=await supabase.rpc('create_finance_shipment_cost',{p_shipment_id:shipment.id,p_client_id:draft.clientId,p_cost_type:draft.stage,p_category_id:draft.categoryId,p_cost_category:draft.categoryName,p_description:draft.description,p_amount:parseAmount(draft.amount),p_currency:draft.currency,p_exchange_rate:parseAmount(draft.exchangeRate),p_payment_date:draft.paymentDate,p_paid_by:draft.paidBy,p_receipt_files:uploaded.metadata,p_notes:draft.notes||null});
    if(e)throw e;persisted=true;if(submitAfter){const{error:se}=await supabase.rpc('submit_finance_shipment_cost',{p_cost_id:(created as any)?.id});if(se)throw se}
   }
   setOpen(false);resetForm();setMessage(submitAfter?'هزینه برای تأیید مالی ارسال شد.':'پیش‌نویس هزینه ذخیره شد.');await load();await onChanged();
  }catch(e:any){if(!persisted&&newUploads.uploadedPaths.length)await supabase.storage.from('finance-receipts').remove(newUploads.uploadedPaths);setError(e?.message||'ذخیره هزینه ناموفق بود.')}finally{setSaving(false)}
 };
 const decide=async(approve:boolean)=>{if(!decision)return;if(!approve&&!decisionReason.trim()){setError('دلیل رد الزامی است.');return}setBusyId(decision.id);setError('');try{const{error:e}=await supabase.rpc('approve_finance_expense',{p_expense_id:decision.id,p_approve:approve,p_rejection_reason:approve?null:decisionReason.trim()});if(e)throw e;setDecision(null);setDecisionReason('');setMessage(approve?'هزینه تأیید شد.':'هزینه رد شد.');await load();await onChanged()}catch(e:any){setError(e?.message||'تصمیم مالی ناموفق بود.')}finally{setBusyId('')}};
 const archive=async(cost:ShipmentCost)=>{const reason=window.prompt('دلیل حذف/بایگانی هزینه را وارد کنید:','اشتباه در ثبت');if(!reason?.trim())return;setBusyId(cost.id);setError('');try{const{error:e}=await supabase.rpc('archive_finance_shipment_cost',{p_cost_id:cost.id,p_reason:reason.trim()});if(e)throw e;setMessage('هزینه به‌صورت Soft Delete بایگانی شد.');await load();await onChanged()}catch(e:any){setError(e?.message||'بایگانی هزینه ناموفق بود.')}finally{setBusyId('')}};
 const previewUrl=async(path:string,type:string,name:string)=>{const{data,error:e}=await supabase.storage.from('finance-receipts').createSignedUrl(path,600);if(e){setError(e.message);return}setPreview({url:data.signedUrl,type,name})};

 return <section className="space-y-4">
  <div className="grid grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6 gap-3">{(fixedStage?[fixedStage]:SHIPMENT_COST_STAGES).map(stage=><div key={stage} className="app-surface border app-border rounded-2xl p-4"><div className="text-xs app-muted">{STAGE_LABELS[stage]}</div><div className="font-black mt-2" dir="ltr">{formatIrr(stageTotals[stage])} <span className="text-xs font-normal">ریال</span></div></div>)}<div className="app-surface border app-border rounded-2xl p-4"><div className="text-xs app-muted">جمع کل تأییدشده</div><div className="font-black mt-2" dir="ltr">{formatIrr(grandTotal)} <span className="text-xs font-normal">ریال</span></div></div></div>
  <div className="app-surface border app-border rounded-2xl p-4">
   <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black flex items-center gap-2"><FileText size={18}/>هزینه‌های محموله</h2><p className="app-muted text-xs mt-1">{fixedStage?'ثبت مستقیم هزینه برای همین مرحله عملیاتی + فیش پرداختی + تأیید مالی':'ثبت هزینه در هر مرحله عملیات + فیش پرداختی + تأیید مالی'}</p></div>{canWrite&&<button onClick={()=>{resetForm();setOpen(true)}} className="px-4 py-3 rounded-xl bg-[var(--primary)] text-white font-bold text-sm inline-flex items-center gap-2"><Plus size={16}/>ثبت هزینه</button>}</div>
   <div className="grid md:grid-cols-4 xl:grid-cols-7 gap-2 mt-4">
    {!fixedStage&&<select className="input" value={filter.stage} onChange={e=>setFilter(f=>({...f,stage:e.target.value as Filter['stage']}))}><option value="">همه مراحل</option>{ALL_SHIPMENT_COST_STAGES.map(s=><option key={s} value={s}>{STAGE_LABELS[s]}</option>)}</select>}
    <select className="input" value={filter.status} onChange={e=>setFilter(f=>({...f,status:e.target.value as Filter['status']}))}><option value="">همه وضعیت‌ها</option>{(['DRAFT','SUBMITTED','APPROVED','REJECTED'] as const).map(s=><option key={s} value={s}>{WORKFLOW_LABELS[s]}</option>)}</select>
    <JalaliDateInput label="از تاریخ" value={filter.from} onChange={iso=>setFilter(f=>({...f,from:iso}))}/>
    <JalaliDateInput label="تا تاریخ" value={filter.to} onChange={iso=>setFilter(f=>({...f,to:iso}))}/>
    <input className="input" inputMode="decimal" dir="ltr" placeholder="حداقل مبلغ ریالی" value={filter.min} onChange={e=>setFilter(f=>({...f,min:e.target.value}))}/>
    <input className="input" inputMode="decimal" dir="ltr" placeholder="حداکثر مبلغ ریالی" value={filter.max} onChange={e=>setFilter(f=>({...f,max:e.target.value}))}/>
    <input className="input" placeholder="جستجوی دسته / شرح" value={filter.query} onChange={e=>setFilter(f=>({...f,query:e.target.value}))}/>
   </div>
   {loading&&<div className="py-12 text-center app-muted"><RefreshCw size={18} className="inline ml-2 animate-spin"/>در حال دریافت هزینه‌ها…</div>}
   {error&&<div className="mt-3 rounded-xl border border-red-500/30 bg-red-500/5 text-red-700 p-3 text-xs">{error}</div>}
   {message&&<div className="mt-3 rounded-xl border border-emerald-500/30 bg-emerald-500/5 text-emerald-700 p-3 text-xs">{message}</div>}
   {!loading&&<div className="overflow-auto mt-4"><table className="w-full text-sm min-w-[1120px]"><thead><tr className="border-b app-border"><th className="p-3 text-right">شرح</th><th>مرحله</th><th>دسته</th><th>تاریخ پرداخت</th><th>مبلغ</th><th>فیش</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>
    {visible.map(cost=><tr key={cost.id} className="border-b app-border/60 align-top"><td className="p-3"><b>{cost.description}</b><div className="text-[10px] app-muted mt-1">{cost.paid_by==='our_company'?'شرکت':'صاحب کالا'} · {cost.created_by===profile.id?'ثبت‌کننده: من':'ثبت‌کننده: کاربر دیگر'}</div>{cost.rejection_reason&&<div className="text-[10px] text-red-700 mt-1">دلیل رد: {cost.rejection_reason}</div>}</td><td><span className="text-xs font-bold">{STAGE_LABELS[cost.cost_type]}</span></td><td>{cost.cost_category}</td><td>{formatJalali(new Date(cost.payment_date+'T12:00:00Z'))}</td><td dir="ltr" className="font-bold">{formatMoney(Number(cost.amount_irr||0)+Number(cost.vat_amount||0),'IRR')}</td><td><div className="flex flex-wrap gap-1">{(cost.receipt_files||[]).map(r=><button key={r.id} onClick={()=>void previewUrl(r.path,r.mime_type,displayReceiptName(r))} className="px-2 py-1 rounded-lg border app-border text-[10px] inline-flex gap-1 items-center" title={displayReceiptName(r)}><Eye size={12}/>{r.mime_type==='application/pdf'?<FileText size={12}/>:<ImageIcon size={12}/>}</button>)}{cost.receipt_file_url&&!(cost.receipt_files||[]).length&&<button onClick={()=>void previewUrl(cost.receipt_file_url,'application/pdf','فیش قدیمی')} className="px-2 py-1 rounded-lg border app-border text-[10px]"><Eye size={12}/></button>}</div></td><td><span className={'px-2 py-1 rounded-full border text-[10px] font-bold '+(cost.workflow_status==='APPROVED'?'text-emerald-700 border-emerald-500/30 bg-emerald-500/10':cost.workflow_status==='REJECTED'?'text-red-700 border-red-500/30 bg-red-500/10':'text-amber-700 border-amber-500/30 bg-amber-500/10')}>{WORKFLOW_LABELS[cost.workflow_status]}</span></td><td><div className="flex flex-wrap gap-1">
     {cost.workflow_status!=='APPROVED'&&cost.created_by===profile.id&&<button onClick={()=>openEdit(cost)} className="px-2 py-1 rounded-lg border app-border text-[10px]"><Save size={12} className="inline ml-1"/>ویرایش</button>}
     {cost.workflow_status==='DRAFT'&&cost.created_by===profile.id&&<button onClick={()=>openEdit(cost)} className="px-2 py-1 rounded-lg border border-emerald-500/30 text-emerald-700 text-[10px]"><Send size={12} className="inline ml-1"/>ارسال</button>}
     {cost.workflow_status==='SUBMITTED'&&canManage&&cost.created_by!==profile.id&&<button onClick={()=>{setDecision(cost);setDecisionReason('')}} className="px-2 py-1 rounded-lg bg-[var(--primary)] text-white text-[10px]"><Check size={12} className="inline ml-1"/>تصمیم</button>}
     {cost.workflow_status!=='APPROVED'&&(cost.created_by===profile.id||canManage)&&<button disabled={busyId===cost.id} onClick={()=>void archive(cost)} className="px-2 py-1 rounded-lg border border-red-500/30 text-red-700 text-[10px]"><Trash2 size={12} className="inline ml-1"/>بایگانی</button>}
    </div></td></tr>)}
   </tbody></table>{!visible.length&&<div className="py-12 text-center app-muted">موردی مطابق فیلترها یافت نشد.</div>}</div>}
  </div>

  {open&&<div className="fixed inset-0 z-[120] bg-black/60 p-4 grid place-items-center"><div className="w-full max-w-4xl max-h-[94vh] overflow-auto rounded-3xl border app-border bg-[var(--surface)] p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-black">{editing?'ویرایش هزینه':'ثبت هزینه جدید'}</h3><p className="text-xs app-muted mt-1">{shipment.display_name||shipment.bill_of_lading_no||'محموله'} · فیش پرداختی خصوصی ذخیره می‌شود</p></div><button className="icon-btn" onClick={()=>{setOpen(false);resetForm()}}><X size={18}/></button></div>
   <div className="grid md:grid-cols-2 gap-3 mt-5">
    <label className="text-xs app-muted">مرحله هزینه<select className="input mt-1" disabled={!!fixedStage} value={draft.stage} onChange={e=>setDraft(d=>({...d,stage:e.target.value as ShipmentCostStage}))}>{ALL_SHIPMENT_COST_STAGES.map(s=><option key={s} value={s}>{STAGE_LABELS[s]}</option>)}</select></label>
    <label className="text-xs app-muted">دسته هزینه<select className="input mt-1" value={draft.categoryId} onChange={e=>chooseCategory(e.target.value)}><option value="">انتخاب دسته</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name_fa}</option>)}</select></label>
    <label className="text-xs app-muted md:col-span-2">عنوان دسته<input className="input mt-1" list="shipment-cost-categories" value={draft.categoryName} onChange={e=>setDraft(d=>({...d,categoryName:e.target.value}))}/></label><datalist id="shipment-cost-categories">{categories.map(c=><option key={c.id} value={c.name_fa}/>)}</datalist>
    <label className="text-xs app-muted md:col-span-2">شرح کامل*<textarea className="input mt-1 min-h-28" value={draft.description} onChange={e=>setDraft(d=>({...d,description:e.target.value}))} placeholder="علت هزینه، مرجع پرداخت، محل خدمت و توضیح کامل…"/></label>
    <label className="text-xs app-muted">مبلغ<input className="input mt-1" inputMode="decimal" dir="ltr" value={draft.amount} onChange={e=>setDraft(d=>({...d,amount:e.target.value}))}/></label>
    <label className="text-xs app-muted">ارز<select className="input mt-1" dir="ltr" value={draft.currency} onChange={e=>setDraft(d=>({...d,currency:e.target.value as Draft['currency'],exchangeRate:e.target.value==='IRR'?'1':d.exchangeRate}))}><option>IRR</option><option>USD</option><option>EUR</option></select></label>
    <label className="text-xs app-muted">نرخ تبدیل به ریال<input className="input mt-1" inputMode="decimal" dir="ltr" value={draft.exchangeRate} onChange={e=>setDraft(d=>({...d,exchangeRate:e.target.value}))} disabled={draft.currency==='IRR'}/></label>
    <JalaliDateInput label="تاریخ پرداخت*" value={draft.paymentDate} onChange={iso=>setDraft(d=>({...d,paymentDate:iso}))}/>
    <label className="text-xs app-muted">پرداخت‌کننده<select className="input mt-1" value={draft.paidBy} onChange={e=>setDraft(d=>({...d,paidBy:e.target.value as Draft['paidBy']}))}><option value="our_company">شرکت ما</option><option value="client_direct">صاحب کالا</option></select></label>
    <label className="text-xs app-muted md:col-span-2">یادداشت<textarea className="input mt-1 min-h-20" value={draft.notes} onChange={e=>setDraft(d=>({...d,notes:e.target.value}))}/></label>
   </div>
   <div className={'mt-5 rounded-2xl border-2 border-dashed p-6 text-center '+(drag?'border-[var(--primary)] bg-[var(--surface-2)]':'app-border')} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void addFiles(Array.from(e.dataTransfer.files))}}>
    <UploadCloud size={28} className="mx-auto app-muted"/><div className="font-bold mt-2">فیش‌های پرداختی</div><div className="text-xs app-muted mt-1">PDF / JPG / PNG · چند فایل · حداکثر ۱۰ مگابایت برای هر فایل</div><button type="button" onClick={()=>inputRef.current?.click()} className="mt-3 px-4 py-2 rounded-xl border app-border font-bold text-xs">انتخاب فایل</button><input ref={inputRef} type="file" multiple accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" className="hidden" onChange={e=>{void addFiles(Array.from(e.target.files||[]));e.currentTarget.value=''}}/>
    {!!files.length&&<div className="mt-4 grid sm:grid-cols-2 gap-3 text-right">{files.map((f,i)=><div key={f.name+i} className="rounded-xl border app-border p-3"><div className="flex items-center gap-2"><button type="button" onClick={()=>previewLocal(f)} className="shrink-0 grid place-items-center w-12 h-12 rounded-lg bg-[var(--surface-2)]">{f.type==='application/pdf'?<FileText size={22}/>:<ImageIcon size={22}/>}</button><div className="min-w-0 flex-1"><b className="block truncate text-xs">{f.name}</b><span className="text-[10px] app-muted">{Math.round(f.size/1024)} KB</span></div><button type="button" onClick={()=>removeNewFile(i)} className="icon-btn"><XCircle size={15}/></button></div></div>)}</div>}
   </div>
   <div className="mt-3 text-[10px] app-muted">پیش‌نویس بدون فیش قابل ذخیره است؛ ارسال برای تأیید مالی بدون حداقل یک فیش مجاز نیست.</div>
   <div className="flex flex-wrap justify-end gap-2 mt-5"><button className="px-4 py-3 rounded-xl border app-border font-bold text-sm" onClick={()=>{setOpen(false);resetForm()}}>انصراف</button><button className="px-4 py-3 rounded-xl border app-border font-bold text-sm" disabled={saving} onClick={()=>void saveDraft(false)}><Save size={15} className="inline ml-1"/>ذخیره پیش‌نویس</button><button className="px-4 py-3 rounded-xl bg-[var(--primary)] text-white font-bold text-sm disabled:opacity-40" disabled={saving} onClick={()=>void saveDraft(true)}><Send size={15} className="inline ml-1"/>{saving?'در حال ذخیره…':'ذخیره و ارسال برای تأیید'}</button></div>
   {error&&<div className="mt-3 rounded-xl border border-red-500/30 bg-red-500/5 p-3 text-xs text-red-700">{error}</div>}
  </div></div>}

  {decision&&<div className="fixed inset-0 z-[130] bg-black/60 p-4 grid place-items-center"><div className="w-full max-w-xl rounded-3xl border app-border bg-[var(--surface)] p-5"><h3 className="font-black text-lg">تأیید هزینه</h3><div className="rounded-2xl border app-border bg-[var(--surface-2)] p-4 mt-4"><b>{decision.description}</b><div className="text-xs app-muted mt-2">{STAGE_LABELS[decision.cost_type]} · {formatMoney(Number(decision.amount_irr||0)+Number(decision.vat_amount||0),'IRR')}</div></div><textarea className="input min-h-28 mt-4" placeholder="برای رد کردن، دلیل الزامی است…" value={decisionReason} onChange={e=>setDecisionReason(e.target.value)}/><div className="flex justify-end gap-2 mt-4"><button className="px-4 py-2 rounded-xl border app-border" onClick={()=>setDecision(null)}>انصراف</button><button className="px-4 py-2 rounded-xl bg-red-700 text-white" disabled={!!busyId} onClick={()=>void decide(false)}>رد هزینه</button><button className="px-4 py-2 rounded-xl bg-emerald-700 text-white" disabled={!!busyId} onClick={()=>void decide(true)}><Check size={15} className="inline ml-1"/>تأیید هزینه</button></div></div></div>}

  {preview&&<div className="fixed inset-0 z-[140] bg-black/70 p-4 grid place-items-center" onClick={()=>{if(preview.url.startsWith('blob:'))URL.revokeObjectURL(preview.url);setPreview(null)}}><div className="w-full max-w-5xl h-[90vh] rounded-2xl bg-black/30 overflow-hidden border border-white/10" onClick={e=>e.stopPropagation()}><div className="h-12 flex items-center justify-between px-3 bg-[var(--surface)]"><b className="text-xs truncate">{preview.name}</b><button className="icon-btn" onClick={()=>{if(preview.url.startsWith('blob:'))URL.revokeObjectURL(preview.url);setPreview(null)}}><X size={17}/></button></div>{preview.type==='application/pdf'?<iframe title={preview.name} src={preview.url} className="w-full h-[calc(90vh-3rem)] bg-white"/>:<div className="h-[calc(90vh-3rem)] grid place-items-center bg-black p-4"><img src={preview.url} alt={preview.name} className="max-h-full max-w-full object-contain"/></div>}</div></div>}
 </section>;
};
