import React,{useCallback,useEffect,useMemo,useState}from'react';
import{BarChart3,Download,GitMerge,LayoutList,Plus,Printer,RefreshCw,Search,Settings2,Tags,Upload,Users,Workflow}from'lucide-react';
import{supabase}from'../../lib/supabase';
import{useAuth}from'../../context/AuthContext';

type Tab='pipeline'|'contacts'|'quotes'|'analytics'|'automation'|'tools';
const csvEscape=(v:unknown)=>{const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s};
const download=(name:string,text:string,type='text/csv;charset=utf-8')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff',text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
const money=(n:number,c='IRR')=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:2}).format(n||0)+' '+c;

export const CRMPage:React.FC=()=>{
 const{profile}=useAuth();const org=profile?.organization_id;
 const[tabs]=useState<Tab[]>(['pipeline','contacts','quotes','analytics','automation','tools']);const[tab,setTab]=useState<Tab>('pipeline');
 const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const[stages,setStages]=useState<any[]>([]),[deals,setDeals]=useState<any[]>([]),[contacts,setContacts]=useState<any[]>([]),[leads,setLeads]=useState<any[]>([]),[quotes,setQuotes]=useState<any[]>([]);
 const[tags,setTags]=useState<any[]>([]),[fields,setFields]=useState<any[]>([]),[views,setViews]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]);
 const[search,setSearch]=useState('');const[modal,setModal]=useState<string|null>(null);const[form,setForm]=useState<Record<string,any>>({});
 const[analytics,setAnalytics]=useState<any>({});const[importErrors,setImportErrors]=useState<any[]>([]);
 const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));
 const load=useCallback(async()=>{
  if(!org)return;setLoading(true);
  try{
   const [p,s,d,c,l,q,t,cf,v,ar]=await Promise.all([
    supabase.from('crm_pipelines').select('*').eq('organization_id',org).is('deleted_at',null).order('created_at'),
    supabase.from('crm_pipeline_stages').select('*').order('position'),
    supabase.from('crm_deals').select('*').eq('organization_id',org).is('deleted_at',null).order('created_at',{ascending:false}),
    supabase.from('crm_contacts').select('*').eq('organization_id',org).is('deleted_at',null).order('full_name'),
    supabase.from('crm_leads').select('*').eq('organization_id',org).is('deleted_at',null).order('created_at',{ascending:false}),
    supabase.from('crm_quotes').select('*').eq('organization_id',org).is('deleted_at',null).order('created_at',{ascending:false}),
    supabase.from('crm_tags').select('*').eq('organization_id',org).is('deleted_at',null).order('name'),
    supabase.from('crm_custom_fields').select('*').eq('organization_id',org).is('deleted_at',null).order('position'),
    supabase.from('crm_saved_views').select('*').eq('organization_id',org).order('name'),
    supabase.from('crm_automation_rules').select('*').eq('organization_id',org).order('created_at',{ascending:false})
   ]);
   for(const r of[p,s,d,c,l,q,t,cf,v,ar])if(r.error)throw r.error;
   setStages(s.data??[]);setDeals(d.data??[]);setContacts(c.data??[]);setLeads(l.data??[]);setQuotes(q.data??[]);setTags(t.data??[]);setFields(cf.data??[]);setViews(v.data??[]);setRules(ar.data??[]);
   const [funnel,win,age,userPerf,forecast]=await Promise.all([
    supabase.rpc('crm_sales_funnel',{p_organization_id:org}),supabase.rpc('crm_win_rate',{p_organization_id:org}),supabase.rpc('crm_deal_age',{p_organization_id:org}),supabase.rpc('crm_user_performance',{p_organization_id:org}),supabase.rpc('crm_monthly_forecast',{p_organization_id:org})
   ]);
   if(funnel.error||win.error||age.error||userPerf.error||forecast.error)throw funnel.error||win.error||age.error||userPerf.error||forecast.error;
   setAnalytics({funnel:funnel.data??[],win:win.data??{},age:age.data??[],user:userPerf.data??[],forecast:forecast.data??[]});
  }catch(e){setError(e instanceof Error?e.message:'بارگذاری CRM ناموفق بود')}finally{setLoading(false)}
 },[org]);
 useEffect(()=>{void load()},[load]);

 const filteredContacts=useMemo(()=>contacts.filter(c=>!search||[c.full_name,c.phone,c.email].join(' ').toLowerCase().includes(search.toLowerCase())),[contacts,search]);
 const filteredDeals=useMemo(()=>deals.filter(d=>!search||[d.title,d.currency].join(' ').toLowerCase().includes(search.toLowerCase())),[deals,search]);

 const save=async()=>{
  if(!org)return;try{
   if(modal==='contact'){const r=await supabase.from('crm_contacts').insert({organization_id:org,full_name:form.full_name,phone:form.phone||null,email:form.email||null,job_title:form.job_title||null,notes:form.notes||null,created_by:profile?.id}).select().single();if(r.error)throw r.error}
   if(modal==='lead'){const r=await supabase.from('crm_leads').insert({organization_id:org,title:form.title,source:form.source||null,status:'new',value:Number(form.value)||0,currency:form.currency||'IRR',owner_id:profile?.id,notes:form.notes||null}).select().single();if(r.error)throw r.error}
   if(modal==='deal'){const stage=stages[0];const r=await supabase.from('crm_deals').insert({organization_id:org,pipeline_id:stage?.pipeline_id,stage_id:stage?.id,title:form.title,amount:Number(form.amount)||0,currency:form.currency||'IRR',client_id:form.client_id||null,contact_id:form.contact_id||null,owner_id:profile?.id,expected_close_date:form.expected_close_date||null,notes:form.notes||null}).select().single();if(r.error)throw r.error}
   if(modal==='tag'){const r=await supabase.from('crm_tags').insert({organization_id:org,name:form.name,color:form.color||null,created_by:profile?.id}).select().single();if(r.error)throw r.error}
   if(modal==='field'){const r=await supabase.from('crm_custom_fields').insert({organization_id:org,entity_type:form.entity_type||'contact',field_key:form.field_key,field_label:form.field_label,field_type:form.field_type||'text',options:form.options?form.options.split(',').map((x:string)=>x.trim()):[],required:Boolean(form.required),created_by:profile?.id}).select().single();if(r.error)throw r.error}
   if(modal==='view'){const r=await supabase.from('crm_saved_views').insert({organization_id:org,entity_type:form.entity_type||'deal',name:form.name,filters:form.filters?JSON.parse(form.filters):{},columns:form.columns?form.columns.split(',').map((x:string)=>x.trim()):[],shared:Boolean(form.shared),created_by:profile?.id}).select().single();if(r.error)throw r.error}
   if(modal==='rule'){const r=await supabase.from('crm_automation_rules').insert({organization_id:org,name:form.name,entity_type:form.entity_type||'deal',trigger_event:form.trigger_event||'created',conditions:form.conditions?JSON.parse(form.conditions):{},actions:form.actions?JSON.parse(form.actions):[],created_by:profile?.id}).select().single();if(r.error)throw r.error}
   setModal(null);setForm({});await load();
  }catch(e){setError(e instanceof Error?e.message:'ذخیره ناموفق بود')}
 };
 const move=async(d:any,stageId:string)=>{const r=await supabase.from('crm_deals').update({stage_id:stageId,updated_at:new Date().toISOString()}).eq('id',d.id).eq('organization_id',org);if(r.error)setError(r.error.message);else await load()};
 const exportCsv=()=>{const rows=tab==='contacts'?contacts:tab==='quotes'?quotes:deals;const keys=rows[0]?Object.keys(rows[0]):[];download('crm-'+tab+'.csv',[keys.join(','),...rows.map(r=>keys.map(k=>csvEscape(r[k])).join(','))].join('\n'))};
 const importCsv=async(file:File)=>{
  if(!org)return;const text=await file.text();const lines=text.replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return;
  const headers=lines[0].split(',').map(x=>x.replace(/^"|"$/g,'').trim());let imported=0;const errors:any[]=[];
  for(let i=1;i<lines.length;i++){const vals=lines[i].split(',').map(x=>x.replace(/^"|"$/g,'').replace(/""/g,'"'));const row=Object.fromEntries(headers.map((h,j)=>[h,vals[j]??'']));try{
   if(tab==='contacts'){const r=await supabase.from('crm_contacts').insert({organization_id:org,full_name:row.full_name||row.name,phone:row.phone||null,email:row.email||null,created_by:profile?.id});if(r.error)throw r.error}
   else if(tab==='leads'){const r=await supabase.from('crm_leads').insert({organization_id:org,title:row.title||row.name,source:row.source||null,status:row.status||'new',value:Number(row.value)||0,currency:row.currency||'IRR',owner_id:profile?.id});if(r.error)throw r.error}
   else{const r=await supabase.from('crm_deals').insert({organization_id:org,title:row.title||row.name,amount:Number(row.amount)||0,currency:row.currency||'IRR',owner_id:profile?.id,stage_id:stages[0]?.id,pipeline_id:stages[0]?.pipeline_id});if(r.error)throw r.error}
   imported++;
  }catch(e){errors.push({row:i+1,error:e instanceof Error?e.message:String(e)})}}
  setImportErrors(errors);await supabase.from('crm_import_jobs').insert({organization_id:org,entity_type:tab==='contacts'?'contact':tab==='leads'?'lead':'deal',source_format:'csv',filename:file.name,status:errors.length?'completed_with_errors':'completed',total_rows:lines.length-1,imported_rows:imported,skipped_rows:errors.length,error_rows:errors,created_by:profile?.id,finished_at:new Date().toISOString()});await load();
 };
 const detectDuplicates=async()=>{
  if(!org)return;const by=new Map<string,any[]>();contacts.forEach(c=>{const k=(c.email||c.phone||c.full_name||'').toLowerCase().replace(/\s+/g,'');if(k){const a=by.get(k)||[];a.push(c);by.set(k,a)}});let n=0;for(const arr of by.values())if(arr.length>1){await supabase.from('crm_dedupe_clusters').insert({organization_id:org,entity_type:'contact',master_id:arr[0].id,candidate_ids:arr.slice(1).map(x=>x.id),match_reason:{key:'email/phone/name'},status:'open'});n++}setError(n+' گروه تکراری شناسایی شد');await load()};
 const merge=async(c:any)=>{
  const dup=prompt('شناسه مخاطب تکراری را وارد کنید');if(!dup)return;const r=await supabase.rpc('crm_merge_contacts',{p_master:c.id,p_duplicate:dup,p_reason:'ادغام دستی از CRM'});if(r.error)setError(r.error.message);else await load()
 };
 const convertQuote=async(q:any)=>{const r=await supabase.rpc('crm_convert_quote_to_case_and_invoice',{p_quote_id:q.id});if(r.error)setError(r.error.message);else{setError('پیشنهاد به پرونده و فاکتور تبدیل شد');await load()}};
 const printQuote=(q:any)=>{const w=window.open('','_blank','width=900,height=1200');if(!w)return;w.document.write('<html dir="rtl"><head><title>'+q.quote_no+'</title><style>@page{size:A4;margin:16mm}body{font-family:Tahoma,Arial;direction:rtl;padding:20px}h1{font-size:24px}.row{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:10px 0}.total{font-size:20px;font-weight:700;margin-top:30px}</style></head><body><h1>پیشنهاد قیمت</h1><div class="row"><b>شماره</b><span>'+q.quote_no+'</span></div><div class="row"><b>عنوان</b><span>'+q.title+'</span></div><div class="row"><b>وضعیت</b><span>'+q.status+'</span></div><div class="row"><b>مبلغ پایه</b><span>'+money(q.subtotal,q.currency)+'</span></div><div class="row"><b>مالیات</b><span>'+money(q.tax,q.currency)+'</span></div><div class="total">جمع کل: '+money(q.total,q.currency)+'</div><p>'+String(q.notes||'').replace(/</g,'&lt;')+'</p><script>window.print()</script></body></html>');w.document.close()};
 const tabsLabels:any={pipeline:'فروش و قیف',contacts:'مخاطبان',quotes:'پیشنهاد قیمت',analytics:'گزارش ۳۶۰',automation:'اتوماسیون',tools:'ابزارها'};
 return <div dir="rtl" className="space-y-4">
  <header className="flex flex-wrap gap-3 items-center"><div className="flex-1"><h1 className="text-2xl font-bold">CRM سازمانی</h1><p className="app-muted text-sm">مخاطب، سرنخ، معامله، پیشنهاد قیمت، اتوماسیون و گزارش.</p></div><button className="icon-btn" onClick={()=>void load()}><RefreshCw size={18}/></button></header>
  <div className="flex gap-1 overflow-x-auto border-b app-border">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={'px-4 py-3 whitespace-nowrap '+(tab===t?'border-b-2 border-[var(--primary)] font-bold':'app-muted')}>{tabsLabels[t]}</button>)}</div>
  <div className="flex flex-wrap gap-2"><div className="flex-1 min-w-[220px] flex items-center gap-2 border app-border rounded-xl px-3"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} className="bg-transparent outline-none min-h-11 flex-1" placeholder="جست‌وجو"/></div><button className="btn-secondary" onClick={exportCsv}><Download size={16}/>CSV</button><label className="btn-secondary cursor-pointer"><Upload size={16}/>Import CSV<input type="file" accept=".csv,text/csv" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importCsv(f)}}/></label></div>
  {loading?<div className="app-card p-8 text-center app-muted">در حال بارگذاری…</div>:
  tab==='pipeline'?<div className="space-y-3"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[{l:'مخاطب',n:contacts.length},{l:'سرنخ',n:leads.length},{l:'معامله',n:deals.length},{l:'پیشنهاد',n:quotes.length}].map(x=><div className="app-card p-4" key={x.l}><div className="app-muted text-xs">{x.l}</div><div className="text-2xl font-bold mt-1">{x.n}</div></div>)}</div><div className="flex gap-2"><button className="btn-primary" onClick={()=>{setModal('deal');setForm({currency:'IRR'})}}><Plus size={16}/>معامله</button><button className="btn-secondary" onClick={()=>{setModal('lead');setForm({currency:'IRR'})}}><Plus size={16}/>سرنخ</button></div><div className="grid md:grid-cols-4 gap-3">{stages.map(s=><div className="app-card p-3 min-h-52" key={s.id}><div className="font-bold mb-3">{s.name}</div>{filteredDeals.filter(d=>d.stage_id===s.id).map(d=><div key={d.id} className="border app-border rounded-xl p-3 mb-2"><b>{d.title}</b><div className="text-xs app-muted mt-1">{money(Number(d.amount),d.currency)}</div><select value={d.stage_id} onChange={e=>void move(d,e.target.value)} className="mt-2 w-full bg-transparent border app-border rounded-lg p-1 text-xs">{stages.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>)}</div>)}</div></div>:
  tab==='contacts'?<div className="space-y-3"><div className="flex gap-2"><button className="btn-primary" onClick={()=>{setModal('contact');setForm({})}}><Plus size={16}/>مخاطب</button><button className="btn-secondary" onClick={()=>void detectDuplicates()}><GitMerge size={16}/>تشخیص تکراری</button></div><div className="grid md:grid-cols-2 gap-3">{filteredContacts.map(c=><div className="app-card p-4" key={c.id}><div className="flex items-center gap-2"><Users size={17}/><b>{c.full_name}</b></div><div className="text-sm app-muted mt-2">{c.phone||'—'} · {c.email||'—'}</div><div className="flex gap-2 mt-3"><button className="btn-secondary text-xs" onClick={()=>void merge(c)}>ادغام</button></div></div>)}</div></div>:
  tab==='quotes'?<div className="space-y-3"><button className="btn-primary" onClick={()=>setError('برای ساخت پیشنهاد ابتدا یک معامله ایجاد کنید؛ رابط اقلام پیشنهاد در مرحله بعد قابل تکمیل است.')}><Plus size={16}/>پیشنهاد جدید</button>{quotes.map(q=><div className="app-card p-4 flex flex-wrap gap-3 items-center" key={q.id}><div className="flex-1"><b>{q.quote_no} — {q.title}</b><div className="text-xs app-muted mt-1">{q.status} · {money(Number(q.total),q.currency)}</div></div><button className="btn-secondary" onClick={()=>printQuote(q)}><Printer size={16}/>A4</button><button className="btn-secondary" onClick={()=>void convertQuote(q)}>تبدیل به پرونده/فاکتور</button></div>)}</div>:
  tab==='analytics'?<div className="space-y-4"><div className="grid md:grid-cols-3 gap-3"><div className="app-card p-4"><b>نرخ برد</b><div className="text-3xl font-bold mt-2">{analytics.win?.rate??0}%</div></div><div className="app-card p-4"><b>ارزش قیف</b><div className="text-2xl font-bold mt-2">{money((analytics.funnel||[]).reduce((a:number,x:any)=>a+Number(x.total_amount||0),0))}</div></div><div className="app-card p-4"><b>معاملات</b><div className="text-3xl font-bold mt-2">{deals.length}</div></div></div><div className="app-card p-4"><h3 className="font-bold mb-3">قیف فروش</h3>{(analytics.funnel||[]).map((x:any)=><div className="flex items-center gap-3 mb-2" key={x.id}><span className="w-32 truncate">{x.name}</span><div className="flex-1 h-3 rounded-full bg-black/10"><div className="h-3 rounded-full bg-[var(--primary)]" style={{width:Math.min(100,Number(x.deal_count)*12)+'%'}}/></div><span>{x.deal_count}</span></div>)}</div><div className="app-card p-4"><h3 className="font-bold mb-3">پیش‌بینی ۶ ماهه</h3>{(analytics.forecast||[]).map((x:any)=><div className="flex justify-between py-2 border-b app-border" key={x.month_gregorian}><span>{new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'long'}).format(new Date(x.month_gregorian))}</span><b>{money(Number(x.forecast_amount))}</b></div>)}</div></div>:
  tab==='automation'?<div className="space-y-3"><button className="btn-primary" onClick={()=>{setModal('rule');setForm({})}}><Workflow size={16}/>قانون جدید</button>{rules.map(r=><div className="app-card p-4" key={r.id}><div className="flex justify-between"><b>{r.name}</b><span className="text-xs app-muted">{r.enabled?'فعال':'خاموش'}</span></div><div className="text-sm app-muted mt-1">{r.entity_type} · {r.trigger_event}</div></div>)}</div>:
  <div className="grid md:grid-cols-2 gap-3"><div className="app-card p-4"><h3 className="font-bold mb-3 flex gap-2"><Tags size={17}/>برچسب‌ها</h3><button className="btn-secondary mb-3" onClick={()=>setModal('tag')}><Plus size={15}/>برچسب</button>{tags.map(t=><span className="inline-block px-2 py-1 rounded-full text-xs border app-border ml-1 mb-1" key={t.id}>{t.name}</span>)}</div><div className="app-card p-4"><h3 className="font-bold mb-3 flex gap-2"><Settings2 size={17}/>فیلدهای سفارشی</h3><button className="btn-secondary mb-3" onClick={()=>setModal('field')}><Plus size={15}/>فیلد</button>{fields.map(f=><div className="text-sm py-2 border-b app-border" key={f.id}>{f.field_label} <span className="app-muted">({f.entity_type}/{f.field_type})</span></div>)}</div><div className="app-card p-4"><h3 className="font-bold mb-3 flex gap-2"><LayoutList size={17}/>نماهای ذخیره‌شده</h3><button className="btn-secondary" onClick={()=>setModal('view')}><Plus size={15}/>نما</button>{views.map(v=><div className="text-sm py-2" key={v.id}>{v.name}</div>)}</div><div className="app-card p-4"><h3 className="font-bold mb-3 flex gap-2"><BarChart3 size={17}/>وضعیت Import</h3><p className="text-sm app-muted">CSV با نگاشت مستقیم ستون‌های استاندارد فعال است. XLSX در این نسخه عمداً به‌دلیل نبود اندازه‌گیری باندل اضافه نشده است.</p>{importErrors.map(e=><div className="text-xs text-red-600" key={e.row}>ردیف {e.row}: {e.error}</div>)}</div></div>}
  {modal&&<div className="fixed inset-0 z-[600] bg-black/40 flex items-center justify-center p-3" onClick={()=>setModal(null)}><div className="w-full max-w-lg app-card p-5" onClick={e=>e.stopPropagation()}><h3 className="font-bold text-lg mb-4">{modal==='contact'?'مخاطب':modal==='lead'?'سرنخ':modal==='deal'?'معامله':modal==='tag'?'برچسب':modal==='field'?'فیلد سفارشی':modal==='view'?'نمای ذخیره‌شده':'قانون اتوماسیون'}</h3><div className="grid gap-3">{['contact','lead','deal'].includes(modal)&&<input className="input" placeholder="عنوان/نام" value={form[modal==='contact'?'full_name':'title']||''} onChange={e=>set(modal==='contact'?'full_name':'title',e.target.value)}/>} {modal==='contact'&&<><input className="input" placeholder="تلفن" value={form.phone||''} onChange={e=>set('phone',e.target.value)}/><input className="input" placeholder="ایمیل" value={form.email||''} onChange={e=>set('email',e.target.value)}/></>}{modal==='deal'&&<input className="input" type="number" placeholder="مبلغ" value={form.amount||''} onChange={e=>set('amount',e.target.value)}/>} {modal==='lead'&&<input className="input" type="number" placeholder="ارزش" value={form.value||''} onChange={e=>set('value',e.target.value)}/>} {modal==='tag'&&<input className="input" placeholder="نام برچسب" value={form.name||''} onChange={e=>set('name',e.target.value)}/>} {modal==='field'&&<><input className="input" placeholder="کلید" value={form.field_key||''} onChange={e=>set('field_key',e.target.value)}/><input className="input" placeholder="عنوان" value={form.field_label||''} onChange={e=>set('field_label',e.target.value)}/><input className="input" placeholder="نوع: text/number/date/select" value={form.field_type||''} onChange={e=>set('field_type',e.target.value)}/></>} {(modal==='view'||modal==='rule')&&<><input className="input" placeholder="نام" value={form.name||''} onChange={e=>set('name',e.target.value)}/><input className="input" placeholder="Entity type" value={form.entity_type||''} onChange={e=>set('entity_type',e.target.value)}/></>}<div className="flex gap-2 justify-end"><button className="btn-secondary" onClick={()=>setModal(null)}>لغو</button><button className="btn-primary" onClick={()=>void save()}>ذخیره</button></div></div></div></div>}
  {error&&<div className="fixed bottom-4 left-4 right-4 md:right-auto z-[700] max-w-xl app-card p-3 shadow-xl text-sm">{error}<button className="block text-xs app-muted mt-2" onClick={()=>setError(null)}>بستن</button></div>}
 </div>
};
