import React,{useCallback,useEffect,useMemo,useState}from'react';
import{BarChart3,Download,GitMerge,Hash,LayoutList,Plus,Printer,RefreshCw,Search,Settings2,Tags,Upload,Users,Workflow,X}from'lucide-react';
import{supabase}from'../../lib/supabase';
import{useAuth}from'../../context/AuthContext';

type Tab='pipeline'|'contacts'|'leads'|'quotes'|'analytics'|'automation'|'tools';
type ModalType='contact'|'lead'|'deal'|'quote'|'tag'|'field'|'view'|'rule';
const tabLabels:Record<Tab,string>={pipeline:'فروش و قیف',contacts:'مخاطبان',leads:'سرنخ‌ها',quotes:'پیشنهاد قیمت',analytics:'گزارش ۳۶۰',automation:'اتوماسیون',tools:'ابزارها'};
const modalLabels:Record<ModalType,string>={contact:'مخاطب',lead:'سرنخ',deal:'معامله',quote:'پیشنهاد قیمت',tag:'برچسب',field:'فیلد سفارشی',view:'نمای ذخیره‌شده',rule:'قانون اتوماسیون'};
const csvEscape=(value:unknown)=>{const text=String(value??'');return/[",\n]/.test(text)?'"'+text.replace(/"/g,'""')+'"':text};
const downloadCsv=(name:string,content:string)=>{const url=URL.createObjectURL(new Blob(['\ufeff',content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const money=(value:number,currency='IRR')=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:2}).format(Number(value)||0)+' '+currency;

export const CRMPage:React.FC=()=>{
 const{profile}=useAuth();
 const org=profile?.organization_id||'';
 const[tab,setTab]=useState<Tab>('pipeline');
 const[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[search,setSearch]=useState('');
 const[modal,setModal]=useState<ModalType|null>(null),[form,setForm]=useState<Record<string,any>>({}),[importErrors,setImportErrors]=useState<any[]>([]);
 const[stages,setStages]=useState<any[]>([]),[deals,setDeals]=useState<any[]>([]),[contacts,setContacts]=useState<any[]>([]),[leads,setLeads]=useState<any[]>([]),[quotes,setQuotes]=useState<any[]>([]),[tags,setTags]=useState<any[]>([]),[fields,setFields]=useState<any[]>([]),[views,setViews]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]),[analytics,setAnalytics]=useState<any>({funnel:[],win:{},forecast:[]});
 const setField=(key:string,value:any)=>setForm(prev=>({...prev,[key]:value}));

 const load=useCallback(async()=>{
  if(!org){setLoading(false);return}
  setLoading(true);setError(null);
  try{
   const rows=await Promise.all([
    supabase.from('crm_pipeline_stages').select('*').order('position'),
    supabase.from('crm_deals').select('*').eq('organization_id',org).is('deleted_at',null).order('created_at',{ascending:false}),
    supabase.from('crm_contacts').select('*').eq('organization_id',org).is('deleted_at',null).order('full_name'),
    supabase.from('crm_leads').select('*').eq('organization_id',org).is('deleted_at',null).order('created_at',{ascending:false}),
    supabase.from('crm_quotes').select('*').eq('organization_id',org).is('deleted_at',null).order('created_at',{ascending:false}),
    supabase.from('crm_tags').select('*').eq('organization_id',org).is('deleted_at',null).order('name'),
    supabase.from('crm_custom_fields').select('*').eq('organization_id',org).is('deleted_at',null).order('position'),
    supabase.from('crm_saved_views').select('*').eq('organization_id',org).order('name'),
    supabase.from('crm_automation_rules').select('*').eq('organization_id',org).order('created_at',{ascending:false}),
   ]);
   const failure=rows.find(row=>row.error)?.error;if(failure)throw failure;
   setStages(rows[0].data||[]);setDeals(rows[1].data||[]);setContacts(rows[2].data||[]);setLeads(rows[3].data||[]);setQuotes(rows[4].data||[]);setTags(rows[5].data||[]);setFields(rows[6].data||[]);setViews(rows[7].data||[]);setRules(rows[8].data||[]);
   const metrics=await Promise.all([supabase.rpc('crm_sales_funnel',{p_organization_id:org}),supabase.rpc('crm_win_rate',{p_organization_id:org}),supabase.rpc('crm_monthly_forecast',{p_organization_id:org})]);
   const metricFailure=metrics.find(row=>row.error)?.error;if(metricFailure)throw metricFailure;
   setAnalytics({funnel:metrics[0].data||[],win:metrics[1].data||{},forecast:metrics[2].data||[]});
  }catch(e){setError(e instanceof Error?e.message:'بارگذاری CRM ناموفق بود')}finally{setLoading(false)}
 },[org]);
 useEffect(()=>{void load()},[load]);

 const q=search.trim().toLowerCase();
 const filteredContacts=useMemo(()=>contacts.filter(x=>!q||[x.full_name,x.phone,x.email,x.job_title].join(' ').toLowerCase().includes(q)),[contacts,q]);
 const filteredLeads=useMemo(()=>leads.filter(x=>!q||[x.title,x.source,x.status,x.currency].join(' ').toLowerCase().includes(q)),[leads,q]);
 const filteredDeals=useMemo(()=>deals.filter(x=>!q||[x.title,x.currency].join(' ').toLowerCase().includes(q)),[deals,q]);

 const closeModal=()=>{setModal(null);setForm({});};
 const openModal=(type:ModalType,initial:Record<string,any>={})=>{setError(null);setForm(initial);setModal(type)};

 const save=async()=>{
  if(!org||!modal)return;
  try{
   if(modal==='contact'){const r=await supabase.from('crm_contacts').insert({organization_id:org,full_name:String(form.full_name||'').trim(),phone:form.phone||null,email:form.email||null,job_title:form.job_title||null,notes:form.notes||null,created_by:profile?.id}).select().single();if(r.error)throw r.error}
   else if(modal==='lead'){const r=await supabase.from('crm_leads').insert({organization_id:org,title:String(form.title||'').trim(),source:form.source||null,status:'new',value:Number(form.value)||0,currency:form.currency||'IRR',owner_id:profile?.id,notes:form.notes||null}).select().single();if(r.error)throw r.error}
   else if(modal==='deal'){const stage=stages.find(x=>x.id===form.stage_id)||stages[0];const r=await supabase.from('crm_deals').insert({organization_id:org,pipeline_id:form.pipeline_id||stage?.pipeline_id||null,stage_id:form.stage_id||stage?.id||null,title:String(form.title||'').trim(),amount:Number(form.amount)||0,currency:form.currency||'IRR',client_id:form.client_id||null,contact_id:form.contact_id||null,owner_id:profile?.id,notes:form.notes||null}).select().single();if(r.error)throw r.error}
   else if(modal==='quote'){const quantity=Math.max(1,Number(form.item_qty)||1);const unitPrice=Math.max(0,Number(form.item_unit_price)||0);const subtotal=quantity*unitPrice;const tax=Math.max(0,Number(form.tax)||0);const quote=await supabase.from('crm_quotes').insert({organization_id:org,deal_id:form.deal_id||null,client_id:form.client_id||null,quote_no:String(form.quote_no||('QT-'+Date.now())).trim(),title:String(form.title||'').trim(),subtotal:subtotal,tax:tax,total:subtotal+tax,currency:form.currency||'IRR',valid_until:form.valid_until||null,notes:form.notes||null,created_by:profile?.id}).select().single();if(quote.error)throw quote.error;const item=await supabase.from('crm_quote_items').insert({quote_id:quote.data.id,description:String(form.item_description||form.title||'').trim(),quantity:quantity,unit_price:unitPrice,position:0});if(item.error){await supabase.from('crm_quotes').update({deleted_at:new Date().toISOString()}).eq('id',quote.data.id);throw item.error}}
   else if(modal==='tag'){const r=await supabase.from('crm_tags').insert({organization_id:org,name:String(form.name||'').trim(),color:form.color||null,created_by:profile?.id}).select().single();if(r.error)throw r.error}
   else if(modal==='field'){const r=await supabase.from('crm_custom_fields').insert({organization_id:org,entity_type:form.entity_type||'contact',field_key:String(form.field_key||'').trim(),field_label:String(form.field_label||'').trim(),field_type:form.field_type||'text',options:form.options?String(form.options).split(',').map(x=>x.trim()).filter(Boolean):[],required:Boolean(form.required),created_by:profile?.id}).select().single();if(r.error)throw r.error}
   else if(modal==='view'){let filters:any={};try{filters=form.filters?JSON.parse(form.filters):{}}catch{throw new Error('فیلترهای نما معتبر نیست.')};const r=await supabase.from('crm_saved_views').insert({organization_id:org,entity_type:form.entity_type||'deal',name:String(form.name||'').trim(),filters:filters,columns:form.columns?String(form.columns).split(',').map(x=>x.trim()).filter(Boolean):[],shared:Boolean(form.shared),created_by:profile?.id}).select().single();if(r.error)throw r.error}
   else if(modal==='rule'){let conditions:any={};let actions:any[]=[];try{conditions=form.conditions?JSON.parse(form.conditions):{}}catch{throw new Error('Conditions معتبر نیست.')};try{actions=form.actions?JSON.parse(form.actions):[]}catch{throw new Error('Actions معتبر نیست.')};const r=await supabase.from('crm_automation_rules').insert({organization_id:org,name:String(form.name||'').trim(),entity_type:form.entity_type||'deal',trigger_event:form.trigger_event||'created',conditions:conditions,actions:actions,created_by:profile?.id}).select().single();if(r.error)throw r.error}
   closeModal();await load();
  }catch(e){setError(e instanceof Error?e.message:'ذخیره ناموفق بود')}
 };

 const moveDeal=async(deal:any,stageId:string)=>{if(!org)return;const r=await supabase.from('crm_deals').update({stage_id:stageId,updated_at:new Date().toISOString()}).eq('id',deal.id).eq('organization_id',org);if(r.error)setError(r.error.message);else await load()};

 const exportCsv=()=>{let rows:any[]=deals;if(tab==='contacts')rows=contacts;else if(tab==='leads')rows=leads;else if(tab==='quotes')rows=quotes;const keys=rows[0]?Object.keys(rows[0]):[];downloadCsv('crm-'+tab+'.csv',[keys.join(','),...rows.map(row=>keys.map(key=>csvEscape(row[key])).join(','))].join('\n'));};

 const importCsv=async(file:File)=>{
  if(!org)return;
  try{
   const lines=(await file.text()).replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return;
   const headers=lines[0].split(',').map(x=>x.replace(/^"|"$/g,'').trim());const errors:any[]=[];let imported=0;
   for(let i=1;i<lines.length;i++){
    const values=lines[i].split(',').map(x=>x.replace(/^"|"$/g,'').replace(/""/g,'"'));const row=Object.fromEntries(headers.map((header,index)=>[header,values[index]||'']));
    try{
     if(tab==='contacts'){const r=await supabase.from('crm_contacts').insert({organization_id:org,full_name:row.full_name||row.name||'',phone:row.phone||null,email:row.email||null,created_by:profile?.id});if(r.error)throw r.error}
     else if(tab==='leads'){const r=await supabase.from('crm_leads').insert({organization_id:org,title:row.title||row.name||'',source:row.source||null,status:row.status||'new',value:Number(row.value)||0,currency:row.currency||'IRR',owner_id:profile?.id});if(r.error)throw r.error}
     else{const stage=stages[0];const r=await supabase.from('crm_deals').insert({organization_id:org,title:row.title||row.name||'',amount:Number(row.amount)||0,currency:row.currency||'IRR',owner_id:profile?.id,stage_id:stage?.id||null,pipeline_id:stage?.pipeline_id||null});if(r.error)throw r.error}
     imported++;
    }catch(e){errors.push({row:i+1,error:e instanceof Error?e.message:String(e)})}
   }
   setImportErrors(errors);const entityType=tab==='contacts'?'contact':tab==='leads'?'lead':'deal';const job=await supabase.from('crm_import_jobs').insert({organization_id:org,entity_type:entityType,source_format:'csv',filename:file.name,status:errors.length?'completed_with_errors':'completed',total_rows:lines.length-1,imported_rows:imported,skipped_rows:errors.length,error_rows:errors,created_by:profile?.id,finished_at:new Date().toISOString()});if(job.error)throw job.error;await load();
  }catch(e){setError(e instanceof Error?e.message:'Import ناموفق بود')}
 };

 const detectDuplicates=async()=>{if(!org)return;const map=new Map<string,any[]>();contacts.forEach(contact=>{const key=String(contact.email||contact.phone||contact.full_name||'').toLowerCase().replace(/\s+/g,'').trim();if(!key)return;const list=map.get(key)||[];list.push(contact);map.set(key,list)});let clusters=0;for(const list of map.values()){if(list.length<2)continue;const r=await supabase.from('crm_dedupe_clusters').insert({organization_id:org,entity_type:'contact',master_id:list[0].id,candidate_ids:list.slice(1).map(x=>x.id),match_reason:{key:'email/phone/name'},status:'open'});if(r.error){setError(r.error.message);return}clusters++}setError(String(clusters)+' گروه تکراری شناسایی شد.');await load()};
 const mergeContact=async(contact:any)=>{const duplicateId=window.prompt('شناسه مخاطب تکراری را وارد کنید');if(!duplicateId)return;const r=await supabase.rpc('crm_merge_contacts',{p_master:contact.id,p_duplicate:duplicateId,p_reason:'ادغام دستی از CRM'});if(r.error)setError(r.error.message);else await load()};
 const convertQuote=async(quote:any)=>{const r=await supabase.rpc('crm_convert_quote_to_case_and_invoice',{p_quote_id:quote.id});if(r.error)setError(r.error.message);else{setError('پیشنهاد به پرونده و فاکتور تبدیل شد.');await load()}};
 const printQuote=(quote:any)=>{const w=window.open('','_blank','width=900,height=1200');if(!w)return;w.document.write('<html dir="rtl"><head><title>'+String(quote.quote_no||'')+'</title><style>@page{size:A4;margin:16mm}body{font-family:Tahoma,Arial;direction:rtl;padding:20px}.row{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:10px 0}.total{font-size:20px;font-weight:700;margin-top:30px}</style></head><body><h1>پیشنهاد قیمت</h1><div class="row"><b>شماره</b><span>'+String(quote.quote_no||'')+'</span></div><div class="row"><b>عنوان</b><span>'+String(quote.title||'')+'</span></div><div class="row"><b>وضعیت</b><span>'+String(quote.status||'')+'</span></div><div class="row"><b>مبلغ پایه</b><span>'+money(Number(quote.subtotal||0),quote.currency)+'</span></div><div class="row"><b>مالیات</b><span>'+money(Number(quote.tax||0),quote.currency)+'</span></div><div class="total">جمع کل: '+money(Number(quote.total||0),quote.currency)+'</div></body></html>');w.document.close();};

 const renderModalFields=()=>{
  if(!modal)return null;
  if(modal==='contact')return <><input className="input" placeholder="نام کامل" value={form.full_name||''} onChange={e=>setField('full_name',e.target.value)}/><input className="input" placeholder="تلفن" value={form.phone||''} onChange={e=>setField('phone',e.target.value)}/><input className="input" type="email" placeholder="ایمیل" value={form.email||''} onChange={e=>setField('email',e.target.value)}/><input className="input" placeholder="سمت" value={form.job_title||''} onChange={e=>setField('job_title',e.target.value)}/></>;
  if(modal==='lead')return <><input className="input" placeholder="عنوان سرنخ" value={form.title||''} onChange={e=>setField('title',e.target.value)}/><input className="input" placeholder="منبع" value={form.source||''} onChange={e=>setField('source',e.target.value)}/><input className="input" type="number" min="0" placeholder="ارزش" value={form.value??''} onChange={e=>setField('value',e.target.value)}/></>;
  if(modal==='deal')return <><input className="input" placeholder="عنوان معامله" value={form.title||''} onChange={e=>setField('title',e.target.value)}/><input className="input" type="number" min="0" placeholder="مبلغ" value={form.amount??''} onChange={e=>setField('amount',e.target.value)}/><select className="input" value={form.stage_id||stages[0]?.id||''} onChange={e=>setField('stage_id',e.target.value)}>{stages.map(stage=><option key={stage.id} value={stage.id}>{stage.name}</option>)}</select></>;
  if(modal==='quote')return <><input className="input" placeholder="عنوان پیشنهاد" value={form.title||''} onChange={e=>setField('title',e.target.value)}/><input className="input" placeholder="شماره پیشنهاد (اختیاری)" value={form.quote_no||''} onChange={e=>setField('quote_no',e.target.value)}/><input className="input" placeholder="شرح قلم" value={form.item_description||''} onChange={e=>setField('item_description',e.target.value)}/><input className="input" type="number" min="1" placeholder="تعداد" value={form.item_qty??1} onChange={e=>setField('item_qty',e.target.value)}/><input className="input" type="number" min="0" placeholder="قیمت واحد" value={form.item_unit_price??0} onChange={e=>setField('item_unit_price',e.target.value)}/><input className="input" type="number" min="0" placeholder="مالیات" value={form.tax??0} onChange={e=>setField('tax',e.target.value)}/><input className="input" type="date" value={form.valid_until||''} onChange={e=>setField('valid_until',e.target.value)}/><select className="input" value={form.deal_id||''} onChange={e=>setField('deal_id',e.target.value)}><option value="">بدون معامله</option>{deals.map(deal=><option key={deal.id} value={deal.id}>{deal.title}</option>)}</select></>;
  if(modal==='tag')return <input className="input" placeholder="نام برچسب" value={form.name||''} onChange={e=>setField('name',e.target.value)}/>;
  if(modal==='field')return <><input className="input" placeholder="کلید" value={form.field_key||''} onChange={e=>setField('field_key',e.target.value)}/><input className="input" placeholder="عنوان" value={form.field_label||''} onChange={e=>setField('field_label',e.target.value)}/><input className="input" placeholder="نوع: text/number/date/select" value={form.field_type||''} onChange={e=>setField('field_type',e.target.value)}/></>;
  if(modal==='view')return <><input className="input" placeholder="نام نما" value={form.name||''} onChange={e=>setField('name',e.target.value)}/><input className="input" placeholder="Entity type" value={form.entity_type||''} onChange={e=>setField('entity_type',e.target.value)}/><textarea className="input min-h-24" placeholder="Filters JSON" value={form.filters||''} onChange={e=>setField('filters',e.target.value)}/><input className="input" placeholder="ستون‌ها با کاما" value={form.columns||''} onChange={e=>setField('columns',e.target.value)}/></>;
  return <><input className="input" placeholder="نام قانون" value={form.name||''} onChange={e=>setField('name',e.target.value)}/><input className="input" placeholder="Entity type" value={form.entity_type||''} onChange={e=>setField('entity_type',e.target.value)}/><input className="input" placeholder="Trigger event" value={form.trigger_event||'created'} onChange={e=>setField('trigger_event',e.target.value)}/><textarea className="input min-h-24" placeholder="Conditions JSON" value={form.conditions||''} onChange={e=>setField('conditions',e.target.value)}/><textarea className="input min-h-24" placeholder="Actions JSON" value={form.actions||''} onChange={e=>setField('actions',e.target.value)}/></>;
 };

 return <div dir="rtl" className="space-y-4">
  <header className="flex flex-wrap items-center gap-3"><div className="flex-1 min-w-0"><h1 className="text-2xl font-bold">CRM سازمانی</h1><p className="app-muted text-sm">مخاطب، سرنخ، معامله، پیشنهاد قیمت، اتوماسیون و گزارش.</p></div><button className="icon-btn" onClick={()=>void load()} aria-label="تازه‌سازی"><RefreshCw size={18}/></button></header>
  <div className="flex gap-1 overflow-x-auto border-b app-border">{(Object.keys(tabLabels) as Tab[]).map(key=><button key={key} onClick={()=>setTab(key)} className={'px-4 py-3 whitespace-nowrap '+(tab===key?'border-b-2 border-[var(--primary)] font-bold':'app-muted')}>{tabLabels[key]}</button>)}</div>
  <div className="flex flex-wrap gap-2"><div className="flex-1 min-w-[220px] flex items-center gap-2 border app-border rounded-xl px-3"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} className="bg-transparent outline-none min-h-11 flex-1" placeholder="جست‌وجو"/></div><button className="btn-secondary" onClick={exportCsv}><Download size={16}/>CSV</button><label className="btn-secondary cursor-pointer"><Upload size={16}/>Import CSV<input type="file" accept=".csv,text/csv" hidden onChange={e=>{const file=e.target.files?.[0];e.currentTarget.value='';if(file)void importCsv(file)}}/></label></div>
  {loading&&<div className="app-card p-8 text-center app-muted">در حال بارگذاری…</div>}
  {!loading&&tab==='pipeline'&&<div className="space-y-3"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['مخاطب',contacts.length],['سرنخ',leads.length],['معامله',deals.length],['پیشنهاد',quotes.length]].map(item=><div className="app-card p-4" key={String(item[0])}><div className="app-muted text-xs">{item[0]}</div><div className="text-2xl font-bold mt-1">{item[1]}</div></div>)}</div><div className="flex flex-wrap gap-2"><button className="btn-primary" onClick={()=>openModal('deal',{currency:'IRR'})}><Plus size={16}/>معامله</button><button className="btn-secondary" onClick={()=>openModal('lead',{currency:'IRR'})}><Plus size={16}/>سرنخ</button></div><div className="grid md:grid-cols-4 gap-3">{stages.map(stage=><div className="app-card p-3 min-h-52" key={stage.id}><div className="font-bold mb-3">{stage.name}</div>{filteredDeals.filter(deal=>deal.stage_id===stage.id).map(deal=><div key={deal.id} className="border app-border rounded-xl p-3 mb-2"><b>{deal.title}</b><div className="text-xs app-muted mt-1">{money(Number(deal.amount),deal.currency)}</div><select value={deal.stage_id||''} onChange={e=>void moveDeal(deal,e.target.value)} className="mt-2 w-full bg-transparent border app-border rounded-lg p-1 text-xs">{stages.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></div>)}</div>)}</div></div>}
  {!loading&&tab==='contacts'&&<div className="space-y-3"><div className="flex gap-2"><button className="btn-primary" onClick={()=>openModal('contact')}><Plus size={16}/>مخاطب</button><button className="btn-secondary" onClick={()=>void detectDuplicates()}><GitMerge size={16}/>تشخیص تکراری</button></div><div className="grid md:grid-cols-2 gap-3">{filteredContacts.map(contact=><div className="app-card p-4" key={contact.id}><div className="flex items-center gap-2"><Users size={17}/><b>{contact.full_name}</b></div><div className="text-sm app-muted mt-2">{contact.phone||'—'} · {contact.email||'—'}</div><button className="btn-secondary text-xs mt-3" onClick={()=>void mergeContact(contact)}>ادغام</button></div>)}</div></div>}
  {!loading&&tab==='leads'&&<div className="space-y-3"><button className="btn-primary" onClick={()=>openModal('lead',{currency:'IRR'})}><Plus size={16}/>سرنخ جدید</button><div className="grid md:grid-cols-2 gap-3">{filteredLeads.map(lead=><div className="app-card p-4" key={lead.id}><div className="flex items-start justify-between gap-2"><div><b>{lead.title}</b><div className="text-xs app-muted mt-1">{lead.source||'بدون منبع'}</div></div><span className="text-xs rounded-full border app-border px-2 py-1">{lead.status||'new'}</span></div><div className="text-sm mt-3">{money(Number(lead.value),lead.currency)}</div></div>)}</div></div>}
  {!loading&&tab==='quotes'&&<div className="space-y-3"><button className="btn-primary" onClick={()=>openModal('quote',{currency:'IRR',item_qty:1,item_unit_price:0,tax:0})}><Plus size={16}/>پیشنهاد جدید</button>{quotes.map(quote=><div className="app-card p-4 flex flex-wrap gap-3 items-center" key={quote.id}><div className="flex-1 min-w-0"><b>{quote.quote_no} — {quote.title}</b><div className="text-xs app-muted mt-1">{quote.status} · {money(Number(quote.total),quote.currency)}</div></div><button className="btn-secondary" onClick={()=>printQuote(quote)}><Printer size={16}/>A4</button><button className="btn-secondary" onClick={()=>void convertQuote(quote)}>تبدیل به پرونده/فاکتور</button></div>)}</div>}
  {!loading&&tab==='analytics'&&<div className="space-y-4"><div className="grid md:grid-cols-3 gap-3"><div className="app-card p-4"><b>نرخ برد</b><div className="text-3xl font-bold mt-2">{analytics.win?.rate??0}%</div></div><div className="app-card p-4"><b>ارزش قیف</b><div className="text-2xl font-bold mt-2">{money((analytics.funnel||[]).reduce((sum:number,item:any)=>sum+Number(item.total_amount||0),0))}</div></div><div className="app-card p-4"><b>معاملات</b><div className="text-3xl font-bold mt-2">{deals.length}</div></div></div><div className="app-card p-4"><h3 className="font-bold mb-3 flex gap-2"><BarChart3 size={17}/>قیف فروش</h3>{(analytics.funnel||[]).map((item:any)=><div className="flex items-center gap-3 mb-2" key={item.id||item.name}><span className="w-32 truncate">{item.name}</span><div className="flex-1 h-3 rounded-full bg-black/10"><div className="h-3 rounded-full bg-[var(--primary)]" style={{width:Math.min(100,Number(item.deal_count||0)*12)+'%'}}/></div><span>{item.deal_count||0}</span></div>)}</div><div className="app-card p-4"><h3 className="font-bold mb-3">پیش‌بینی ۶ ماهه</h3>{(analytics.forecast||[]).map((item:any)=><div className="flex justify-between py-2 border-b app-border" key={item.month_gregorian}><span>{item.month_gregorian?new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'long'}).format(new Date(item.month_gregorian)):'—'}</span><b>{money(Number(item.forecast_amount||0))}</b></div>)}</div></div>}
  {!loading&&tab==='automation'&&<div className="space-y-3"><button className="btn-primary" onClick={()=>openModal('rule')}><Workflow size={16}/>قانون جدید</button>{rules.map(rule=><div className="app-card p-4" key={rule.id}><div className="flex justify-between"><b>{rule.name}</b><span className="text-xs app-muted">{rule.enabled?'فعال':'خاموش'}</span></div><div className="text-sm app-muted mt-1">{rule.entity_type} · {rule.trigger_event}</div></div>)}</div>}
  {!loading&&tab==='tools'&&<div className="grid md:grid-cols-2 gap-3"><div className="app-card p-4"><h3 className="font-bold mb-3 flex gap-2"><Tags size={17}/>برچسب‌ها</h3><button className="btn-secondary mb-3" onClick={()=>openModal('tag')}><Plus size={15}/>برچسب</button>{tags.map(tag=><span className="inline-block px-2 py-1 rounded-full text-xs border app-border ml-1 mb-1" key={tag.id}>{tag.name}</span>)}</div><div className="app-card p-4"><h3 className="font-bold mb-3 flex gap-2"><Settings2 size={17}/>فیلدهای سفارشی</h3><button className="btn-secondary mb-3" onClick={()=>openModal('field')}><Plus size={15}/>فیلد</button>{fields.map(field=><div className="text-sm py-2 border-b app-border" key={field.id}>{field.field_label} <span className="app-muted">({field.entity_type}/{field.field_type})</span></div>)}</div><div className="app-card p-4"><h3 className="font-bold mb-3 flex gap-2"><LayoutList size={17}/>نماهای ذخیره‌شده</h3><button className="btn-secondary" onClick={()=>openModal('view')}><Plus size={15}/>نما</button>{views.map(view=><div className="text-sm py-2" key={view.id}>{view.name}</div>)}</div><div className="app-card p-4"><h3 className="font-bold mb-3 flex gap-2"><Hash size={17}/>Import</h3><p className="text-sm app-muted">CSV برای مخاطب، سرنخ و معامله فعال است.</p>{importErrors.map(item=><div className="text-xs text-red-600" key={item.row}>ردیف {item.row}: {item.error}</div>)}</div></div>}
  {modal&&<div className="fixed inset-0 z-[600] bg-black/40 flex items-center justify-center p-3" onClick={closeModal}><div className="w-full max-w-lg app-card p-5 max-h-[90vh] overflow-auto" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-4"><h3 className="font-bold text-lg">{modalLabels[modal]}</h3><button className="icon-btn" onClick={closeModal}><X size={17}/></button></div><div className="grid gap-3">{renderModalFields()}<div className="flex gap-2 justify-end pt-2"><button className="btn-secondary" onClick={closeModal}>لغو</button><button className="btn-primary" onClick={()=>void save()}>ذخیره</button></div></div></div></div>}
  {error&&<div className="fixed bottom-4 left-4 right-4 md:right-auto z-[700] max-w-xl app-card p-3 shadow-xl text-sm">{error}<button className="block text-xs app-muted mt-2" onClick={()=>setError(null)}>بستن</button></div>}
 </div>;
};