import React,{useEffect,useState}from'react';
import{AlertTriangle,Bot,Check,FileCog,History,Plus,RefreshCw,Save,ShieldCheck,Trash2,UserCog}from'lucide-react';
import{useAuth}from'../context/AuthContext';
import{supabase}from'../lib/supabase';

const input='w-full min-h-10 rounded-xl border app-border bg-[var(--surface-2)] px-3 text-sm outline-none focus:border-[var(--primary)]';
const tabs=[['users','کاربران'],['rules','قواعد مدارک'],['categories','دسته هزینه'],['ai','AI Gateway'],['print','قالب چاپ'],['audit','Audit Log']] as const;
type Tab=typeof tabs[number][0];

export const AdvancedSettingsPage:React.FC=()=>{
 const{profile}=useAuth();const owner=profile?.role==='owner';const[tab,setTab]=useState<Tab>('ai');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[users,setUsers]=useState<any[]>([]);const[rules,setRules]=useState<any[]>([]);const[cats,setCats]=useState<any[]>([]);const[templates,setTemplates]=useState<any[]>([]);const[audit,setAudit]=useState<any[]>([]);const[gateway,setGateway]=useState<any>({enabled:true,online_enabled:true,preferred_provider:'gemini',fallback_providers:['cloudflare','groq','openrouter','openai'],confidence_threshold:.75,redaction_enabled:true,max_commands_per_minute:20});
 const[rule,setRule]=useState<any>({rule_name:'',document_type:'',condition_json:'{}',required:true,priority:100,note:'',is_active:true});
 const[cat,setCat]=useState<any>({code:'',name_fa:'',name_en:'',description:'',is_pass_through:false,is_billable_default:true,is_active:true,sort_order:999});
 const[tpl,setTpl]=useState<any>({template_key:'',name:'',document_type:'',html_template:'',css_text:'',is_active:true});
 const[newUser,setNewUser]=useState<any>({user_id:'',role:'client',client_id:'',full_name:'',phone:''});

 const load=async()=>{
  if(!owner)return;setBusy(true);setMessage('');
  try{
   const [u,r,c,t,g,a]=await Promise.all([
    supabase.from('profiles').select('id,full_name,phone,role,client_id,is_active,created_at').eq('organization_id',profile!.organization_id).order('full_name'),
    supabase.from('document_requirement_rules').select('*').eq('organization_id',profile!.organization_id).order('priority').order('rule_name'),
    supabase.from('finance_cost_categories').select('*').eq('organization_id',profile!.organization_id).order('sort_order').order('name_fa'),
    supabase.from('print_templates').select('*').eq('organization_id',profile!.organization_id).order('name'),
    supabase.from('ai_gateway_settings').select('*').eq('organization_id',profile!.organization_id).maybeSingle(),
    supabase.from('audit_logs').select('id,user_id,action,table_name,record_id,old_data,new_data,created_at').eq('organization_id',profile!.organization_id).order('created_at',{ascending:false}).limit(300)
   ]);
   const err=[u,r,c,t,g,a].find(x=>x.error)?.error;if(err)throw err;
   setUsers(u.data||[]);setRules(r.data||[]);setCats(c.data||[]);setTemplates(t.data||[]);if(g.data)setGateway(g.data);setAudit(a.data||[]);
  }catch(e:any){setMessage(e?.message||'دریافت تنظیمات پیشرفته ناموفق بود.')}finally{setBusy(false)}
 };
 useEffect(()=>{void load()},[owner,profile?.organization_id]);

 const saveGateway=async()=>{setBusy(true);try{const{error}=await supabase.from('ai_gateway_settings').upsert({...gateway,organization_id:profile!.organization_id,updated_by:profile!.id,updated_at:new Date().toISOString()},{onConflict:'organization_id'});if(error)throw error;setMessage('تنظیمات AI Gateway ذخیره شد.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const saveRule=async()=>{if(!rule.rule_name||!rule.document_type){setMessage('نام Rule و نوع سند الزامی است.');return}let condition:any={};try{condition=JSON.parse(rule.condition_json||'{}')}catch{setMessage('condition JSON معتبر نیست.');return}setBusy(true);try{const{error}=await supabase.from('document_requirement_rules').insert({...rule,condition_json:condition,organization_id:profile!.organization_id,created_by:profile!.id,updated_by:profile!.id});if(error)throw error;setRule({rule_name:'',document_type:'',condition_json:'{}',required:true,priority:100,note:'',is_active:true});await load();setMessage('Rule ایجاد شد.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const delRule=async(id:string)=>{if(!confirm('این Rule حذف شود؟'))return;const{error}=await supabase.from('document_requirement_rules').delete().eq('id',id);if(error)setMessage(error.message);else await load()};
 const saveCat=async()=>{if(!cat.name_fa){setMessage('نام فارسی دسته هزینه الزامی است.');return}setBusy(true);try{const{error}=await supabase.from('finance_cost_categories').insert({...cat,code:cat.code||'AI_'+Date.now(),organization_id:profile!.organization_id});if(error)throw error;setCat({code:'',name_fa:'',name_en:'',description:'',is_pass_through:false,is_billable_default:true,is_active:true,sort_order:999});await load();setMessage('دسته هزینه ایجاد شد.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const delCat=async(id:string)=>{if(!confirm('این دسته حذف شود؟'))return;const{error}=await supabase.from('finance_cost_categories').delete().eq('id',id);if(error)setMessage(error.message);else await load()};
 const saveTpl=async()=>{if(!tpl.template_key||!tpl.name||!tpl.document_type){setMessage('کلید، نام و نوع قالب الزامی است.');return}setBusy(true);try{const{error}=await supabase.from('print_templates').insert({...tpl,organization_id:profile!.organization_id,created_by:profile!.id,updated_by:profile!.id});if(error)throw error;setTpl({template_key:'',name:'',document_type:'',html_template:'',css_text:'',is_active:true});await load();setMessage('قالب چاپ ایجاد شد.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const delTpl=async(id:string)=>{if(!confirm('این قالب حذف شود؟'))return;const{error}=await supabase.from('print_templates').delete().eq('id',id);if(error)setMessage(error.message);else await load()};
 const updateUser=async(u:any)=>{const{error}=await supabase.from('profiles').update({role:u.role,is_active:u.is_active,full_name:u.full_name,phone:u.phone,updated_at:new Date().toISOString()}).eq('id',u.id);if(error)setMessage(error.message);else{await load();setMessage('اطلاعات کاربر ذخیره شد.')}};
 const createProfile=async()=>{if(!newUser.user_id||!newUser.full_name){setMessage('برای افزودن عضو موجود، User ID و نام الزامی است.');return}setBusy(true);try{const{error}=await supabase.rpc('owner_insert_profile',{p_user_id:newUser.user_id,p_role:newUser.role,p_client_id:newUser.client_id||null,p_full_name:newUser.full_name,p_phone:newUser.phone||null});if(error)throw error;setNewUser({user_id:'',role:'client',client_id:'',full_name:'',phone:''});await load();setMessage('پروفایل کاربر ایجاد شد.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};

 if(!owner)return <main dir="rtl" className="p-6"><div className="max-w-xl mx-auto rounded-2xl border border-red-500/30 bg-red-500/5 p-6 text-center"><ShieldCheck className="mx-auto mb-3 text-red-500"/><h1 className="font-black text-lg">دسترسی غیرمجاز</h1><p className="text-xs app-muted mt-2">تنظیمات پیشرفته فقط برای Owner در Backend و RLS قابل دسترسی است.</p></div></main>;

 return <main dir="rtl" className="min-h-screen p-4 md:p-6"><div className="max-w-[1600px] mx-auto">
  <header className="flex flex-wrap items-center justify-between gap-3 mb-5"><div><div className="text-[10px] app-muted">OWNER CONTROL PLANE</div><h1 className="text-2xl font-black">تنظیمات پیشرفته</h1><p className="text-xs app-muted mt-1">مدیریت مرکزی AI، قواعد مدارک، هزینه، قالب چاپ و Audit.</p></div><button className="icon-btn" onClick={()=>void load()} title="بروزرسانی"><RefreshCw size={17} className={busy?'animate-spin':''}/></button></header>
  <div className="flex gap-2 overflow-x-auto pb-2 mb-4">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-xl text-xs font-bold whitespace-nowrap border ${tab===id?'bg-[var(--primary)] text-white border-[var(--primary)]':'app-border bg-[var(--surface)]'}`}>{label}</button>)}</div>
  {message&&<div className="mb-4 rounded-xl border app-border bg-[var(--surface-2)] p-3 text-xs">{message}</div>}
  {tab==='ai'&&<section className="rounded-2xl border app-border bg-[var(--surface)] p-5 space-y-4"><div className="flex items-center gap-2"><Bot size={19} className="text-[var(--primary)]"/><div><h2 className="font-black">AI Gateway</h2><p className="text-xs app-muted">کلیدهای مدل فقط در Edge/Server نگهداری می‌شوند.</p></div></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={gateway.enabled!==false} onChange={e=>setGateway({...gateway,enabled:e.target.checked})}/> فعال بودن AI Operator</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={gateway.online_enabled!==false} onChange={e=>setGateway({...gateway,online_enabled:e.target.checked})}/> مدل آنلاین فعال</label><label>Provider<select className={input} value={gateway.preferred_provider||'gemini'} onChange={e=>setGateway({...gateway,preferred_provider:e.target.value})}><option>gemini</option><option>cloudflare</option><option>groq</option><option>openrouter</option><option>openai</option></select></label><label>Confidence<input className={input} type="number" min="0" max="1" step=".01" value={gateway.confidence_threshold??.75} onChange={e=>setGateway({...gateway,confidence_threshold:Number(e.target.value)})}/></label><label>Rate Limit / min<input className={input} type="number" min="1" max="120" value={gateway.max_commands_per_minute??20} onChange={e=>setGateway({...gateway,max_commands_per_minute:Number(e.target.value)})}/></label><label className="flex items-center gap-2 text-xs mt-6"><input type="checkbox" checked={gateway.redaction_enabled!==false} onChange={e=>setGateway({...gateway,redaction_enabled:e.target.checked})}/> Redaction فعال</label></div><div><div className="text-xs font-bold mb-2">Fallback</div><div className="flex flex-wrap gap-2">{['cloudflare','gemini','groq','openrouter','openai'].map(p=><label key={p} className="rounded-lg bg-[var(--surface-2)] px-3 py-2 text-xs"><input type="checkbox" className="ml-1" checked={(gateway.fallback_providers||[]).includes(p)} onChange={e=>setGateway({...gateway,fallback_providers:e.target.checked?Array.from(new Set([...(gateway.fallback_providers||[]),p])):(gateway.fallback_providers||[]).filter((x:string)=>x!==p)})}/>{p}</label>)}</div></div><button onClick={()=>void saveGateway()} disabled={busy} className="px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white text-xs font-bold inline-flex items-center gap-2"><Save size={14}/> ذخیره</button></section>}
  {tab==='users'&&<section className="space-y-4"><div className="rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="flex items-center gap-2 mb-3"><UserCog size={18}/><div><h2 className="font-black">کاربران و نقش‌ها</h2><p className="text-xs app-muted">تغییر نقش/وضعیت از RLS موجود عبور می‌کند؛ حذف فیزیکی پروفایل عمداً ممنوع است.</p></div></div><div className="grid lg:grid-cols-5 gap-2">{[newUser.user_id,newUser.full_name,newUser.phone,newUser.client_id].map((_,i)=>null)}<input className={input} placeholder="User ID عضو موجود" value={newUser.user_id} onChange={e=>setNewUser({...newUser,user_id:e.target.value})}/><input className={input} placeholder="نام کامل" value={newUser.full_name} onChange={e=>setNewUser({...newUser,full_name:e.target.value})}/><input className={input} placeholder="تلفن" value={newUser.phone} onChange={e=>setNewUser({...newUser,phone:e.target.value})}/><select className={input} value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}>{['client','warehouse','accountant','broker','admin','owner'].map(r=><option key={r}>{r}</option>)}</select><input className={input} placeholder="Client ID اختیاری" value={newUser.client_id} onChange={e=>setNewUser({...newUser,client_id:e.target.value})}/></div><button onClick={()=>void createProfile()} className="mt-3 px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white text-xs font-bold inline-flex items-center gap-2"><Plus size={14}/> ایجاد پروفایل عضو موجود</button></div><div className="grid lg:grid-cols-2 gap-3">{users.map(u=><div key={u.id} className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="text-xs app-muted break-all">{u.id}</div><input className={input+' mt-2'} value={u.full_name||''} onChange={e=>setUsers(xs=>xs.map(z=>z.id===u.id?{...z,full_name:e.target.value}:z))}/><input className={input+' mt-2'} value={u.phone||''} onChange={e=>setUsers(xs=>xs.map(z=>z.id===u.id?{...z,phone:e.target.value}:z))}/><div className="grid grid-cols-2 gap-2 mt-2"><select className={input} value={u.role} disabled={u.id===profile!.id} onChange={e=>setUsers(xs=>xs.map(z=>z.id===u.id?{...z,role:e.target.value}:z))}>{['client','warehouse','accountant','broker','admin','owner'].map(r=><option key={r}>{r}</option>)}</select><label className="min-h-10 rounded-xl border app-border bg-[var(--surface-2)] px-3 text-xs flex items-center gap-2"><input type="checkbox" checked={u.is_active} disabled={u.id===profile!.id} onChange={e=>setUsers(xs=>xs.map(z=>z.id===u.id?{...z,is_active:e.target.checked}:z))}/> فعال</label></div><button onClick={()=>void updateUser(u)} className="mt-3 px-3 py-2 rounded-xl border app-border text-xs font-bold"><Save size={13} className="inline ml-1"/> ذخیره کاربر</button></div>)}</div></section>}
  {tab==='rules'&&<section className="space-y-4"><div className="rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-2"><input className={input} placeholder="نام Rule" value={rule.rule_name} onChange={e=>setRule({...rule,rule_name:e.target.value})}/><input className={input} placeholder="نوع سند" value={rule.document_type} onChange={e=>setRule({...rule,document_type:e.target.value})}/><input className={input} placeholder="Priority" type="number" value={rule.priority} onChange={e=>setRule({...rule,priority:Number(e.target.value)})}/><input className={input} placeholder='Condition JSON' value={rule.condition_json} onChange={e=>setRule({...rule,condition_json:e.target.value})}/></div><textarea className={input+' mt-2'} placeholder="یادداشت" value={rule.note} onChange={e=>setRule({...rule,note:e.target.value})}/><button onClick={()=>void saveRule()} className="mt-2 px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white text-xs font-bold"><Plus size={14} className="inline ml-1"/> ایجاد Rule</button></div><div className="space-y-2">{rules.map(r=><div key={r.id} className="rounded-xl border app-border bg-[var(--surface)] p-3 flex flex-wrap items-center gap-3"><div className="flex-1 min-w-[220px]"><b className="text-sm">{r.rule_name}</b><div className="text-[10px] app-muted">{r.document_type} · priority {r.priority}</div></div><span className="text-xs">{r.required?'الزامی':'اختیاری'}</span><button className="text-red-500" onClick={()=>void delRule(r.id)}><Trash2 size={15}/></button></div>)}</div></section>}
  {tab==='categories'&&<section className="space-y-4"><div className="rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-2"><input className={input} placeholder="Code" value={cat.code} onChange={e=>setCat({...cat,code:e.target.value})}/><input className={input} placeholder="نام فارسی" value={cat.name_fa} onChange={e=>setCat({...cat,name_fa:e.target.value})}/><input className={input} placeholder="نام انگلیسی" value={cat.name_en} onChange={e=>setCat({...cat,name_en:e.target.value})}/><input className={input} type="number" placeholder="Sort" value={cat.sort_order} onChange={e=>setCat({...cat,sort_order:Number(e.target.value)})}/></div><button onClick={()=>void saveCat()} className="mt-2 px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white text-xs font-bold"><Plus size={14} className="inline ml-1"/> ایجاد دسته</button></div><div className="grid md:grid-cols-2 gap-2">{cats.map(c=><div key={c.id} className="rounded-xl border app-border bg-[var(--surface)] p-3 flex items-center justify-between"><div><b className="text-sm">{c.name_fa}</b><div className="text-[10px] app-muted">{c.code}</div></div><button className="text-red-500" onClick={()=>void delCat(c.id)}><Trash2 size={15}/></button></div>)}</div></section>}
  {tab==='print'&&<section className="space-y-4"><div className="rounded-2xl border app-border bg-[var(--surface)] p-5 grid md:grid-cols-2 gap-2"><input className={input} placeholder="Template Key" value={tpl.template_key} onChange={e=>setTpl({...tpl,template_key:e.target.value})}/><input className={input} placeholder="نام قالب" value={tpl.name} onChange={e=>setTpl({...tpl,name:e.target.value})}/><input className={input} placeholder="Document Type" value={tpl.document_type} onChange={e=>setTpl({...tpl,document_type:e.target.value})}/><textarea className={input} placeholder="HTML Template" value={tpl.html_template} onChange={e=>setTpl({...tpl,html_template:e.target.value})}/><textarea className={input} placeholder="CSS" value={tpl.css_text} onChange={e=>setTpl({...tpl,css_text:e.target.value})}/><button onClick={()=>void saveTpl()} className="px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white text-xs font-bold"><Plus size={14} className="inline ml-1"/> ایجاد قالب</button></div><div className="space-y-2">{templates.map(t=><div key={t.id} className="rounded-xl border app-border bg-[var(--surface)] p-3 flex justify-between"><div><b>{t.name}</b><div className="text-[10px] app-muted">{t.template_key} · {t.document_type}</div></div><button className="text-red-500" onClick={()=>void delTpl(t.id)}><Trash2 size={15}/></button></div>)}</div></section>}
  {tab==='audit'&&<section className="rounded-2xl border app-border bg-[var(--surface)] overflow-hidden"><div className="p-4 border-b app-border flex items-center gap-2"><History size={17}/><b>Audit Log — فقط خواندنی</b></div><div className="max-h-[70vh] overflow-auto">{audit.map(a=><details key={a.id} className="p-3 border-b app-border"><summary className="cursor-pointer text-xs"><b>{a.action}</b> · {a.table_name} · {a.created_at}</summary><pre className="mt-2 text-[9px] overflow-auto" dir="ltr">{JSON.stringify({user_id:a.user_id,record_id:a.record_id,old_data:a.old_data,new_data:a.new_data},null,2)}</pre></details>)}</div></section>}
 </div></main>;
};
