import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CheckCircle2,AlertCircle,FileCheck2,FileText,Loader2,ReceiptText,ShipWheel,WalletCards,Edit3,Trash2,Save,X} from 'lucide-react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../lib/supabase';

const labels:Record<string,string>={draft:'پیش‌نویس',registration_order:'ثبت سفارش',documents_ready:'اسناد آماده',epl_submitted:'اظهار ثبت شد',kottaj_received:'کوتاژ دریافت شد',path_green:'مسیر سبز',path_yellow:'مسیر زرد',path_red:'مسیر قرمز',valuation:'ارزش‌گذاری',duties_calculation:'محاسبه حقوق و عوارض',exit_permit:'مجوز خروج',completed:'تکمیل‌شده',archived:'بایگانی'};
const stages=['draft','registration_order','documents_ready','epl_submitted','kottaj_received','path','valuation','duties_calculation','exit_permit','completed','archived'];
const required=[['PROFORMA_INVOICE','پروفورما'],['COMMERCIAL_INVOICE','کامرشال اینویس'],['PACKING_LIST','پکینگ لیست'],['BILL_OF_LADING','B/L'],['CERTIFICATE_OF_ORIGIN','گواهی مبدأ']] as const;
const stageLabel=(s:string)=>labels[s]||s; const money=(n:any)=>n==null?'—':`${Number(n).toLocaleString('fa-IR')} ریال`;
type CaseRow={id:string;case_number:string|null;status:string;registration_order_no:string|null;warehouse_receipt_no:string|null;release_status:string|null;valuation_status:string|null;cargo_description:string|null;proforma_no:string|null;cargo_count:number|null;cargo_count_unit:string|null;net_weight_kg:number|null;gross_weight_kg:number|null};

export const CaseOperationsPage:React.FC=()=>{
 const[params]=useSearchParams(); const requested=params.get('caseId')||'';
 const[cases,setCases]=useState<CaseRow[]>([]),[selected,setSelected]=useState(requested),[docs,setDocs]=useState<any[]>([]),[decl,setDecl]=useState<any>(null),[permits,setPermits]=useState<any[]>([]),[exit,setExit]=useState<any>(null),[readiness,setReadiness]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(false),[form,setForm]=useState<any>({});
 const load=async(id:string)=>{setBusy(true);setError('');try{const{data:c,error:ce}=await supabase.from('cases').select('id,case_number,status,registration_order_no,warehouse_receipt_no,release_status,valuation_status,cargo_description,proforma_no,cargo_count,cargo_count_unit,net_weight_kg,gross_weight_kg').order('created_at',{ascending:false});if(ce)throw ce;const rows=(c||[]) as CaseRow[];setCases(rows);const id2=id&&rows.some(x=>x.id===id)?id:(rows[0]?.id||'');if(id2!==id)setSelected(id2);if(!id2){setDocs([]);setDecl(null);setPermits([]);setExit(null);setReadiness(null);return}const current=rows.find(x=>x.id===id2);if(current&&!editing)setForm({...current});
 const[{data:d,error:de},{data:dr,error:dre},{data:p,error:pe},{data:e,error:ee},{data:r,error:re}]=await Promise.all([supabase.from('customs_documents').select('document_type,status').eq('case_id',id2),supabase.from('customs_declarations').select('id,kottaj_number,customs_path,declaration_date,assessed_value_irr,total_duties_irr').eq('case_id',id2).order('created_at',{ascending:false}).limit(1),supabase.from('permits').select('id,permit_type,permit_number,issuing_authority,status,issued_at,expires_at').eq('case_id',id2).order('created_at',{ascending:false}),supabase.from('case_exit_operations').select('id,exit_status,exit_permit_number,exit_permit_date,authorized_at,exited_at,vehicle_plate,driver_name').eq('case_id',id2).order('updated_at',{ascending:false}).limit(1),supabase.rpc('get_case_completion_readiness',{p_case_id:id2})]);if(de)throw de;if(dre)throw dre;if(pe)throw pe;if(ee)throw ee;setDocs(d||[]);setDecl((dr||[])[0]||null);setPermits(p||[]);setExit((e||[])[0]||null);setReadiness(re?null:r||null)}catch(e:any){setError(e?.message||'دریافت اطلاعات پرونده ناموفق بود')}finally{setBusy(false)}};
 useEffect(()=>{void load(requested)},[requested]); useEffect(()=>{if(selected&&selected!==requested)void load(selected)},[selected]);
 const current=useMemo(()=>cases.find(x=>x.id===selected)||null,[cases,selected]);
 const approved=new Set(docs.filter(d=>d.status==='approved').map(d=>String(d.document_type||'').toUpperCase())); const docCount=required.filter(([t])=>approved.has(t)).length; const pathStage=current?.status?.startsWith('path_')?'path':current?.status||''; const idx=stages.indexOf(pathStage);
 const saveCase=async()=>{if(!current)return;setBusy(true);setError('');try{const payload={case_number:form.case_number?.trim()||null,registration_order_no:form.registration_order_no?.trim()||null,proforma_no:form.proforma_no?.trim()||null,cargo_description:form.cargo_description?.trim()||null,cargo_count:form.cargo_count===''||form.cargo_count==null?null:Number(form.cargo_count),cargo_count_unit:form.cargo_count_unit?.trim()||null,net_weight_kg:form.net_weight_kg===''||form.net_weight_kg==null?null:Number(form.net_weight_kg),gross_weight_kg:form.gross_weight_kg===''||form.gross_weight_kg==null?null:Number(form.gross_weight_kg),warehouse_receipt_no:form.warehouse_receipt_no?.trim()||null,release_status:form.release_status?.trim()||null,valuation_status:form.valuation_status?.trim()||null};const{error}=await supabase.from('cases').update(payload).eq('id',current.id);if(error)throw error;setEditing(false);await load(current.id)}catch(e:any){setError(e?.message||'ویرایش پرونده ناموفق بود')}finally{setBusy(false)}};
 const deleteCase=async()=>{if(!current)return;if(!window.confirm(`پرونده «${current.case_number||current.id.slice(0,8)}» حذف شود؟`))return;setBusy(true);setError('');try{const{error}=await supabase.rpc('delete_case_safely',{p_case_id:current.id});if(error)throw error;window.location.href='/operations?tab=case'}catch(e:any){setError(e?.message||'حذف پرونده انجام نشد')}finally{setBusy(false)}};
 const next=useMemo(()=>{if(!current)return null;switch(current.status){case'draft':return['/operations?tab=pre-declaration&caseId='+selected,'شروع/پیش‌اظهار'];case'registration_order':return['/operations?tab=declaration&caseId='+selected,'تکمیل اظهار'];case'documents_ready':return['/operations?tab=declaration&caseId='+selected,'ثبت اظهار EPL'];case'epl_submitted':return['/operations?tab=declaration&caseId='+selected,'ثبت کوتاژ و مسیر'];case'kottaj_received':return['/stage?caseId='+selected,'ادامه چک‌لیست'];case'path_green':case'path_yellow':case'path_red':case'valuation':return['/operations?tab=valuation&caseId='+selected,'ثبت ارزش‌گذاری'];case'duties_calculation':return['/operations?tab=duties&caseId='+selected,'ثبت محاسبه حقوق و عوارض'];case'exit_permit':return['/operations?tab=exit&caseId='+selected,'ثبت خروج'];default:return null}},[current,selected]);
 if(!current)return <main dir="rtl" className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8"><div className="max-w-6xl mx-auto space-y-4"><h1 className="text-2xl font-black">مدیریت پرونده</h1>{error&&<div className="p-4 rounded-xl border border-red-900 text-red-300">{error}</div>}<div className="p-5 rounded-2xl border border-slate-800 bg-slate-900">پرونده‌ای برای نمایش وجود ندارد.</div></div></main>;
 return <main dir="rtl" className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8"><div className="max-w-6xl mx-auto space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs text-cyan-400 font-bold">مدیریت پرونده</div><h1 className="text-2xl font-black mt-1">{current.case_number||current.id.slice(0,8)}</h1><p className="text-sm text-slate-400 mt-1">{current.cargo_description||'پرونده گمرکی'} · وضعیت: <b className="text-slate-200">{stageLabel(current.status)}</b></p></div><div className="flex gap-2"><button onClick={()=>{setForm({...current});setEditing(true)}} className="px-3 py-2 rounded-xl border border-amber-500/40 text-amber-300 text-sm"><Edit3 className="inline ml-1" size={15}/>ویرایش</button><button onClick={deleteCase} disabled={busy} className="px-3 py-2 rounded-xl border border-red-500/40 text-red-300 text-sm"><Trash2 className="inline ml-1" size={15}/>حذف</button><Link to="/" className="px-4 py-2 rounded-xl border border-slate-700 bg-slate-900"><ArrowLeft className="inline ml-2" size={16}/>صفحه اصلی</Link></div></header>
 {error&&<div className="p-4 rounded-xl border border-red-900 bg-red-950/20 text-red-300"><AlertCircle className="inline ml-2" size={16}/>{error}</div>}
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><label className="text-sm text-slate-400">انتخاب پرونده</label><select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3">{cases.map(c=><option key={c.id} value={c.id}>{c.case_number||c.id.slice(0,8)} — {stageLabel(c.status)}</option>)}</select></section>
 {editing&&<section className="rounded-2xl border border-amber-500/30 bg-slate-900 p-5"><div className="flex items-center justify-between mb-4"><h2 className="font-black">ویرایش پرونده</h2><button onClick={()=>setEditing(false)}><X size={18}/></button></div><div className="grid md:grid-cols-2 gap-3">{[['case_number','شماره پرونده'],['registration_order_no','شماره ثبت سفارش'],['proforma_no','شماره پروفرما'],['cargo_description','شرح کالا'],['cargo_count','تعداد'],['cargo_count_unit','واحد'],['net_weight_kg','وزن خالص (کیلوگرم)'],['gross_weight_kg','وزن ناخالص (کیلوگرم)'],['warehouse_receipt_no','شماره قبض انبار'],['release_status','وضعیت آزادسازی'],['valuation_status','وضعیت ارزش‌گذاری']].map(([k,l])=><label key={k} className="text-xs text-slate-400">{l}<input value={form[k]??''} onChange={e=>setForm((p:any)=>({...p,[k]:e.target.value}))} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm text-slate-100"/></label>)}</div><button onClick={saveCase} disabled={busy} className="mt-4 rounded-xl bg-cyan-600 px-5 py-3 font-bold"><Save className="inline ml-1" size={16}/>ذخیره تغییرات</button></section>}
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between gap-3 mb-4"><h2 className="font-black">گردش پرونده</h2><span className="text-xs text-cyan-300">{stageLabel(current.status)}</span></div><div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2">{stages.map((s,i)=>{const ok=i<idx||i===idx;const display=s==='path'?(current.status.startsWith('path_')?stageLabel(current.status):'مسیر گمرکی'):stageLabel(s);return <div key={s} className={`rounded-xl border p-2 text-center text-xs ${ok?'border-emerald-900 bg-emerald-950/20 text-emerald-300':'border-slate-800 bg-slate-950 text-slate-500'}`}><div>{ok?<CheckCircle2 className="mx-auto mb-1" size={15}/>:<div className="h-[15px] mb-1"/>}</div>{display}</div>})}</div></section>
 <div className="grid lg:grid-cols-2 gap-5"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-2 mb-4"><FileCheck2 className="text-cyan-400" size={20}/><h2 className="font-black">اسناد پایه</h2><span className="mr-auto text-sm">{docCount}/۵</span></div><div className="space-y-2">{required.map(([t,n])=>{const ok=approved.has(t);return <div key={t} className="flex items-center justify-between rounded-xl bg-slate-950 p-3"><span>{n}</span><span className={ok?'text-emerald-400':'text-amber-400'}>{ok?'تأیید شده':'نیازمند تأیید'}</span></div>})}</div><Link to={`/documents?caseId=${encodeURIComponent(selected)}`} className="mt-4 inline-block rounded-xl border border-slate-700 px-4 py-2 text-sm"><FileText className="inline ml-2" size={15}/>مدیریت اسناد</Link></section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-2 mb-4"><ShipWheel className="text-cyan-400" size={20}/><h2 className="font-black">اظهار و کوتاژ</h2></div><div className="grid grid-cols-2 gap-3"><Info t="ثبت سفارش" v={current.registration_order_no||'ثبت نشده'}/><Info t="کوتاژ" v={decl?.kottaj_number||'ثبت نشده'}/><Info t="مسیر گمرکی" v={decl?.customs_path?`مسیر ${decl.customs_path}`:'ثبت نشده'}/><Info t="قبض انبار" v={current.warehouse_receipt_no||'ثبت نشده'}/></div><Link to={`/operations?tab=declaration&caseId=${encodeURIComponent(selected)}`} className="mt-4 inline-block rounded-xl border border-slate-700 px-4 py-2 text-sm">اظهار / کوتاژ</Link></section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-2 mb-4"><ReceiptText className="text-cyan-400" size={20}/><h2 className="font-black">ارزش‌گذاری و حقوق</h2></div><div className="grid grid-cols-2 gap-3"><Info t="ارزش اظهار" v={money(decl?.assessed_value_irr)}/><Info t="وضعیت ارزش‌گذاری" v={current.valuation_status||'محاسبه نشده'}/><Info t="حقوق و عوارض" v={money(decl?.total_duties_irr)}/><Info t="آمادگی تکمیل" v={readiness?.ready===true?'آماده':'نیازمند اقدام'}/></div><div className="mt-4 flex flex-wrap gap-2"><Link to={`/operations?tab=valuation&caseId=${encodeURIComponent(selected)}`} className="rounded-xl border border-slate-700 px-4 py-2 text-sm">ارزش‌گذاری</Link><Link to={`/operations?tab=duties&caseId=${encodeURIComponent(selected)}`} className="rounded-xl border border-slate-700 px-4 py-2 text-sm">حقوق و عوارض</Link></div></section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-2 mb-4"><WalletCards className="text-cyan-400" size={20}/><h2 className="font-black">مجوزها و خروج</h2></div><div className="grid grid-cols-2 gap-3"><Info t="مجوزهای در انتظار" v={String(permits.filter(p=>p.status==='pending').length)}/><Info t="وضعیت آزادسازی" v={current.release_status||'ثبت نشده'}/><Info t="وضعیت خروج" v={exit?.exit_status||'ثبت نشده'}/><Info t="شماره مجوز خروج" v={exit?.exit_permit_number||'ثبت نشده'}/></div><Link to={`/operations?tab=exit&caseId=${encodeURIComponent(selected)}`} className="mt-4 inline-block rounded-xl border border-slate-700 px-4 py-2 text-sm">مدیریت خروج</Link></section></div>
 {next&&<section className="rounded-2xl border border-cyan-900 bg-cyan-950/20 p-5 flex flex-wrap items-center justify-between gap-3"><div><div className="font-black">اقدام بعدی</div><div className="text-sm text-slate-400 mt-1">{next[1]}</div></div><Link to={next[0]} className="rounded-xl bg-cyan-600 px-5 py-3 font-bold">ادامه عملیات</Link></section>}{busy&&<div className="text-center text-sm text-slate-500"><Loader2 className="inline ml-2 animate-spin" size={16}/>در حال به‌روزرسانی...</div>}</div></main>;
};
const Info=({t,v}:{t:string;v:string})=><div className="rounded-xl bg-slate-950 p-3"><div className="text-[11px] text-slate-500">{t}</div><div className="mt-1 text-sm font-bold break-words">{v}</div></div>;
