import React,{useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,History,Loader2,ShieldAlert} from 'lucide-react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../lib/supabase';

const labels:Record<string,string>={draft:'پیش‌نویس',registration_order:'ثبت سفارش',documents_ready:'اسناد آماده',epl_submitted:'اظهار ثبت شد',kottaj_received:'کوتاژ دریافت شد',path_green:'مسیر سبز',path_yellow:'مسیر زرد',path_red:'مسیر قرمز',valuation:'ارزش‌گذاری',duties_calculation:'محاسبه حقوق',exit_permit:'مجوز خروج',completed:'تکمیل‌شده',archived:'بایگانی'};
const stages=['registration_order','documents_ready','epl_submitted','kottaj_received','path_green','path_yellow','path_red','valuation','duties_calculation','exit_permit','completed','archived'];

export const CaseStagePage:React.FC=()=>{
 const [params]=useSearchParams();const caseId=params.get('caseId')||'';
 const [cases,setCases]=useState<any[]>([]),[selected,setSelected]=useState(''),[target,setTarget]=useState(''),[notes,setNotes]=useState(''),[current,setCurrent]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=async()=>{const {data,error}=await supabase.from('cases').select('id,case_number,status,client_id,created_at').order('created_at',{ascending:false});if(error){setError(error.message);return}setCases(data||[]);const id=caseId||selected;if(id&&data?.some(x=>x.id===id)){setSelected(id);setCurrent(data.find(x=>x.id===id));}};
 useEffect(()=>{load()},[caseId]);
 const choose=(id:string)=>{setSelected(id);setCurrent(cases.find(x=>x.id===id)||null);setTarget('');setMessage('');setError('')};
 const advance=async()=>{if(!selected)return setError('پرونده را انتخاب کنید.');if(!target)return setError('مرحله هدف را انتخاب کنید.');setBusy(true);setMessage('');setError('');try{const {data,error}=await supabase.rpc('advance_case_stage',{p_case_id:selected,p_target_status:target,p_notes:notes||null});if(error)throw error;setMessage(`مرحله پرونده به «${labels[data]||data}» تغییر کرد.`);setNotes('');setTarget('');await load()}catch(e:any){setError(e?.message||'عبور از مرحله انجام نشد')}finally{setBusy(false)}};
 return <main className="min-h-screen bg-slate-950 text-slate-100 p-5 md:p-8" dir="rtl"><div className="max-w-5xl mx-auto"><header className="flex flex-wrap items-center justify-between gap-4 mb-6"><div><div className="flex items-center gap-3"><ShieldAlert className="text-cyan-400" size={28}/><h1 className="text-2xl font-black">کنترل مراحل پرونده</h1></div><p className="text-sm text-slate-400 mt-2">عبور مرحله‌ای پرونده با کنترل پیش‌نیازهای عملیاتی در دیتابیس.</p></div><Link to={selected?`/operations?caseId=${encodeURIComponent(selected)}`:'/operations'} className="px-4 py-2 rounded-xl border border-slate-700 bg-slate-900"><ArrowRight className="inline ml-2" size={16}/> پرونده</Link></header>
 <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5 mb-5"><label className="text-sm text-slate-400">پرونده</label><select value={selected} onChange={e=>choose(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 p-3"> <option value="">انتخاب پرونده</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number||c.id.slice(0,8)} — {labels[c.status]||c.status}</option>)}</select>{current&&<div className="mt-4 grid md:grid-cols-3 gap-3"><Info t="شماره پرونده" v={current.case_number||'—'}/><Info t="وضعیت فعلی" v={labels[current.status]||current.status}/><Info t="شناسه" v={current.id}/></div>}</section>
 <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="grid md:grid-cols-2 gap-4"><div><label className="text-sm text-slate-400">مرحله هدف</label><select value={target} onChange={e=>setTarget(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 p-3"><option value="">انتخاب مرحله</option>{stages.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div><div><label className="text-sm text-slate-400">یادداشت تغییر مرحله</label><input value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 p-3" placeholder="اختیاری"/></div></div><button disabled={busy||!selected||!target} onClick={advance} className="mt-5 px-5 py-3 rounded-xl bg-cyan-600 disabled:opacity-50 font-bold">{busy?<><Loader2 className="inline ml-2 animate-spin" size={17}/> در حال بررسی پیش‌نیازها...</>:<><CheckCircle2 className="inline ml-2" size={17}/> بررسی و عبور مرحله</>}</button>{message&&<div className="mt-4 rounded-xl border border-emerald-900 bg-emerald-950/30 p-4 text-emerald-300">{message}</div>}{error&&<div className="mt-4 rounded-xl border border-red-900 bg-red-950/30 p-4 text-red-300 whitespace-pre-wrap">{error}</div>}</section>
 <section className="mt-5 bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex items-center gap-2 mb-3"><History className="text-cyan-400" size={20}/><h2 className="font-black">اصل کنترل</h2></div><p className="text-sm text-slate-400 leading-7">تغییر مرحله مستقیماً از جدول پرونده انجام نمی‌شود؛ تابع دیتابیس پیش‌نیازها را بررسی می‌کند و تغییر موفق را در تاریخچه وضعیت ثبت می‌کند.</p></section>
 </div></main>;
};
const Info=({t,v}:{t:string;v:string})=><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="text-xs text-slate-500">{t}</div><div className="mt-1 text-sm break-all">{v}</div></div>;
