import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,FileCheck2,FileText,History,Loader2,ShieldAlert,ShipWheel} from 'lucide-react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../lib/supabase';

const labels:Record<string,string>={draft:'پیش‌نویس',registration_order:'ثبت سفارش',documents_ready:'اسناد آماده',epl_submitted:'اظهار ثبت شد',kottaj_received:'کوتاژ دریافت شد',path_green:'مسیر سبز',path_yellow:'مسیر زرد',path_red:'مسیر قرمز',valuation:'ارزش‌گذاری',duties_calculation:'محاسبه حقوق',exit_permit:'مجوز خروج',completed:'تکمیل‌شده',archived:'بایگانی'};
const stages=['draft','registration_order','documents_ready','epl_submitted','kottaj_received','path_green','path_yellow','path_red','valuation','duties_calculation','exit_permit','completed','archived'];
const nextStages:Record<string,string[]>={draft:['registration_order','documents_ready'],registration_order:['documents_ready'],documents_ready:['epl_submitted'],epl_submitted:['kottaj_received'],kottaj_received:['path_green','path_yellow','path_red'],path_green:['valuation'],path_yellow:['valuation'],path_red:['valuation'],valuation:['duties_calculation'],duties_calculation:['exit_permit'],exit_permit:['completed'],completed:['archived']};
const required=[['PROFORMA_INVOICE','پروفورما'],['COMMERCIAL_INVOICE','کامرشال اینویس'],['PACKING_LIST','پکینگ لیست'],['BILL_OF_LADING','B/L'],['CERTIFICATE_OF_ORIGIN','گواهی مبدأ']] as const;

type CaseRow={id:string;case_number:string|null;status:string;client_id:string|null;registration_order_no:string|null;warehouse_receipt_no:string|null;release_status:string|null;valuation_status:string|null};
type Decl={id:string;kottaj_number:string|null;customs_path:string|null;declaration_date:string|null;assessed_value_irr:number|null;total_duties_irr:number|null};
type Doc={document_type:string|null;status:string|null};

export const CaseStagePage:React.FC=()=>{
 const [params]=useSearchParams();const caseId=params.get('caseId')||'';
 const [cases,setCases]=useState<CaseRow[]>([]),[selected,setSelected]=useState(''),[current,setCurrent]=useState<CaseRow|null>(null),[target,setTarget]=useState(''),[notes,setNotes]=useState('');
 const [docs,setDocs]=useState<Doc[]>([]),[decl,setDecl]=useState<Decl|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');

 const loadCases=async()=>{const{data,error}=await supabase.from('cases').select('id,case_number,status,client_id,registration_order_no,warehouse_receipt_no,release_status,valuation_status').order('created_at',{ascending:false});if(error){setError(error.message);return}const rows=(data||[]) as CaseRow[];setCases(rows);const id=caseId||selected;if(id&&rows.some(x=>x.id===id)){setSelected(id);setCurrent(rows.find(x=>x.id===id)||null)}};
 const loadCaseData=async(id:string)=>{if(!id){setDocs([]);setDecl(null);return}const[{data:d,error:de},{data:r,error:re}]=await Promise.all([supabase.from('customs_documents').select('document_type,status').eq('case_id',id),supabase.from('customs_declarations').select('id,kottaj_number,customs_path,declaration_date,assessed_value_irr,total_duties_irr').eq('case_id',id).order('created_at',{ascending:false}).limit(1)]);if(de)throw de;if(re)throw re;setDocs((d||[]) as Doc[]);setDecl(((r||[])[0]||null) as Decl|null)};
 const load=async()=>{setBusy(true);setError('');try{await loadCases();if(selected||caseId)await loadCaseData(selected||caseId)}catch(e:any){setError(e?.message||'دریافت اطلاعات پرونده ناموفق بود')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[caseId]);
 useEffect(()=>{if(selected)void loadCaseData(selected).catch((e:any)=>setError(e?.message||'دریافت اطلاعات پرونده ناموفق بود'))},[selected]);
 const choose=(id:string)=>{setSelected(id);setCurrent(cases.find(x=>x.id===id)||null);setTarget('');setNotes('');setMessage('');setError('')};
 const readiness=useMemo(()=>{const approved=new Set(docs.filter(d=>d.status==='approved').map(d=>d.document_type));const items=required.map(([type,name])=>({type,name,ok:approved.has(type)}));return{items,approved:items.filter(x=>x.ok).length,complete:items.every(x=>x.ok)}},[docs]);
 const allowed=nextStages[current?.status||'']||[];
 const advance=async()=>{if(!selected)return setError('پرونده را انتخاب کنید.');if(!target)return setError('مرحله هدف را انتخاب کنید.');setBusy(true);setMessage('');setError('');try{const{data,error}=await supabase.rpc('advance_case_stage',{p_case_id:selected,p_target_status:target,p_notes:notes||null});if(error)throw error;setMessage(`مرحله پرونده به «${labels[data]||data}» تغییر کرد.`);setNotes('');setTarget('');await loadCases();await loadCaseData(selected)}catch(e:any){setError(e?.message||'عبور از مرحله انجام نشد')}finally{setBusy(false)}};
 const stageIndex=stages.indexOf(current?.status||'draft');
 return <main className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8" dir="rtl"><div className="max-w-6xl mx-auto space-y-5">
  <header className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-3"><ShieldAlert className="text-cyan-400" size={28}/><h1 className="text-2xl font-black">کنترل مراحل پرونده</h1></div><p className="text-sm text-slate-400 mt-2">هر عبور مرحله‌ای در دیتابیس کنترل می‌شود؛ مدارک و اظهار واقعی پرونده مبنای آمادگی هستند.</p></div><Link to={selected?`/operations?caseId=${encodeURIComponent(selected)}`:'/operations'} className="px-4 py-2 rounded-xl border border-slate-700 bg-slate-900"><ArrowRight className="inline ml-2" size={16}/> پرونده</Link></header>
  {error&&<div className="rounded-xl border border-red-900 bg-red-950/30 p-4 text-red-300 whitespace-pre-wrap">{error}</div>}
  {message&&<div className="rounded-xl border border-emerald-900 bg-emerald-950/30 p-4 text-emerald-300">{message}</div>}
  <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><label className="text-sm text-slate-400">پرونده</label><select value={selected} onChange={e=>choose(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 p-3"><option value="">انتخاب پرونده</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number||c.id.slice(0,8)} — {labels[c.status]||c.status}</option>)}</select>{current&&<div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-3"><Info t="شماره پرونده" v={current.case_number||'—'}/><Info t="وضعیت فعلی" v={labels[current.status]||current.status}/><Info t="ثبت سفارش" v={current.registration_order_no||'ثبت نشده'}/><Info t="قبض انبار" v={current.warehouse_receipt_no||'ثبت نشده'}/></div>}</section>
  {current&&<><section className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><FileCheck2 className="text-cyan-400" size={20}/><h2 className="font-black">آمادگی مدارک برای گردش پرونده</h2></div><b className={readiness.complete?'text-emerald-400':'text-amber-400'}>{readiness.approved} از ۵ تأیید شده</b></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-2">{readiness.items.map(x=><div key={x.type} className={`rounded-xl border p-3 ${x.ok?'border-emerald-900 bg-emerald-950/20':'border-amber-900 bg-amber-950/20'}`}><div className="flex items-center gap-2 text-sm"><span>{x.ok?'✓':'!'}</span><span>{x.name}</span></div><div className="text-[11px] mt-1 text-slate-500">{x.ok?'تأیید شده':'نیازمند تأیید'}</div></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><Link to={`/operations?tab=documents&caseId=${encodeURIComponent(selected)}`} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-2 text-sm"><FileText className="inline ml-2" size={15}/>مدیریت اسناد</Link><Link to={`/operations?tab=declaration&caseId=${encodeURIComponent(selected)}`} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-2 text-sm">ثبت/مشاهده اظهار EPL</Link></div></section>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><ShipWheel className="text-cyan-400" size={20}/><h2 className="font-black">وضعیت اظهار و عملیات</h2></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Info t="کوتاژ" v={decl?.kottaj_number||'ثبت نشده'}/><Info t="مسیر گمرکی" v={decl?.customs_path?`مسیر ${decl.customs_path}`:'ثبت نشده'}/><Info t="ارزش اظهار" v={decl?.assessed_value_irr!=null?`${decl.assessed_value_irr.toLocaleString('fa-IR')} ریال`:'—'}/><Info t="وضعیت ارزش‌گذاری" v={current.valuation_status||'محاسبه نشده'}/></div></section>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><History className="text-cyan-400" size={20}/><h2 className="font-black">مسیر پرونده</h2></div><div className="overflow-x-auto pb-2"><div className="flex min-w-max gap-2">{stages.map((s,i)=><div key={s} className={`rounded-xl border px-3 py-2 text-xs ${i===stageIndex?'border-cyan-500 bg-cyan-950/40 text-cyan-300':i<stageIndex?'border-emerald-900 bg-emerald-950/20 text-emerald-300':'border-slate-800 bg-slate-950 text-slate-500'}`}>{labels[s]}</div>)}</div></div></section>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="grid md:grid-cols-2 gap-4"><div><label className="text-sm text-slate-400">مرحله بعدی مجاز</label><select value={target} onChange={e=>setTarget(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 p-3"><option value="">انتخاب مرحله</option>{allowed.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div><div><label className="text-sm text-slate-400">یادداشت تغییر مرحله</label><input value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 p-3" placeholder="اختیاری"/></div></div><button disabled={busy||!selected||!target} onClick={advance} className="mt-5 px-5 py-3 rounded-xl bg-cyan-600 disabled:opacity-50 font-bold">{busy?<><Loader2 className="inline ml-2 animate-spin" size={17}/>در حال بررسی پیش‌نیازها...</>:<><CheckCircle2 className="inline ml-2" size={17}/>بررسی و عبور مرحله</>}</button></section></>}
  {!current&&!busy&&<div className="rounded-2xl border border-slate-800 bg-slate-900 p-10 text-center text-slate-500">یک پرونده را انتخاب کنید.</div>}
  {busy&&<div className="flex justify-center py-5"><Loader2 className="animate-spin text-cyan-400"/></div>}
 </div></main>;
};
const Info=({t,v}:{t:string;v:string})=><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="text-xs text-slate-500">{t}</div><div className="mt-1 text-sm break-all">{v}</div></div>;
