import React,{useEffect,useMemo,useState} from 'react';
import {FolderOpen,Loader2,Search,Ship} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {buildCargoName} from '../lib/cargoNaming';

type Row={id:string;case_id:string|null;bl:string;vessel:string;owner:string;qty:number|string;unit:string;displayName:string;caseNumber:string};
export const CaseDocumentManagementPage:React.FC=()=>{
 const[rows,setRows]=useState<Row[]>([]);const[q,setQ]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const{data:s,error:se}=await supabase.from('shipments').select('id,case_id,bill_of_lading_no,vessel_id,client_id,cargo_count,cargo_count_unit,created_at,updated_at').order('updated_at',{ascending:false});if(se)throw se;const ss=s||[];const vids=ss.map((x:any)=>x.vessel_id).filter(Boolean),cids=ss.map((x:any)=>x.client_id).filter(Boolean),caseIds=ss.map((x:any)=>x.case_id).filter(Boolean);const[{data:vs,error:ve},{data:cs,error:ce},{data:cases,error:casee}]=await Promise.all([vids.length?supabase.from('vessels').select('id,name').in('id',vids):Promise.resolve({data:[],error:null} as any),cids.length?supabase.from('clients').select('id,name').in('id',cids):Promise.resolve({data:[],error:null} as any),caseIds.length?supabase.from('cases').select('id,case_number').in('id',caseIds):Promise.resolve({data:[],error:null} as any)]);if(ve||ce||casee)throw ve||ce||casee;const vm=new Map((vs||[]).map((x:any)=>[x.id,x.name||''])),cm=new Map((cs||[]).map((x:any)=>[x.id,x.name||''])),km=new Map((cases||[]).map((x:any)=>[x.id,x.case_number||'']));setRows(ss.map((x:any)=>{const owner=cm.get(x.client_id)||'',vessel=vm.get(x.vessel_id)||'';return{id:x.id,case_id:x.case_id||null,bl:x.bill_of_lading_no||'',vessel,owner,qty:x.cargo_count??'',unit:x.cargo_count_unit||'',displayName:buildCargoName(x.cargo_count,x.cargo_count_unit,owner,vessel),caseNumber:km.get(x.case_id)||'—'}}))}catch(e:any){setError(e?.message||'دریافت محموله‌ها ناموفق بود')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);const filtered=useMemo(()=>rows.filter(r=>`${r.displayName} ${r.bl} ${r.owner} ${r.vessel} ${r.caseNumber}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 return <main dir="rtl" className="min-h-screen p-4 md:p-6" style={{background:'var(--bg)',color:'var(--text)'}}><div className="max-w-6xl mx-auto space-y-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] app-muted">CUSTOMS OS</div><h1 className="text-2xl md:text-3xl font-black mt-1">محموله‌ها</h1><p className="text-xs app-muted mt-1">گردش سیستم صفحه‌به‌صفحه است؛ از محموله شروع می‌شود و بعد به مدارک، اطلاعات نهایی، اظهارنامه، چک‌لیست و درب خروج می‌رود.</p></div><Link to="/" className="px-4 py-2 rounded-xl border app-border bg-[var(--surface)] text-xs font-bold">صفحه اصلی</Link></header>{error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-500">{error}</div>}<section className="rounded-2xl border app-border bg-[var(--surface)] overflow-hidden"><div className="p-4 border-b app-border flex items-center justify-between"><div className="font-black">ثبت و مدیریت محموله</div><span className="text-[10px] app-muted">{filtered.length} مورد</span></div><div className="p-3"><div className="relative"><Search size={16} className="absolute right-3 top-3 app-muted"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجوی نام محموله، B/L، کشتی، صاحب کالا..." className="w-full rounded-xl border app-border bg-[var(--surface-2)] pr-9 p-2.5 text-xs"/></div></div><div>{busy&&!rows.length?<div className="p-8 text-center"><Loader2 className="animate-spin mx-auto"/></div>:filtered.map(r=><div key={r.id} className="p-4 border-t app-border flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><div className="font-bold text-sm truncate">{r.displayName}</div><div className="text-[11px] app-muted mt-1">{r.owner||'صاحب کالا —'} · {r.vessel||'حمل زمینی'} · B/L: {r.bl||'—'}</div><div className="text-[10px] app-muted mt-1">پرونده: {r.caseNumber}</div></div><div className="flex gap-2"><Link to={`/documents?shipmentId=${encodeURIComponent(r.id)}`} className="px-3 py-2 rounded-xl border app-border text-xs font-bold"><FolderOpen size={15} className="inline ml-1"/> مدارک</Link>{r.case_id&&<Link to={`/operations?tab=declaration&caseId=${encodeURIComponent(r.case_id)}`} className="px-3 py-2 rounded-xl bg-[var(--primary)] text-white text-xs font-bold">اظهارنامه</Link>}</div></div>)}{!filtered.length&&!busy&&<div className="p-10 text-center app-muted"><Ship size={36} className="mx-auto mb-2"/>محموله‌ای پیدا نشد.</div>}</div></section></div></main>;
};
