import React,{useEffect,useMemo,useState} from 'react';
import {FolderOpen,Loader2,Search,Ship,Edit3,Trash2,Save,X} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {buildCargoName} from '../lib/cargoNaming';

type Row={id:string;case_id:string|null;bl:string;vessel:string;owner:string;qty:number|string;unit:string;net:number|string;gross:number|string;displayName:string;caseNumber:string;client_id:string|null;vessel_id:string|null};
export const CaseDocumentManagementPage:React.FC=()=>{
 const[rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState<Row|null>(null),[form,setForm]=useState<any>({}),[clients,setClients]=useState<any[]>([]),[vessels,setVessels]=useState<any[]>([]);
 const load=async()=>{setBusy(true);setError('');try{const{data:s,error:se}=await supabase.from('shipments').select('id,case_id,bill_of_lading_no,vessel_id,client_id,cargo_count,cargo_count_unit,net_weight_kg,gross_weight_kg,created_at,updated_at').order('updated_at',{ascending:false});if(se)throw se;const ss=s||[];const vids=ss.map((x:any)=>x.vessel_id).filter(Boolean),cids=ss.map((x:any)=>x.client_id).filter(Boolean),caseIds=ss.map((x:any)=>x.case_id).filter(Boolean);const[{data:vs,error:ve},{data:cs,error:ce},{data:cases,error:casee}]=await Promise.all([vids.length?supabase.from('vessels').select('id,name').in('id',vids):Promise.resolve({data:[],error:null} as any),cids.length?supabase.from('clients').select('id,name').in('id',cids):Promise.resolve({data:[],error:null} as any),caseIds.length?supabase.from('cases').select('id,case_number').in('id',caseIds):Promise.resolve({data:[],error:null} as any)]);if(ve||ce||casee)throw ve||ce||casee;setClients(cs||[]);setVessels(vs||[]);const vm=new Map<string,string>((vs||[]).map((x:any)=>[x.id,String(x.name||'')] as [string,string])),cm=new Map<string,string>((cs||[]).map((x:any)=>[x.id,String(x.name||'')] as [string,string])),km=new Map<string,string>((cases||[]).map((x:any)=>[x.id,String(x.case_number||'')] as [string,string]));setRows(ss.map((x:any)=>{const owner=cm.get(x.client_id)||'',vessel=vm.get(x.vessel_id)||'';return{id:x.id,case_id:x.case_id||null,bl:x.bill_of_lading_no||'',vessel,owner,qty:x.cargo_count??'',unit:x.cargo_count_unit||'',net:x.net_weight_kg??'',gross:x.gross_weight_kg??'',displayName:buildCargoName(x.cargo_count,x.cargo_count_unit,owner,vessel),caseNumber:km.get(x.case_id)||'—',client_id:x.client_id||null,vessel_id:x.vessel_id||null}}))}catch(e:any){setError(e?.message||'دریافت محموله‌ها ناموفق بود')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);const filtered=useMemo(()=>rows.filter(r=>`${r.displayName} ${r.bl} ${r.owner} ${r.vessel} ${r.caseNumber}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const openEdit=(r:Row)=>{setEditing(r);setForm({client_id:r.client_id||'',vessel_id:r.vessel_id||'',bl:r.bl,qty:r.qty,unit:r.unit,net:r.net,gross:r.gross})};
 const save=async()=>{if(!editing)return;setBusy(true);setError('');try{const{error}=await supabase.from('shipments').update({client_id:form.client_id||null,vessel_id:form.vessel_id||null,bill_of_lading_no:String(form.bl||'').trim()||null,cargo_count:form.qty===''||form.qty==null?null:Number(form.qty),cargo_count_unit:String(form.unit||'').trim()||null,net_weight_kg:form.net===''||form.net==null?null:Number(form.net),gross_weight_kg:form.gross===''||form.gross==null?null:Number(form.gross)}).eq('id',editing.id);if(error)throw error;setEditing(null);await load()}catch(e:any){setError(e?.message||'ویرایش محموله ناموفق بود')}finally{setBusy(false)}};
 const remove=async(r:Row)=>{if(!window.confirm(`محموله «${r.displayName}» حذف شود؟`))return;setBusy(true);setError('');try{const{error}=await supabase.from('shipments').delete().eq('id',r.id);if(error)throw error;await load()}catch(e:any){setError(e?.message||'حذف محموله انجام نشد')}finally{setBusy(false)}};
 return <main dir="rtl" className="min-h-screen p-4 md:p-6" style={{background:'var(--bg)',color:'var(--text)'}}><div className="max-w-6xl mx-auto space-y-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] app-muted">CUSTOMS OS</div><h1 className="text-2xl md:text-3xl font-black mt-1">محموله‌ها</h1><p className="text-xs app-muted mt-1">ثبت، ویرایش و حذف محموله‌ها</p></div><Link to="/" className="px-4 py-2 rounded-xl border app-border bg-[var(--surface)] text-xs font-bold">صفحه اصلی</Link></header>{error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-500">{error}</div>}
 {editing&&<section className="rounded-2xl border border-amber-500/30 bg-[var(--surface)] p-4"><div className="flex items-center justify-between mb-4"><h2 className="font-black">ویرایش محموله</h2><button onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="grid md:grid-cols-2 gap-3"><label className="text-xs app-muted">صاحب کالا<select value={form.client_id||''} onChange={e=>setForm((p:any)=>({...p,client_id:e.target.value}))} className="mt-1 w-full rounded-xl border app-border bg-[var(--surface-2)] p-3 text-sm"><option value="">بدون انتخاب</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs app-muted">کشتی<select value={form.vessel_id||''} onChange={e=>setForm((p:any)=>({...p,vessel_id:e.target.value}))} className="mt-1 w-full rounded-xl border app-border bg-[var(--surface-2)] p-3 text-sm"><option value="">بدون انتخاب</option>{vessels.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><Field label="شماره بارنامه" value={form.bl} onChange={(v:string)=>setForm((p:any)=>({...p,bl:v}))}/><Field label="تعداد" value={form.qty} onChange={(v:string)=>setForm((p:any)=>({...p,qty:v}))}/><Field label="واحد" value={form.unit} onChange={(v:string)=>setForm((p:any)=>({...p,unit:v}))}/><Field label="وزن خالص (کیلوگرم)" value={form.net} onChange={(v:string)=>setForm((p:any)=>({...p,net:v}))}/><Field label="وزن ناخالص (کیلوگرم)" value={form.gross} onChange={(v:string)=>setForm((p:any)=>({...p,gross:v}))}/></div><button onClick={save} disabled={busy} className="mt-4 rounded-xl bg-cyan-600 px-5 py-3 font-bold"><Save className="inline ml-1" size={16}/>ذخیره</button></section>}
 <section className="rounded-2xl border app-border bg-[var(--surface)] overflow-hidden"><div className="p-4 border-b app-border flex items-center justify-between"><div className="font-black">مدیریت محموله</div><span className="text-[10px] app-muted">{filtered.length} مورد</span></div><div className="p-3"><div className="relative"><Search size={16} className="absolute right-3 top-3 app-muted"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجوی نام محموله، B/L، کشتی، صاحب کالا..." className="w-full rounded-xl border app-border bg-[var(--surface-2)] pr-9 p-2.5 text-xs"/></div></div><div>{busy&&!rows.length?<div className="p-8 text-center"><Loader2 className="animate-spin mx-auto"/></div>:filtered.map(r=><div key={r.id} className="p-4 border-t app-border flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><div className="font-bold text-sm truncate">{r.displayName}</div><div className="text-[11px] app-muted mt-1">{r.owner||'صاحب کالا —'} · {r.vessel||'حمل زمینی'} · B/L: {r.bl||'—'}</div><div className="text-[10px] app-muted mt-1">تعداد: {r.qty||'—'} {r.unit||''} · خالص: {r.net||'—'} کیلو · ناخالص: {r.gross||'—'} کیلو · پرونده: {r.caseNumber}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>openEdit(r)} className="px-3 py-2 rounded-xl border border-amber-500/40 text-amber-300 text-xs font-bold"><Edit3 size={15} className="inline ml-1"/>ویرایش</button><button onClick={()=>remove(r)} disabled={busy} className="px-3 py-2 rounded-xl border border-red-500/40 text-red-300 text-xs font-bold"><Trash2 size={15} className="inline ml-1"/>حذف</button><Link to={`/documents?shipmentId=${encodeURIComponent(r.id)}`} className="px-3 py-2 rounded-xl border app-border text-xs font-bold"><FolderOpen size={15} className="inline ml-1"/>مدارک</Link>{r.case_id&&<Link to={`/operations?tab=declaration&caseId=${encodeURIComponent(r.case_id)}`} className="px-3 py-2 rounded-xl bg-[var(--primary)] text-white text-xs font-bold">اظهارنامه</Link>}</div></div>)}{!filtered.length&&!busy&&<div className="p-10 text-center app-muted"><Ship size={36} className="mx-auto mb-2"/>محموله‌ای پیدا نشد.</div>}</div></section></div></main>;
};
const Field=({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void})=><label className="text-xs app-muted">{label}<input value={value??''} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border app-border bg-[var(--surface-2)] p-3 text-sm"/></label>;
