import React,{useEffect,useState} from 'react';
import {AlertTriangle,Loader2,Trash2,RefreshCw} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {buildCargoName} from '../lib/cargoNaming';

type Row={id:string;caseNumber:string;name:string;status:string;owner:string;vessel:string;qty:number|string|null;unit:string};
const labels:Record<string,string>={draft:'پیش‌نویس',registration_order:'ثبت سفارش',documents_ready:'مدارک آماده',epl_submitted:'اظهار ثبت شد',kottaj_received:'کوتاژ دریافت شد',path_green:'مسیر سبز',path_yellow:'مسیر زرد',path_red:'مسیر قرمز',valuation:'ارزیابی',duties_calculation:'محاسبه حقوق و عوارض',exit_permit:'پروانه خروج',completed:'تکمیل شده',archived:'بایگانی'};
export const CaseDeletePage:React.FC=()=>{const[rows,setRows]=useState<Row[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const[{data:s,error:se},{data:c,error:ce},{data:v,error:ve},{data:cl,error:cle}]=await Promise.all([supabase.from('shipments').select('id,case_id,cargo_count,cargo_count_unit,client_id,vessel_id').not('case_id','is',null),supabase.from('cases').select('id,case_number,status,display_name'),supabase.from('vessels').select('id,name'),supabase.from('clients').select('id,name')]);if(se)throw se;if(ce)throw ce;if(ve)throw ve;if(cle)throw cle;const cm=new Map((c||[]).map((x:any)=>[x.id,x])),vm=new Map((v||[]).map((x:any)=>[x.id,x.name||''])),lm=new Map((cl||[]).map((x:any)=>[x.id,x.name||'']));const grouped=new Map<string,any>();(s||[]).forEach((x:any)=>{if(!grouped.has(x.case_id))grouped.set(x.case_id,x)});setRows((c||[]).map((x:any)=>{const sh=grouped.get(x.id),owner=sh?lm.get(sh.client_id)||'':'',vessel=sh?vm.get(sh.vessel_id)||'':'';return{id:x.id,caseNumber:x.case_number||'—',name:x.display_name||buildCargoName(sh?.cargo_count,sh?.cargo_count_unit,owner,vessel),status:x.status,owner,vessel,qty:sh?.cargo_count??null,unit:sh?.cargo_count_unit||''}}));}catch(e:any){setError(e?.message||'دریافت پرونده‌ها ناموفق بود')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const remove=async(r:Row)=>{if(!confirm(`پرونده «${r.name}» حذف شود؟ این عملیات قابل برگشت نیست.`))return;setBusy(true);setError('');setMessage('');try{const{error}=await supabase.rpc('delete_case_safely',{p_case_id:r.id});if(error)throw error;setMessage(`پرونده «${r.name}» حذف شد.`);await load();}catch(e:any){setError(e?.message||'حذف پرونده انجام نشد')}finally{setBusy(false)}};
 return <main dir="rtl" className="min-h-screen p-4 md:p-6" style={{background:'var(--bg)',color:'var(--text)'}}><div className="max-w-5xl mx-auto space-y-4"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-black">حذف پرونده</h1><p className="text-xs app-muted mt-1">حذف فقط برای پرونده‌های بدون تراکنش مالی و عملیات خروج فعال است.</p></div><button className="icon-btn" onClick={()=>void load()}><RefreshCw size={17}/></button></header>{error&&<div className="rounded-xl border border-red-400/40 bg-red-500/10 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-400/40 bg-emerald-500/10 p-3 text-sm text-emerald-700">{message}</div>}<div className="rounded-xl border border-amber-400/40 bg-amber-500/10 p-4 text-xs"><AlertTriangle size={16} className="inline ml-1"/> حذف پرونده دائمی است و محموله‌ها و رکوردهای وابسته‌ای که با CASCADE تعریف شده‌اند نیز حذف می‌شوند.</div><section className="rounded-2xl border app-border bg-[var(--surface)] overflow-hidden">{busy&&!rows.length?<div className="p-10 text-center"><Loader2 className="animate-spin mx-auto"/></div>:!rows.length?<div className="p-10 text-center app-muted">پرونده‌ای برای حذف وجود ندارد.</div>:rows.map(r=><div key={r.id} className="p-4 border-b app-border last:border-0 flex flex-col md:flex-row md:items-center gap-3"><div className="flex-1 min-w-0"><div className="font-black truncate">{r.name}</div><div className="text-xs app-muted mt-1">پرونده: {r.caseNumber} · {labels[r.status]||r.status} · {r.vessel||'کشتی —'} · {r.owner||'صاحب کالا —'}</div></div><button disabled={busy} onClick={()=>void remove(r)} className="px-4 py-2 rounded-xl bg-red-600 text-white text-xs font-bold disabled:opacity-50"><Trash2 size={15} className="inline ml-1"/>حذف پرونده</button></div>)}</section></div></main>};
export default CaseDeletePage;
