import React,{useEffect,useMemo,useState} from 'react';
import {CloudSun,Compass,RefreshCw,Ship,Wind,Radio,Search,LocateFixed,Navigation} from 'lucide-react';
import {MapContainer,TileLayer,Marker,Popup,Polyline,useMap} from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {supabase} from '../lib/supabase';

const ports=[['روسیه / آستراخان',46.35,48.04],['آستارا',38.43,48.87],['انزلی',37.47,49.46],['امیرآباد',36.93,53.42],['نوشهر',36.65,51.50],['فریدونکنار',36.69,52.52],['ترکمن',36.90,54.07],['بندر گز',36.76,53.95]] as const;
type Vessel={id:string;name:string;imo_number:string|null;mmsi_number:string|null;last_latitude:number|null;last_longitude:number|null;last_position_at:string|null;last_position_source:string|null;last_speed_knots:number|null;last_course_deg:number|null};
type LiveVessel={mmsi:string;name:string;lat:number;lon:number;sog:number|null;cog:number|null;heading:number|null;seen:string|null};
const portPositions=ports.map(p=>[p[1],p[2]] as [number,number]);
const vesselIcon=L.divIcon({className:'',html:'<div style="width:12px;height:12px;border-radius:50%;background:#22d3ee;border:2px solid white;box-shadow:0 0 0 2px rgba(34,211,238,.25),0 0 12px rgba(34,211,238,.8)"></div>',iconSize:[12,12],iconAnchor:[6,6]});
const portIcon=L.divIcon({className:'',html:'<div style="width:9px;height:9px;border-radius:50%;background:#f59e0b;border:2px solid white;box-shadow:0 0 8px rgba(245,158,11,.7)"></div>',iconSize:[9,9],iconAnchor:[4.5,4.5]});
const FitCaspian=()=>{const map=useMap();useEffect(()=>{map.fitBounds([[36,46],[47.2,56.2]],{padding:[20,20]});},[map]);return null};
const FlyTo=({position}:{position:[number,number]})=>{const map=useMap();useEffect(()=>{map.flyTo(position,8,{duration:1.2});},[map,position]);return null};

export const CaspianMaritimePage:React.FC=()=>{
 const[port,setPort]=useState(ports[2]);const[w,setW]=useState<any>();const[v,setV]=useState<Vessel[]>([]);const[live,setLive]=useState<LiveVessel[]>([]);const[busy,setBusy]=useState(false);const[aisBusy,setAisBusy]=useState(false);const[aisMsg,setAisMsg]=useState('');const[search,setSearch]=useState('');const[selected,setSelected]=useState<string|null>(null);const[mmsi,setMmsi]=useState('422029300');const[focus,setFocus]=useState<[number,number]|null>(null);
 const load=async()=>{setBusy(true);try{const j=await fetch(`https://marine-api.open-meteo.com/v1/marine?latitude=${port[1]}&longitude=${port[2]}&current=wave_height,wave_direction,wind_wave_height,swell_wave_height&timezone=auto`).then(r=>r.json());setW(j.current)}catch{setW(null)}try{const{data,error}=await supabase.from('vessels').select('id,name,imo_number,mmsi_number,last_latitude,last_longitude,last_position_at,last_position_source,last_speed_knots,last_course_deg').order('name',{ascending:true});if(error)throw error;setV((data||[]) as Vessel[])}catch{setV([])}setBusy(false)};
 const loadLiveAIS=async()=>{setAisBusy(true);setAisMsg('در حال دریافت AIS واقعی دریای خزر...');try{const{data,error}=await supabase.functions.invoke('sync-vessel-ais-v2',{body:{mode:'live-caspian'}});if(error)throw error;setLive(Array.isArray(data?.vessels)?data.vessels as LiveVessel[]:[]);setAisMsg(`AIS زنده: ${data?.count||0} کشتی از Open Waters دریافت شد`)}catch(e:any){setAisMsg(e?.message||'خطا در دریافت AIS زنده')}finally{setAisBusy(false)}};
 const syncAIS=async()=>{setAisBusy(true);setAisMsg('در حال به‌روزرسانی AIS کشتی‌های ثبت‌شده...');try{const{data,error}=await supabase.functions.invoke('sync-vessel-ais-v2');if(error)throw error;if(data?.code==='MMSI_REQUIRED')throw new Error(data.message);setAisMsg(`کشتی‌های ثبت‌شده: ${data?.updated?.length||0} موقعیت به‌روزرسانی شد`);await load();await loadLiveAIS()}catch(e:any){setAisMsg(e?.message||'خطا در دریافت AIS')}finally{setAisBusy(false)}};
 const lookupMMSI=async()=>{const value=mmsi.replace(/\D/g,'');setMmsi(value);if(!/^\d{9}$/.test(value)){setAisMsg('MMSI باید دقیقاً ۹ رقم باشد.');return}setAisBusy(true);setAisMsg(`در حال جستجوی مستقیم MMSI ${value}...`);try{const{data,error}=await supabase.functions.invoke('sync-vessel-ais-v2',{body:{mode:'lookup-mmsi',mmsi:value}});if(error)throw error;if(data?.found&&data?.vessel){const x=data.vessel as LiveVessel;setLive(prev=>[x,...prev.filter(y=>y.mmsi!==x.mmsi)]);setFocus([x.lat,x.lon]);setAisMsg(`موقعیت واقعی ${x.name||value} دریافت شد · آخرین دریافت AIS: ${x.seen?new Date(x.seen).toLocaleString('fa-IR'):'نامشخص'}`)}else{setAisMsg(data?.message||'برای این MMSI در ۳۰ دقیقه اخیر موقعیت AIS دریافت نشده است.')}}catch(e:any){setAisMsg(e?.message||'خطا در جستجوی MMSI')}finally{setAisBusy(false)}};
 useEffect(()=>{load();loadLiveAIS()},[port]);
 const active=v.filter(x=>x.last_latitude!=null&&x.last_longitude!=null);
 const filteredVessels=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return v;return v.filter(x=>[x.name,x.imo_number,x.mmsi_number].some(value=>String(value||'').toLowerCase().includes(q)))},[v,search]);
 const activePositions=useMemo(()=>active.map(x=>[x.last_latitude as number,x.last_longitude as number] as [number,number]),[active]);
 return <main dir="rtl" className="min-h-screen bg-[var(--background)] text-[var(--text)] p-4 md:p-6"><div className="max-w-7xl mx-auto">
  <header className="flex flex-wrap justify-between gap-3 mb-5"><div><span className="text-[10px] app-muted">CASPIAN MARITIME / LIVE AIS</span><h1 className="text-2xl font-black">هوا و مسیر دریایی خزر</h1><p className="text-xs app-muted mt-1">نقشه واقعی، Master Data و ردیابی مستقیم با MMSI</p></div><div className="flex flex-wrap gap-2"><button onClick={loadLiveAIS} disabled={aisBusy} className="px-3 py-2 rounded-xl border app-border bg-[var(--surface)] text-xs"><Radio size={14} className="inline ml-1"/>{aisBusy?'دریافت AIS...':'دریافت AIS زنده'}</button><button onClick={syncAIS} disabled={aisBusy} className="px-3 py-2 rounded-xl border app-border bg-[var(--surface)] text-xs">به‌روزرسانی کشتی‌های من</button><button onClick={load} disabled={busy} className="px-3 py-2 rounded-xl border app-border bg-[var(--surface)] text-xs"><RefreshCw size={14} className="inline ml-1"/>فهرست</button></div></header>
  {aisMsg&&<div className="mb-3 rounded-xl border app-border bg-[var(--surface)] px-3 py-2 text-xs app-muted">{aisMsg}</div>}
  <section className="rounded-2xl border app-border bg-[var(--surface)] p-4 mb-3"><div className="flex items-center gap-2 mb-3"><Navigation size={17} className="text-cyan-300"/><div><div className="text-[10px] app-muted">DIRECT AIS LOOKUP</div><h2 className="font-bold">ردیابی مستقیم با MMSI</h2></div></div><div className="flex flex-col sm:flex-row gap-2"><input dir="ltr" inputMode="numeric" maxLength={9} value={mmsi} onChange={e=>setMmsi(e.target.value.replace(/\D/g,'').slice(0,9))} onKeyDown={e=>{if(e.key==='Enter')lookupMMSI()}} placeholder="مثلاً 422029300" className="flex-1 min-h-11 rounded-xl border app-border bg-[var(--surface-2)] px-3 text-sm outline-none"/><button onClick={lookupMMSI} disabled={aisBusy||mmsi.length!==9} className="min-h-11 px-5 rounded-xl bg-cyan-400 text-slate-950 font-bold text-sm disabled:opacity-50"><LocateFixed size={15} className="inline ml-1"/>ردیابی MMSI</button></div><div className="text-[10px] app-muted mt-2">نمونه آماده: RASHA 1 · IMO 8860028 · MMSI 422029300</div></section>
  <section className="rounded-2xl border app-border bg-[var(--surface)] p-4 mb-3"><div className="flex flex-wrap items-center justify-between gap-3 mb-3"><div><div className="text-[10px] app-muted">MASTER DATA / VESSELS</div><h2 className="font-bold mt-1">فهرست کشتی‌ها</h2><div className="text-[10px] app-muted mt-1">{v.length} کشتی · {active.length} دارای موقعیت ذخیره‌شده</div></div><div className="relative w-full sm:w-72"><Search size={15} className="absolute right-3 top-3 app-muted"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جستجوی نام، IMO یا MMSI" className="w-full min-h-10 rounded-xl border app-border bg-[var(--surface-2)] pr-9 pl-3 text-xs outline-none"/></div></div>{busy?<div className="py-8 text-center app-muted text-xs">در حال فراخوانی فهرست کشتی‌ها...</div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-2">{filteredVessels.map(x=><button type="button" key={x.id} onClick={()=>{setSelected(x.id);if(x.mmsi_number)setMmsi(x.mmsi_number)}} className={`text-right rounded-xl border p-3 transition ${selected===x.id?'border-cyan-400/70 bg-cyan-400/10':'app-border bg-[var(--surface-2)] hover:bg-[var(--surface)]'}`}><div className="flex items-center justify-between gap-2"><b className="text-sm truncate">{x.name||'بدون نام'}</b><Ship size={16} className="shrink-0 text-cyan-300"/></div><div className="text-[10px] app-muted mt-2">IMO: {x.imo_number||'—'} · MMSI: {x.mmsi_number||'—'}</div><div className="flex items-center justify-between mt-2 text-[10px] app-muted"><span>{x.last_position_source||'بدون موقعیت AIS'}</span><span>{x.last_position_at?new Date(x.last_position_at).toLocaleString('fa-IR'):'موقعیت ثبت نشده'}</span></div></button>)}{!filteredVessels.length&&<div className="text-xs app-muted py-5">کشتی موردنظر پیدا نشد.</div>}</div>}</section>
  <div className="grid lg:grid-cols-[.8fr_1.5fr] gap-3"><section className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex justify-between"><div><div className="text-[10px] app-muted">MARINE WEATHER</div><h2 className="font-bold mt-1">وضعیت موج</h2></div><CloudSun className="text-cyan-300" size={20}/></div><select value={port[0]} onChange={e=>setPort(ports.find(p=>p[0]===e.target.value)||ports[2])} className="w-full mt-4 min-h-10 rounded-xl border app-border bg-[var(--surface-2)] px-3 text-sm">{ports.map(p=><option key={p[0]}>{p[0]}</option>)}</select>{busy?<div className="py-10 text-center app-muted">در حال دریافت...</div>:<div className="grid grid-cols-2 gap-2 mt-4"><div className="p-3 rounded-xl bg-[var(--surface-2)]"><span className="text-[10px] app-muted">ارتفاع موج</span><b className="block text-xl mt-1">{w?.wave_height??'—'} m</b></div><div className="p-3 rounded-xl bg-[var(--surface-2)]"><span className="text-[10px] app-muted">جهت موج</span><b className="block text-xl mt-1">{w?.wave_direction??'—'}°</b></div><div className="p-3 rounded-xl bg-[var(--surface-2)]"><span className="text-[10px] app-muted">باد-موج</span><b className="block text-xl mt-1">{w?.wind_wave_height??'—'} m</b></div><div className="p-3 rounded-xl bg-[var(--surface-2)]"><span className="text-[10px] app-muted">Swell</span><b className="block text-xl mt-1">{w?.swell_wave_height??'—'} m</b></div></div>}</section>
  <section className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex items-center justify-between mb-3"><div><div className="text-[10px] app-muted">LIVE AIS · OPEN WATERS</div><h2 className="font-bold mt-1">نقشه زنده دریای خزر</h2></div><Ship size={20} className="text-cyan-300"/></div><div className="relative h-[420px] rounded-xl overflow-hidden border app-border"><MapContainer center={[39.5,51.5]} zoom={5} minZoom={4} maxZoom={12} scrollWheelZoom className="h-full w-full"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><FitCaspian/>{focus&&<FlyTo position={focus}/>}<Polyline positions={portPositions} pathOptions={{color:'#22d3ee',weight:2,opacity:.45,dashArray:'6 8'}}/>{ports.map(p=><Marker key={p[0]} position={[p[1],p[2]]} icon={portIcon}><Popup><b>{p[0]}</b><br/>بندر/نقطه مسیر خزر</Popup></Marker>)}{live.map(x=><Marker key={`live-${x.mmsi}`} position={[x.lat,x.lon]} icon={vesselIcon}><Popup><b>{x.name||'Unknown vessel'}</b><br/>MMSI: {x.mmsi}<br/>مختصات: {x.lat.toFixed(5)}, {x.lon.toFixed(5)}<br/>سرعت: {x.sog??'—'} kn<br/>Course: {x.cog??'—'}°<br/>{x.seen?new Date(x.seen).toLocaleString('fa-IR'):'زمان نامشخص'}</Popup></Marker>)}{activePositions.map((p,i)=><Marker key={`db-${active[i].id}`} position={p} icon={vesselIcon}><Popup><b>{active[i].name}</b><br/>IMO: {active[i].imo_number||'—'}<br/>MMSI: {active[i].mmsi_number||'—'}<br/>منبع: {active[i].last_position_source||'—'}</Popup></Marker>)}</MapContainer><div className="absolute z-[1000] bottom-2 right-2 rounded-lg bg-black/65 text-white px-2 py-1 text-[10px]">{live.length} کشتی AIS · نقشه تعاملی</div></div></section></div>
  <section className="rounded-2xl border app-border bg-[var(--surface)] p-4 mt-3"><div className="flex items-center gap-2 mb-3"><Compass size={17} className="text-cyan-300"/><h2 className="font-bold text-sm">کشتی‌های AIS زنده</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-2">{live.map(x=><button type="button" key={x.mmsi} onClick={()=>setFocus([x.lat,x.lon])} className="text-right rounded-xl bg-[var(--surface-2)] p-3 hover:bg-[var(--surface)]"><div className="flex justify-between"><b className="text-sm truncate">{x.name||'Unknown vessel'}</b><Ship size={15}/></div><div className="text-[10px] app-muted mt-2">MMSI: {x.mmsi}</div><div className="text-[10px] app-muted mt-2">مختصات: {x.lat.toFixed(5)}, {x.lon.toFixed(5)}</div><div className="flex gap-3 text-[10px] app-muted mt-2"><span><Wind size={11} className="inline ml-1"/>{x.sog??'—'} kn</span><span>Course {x.cog??'—'}°</span></div><div className="text-[10px] app-muted mt-1">{x.seen?new Date(x.seen).toLocaleString('fa-IR'):'زمان نامشخص'}</div></button>)}{!live.length&&<div className="text-xs app-muted">در این لحظه داده AIS زنده دریافت نشد.</div>}</div></section>
  {selected&&v.find(x=>x.id===selected)&&(()=>{const x=v.find(y=>y.id===selected)!;return <section className="rounded-2xl border app-border bg-[var(--surface)] p-4 mt-3"><div className="flex items-center gap-2 mb-3"><LocateFixed size={17} className="text-cyan-300"/><h2 className="font-bold text-sm">جزئیات کشتی انتخاب‌شده</h2></div><div className="grid md:grid-cols-4 gap-2 text-xs"><div className="rounded-xl bg-[var(--surface-2)] p-3"><span className="app-muted block text-[10px]">نام</span><b>{x.name||'—'}</b></div><div className="rounded-xl bg-[var(--surface-2)] p-3"><span className="app-muted block text-[10px]">IMO</span><b>{x.imo_number||'—'}</b></div><div className="rounded-xl bg-[var(--surface-2)] p-3"><span className="app-muted block text-[10px]">MMSI</span><b dir="ltr">{x.mmsi_number||'—'}</b></div><div className="rounded-xl bg-[var(--surface-2)] p-3"><span className="app-muted block text-[10px]">آخرین منبع</span><b>{x.last_position_source||'—'}</b></div></div></section>})()}
 </div></main>;
};
