import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,Download,FileText,Loader2,Trash2,Upload} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';

type Client={id:string;name:string;national_id:string|null};type Doc={id:string;original_name:string;display_name:string|null;storage_path:string;mime_type:string|null;size_bytes:number|null;created_at:string};
const BUCKET='customs_documents';
export const ClientDocumentManagerPage:React.FC=()=>{const[clients,setClients]=useState<Client[]>([]);const[selected,setSelected]=useState('');const[docs,setDocs]=useState<Doc[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const[input]=useState(()=>React.createRef<HTMLInputElement>());
 const profile=async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('کاربر وارد نشده است.');const{data,error}=await supabase.from('profiles').select('organization_id').eq('id',user.id).single();if(error||!data?.organization_id)throw error||new Error('سازمان کاربر مشخص نیست.');return{user,org:data.organization_id};};
 const loadClients=async()=>{const{org}=await profile();const{data,error}=await supabase.from('clients').select('id,name,national_id').eq('organization_id',org).order('name');if(error)throw error;setClients((data||[]) as Client[]);const saved=localStorage.getItem('customs_last_client');const sid=JSON.parse(saved||'null')?.id;setSelected(sid&&data?.some((x:any)=>x.id===sid)?sid:data?.[0]?.id||'')};
 const loadDocs=async(id:string)=>{if(!id)return setDocs([]);const{data,error}=await supabase.from('customs_documents').select('id,original_name,display_name,storage_path,mime_type,size_bytes,created_at').eq('client_id',id).is('shipment_id',null).order('created_at',{ascending:false});if(error)throw error;setDocs((data||[]) as Doc[])};
 useEffect(()=>{void loadClients().catch(e=>setError(e.message))},[]);useEffect(()=>{void loadDocs(selected).catch(e=>setError(e.message))},[selected]);
 const upload=async(files:FileList|null)=>{if(!files?.length||!selected)return;setBusy(true);setError('');try{const{user,org}=await profile();for(const f of Array.from(files)){if(!/\.(pdf|jpe?g|png)$/i.test(f.name))throw new Error('فقط PDF/JPG/PNG قابل آپلود است.');const safe=f.name.replace(/[^\w.\-\u0600-\u06ff]+/g,'_');const path=`${org}/clients/${selected}/${crypto.randomUUID()}-${safe}`;const{error:ue}=await supabase.storage.from(BUCKET).upload(path,f,{contentType:f.type||'application/octet-stream',upsert:false});if(ue)throw ue;const{error:de}=await supabase.from('customs_documents').insert({organization_id:org,client_id:selected,shipment_id:null,case_id:null,document_type:'TECHNICAL_SPEC_CATALOG',original_name:f.name,display_name:f.name,storage_path:path,mime_type:f.type,size_bytes:f.size,created_by:user.id,status:'review',tags:[]});if(de)throw de}await loadDocs(selected);setMessage('مدرک شرکت ذخیره شد.')}catch(e:any){setError(e.message||'آپلود ناموفق بود')}finally{setBusy(false)}};
 const download=async(d:Doc)=>{const{data,error}=await supabase.storage.from(BUCKET).download(d.storage_path);if(error)return setError(error.message);const u=URL.createObjectURL(data);const a=document.createElement('a');a.href=u;a.download=d.original_name;a.click();URL.revokeObjectURL(u)};
 const remove=async(d:Doc)=>{if(!window.confirm(`مدرک «${d.original_name}» حذف شود؟`))return;setBusy(true);try{await supabase.storage.from(BUCKET).remove([d.storage_path]);const{error}=await supabase.from('customs_documents').delete().eq('id',d.id);if(error)throw error;await loadDocs(selected)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const client=clients.find(x=>x.id===selected);return <main dir="rtl" className="min-h-screen p-5 md:p-8" style={{background:'var(--bg)',color:'var(--text)'}}><div className="max-w-6xl mx-auto space-y-5"><header className="flex items-center justify-between"><div><div className="text-xs app-muted">فایل منیجر</div><h1 className="text-2xl font-black">مدارک شرکت‌ها</h1><p className="text-sm app-muted mt-1">مدارک ثابت هر شرکت برای مراجعه و استفاده در زمان نیاز.</p></div><Link to="/clients" className="px-4 py-2 rounded-xl border app-border bg-[var(--surface)] text-sm"><ArrowRight className="inline ml-1" size={15}/>صاحبان کالا</Link></header>{error&&<div className="rounded-xl border border-red-400/40 bg-red-500/10 p-3 text-sm">{error}</div>}{message&&<div className="rounded-xl border border-emerald-400/40 bg-emerald-500/10 p-3 text-sm">{message}</div>}<section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><label className="text-sm font-bold">شرکت</label><select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 w-full rounded-xl border app-border bg-[var(--surface-2)] p-3">{clients.map(c=><option key={c.id} value={c.id}>{c.name} — {c.national_id||'بدون شناسه ملی'}</option>)}</select>{client&&<div className="mt-3 text-xs app-muted">مدارک اختصاصی: {client.name}</div>}</section><section className="rounded-2xl border app-border bg-[var(--surface)] overflow-hidden"><div className="p-5 border-b app-border flex items-center justify-between"><h2 className="font-black">مدارک شرکت</h2><button disabled={!selected||busy} onClick={()=>input.current?.click()} className="px-4 py-2 rounded-xl bg-[var(--primary)] text-white font-bold"><Upload size={15} className="inline ml-2"/>آپلود مدرک</button><input ref={input} hidden type="file" multiple accept="application/pdf,image/jpeg,image/png" onChange={e=>{void upload(e.target.files);e.currentTarget.value=''}}/></div>{docs.length===0?<div className="p-8 text-center app-muted">هنوز مدرکی برای این شرکت ثبت نشده است.</div>:<div>{docs.map(d=><div key={d.id} className="flex items-center justify-between gap-3 p-4 border-b app-border"><div className="flex items-center gap-3 min-w-0"><FileText size={19}/><div className="min-w-0"><div className="font-semibold truncate">{d.display_name||d.original_name}</div><div className="text-xs app-muted">{new Date(d.created_at).toLocaleDateString('fa-IR')}</div></div></div><div className="flex gap-2"><button onClick={()=>void download(d)} className="p-2 rounded-lg border app-border" title="دانلود"><Download size={16}/></button><button onClick={()=>void remove(d)} disabled={busy} className="p-2 rounded-lg border border-red-400/40 text-red-500" title="حذف"><Trash2 size={16}/></button></div></div>)}</div>}</section></div></main>};
