import React,{useEffect,useMemo,useState} from 'react';
import {Anchor,ArrowRight,Clock3,FileCheck2,Plus,RefreshCw,ShieldCheck,Truck,Wallet,Check,Trash2} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
const labels:Record<string,string>={draft:'پیش‌نویس',registration_order:'ثبت سفارش',documents_ready:'اسناد آماده',epl_submitted:'اظهار ثبت شد',kottaj_received:'کوتاژ دریافت شد',path_green:'مسیر سبز',path_yellow:'مسیر زرد',path_red:'مسیر قرمز',valuation:'ارزش‌گذاری',duties_calculation:'محاسبه حقوق',exit_permit:'مجوز خروج',completed:'تکمیل‌شده',archived:'بایگانی'};
const shipmentLabels:Record<string,string>={draft:'پیش‌نویس',booking_confirmed:'تأیید رزرو',loading:'در حال بارگیری',loaded:'بارگیری کامل',departed:'حرکت',in_transit:'در مسیر',approaching_destination:'نزدیک مقصد',anchorage:'لنگرگاه',berthing:'پهلوگیری',discharging:'در حال تخلیه',discharged:'تخلیه کامل',completed:'تکمیل',delayed:'تأخیر',cancelled:'لغو'};
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(Math.round(n));
const dt=(v:string)=>new Date(v).toLocaleString('fa-IR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const emptyReminder={title:'',description:'',dueAt:'',priority:'normal',caseId:'',shipmentId:''};
export const ControlCenterPage:React.FC=()=>{
 const[cases,setCases]=useState<any[]>([]),[shipments,setShipments]=useState<any[]>([]),[permits,setPermits]=useState<any[]>([]),[exits,setExits]=useState<any[]>([]),[finance,setFinance]=useState<any[]>([]),[reminders,setReminders]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[reminder,setReminder]=useState(emptyReminder),[savingReminder,setSavingReminder]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const results=await Promise.all([supabase.from('cases').select('id,case_number,status,client_id,created_at').order('created_at',{ascending:false}),supabase.rpc('get_control_center_shipments'),supabase.from('permits').select('id,case_id,permit_type,status,expires_at').order('created_at',{ascending:false}),supabase.from('case_exit_operations').select('id,case_id,exit_status,exit_permit_no,exit_at,vehicle_plate').order('updated_at',{ascending:false}),supabase.from('financial_transactions').select('id,case_id,transaction_type,base_amount_irr').order('transaction_date',{ascending:false}),supabase.from('operational_reminders').select('id,title,description,due_at,priority,status,case_id,shipment_id,created_at').eq('status','open').order('due_at',{ascending:true})]);const bad=results.find(r=>r.error);if(bad?.error)throw bad.error;const[{data:c},{data:s},{data:p},{data:e},{data:f},{data:rm}]=results;setCases(c||[]);setShipments(s||[]);setPermits(p||[]);setExits(e||[]);setFinance(f||[]);setReminders(rm||[])}catch(e:any){setError(e?.message||'خطا در دریافت اطلاعات مرکز کنترل')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const openCases=cases.filter(x=>!['completed','archived'].includes(x.status)),pendingPermits=permits.filter(x=>x.status==='pending'),pendingExits=exits.filter(x=>!['exited','cancelled'].includes(x.exit_status)),financeTotal=useMemo(()=>finance.reduce((n,x)=>n+(Number(x.base_amount_irr)||0)*(x.transaction_type==='expense'||x.transaction_type==='withdrawal'?-1:1),0),[finance]),dueReminders=reminders.filter(r=>new Date(r.due_at).getTime()<=Date.now());
 const saveReminder=async()=>{setError('');if(!reminder.title.trim())return setError('عنوان Reminder را وارد کنید.');if(!reminder.dueAt)return setError('تاریخ و زمان Reminder را وارد کنید.');const due=new Date(reminder.dueAt);if(Number.isNaN(due.getTime()))return setError('تاریخ و زمان Reminder نامعتبر است.');setSavingReminder(true);try{const{error:e}=await supabase.rpc('create_operational_reminder',{p_title:reminder.title.trim(),p_description:reminder.description.trim()||null,p_due_at:due.toISOString(),p_priority:reminder.priority,p_case_id:reminder.caseId||null,p_shipment_id:reminder.shipmentId||null});if(e)throw e;setReminder(emptyReminder);await load()}catch(e:any){setError(e?.message||'ثبت Reminder انجام نشد.')}finally{setSavingReminder(false)}};
 const completeReminder=async(id:string)=>{const{error:e}=await supabase.from('operational_reminders').update({status:'done',completed_at:new Date().toISOString()}).eq('id',id);if(e)setError(e.message);else await load()};
 const deleteReminder=async(id:string)=>{const{error:e}=await supabase.from('operational_reminders').delete().eq('id',id);if(e)setError(e.message);else await load()};
 return <main className="min-h-screen p-4 sm:p-6 lg:p-8" dir="rtl"><div className="max-w-[1720px] mx-auto"><header className="flex flex-col xl:flex-row xl:items-end xl:justify-between gap-4 mb-6"><div><div className="text-xs app-muted mb-2">Operations Control Center</div><h1 className="text-2xl sm:text-3xl font-black">مرکز کنترل عملیات</h1><p className="text-sm app-muted mt-1">همه پرونده‌های فعال، محموله‌ها، مجوزها، خروج، مالی و کارهای پیگیری در یک صفحه.</p></div><div className="flex gap-2"><button onClick={load} className="icon-btn" title="بروزرسانی"><RefreshCw size={17} className={loading?'animate-spin':''}/></button><Link to="/" className="inline-flex items-center gap-2 rounded-xl border app-border bg-[var(--surface)] px-4 py-2.5 text-sm font-bold"><ArrowRight size={16}/> صفحه اصلی</Link></div></header>{error&&<div className="mb-5 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm">{error}</div>}
 <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-5"><Stat icon={FileCheck2} title="پرونده باز" value={openCases.length}/><Stat icon={Anchor} title="محموله" value={shipments.length}/><Stat icon={ShieldCheck} title="مجوز در انتظار" value={pendingPermits.length}/><Stat icon={Truck} title="خروج باز" value={pendingExits.length}/><Stat icon={Wallet} title="خالص مالی IRR" value={money(financeTotal)}/></div>
 <section className="rounded-2xl border app-border bg-[var(--surface)] p-4 sm:p-5 mb-5"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3 mb-4"><div><h2 className="font-black flex items-center gap-2"><Clock3 size={18} className="text-[var(--primary)]"/> Reminder و کارهای پیگیری</h2><p className="text-xs app-muted mt-1">کارهای باز، سررسیدشده و متصل به پرونده.</p></div><div className="flex gap-2 text-xs"><span className="rounded-full px-3 py-1 bg-red-500/10 text-red-500 font-bold">سررسید: {dueReminders.length}</span><span className="rounded-full px-3 py-1 bg-amber-500/10 text-amber-500 font-bold">باز: {reminders.length}</span></div></div>
 <div className="grid lg:grid-cols-[1fr_1.5fr] gap-4"><div className="rounded-xl border app-border bg-[var(--surface-2)] p-4 space-y-2"><input placeholder="عنوان کار / پیگیری" value={reminder.title} onChange={e=>setReminder(x=>({...x,title:e.target.value}))} className="w-full rounded-lg border app-border bg-[var(--surface)] px-3 py-2 text-sm"/><textarea placeholder="توضیح کوتاه" value={reminder.description} onChange={e=>setReminder(x=>({...x,description:e.target.value}))} className="w-full rounded-lg border app-border bg-[var(--surface)] px-3 py-2 text-sm min-h-20"/><div className="grid grid-cols-2 gap-2"><input type="datetime-local" value={reminder.dueAt} onChange={e=>setReminder(x=>({...x,dueAt:e.target.value}))} className="rounded-lg border app-border bg-[var(--surface)] px-2 py-2 text-xs"/><select value={reminder.priority} onChange={e=>setReminder(x=>({...x,priority:e.target.value}))} className="rounded-lg border app-border bg-[var(--surface)] px-2 py-2 text-xs"><option value="low">کم</option><option value="normal">عادی</option><option value="high">مهم</option><option value="urgent">فوری</option></select></div><div className="grid grid-cols-2 gap-2"><select value={reminder.caseId} onChange={e=>setReminder(x=>({...x,caseId:e.target.value}))} className="rounded-lg border app-border bg-[var(--surface)] px-2 py-2 text-xs"><option value="">بدون پرونده</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number||c.id.slice(0,8)}</option>)}</select><select value={reminder.shipmentId} onChange={e=>setReminder(x=>({...x,shipmentId:e.target.value}))} className="rounded-lg border app-border bg-[var(--surface)] px-2 py-2 text-xs"><option value="">بدون محموله</option>{shipments.map(s=><option key={s.id} value={s.id}>{s.cargo_count||'—'} {s.cargo_count_unit||''} · {s.client_name||'بدون صاحب کالا'} · {s.vessel_name||'کشتی نامشخص'}</option>)}</select></div><button onClick={saveReminder} disabled={savingReminder} className="w-full rounded-lg bg-[var(--primary)] text-white px-3 py-2.5 text-sm font-bold disabled:opacity-60"><Plus size={15} className="inline ml-1"/>{savingReminder?'در حال ثبت...':'ثبت Reminder'}</button></div>
 <div className="space-y-2 max-h-80 overflow-auto">{reminders.map(r=>{const overdue=new Date(r.due_at).getTime()<=Date.now();return <div key={r.id} className={`rounded-xl border p-3 ${overdue?'border-red-500/30 bg-red-500/5':'app-border bg-[var(--surface-2)]'}`}><div className="flex items-start gap-3"><span className={`mt-1 h-2.5 w-2.5 rounded-full ${overdue?'bg-red-500':'bg-[var(--primary)]'}`}/><div className="min-w-0 flex-1"><div className="font-bold text-sm">{r.title}</div><div className="text-xs app-muted mt-1">{r.description||'بدون توضیح'} · {dt(r.due_at)}</div><div className="text-[11px] app-muted mt-1">{r.case_id?'متصل به پرونده':''}{r.shipment_id?' · متصل به محموله':''} · اولویت {r.priority}</div></div><button onClick={()=>completeReminder(r.id)} title="انجام شد" className="icon-btn !w-8 !h-8"><Check size={15}/></button><button onClick={()=>deleteReminder(r.id)} title="حذف" className="icon-btn !w-8 !h-8 text-red-500"><Trash2 size={14}/></button></div></div>})}{reminders.length===0&&<div className="py-10 text-center app-muted text-sm">Reminder فعالی ندارید.</div>}</div></div></section>
 <div className="grid xl:grid-cols-2 gap-5"><Panel title="پرونده‌های فعال" subtitle="هر پرونده و وضعیت فعلی آن" icon={FileCheck2}>{cases.slice(0,15).map(c=><Row key={c.id} title={c.case_number||c.id.slice(0,8)} subtitle={`${labels[c.status]||c.status||'بدون وضعیت'}`} to={`/operations?caseId=${encodeURIComponent(c.id)}`}/>)}{cases.length===0&&<Empty text="پرونده‌ای ثبت نشده."/>}</Panel><Panel title="کشتیرانی و محموله" subtitle="تعداد · واحد · صاحب کالا · نام کشتی" icon={Anchor}>{shipments.slice(0,15).map(s=><Row key={s.id} title={`${s.cargo_count!=null?new Intl.NumberFormat('fa-IR').format(Number(s.cargo_count)):'—'} ${s.cargo_count_unit||''} · ${s.client_name||'صاحب کالا نامشخص'} · ${s.vessel_name||'کشتی نامشخص'}`} subtitle={`${s.bill_of_lading_no||'B/L ثبت نشده'} · ${s.shipping_line||'کشتیرانی نامشخص'} · ${shipmentLabels[s.current_status]||s.current_status||'بدون وضعیت'} · ${s.current_location||'موقعیت ثبت نشده'}`} to="/maritime"/>)}{shipments.length===0&&<Empty text="محموله‌ای ثبت نشده."/>}</Panel><Panel title="مجوزها و خروج" subtitle="مواردی که باید پیگیری شوند" icon={ShieldCheck}>{permits.filter(x=>x.status==='pending').slice(0,8).map(p=><Row key={p.id} title={p.permit_type||'مجوز'} subtitle={`در انتظار · سررسید ${p.expires_at?dt(p.expires_at):'ثبت نشده'}`} to="/operations?tab=documents"/>)}{exits.filter(x=>!['exited','cancelled'].includes(x.exit_status)).slice(0,8).map(x=><Row key={x.id} title={x.exit_permit_no||'مجوز خروج'} subtitle={`${x.vehicle_plate||'پلاک نامشخص'} · ${x.exit_status||'بدون وضعیت'}`} to="/exit"/>)}{pendingPermits.length===0&&pendingExits.length===0&&<Empty text="مورد باز وجود ندارد."/>}</Panel><Panel title="وضعیت مالی" subtitle="نمای خلاصه دفتر مالی" icon={Wallet}><div className="rounded-xl bg-[var(--surface-2)] p-5 text-center"><div className="text-xs app-muted">خالص مالی</div><div className="text-3xl font-black mt-2" dir="rtl">{money(financeTotal)} <span className="text-sm">ریال</span></div><Link to="/finance" className="inline-block mt-4 text-sm font-bold text-[var(--primary)]">مشاهده مالی</Link></div></Panel></div></div></main>};
const Stat=({icon:Icon,title,value}:{icon:any,title:string,value:any})=><div className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex items-center gap-2 text-xs app-muted"><Icon size={16}/>{title}</div><div className="text-2xl font-black mt-2">{value}</div></div>;
const Panel=({title,subtitle,icon:Icon,children}:{title:string,subtitle:string,icon:any,children:React.ReactNode})=><section className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex items-center gap-2 mb-3"><Icon size={18} className="text-[var(--primary)]"/><div><h2 className="font-black">{title}</h2><p className="text-xs app-muted">{subtitle}</p></div></div><div className="space-y-2">{children}</div></section>;
const Row=({title,subtitle,to}:{title:string,subtitle:string,to:string})=><Link to={to} className="block rounded-xl bg-[var(--surface-2)] p-3 hover:opacity-80"><div className="font-bold text-sm">{title}</div><div className="text-xs app-muted mt-1">{subtitle}</div></Link>;
const Empty=({text}:{text:string})=><div className="py-8 text-center app-muted text-sm">{text}</div>;
