import React,{useEffect,useMemo,useRef,useState} from 'react';
import {AlertTriangle,Download,Eye,FileText,Loader2,Plus,RefreshCw,Search,Upload,X} from 'lucide-react';
import {supabase} from '../lib/supabase';

type DocType='PROFORMA_INVOICE'|'COMMERCIAL_INVOICE'|'PACKING_LIST'|'BILL_OF_LADING'|'DELIVERY_ORDER'|'EPL_DELIVERY_ORDER'|'WAREHOUSE_RECEIPT'|'IMPORT_LICENSE'|'SATA_PAYMENT_DOC'|'INSURANCE_POLICY'|'CERTIFICATE_OF_ORIGIN'|'INSPECTION_CERTIFICATE'|'TECHNICAL_SPEC_CATALOG'|'POWER_OF_ATTORNEY'|'CUSTOMS_DECLARATION_PRINT';
type Shipment={id:string;case_id:string|null;bill_of_lading_no:string|null;net_weight_kg:number|null;gross_weight_kg:number|null;vessel_id:string|null;vessel_name:string;quantity:number|null;cargo_owner:string};
type Doc={id:string;shipment_id:string|null;document_type:DocType|null;original_name:string;display_name:string|null;storage_path:string|null;mime_type:string|null;size_bytes:number|null;status:string;tags:string[];document_number:string|null;issue_date_shamsi:string|null;gross_weight_kg:number|null;net_weight_kg:number|null;quantity:number|null;packaging_type:string|null;currency:string|null;invoice_amount:number|null;exporter_name:string|null;importer_name:string|null};
const TYPES:{v:DocType;l:string}[]=[['PROFORMA_INVOICE','پروفرما'],['COMMERCIAL_INVOICE','سیاهه خرید'],['PACKING_LIST','پکینگ لیست / عدل‌بندی'],['BILL_OF_LADING','بارنامه'],['DELIVERY_ORDER','ترخیصیه کشتیرانی'],['EPL_DELIVERY_ORDER','ترخیصیه الکترونیک'],['WAREHOUSE_RECEIPT','قبض انبار'],['IMPORT_LICENSE','ثبت سفارش'],['SATA_PAYMENT_DOC','کد ساتا / اسناد بانکی'],['INSURANCE_POLICY','بیمه‌نامه'],['CERTIFICATE_OF_ORIGIN','گواهی مبدأ'],['INSPECTION_CERTIFICATE','گواهی بازرسی کالا'],['TECHNICAL_SPEC_CATALOG','آنالیز / کاتالوگ فنی'],['POWER_OF_ATTORNEY','وکالت‌نامه / مدارک هویتی'],['CUSTOMS_DECLARATION_PRINT','پرینت اظهارنامه / کوتاژ']];
const required:DocType[]=['PROFORMA_INVOICE','COMMERCIAL_INVOICE','PACKING_LIST','BILL_OF_LADING','DELIVERY_ORDER','WAREHOUSE_RECEIPT','IMPORT_LICENSE','CERTIFICATE_OF_ORIGIN'];
const TAGS=['نیاز به اصلاح','تأیید گمرک','مغایرت‌دار'];
const label=(t:DocType|null)=>TYPES.find(x=>x.v===t)?.l||'دسته‌بندی نشده';
const kg=(v:unknown)=>{const n=Number(String(v??'').replace(/[٬,]/g,'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?Math.round(n):null};
const isImage=(d:Doc)=>/^image\//i.test(d.mime_type||'');
const isPdf=(d:Doc)=>/pdf/i.test(d.mime_type||'')||/\.pdf$/i.test(d.original_name);

export const CustomsDocumentManagerPage:React.FC=()=>{
 const[shipments,setShipments]=useState<Shipment[]>([]),[shipmentId,setShipmentId]=useState(''),[docs,setDocs]=useState<Doc[]>([]),[query,setQuery]=useState(''),[type,setType]=useState<DocType|''>(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Doc|null>(null),[preview,setPreview]=useState(''),[drag,setDrag]=useState(false),[mismatches,setMismatches]=useState<any[]>([]);const inputRef=useRef<HTMLInputElement>(null);
 const loadShipments=async()=>{setBusy(true);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('کاربر وارد نشده است.');const{data:p,error:pe}=await supabase.from('profiles').select('organization_id').eq('id',user.id).single();if(pe||!p?.organization_id)throw pe||new Error('سازمان کاربر مشخص نیست.');const[{data:s,error:se},{data:v,error:ve},{data:docMeta,error:de}]=await Promise.all([supabase.from('shipments').select('id,case_id,bill_of_lading_no,net_weight_kg,gross_weight_kg,vessel_id').eq('organization_id',p.organization_id).order('created_at',{ascending:false}),supabase.from('vessels').select('id,name').eq('organization_id',p.organization_id),supabase.from('customs_documents').select('shipment_id,quantity,importer_name').eq('organization_id',p.organization_id)]);if(se)throw se;if(ve)throw ve;if(de)throw de;const names=new Map((v||[]).map((x:any)=>[x.id,x.name]));const meta=new Map<string,{quantity:number;owner:string}>();for(const row of docMeta||[]){if(!row.shipment_id)continue;const q=Number(row.quantity);const prev=meta.get(row.shipment_id)||{quantity:0,owner:''};if(Number.isFinite(q)&&q>0)prev.quantity+=q;if(!prev.owner&&String(row.importer_name||'').trim())prev.owner=String(row.importer_name).trim();meta.set(row.shipment_id,prev)}const rows=(s||[]).map((x:any)=>{const m=meta.get(x.id);return{...x,vessel_name:names.get(x.vessel_id)||'',quantity:m?.quantity||null,cargo_owner:m?.owner||''}}) as Shipment[];setShipments(rows);if(!shipmentId&&rows[0])setShipmentId(rows[0].id);}catch(e:any){setError(e?.message||'دریافت محموله‌ها ناموفق بود')}finally{setBusy(false)}};
 const loadDocs=async(id:string)=>{if(!id){setDocs([]);setMismatches([]);return}setBusy(true);try{const{data,error:e}=await supabase.from('customs_documents').select('*').eq('shipment_id',id).order('created_at',{ascending:false});if(e)throw e;setDocs((data||[]) as Doc[]);const{data:v}=await supabase.rpc('validate_shipment_documents',{p_shipment_id:id});setMismatches(v?.mismatches||[]);}catch(e:any){setError(e?.message||'دریافت اسناد ناموفق بود')}finally{setBusy(false)}};
 useEffect(()=>{loadShipments()},[]);useEffect(()=>{loadDocs(shipmentId)},[shipmentId]);
 const current=shipments.find(s=>s.id===shipmentId);const filtered=useMemo(()=>docs.filter(d=>(!type||d.document_type===type)&&(!query||`${d.display_name||d.original_name} ${d.document_number||''}`.toLowerCase().includes(query.toLowerCase()))),[docs,type,query]);const missing=required.filter(t=>!docs.some(d=>d.document_type===t&&!['rejected','archived'].includes(d.status)));
 const save=async(d:Doc,patch:Partial<Doc>)=>{const{error:e}=await supabase.from('customs_documents').update(patch).eq('id',d.id);if(e){setError(e.message);return}setDocs(ds=>ds.map(x=>x.id===d.id?{...x,...patch}:x));setSelected(s=>s&&s.id===d.id?{...s,...patch}:s);if(patch.quantity!==undefined||patch.importer_name!==undefined)loadShipments()};
 const upload=async(files:FileList|null)=>{if(!files?.length||!current)return;setBusy(true);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('کاربر وارد نشده است.');const{data:p,error:pe}=await supabase.from('profiles').select('organization_id').eq('id',user.id).single();if(pe||!p?.organization_id)throw pe||new Error('سازمان کاربر مشخص نیست.');for(const f of Array.from(files)){if(!/\.(pdf|jpe?g|png|xls|xlsx)$/i.test(f.name))throw new Error('فقط PDF، JPG، PNG و Excel مجاز است.');const path=`${p.organization_id}/${current.id}/${crypto.randomUUID()}-${f.name.replace(/[^\w.\-\u0600-\u06ff]+/g,'_')}`;const{error:ue}=await supabase.storage.from('customs-documents').upload(path,f,{contentType:f.type||'application/octet-stream'});if(ue)throw ue;const{error:de}=await supabase.from('customs_documents').insert({organization_id:p.organization_id,shipment_id:current.id,case_id:current.case_id,original_name:f.name,display_name:f.name,storage_path:path,mime_type:f.type||'application/octet-stream',size_bytes:f.size,created_by:user.id,status:'review',tags:[]});if(de)throw de}await loadDocs(current.id);await loadShipments()}catch(e:any){setError(e?.message||'بارگذاری ناموفق بود')}finally{setBusy(false)}};
 const openPreview=async(d:Doc)=>{if(!d.storage_path)return;const{data,error:e}=await supabase.storage.from('customs-documents').createSignedUrl(d.storage_path,900);if(e){setError(e.message);return}setPreview(data?.signedUrl||'')};
 const download=async(d:Doc)=>{if(!d.storage_path)return;const{data,error:e}=await supabase.storage.from('customs-documents').download(d.storage_path);if(e){setError(e.message);return}const u=URL.createObjectURL(data);const a=document.createElement('a');a.href=u;a.download=d.display_name||d.original_name;a.click();URL.revokeObjectURL(u)};
 return <main dir="rtl" className="min-h-screen p-4 md:p-6" style={{background:'var(--bg)',color:'var(--text)'}}><div className="max-w-7xl mx-auto space-y-4">
 <header className="flex items-center gap-3"><div><h1 className="text-2xl font-black">فایل‌منیجر اسناد گمرکی</h1><p className="text-xs app-muted mt-1">محموله‌ها با تعداد و صاحب کالا، و اسناد به سبک فایل‌منیجر موبایل نمایش داده می‌شوند.</p></div><button className="icon-btn mr-auto" onClick={loadShipments} title="بروزرسانی"><RefreshCw size={17}/></button></header>
 <section className="rounded-2xl border app-border bg-[var(--surface)] p-3 grid md:grid-cols-[minmax(280px,1fr)_minmax(220px,1.3fr)_auto] gap-2"><select className="field" value={shipmentId} onChange={e=>setShipmentId(e.target.value)}><option value="">انتخاب محموله / کشتی</option>{shipments.map(s=><option key={s.id} value={s.id}>{s.vessel_name||'کشتی بدون نام'}{s.bill_of_lading_no?` — ${s.bill_of_lading_no}`:''} · {s.quantity??'—'} عدد · {s.cargo_owner||'صاحب کالا نامشخص'}</option>)}</select><div className="relative"><Search className="absolute right-3 top-2.5 app-muted" size={16}/><input className="field w-full pr-9" placeholder="جستجوی سند یا شماره سند" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="field" value={type} onChange={e=>setType(e.target.value as DocType)}><option value="">همه اسناد</option>{TYPES.map(t=><option key={t.v} value={t.v}>{t.l}</option>)}</select></section>
 {current&&<section className="rounded-2xl border app-border bg-[var(--surface)] px-4 py-3 flex flex-wrap items-center gap-5 text-sm"><strong>{current.vessel_name||'کشتی بدون نام'}</strong><span className="app-muted">بارنامه: {current.bill_of_lading_no||'—'}</span><span className="app-muted">تعداد: {current.quantity==null?'—':current.quantity.toLocaleString('fa-IR')}</span><span className="app-muted">صاحب کالا: {current.cargo_owner||'—'}</span><span className="app-muted">وزن خالص: {current.net_weight_kg==null?'—':current.net_weight_kg.toLocaleString('fa-IR')} کیلوگرم</span><span className={missing.length?'text-amber-400':'text-emerald-400'}>{missing.length?`${missing.length} مدرک کسری`:'مدارک کامل'}</span></section>}
 {mismatches.length>0&&<section className="rounded-2xl border border-amber-500/40 bg-amber-500/10 px-4 py-3"><div className="flex items-center gap-2 font-bold text-amber-300"><AlertTriangle size={18}/>مغایرت احتمالی</div>{mismatches.slice(0,6).map((m:any,i:number)=><div key={i} className="text-xs mt-1">• {m.message||'مغایرت بین اسناد'}</div>)}</section>}
 <section onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);upload(e.dataTransfer.files)}} className={`rounded-2xl border border-dashed p-5 flex items-center gap-3 ${drag?'border-[var(--primary)] bg-[var(--primary)]/10':'app-border bg-[var(--surface)]'}`}><Upload size={22}/><div className="flex-1"><strong>افزودن سند</strong><div className="text-xs app-muted">فایل را اینجا رها کنید یا انتخاب کنید · PDF، JPG، PNG، Excel</div></div><button disabled={!current||busy} onClick={()=>inputRef.current?.click()} className="px-4 py-2 rounded-xl bg-[var(--primary)] text-white font-bold text-sm disabled:opacity-50"><Plus size={15} className="inline ml-1"/>انتخاب فایل</button><input ref={inputRef} hidden type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.xls,.xlsx" onChange={e=>upload(e.target.files)}/></section>
 <section className="rounded-2xl border app-border bg-[var(--surface)] overflow-hidden"><div className="px-4 py-3 border-b app-border flex justify-between items-center"><div><strong>اسناد محموله</strong><div className="text-[11px] app-muted mt-0.5">نام فایل مستقیماً زیر هر سند نمایش داده می‌شود.</div></div><span className="text-xs app-muted">{filtered.length} فایل</span></div>{filtered.length===0?<div className="p-10 text-center app-muted">{current?'برای این محموله سندی ثبت نشده است.':'ابتدا محموله را انتخاب کنید.'}</div>:<div className="p-3 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-3">{filtered.map(d=><article key={d.id} className="group rounded-2xl border app-border bg-[var(--surface-2)]/50 p-3 min-w-0 hover:border-[var(--primary)]/60 transition-colors"><button className="w-full text-right" onClick={()=>setSelected(d)} title={d.display_name||d.original_name}><div className="aspect-[4/3] rounded-xl bg-[var(--surface)] border app-border grid place-items-center overflow-hidden mb-2">{isImage(d)?<img src={d.storage_path?undefined:undefined} alt="" className="hidden"/>:<div className="relative"><FileText size={42}/><span className="absolute -bottom-1 -left-2 text-[8px] font-black px-1.5 py-0.5 rounded bg-[var(--primary)] text-white">{isPdf(d)?'PDF':'FILE'}</span></div>}</div><strong className="block text-xs leading-5 break-words line-clamp-2 min-h-10">{d.display_name||d.original_name||'سند بدون نام'}</strong><span className="block text-[10px] app-muted mt-1 truncate">{label(d.document_type)}</span></button><div className="mt-2 flex items-center justify-between gap-1"><span className="text-[9px] app-muted truncate">{d.size_bytes?`${Math.max(1,Math.round(d.size_bytes/1024))} KB`:''}</span><div className="flex gap-1"><button className="icon-btn !h-7 !w-7" title="پیش‌نمایش" onClick={()=>openPreview(d)}><Eye size={13}/></button><button className="icon-btn !h-7 !w-7" title="دانلود" onClick={()=>download(d)}><Download size={13}/></button></div></div></article>)}</div>}</section>
 {busy&&<div className="fixed bottom-4 left-4 rounded-xl bg-[var(--surface)] border app-border px-4 py-2 text-xs flex items-center gap-2"><Loader2 className="animate-spin" size={15}/>در حال پردازش...</div>}{error&&<div className="fixed bottom-4 right-4 max-w-md rounded-xl bg-red-500/10 border border-red-500/30 p-3 text-xs">{error}</div>}
 {selected&&<div className="fixed inset-0 z-50 bg-black/60 grid place-items-center p-4" onClick={()=>setSelected(null)}><div className="w-full max-w-2xl max-h-[90vh] overflow-auto rounded-2xl bg-[var(--surface)] border app-border p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="font-black">کنترل اطلاعات استخراج‌شده</h2><button className="icon-btn" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="grid md:grid-cols-2 gap-3 mt-4">{([['document_number','شماره سند'],['issue_date_shamsi','تاریخ صدور شمسی'],['net_weight_kg','وزن خالص (کیلوگرم)'],['gross_weight_kg','وزن ناخالص (کیلوگرم)'],['quantity','تعداد'],['packaging_type','نوع بسته'],['currency','نوع ارز'],['invoice_amount','مبلغ فاکتور'],['exporter_name','فروشنده'],['importer_name','صاحب کالا']] as const).map(([k,l])=><label key={k} className="text-xs"><span className="block mb-1">{l}</span><input className="field w-full" value={(selected as any)[k]??''} onChange={e=>setSelected({...selected,[k]:k.includes('weight')?kg(e.target.value):e.target.value})}/></label>)}</div><div className="mt-4 flex flex-wrap gap-1">{TAGS.map(t=><button key={t} onClick={()=>setSelected({...selected,tags:selected.tags.includes(t)?selected.tags.filter(x=>x!==t):[...selected.tags,t]})} className={`text-xs px-3 py-1.5 rounded-full border ${selected.tags.includes(t)?'border-[var(--primary)] bg-[var(--primary)]/10':'app-border app-muted'}`}>{t}</button>)}</div><button className="mt-5 w-full py-2.5 rounded-xl bg-[var(--primary)] text-white font-bold" onClick={async()=>{await save(selected,{document_number:selected.document_number,issue_date_shamsi:selected.issue_date_shamsi,net_weight_kg:kg(selected.net_weight_kg),gross_weight_kg:kg(selected.gross_weight_kg),quantity:selected.quantity,packaging_type:selected.packaging_type,currency:selected.currency,invoice_amount:selected.invoice_amount,exporter_name:selected.exporter_name,importer_name:selected.importer_name,tags:selected.tags});setSelected(null)}}>ذخیره اطلاعات</button></div></div>}
 {preview&&<div className="fixed inset-0 z-[60] bg-black/70 p-4 grid place-items-center" onClick={()=>setPreview('')}><div className="w-full h-full max-w-5xl bg-white rounded-2xl overflow-hidden" onClick={e=>e.stopPropagation()}><div className="h-12 px-3 flex justify-end items-center border-b"><button className="icon-btn" onClick={()=>setPreview('')}><X size={18}/></button></div><iframe title="پیش‌نمایش سند" src={preview} className="w-full h-[calc(100%-3rem)]"/></div></div>}
 </div></main>;
};