import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Download,Eye,ExternalLink,FileText,Image as ImageIcon,List,LayoutGrid,Loader2,RefreshCw,Search,Upload,X,Check} from 'lucide-react';
import PdfDocumentViewer from '../components/PdfDocumentViewer';
import {supabase} from '../lib/supabase';

type DocType='PROFORMA_INVOICE'|'COMMERCIAL_INVOICE'|'PACKING_LIST'|'BILL_OF_LADING'|'DELIVERY_ORDER'|'WAREHOUSE_RECEIPT'|'IMPORT_LICENSE'|'CERTIFICATE_OF_ORIGIN'|'INSPECTION_CERTIFICATE'|'INSURANCE_POLICY'|'SATA_PAYMENT_DOC'|'TECHNICAL_SPEC_CATALOG'|'POWER_OF_ATTORNEY'|'CUSTOMS_DECLARATION_PRINT';
type Shipment={id:string;case_id:string|null;bill_of_lading_no:string|null;net_weight_kg:number|null;vessel_name:string;quantity:number|null;quantity_unit:string;cargo_owner:string;cargo_description:string};
type Doc={id:string;shipment_id:string|null;document_type:DocType|null;original_name:string|null;display_name:string|null;storage_path:string|null;mime_type:string|null;size_bytes:number|null;status:string|null};
const BUCKET='customs_documents';
const TYPES:{v:DocType;l:string}[]=[{v:'PROFORMA_INVOICE',l:'پروفرما اینویس'},{v:'COMMERCIAL_INVOICE',l:'کامرشال اینویس / سیاهه خرید'},{v:'PACKING_LIST',l:'پکینگ لیست / عدل‌بندی'},{v:'BILL_OF_LADING',l:'بارنامه / B/L'},{v:'DELIVERY_ORDER',l:'ترخیصیه کشتیرانی'},{v:'WAREHOUSE_RECEIPT',l:'قبض انبار'},{v:'IMPORT_LICENSE',l:'ثبت سفارش'},{v:'CERTIFICATE_OF_ORIGIN',l:'گواهی مبدأ'},{v:'INSPECTION_CERTIFICATE',l:'گواهی بازرسی'},{v:'INSURANCE_POLICY',l:'بیمه‌نامه'},{v:'SATA_PAYMENT_DOC',l:'کد ساتا / اسناد بانکی'},{v:'TECHNICAL_SPEC_CATALOG',l:'آنالیز / کاتالوگ فنی'},{v:'POWER_OF_ATTORNEY',l:'وکالت‌نامه / مدارک هویتی'},{v:'CUSTOMS_DECLARATION_PRINT',l:'پرینت اظهارنامه / کوتاژ'}];
const REQUIRED:DocType[]=['PROFORMA_INVOICE','COMMERCIAL_INVOICE','PACKING_LIST','BILL_OF_LADING','CERTIFICATE_OF_ORIGIN'];
const label=(t:DocType|null)=>TYPES.find(x=>x.v===t)?.l||'دسته‌بندی نشده';
const inferType=(name:string):DocType|null=>{const n=name.toLowerCase();if(/proforma|pro forma|پروفرما|پروفورما/.test(n))return'PROFORMA_INVOICE';if(/commercial|سیاهه|کامرشال|invoice/.test(n))return'COMMERCIAL_INVOICE';if(/packing|pack list|عدل|بسته بندی|پکینگ/.test(n))return'PACKING_LIST';if(/bill of lading|b l|bl |بارنامه/.test(n))return'BILL_OF_LADING';if(/delivery order|do |ترخیصیه/.test(n))return'DELIVERY_ORDER';if(/warehouse|قبض انبار/.test(n))return'WAREHOUSE_RECEIPT';if(/import license|order registration|ثبت سفارش/.test(n))return'IMPORT_LICENSE';if(/origin|certificate of origin|گواهی مبدأ|گواهی مبدا/.test(n))return'CERTIFICATE_OF_ORIGIN';if(/inspection|sgs|بازرسی/.test(n))return'INSPECTION_CERTIFICATE';if(/insurance|بیمه/.test(n))return'INSURANCE_POLICY';if(/sata|ساتا|bank|بانک/.test(n))return'SATA_PAYMENT_DOC';if(/catalog|technical|آنالیز|کاتالوگ/.test(n))return'TECHNICAL_SPEC_CATALOG';if(/power|attorney|وکالت/.test(n))return'POWER_OF_ATTORNEY';if(/declaration|اظهارنامه|کوتاژ/.test(n))return'CUSTOMS_DECLARATION_PRINT';return null};
const fileName=(d:Doc)=>String(d.original_name||d.display_name||d.storage_path?.split('/').pop()||'سند بدون نام').replace(/^[0-9a-f-]{36}-/i,'');
const ext=(name:string)=>name.includes('.')?name.split('.').pop()!.toUpperCase():'FILE';
const isPdf=(d:Doc)=>/application\/pdf/i.test(d.mime_type||'')||/\.pdf$/i.test(fileName(d));
const isImage=(d:Doc)=>/^image\/(jpeg|jpg|png)$/i.test(d.mime_type||'')||/\.(jpe?g|png)$/i.test(fileName(d));
const sizeText=(n:number|null)=>!n?'':n<1048576?`${Math.max(1,Math.round(n/1024))} KB`:`${(n/1048576).toFixed(1)} MB`;
const statusLabel=(s:string|null)=>s==='approved'?'تأیید شده':s==='rejected'?'رد شده':s==='archived'?'بایگانی شده':s==='processing'?'در حال پردازش':'در انتظار بررسی';
const statusClass=(s:string|null)=>s==='approved'?'bg-green-500/15 text-green-700':s==='rejected'?'bg-red-500/15 text-red-700':s==='archived'?'bg-gray-500/15 text-gray-700':'bg-amber-500/15 text-amber-700';

export const CustomsDocumentManagerPage:React.FC=()=>{
 const[shipments,setShipments]=useState<Shipment[]>([]);const[shipmentId,setShipmentId]=useState('');const[docs,setDocs]=useState<Doc[]>([]);const[q,setQ]=useState('');const[type,setType]=useState('');const[status,setStatus]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[selected,setSelected]=useState<Doc|null>(null);const[previewUrl,setPreviewUrl]=useState('');const[view,setView]=useState<'grid'|'list'>('grid');const[inputRef]=useState(()=>React.createRef<HTMLInputElement>());
 const profile=async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('کاربر وارد نشده است.');const{data,error}=await supabase.from('profiles').select('organization_id').eq('id',user.id).single();if(error||!data?.organization_id)throw error||new Error('سازمان کاربر مشخص نیست.');return{user,org:data.organization_id as string};};
 const loadShipments=async()=>{setBusy(true);setError('');try{const{org}=await profile();const{data:links,error:le}=await supabase.from('shipment_documents').select('shipment_id').eq('organization_id',org).not('shipment_id','is',null);if(le)throw le;const ids=[...new Set((links||[]).map((x:any)=>x.shipment_id).filter(Boolean))];if(!ids.length){setShipments([]);setShipmentId('');return}const[{data:s,error:se},{data:c,error:ce},{data:v,error:ve},{data:cl,error:cle}]=await Promise.all([supabase.from('shipments').select('id,case_id,bill_of_lading_no,net_weight_kg,vessel_id,cargo_count,cargo_count_unit,client_id').eq('organization_id',org).in('id',ids).order('created_at',{ascending:false}),supabase.from('cases').select('id,cargo_description').eq('organization_id',org),supabase.from('vessels').select('id,name').eq('organization_id',org),supabase.from('clients').select('id,name').eq('organization_id',org)]);if(se)throw se;if(ce)throw ce;if(ve)throw ve;if(cle)throw cle;const cm=new Map((c||[]).map((x:any)=>[x.id,x.cargo_description||'']));const vm=new Map((v||[]).map((x:any)=>[x.id,x.name||'']));const lm=new Map((cl||[]).map((x:any)=>[x.id,x.name||'']));setShipments((s||[]).map((x:any)=>({id:x.id,case_id:x.case_id||null,bill_of_lading_no:x.bill_of_lading_no||null,net_weight_kg:x.net_weight_kg??null,vessel_name:vm.get(x.vessel_id)||'',quantity:x.cargo_count??null,quantity_unit:x.cargo_count_unit||'',cargo_owner:lm.get(x.client_id)||'',cargo_description:cm.get(x.case_id)||''})));setShipmentId(prev=>(s||[]).some((x:any)=>x.id===prev)?prev:((s||[])[0]?.id||''));}catch(e:any){setError(e?.message||'دریافت محموله‌ها ناموفق بود')}finally{setBusy(false)}};
 const loadDocs=async(id:string)=>{if(!id){setDocs([]);return}setBusy(true);setError('');try{const{data,error}=await supabase.from('customs_documents').select('id,shipment_id,document_type,original_name,display_name,storage_path,mime_type,size_bytes,status').eq('shipment_id',id).order('created_at',{ascending:false});if(error)throw error;setDocs((data||[]) as Doc[]);}catch(e:any){setError(e?.message||'دریافت اسناد ناموفق بود')}finally{setBusy(false)}};
 useEffect(()=>{void loadShipments()},[]);useEffect(()=>{void loadDocs(shipmentId)},[shipmentId]);
 const current=shipments.find(x=>x.id===shipmentId);const typed=(d:Doc)=>d.document_type||inferType(fileName(d));const filtered=useMemo(()=>docs.filter(d=>{const n=fileName(d);const t=typed(d);return(!type||t===type)&&(!status||d.status===status)&&(!q||`${n} ${label(t)}`.toLowerCase().includes(q.toLowerCase()))}),[docs,q,type,status]);
 const upload=async(files:FileList|null)=>{if(!files?.length||!current)return;setBusy(true);setError('');try{const{user,org}=await profile();for(const f of Array.from(files)){const ok=/\.(pdf|jpe?g|png)$/i.test(f.name)||['application/pdf','image/jpeg','image/png'].includes(f.type);if(!ok)throw new Error(`فرمت «${f.name}» پشتیبانی نمی‌شود.`);if(f.size>50*1024*1024)throw new Error(`حجم «${f.name}» بیشتر از 50 MB است.`);const safe=f.name.replace(/[^\w.\-\u0600-\u06ff]+/g,'_');const mime=f.type||(/\.pdf$/i.test(f.name)?'application/pdf':/\.png$/i.test(f.name)?'image/png':'image/jpeg');const path=`${org}/${current.id}/${crypto.randomUUID()}-${safe}`;const documentType=inferType(f.name);const{error:ue}=await supabase.storage.from(BUCKET).upload(path,f,{contentType:mime,cacheControl:'3600',upsert:false});if(ue)throw new Error(`آپلود «${f.name}» ناموفق بود: ${ue.message}`);const{error:de}=await supabase.from('customs_documents').insert({organization_id:org,shipment_id:current.id,case_id:current.case_id,document_type:documentType,original_name:f.name,display_name:f.name,storage_path:path,mime_type:mime,size_bytes:f.size,created_by:user.id,status:'review',tags:[]});if(de){await supabase.storage.from(BUCKET).remove([path]);throw new Error(`فایل ذخیره شد ولی ثبت سند ناموفق بود: ${de.message}`)}}await loadDocs(current.id);}catch(e:any){setError(e?.message||'بارگذاری ناموفق بود')}finally{setBusy(false)}};
 const audit=async(d:Doc,oldStatus:string,newStatus:string)=>{try{const{user,org}=await profile();await supabase.from('audit_logs').insert({organization_id:org,user_id:user.id,action:'DOCUMENT_STATUS_CHANGED',table_name:'customs_documents',record_id:d.id,old_data:{status:oldStatus},new_data:{status:newStatus}})}catch{}};
 const setDocStatus=async(d:Doc,next:string)=>{if(d.status===next)return;setBusy(true);setError('');try{const{user}=await profile();const review=next==='approved'||next==='rejected';const{error}=await supabase.from('customs_documents').update({status:next,reviewed_at:review?new Date().toISOString():null,reviewed_by:review?user.id:null}).eq('id',d.id);if(error)throw error;await audit(d,d.status||'review',next);setDocs(prev=>prev.map(x=>x.id===d.id?{...x,status:next}:x));setSelected(prev=>prev?.id===d.id?{...prev,status:next}:prev);}catch(e:any){setError(e?.message||'تغییر وضعیت سند ناموفق بود')}finally{setBusy(false)}};
 const openPreview=async(d:Doc)=>{if(!d.storage_path){setError(`مسیر فایل «${fileName(d)}» ثبت نشده است.`);return}setError('');const{data,error}=await supabase.storage.from(BUCKET).createSignedUrl(d.storage_path,3600);if(error||!data?.signedUrl){setError(`پیش‌نمایش «${fileName(d)}» ناموفق بود: ${error?.message||'لینک امن ساخته نشد'}`);return}setSelected(d);setPreviewUrl(data.signedUrl)};
 const download=async(d:Doc)=>{if(!d.storage_path)return;const{data,error}=await supabase.storage.from(BUCKET).download(d.storage_path);if(error){setError(`دانلود «${fileName(d)}» ناموفق بود: ${error.message}`);return}const u=URL.createObjectURL(data);const a=document.createElement('a');a.href=u;a.download=fileName(d);document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 const FileIcon=({d,large=false}:{d:Doc;large?:boolean})=>isImage(d)?<ImageIcon size={large?54:24}/>:<FileText size={large?54:24}/>;
 const completeness=REQUIRED.map(t=>({t,ok:docs.some(d=>typed(d)===t&&d.status!=='rejected')}));const completeCount=completeness.filter(x=>x.ok).length;
 return <main dir="rtl" className="min-h-screen p-4 md:p-6" style={{background:'var(--bg)',color:'var(--text)'}}><div className="max-w-7xl mx-auto space-y-4">
 <header className="flex items-center gap-3"><div><h1 className="text-2xl font-black">فایل‌های محموله</h1><p className="text-xs app-muted mt-1">مدیریت اسناد، وضعیت بررسی و کنترل کامل بودن مدارک محموله.</p></div><div className="mr-auto flex gap-1"><button className="icon-btn" onClick={()=>setView('grid')} title="نمایش شبکه"><LayoutGrid size={17}/></button><button className="icon-btn" onClick={()=>setView('list')} title="نمایش فهرست"><List size={17}/></button><button className="icon-btn" onClick={()=>void loadShipments()} title="بروزرسانی"><RefreshCw size={17}/></button></div></header>
 {error&&<div className="rounded-xl border border-red-400/40 bg-red-500/10 p-3 text-sm text-red-700">{error}<button className="float-left" onClick={()=>setError('')}><X size={15}/></button></div>}
 <section className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex flex-col md:flex-row gap-3 items-end"><label className="block flex-1 w-full"><span className="text-xs app-muted">محموله</span><select value={shipmentId} onChange={e=>setShipmentId(e.target.value)} className="mt-1 w-full rounded-xl border app-border bg-[var(--surface-2)] p-3">{!shipments.length&&<option value="">محموله‌ای دارای سند یافت نشد</option>}{shipments.map(s=><option key={s.id} value={s.id}>{s.cargo_description||'بدون شرح کالا'} — B/L: {s.bill_of_lading_no||'—'} — {s.cargo_owner||'بدون صاحب کالا'}</option>)}</select></label><button disabled={!current||busy} onClick={()=>inputRef.current?.click()} className="rounded-xl px-4 py-3 bg-[var(--primary)] text-white font-bold disabled:opacity-50"><Upload size={16} className="inline ml-2"/>آپلود فایل</button><input ref={inputRef} hidden type="file" multiple accept="application/pdf,.pdf,image/jpeg,.jpg,.jpeg,image/png,.png" onChange={e=>{void upload(e.target.files);e.currentTarget.value=''}}/></div>{current&&<div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-4 text-sm"><div className="rounded-xl bg-[var(--surface-2)] p-3"><span className="app-muted text-xs block">کالا</span><b>{current.cargo_description||'—'}</b></div><div className="rounded-xl bg-[var(--surface-2)] p-3"><span className="app-muted text-xs block">صاحب کالا</span><b>{current.cargo_owner||'—'}</b></div><div className="rounded-xl bg-[var(--surface-2)] p-3"><span className="app-muted text-xs block">تعداد</span><b>{current.quantity??'—'} {current.quantity_unit}</b></div><div className="rounded-xl bg-[var(--surface-2)] p-3"><span className="app-muted text-xs block">وزن خالص</span><b>{current.net_weight_kg??'—'} kg</b></div><div className="rounded-xl bg-[var(--surface-2)] p-3"><span className="app-muted text-xs block">کشتی</span><b>{current.vessel_name||'—'}</b></div></div>}</section>
 {current&&<section className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex items-center justify-between mb-3"><b>کامل بودن مدارک پایه</b><span className="text-sm font-bold">{completeCount} از {REQUIRED.length}</span></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-2">{completeness.map(x=><div key={x.t} className={`rounded-xl p-3 ${x.ok?'bg-green-500/10':'bg-amber-500/10'}`}><div className="flex items-center gap-2 text-sm"><span className={`w-6 h-6 rounded-full flex items-center justify-center ${x.ok?'bg-green-500 text-white':'bg-amber-500/20'}`}>{x.ok?<Check size={15}/>:<span>!</span>}</span><span>{label(x.t)}</span></div></div>)}</div></section>}
 <section className="flex flex-col md:flex-row gap-2"><div className="relative flex-1"><Search size={17} className="absolute right-3 top-3.5 app-muted"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجوی نام فایل یا نوع سند..." className="w-full rounded-xl border app-border bg-[var(--surface)] p-3 pr-10"/></div><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border app-border bg-[var(--surface)] p-3"><option value="">همه اسناد</option>{TYPES.map(t=><option key={t.v} value={t.v}>{t.l}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border app-border bg-[var(--surface)] p-3"><option value="">همه وضعیت‌ها</option><option value="review">در انتظار بررسی</option><option value="processing">در حال پردازش</option><option value="approved">تأیید شده</option><option value="rejected">رد شده</option><option value="archived">بایگانی شده</option></select><div className="flex rounded-xl border app-border overflow-hidden bg-[var(--surface)]"><button onClick={()=>setView('grid')} className={`p-3 ${view==='grid'?'bg-[var(--surface-2)]':''}`} title="نمایش آیکونی"><LayoutGrid size={18}/></button><button onClick={()=>setView('list')} className={`p-3 ${view==='list'?'bg-[var(--surface-2)]':''}`} title="نمایش لیستی"><List size={18}/></button></div></section>
 {busy&&<div className="flex justify-center py-4"><Loader2 className="animate-spin"/></div>}
 {!busy&&!filtered.length&&<div className="rounded-2xl border app-border bg-[var(--surface)] p-10 text-center app-muted">برای این محموله فایل ثبت نشده است.</div>}
 {!busy&&filtered.length>0&&view==='grid'&&<section className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-3">{filtered.map(d=><article key={d.id} className="rounded-2xl border app-border bg-[var(--surface)] p-3 hover:shadow-md transition-shadow"><button onClick={()=>void openPreview(d)} className="w-full text-right"><div className="h-36 rounded-xl bg-[var(--surface-2)] flex items-center justify-center overflow-hidden">{isImage(d)?<ImageIcon size={54}/>:<div className="flex flex-col items-center gap-2 app-muted"><FileIcon d={d} large/><span className="text-xs font-bold">{ext(fileName(d))}</span></div>}</div><div className="mt-3 min-w-0"><div className="font-bold text-sm break-all leading-5" title={fileName(d)}>{fileName(d)}</div><div className="text-xs app-muted mt-1 truncate">{label(typed(d))}</div><div className="flex items-center justify-between mt-2"><span className="text-[11px] app-muted">{sizeText(d.size_bytes)||'—'}</span><span className={`text-[10px] px-2 py-1 rounded-full font-bold ${statusClass(d.status)}`}>{statusLabel(d.status)}</span></div></div></button><div className="flex gap-1 mt-2"><button className="icon-btn flex-1" onClick={()=>void openPreview(d)} title="نمایش"><Eye size={16}/></button><button className="icon-btn flex-1" onClick={()=>void download(d)} title="دانلود"><Download size={16}/></button></div></article>)}</section>}
 {!busy&&filtered.length>0&&view==='list'&&<section className="rounded-2xl border app-border bg-[var(--surface)] overflow-hidden"><div className="grid grid-cols-[minmax(0,1fr)_150px_130px_110px] gap-3 px-4 py-3 text-xs app-muted border-b app-border"><span>نام فایل</span><span>نوع سند</span><span>وضعیت</span><span>عملیات</span></div>{filtered.map(d=><div key={d.id} className="grid grid-cols-[minmax(0,1fr)_150px_130px_110px] gap-3 items-center px-4 py-3 border-b app-border last:border-b-0"><button onClick={()=>void openPreview(d)} className="flex items-center gap-3 min-w-0 text-right"><div className="w-10 h-10 rounded-lg bg-[var(--surface-2)] flex items-center justify-center shrink-0"><FileIcon d={d}/></div><span className="font-semibold text-sm break-all">{fileName(d)}</span></button><span className="text-xs app-muted">{label(typed(d))}</span><span className={`text-xs px-2 py-1 rounded-full w-fit ${statusClass(d.status)}`}>{statusLabel(d.status)}</span><div className="flex gap-1"><button className="icon-btn" onClick={()=>void openPreview(d)} title="نمایش"><Eye size={15}/></button><button className="icon-btn" onClick={()=>void download(d)} title="دانلود"><Download size={15}/></button></div></div>)}</section>}
 {selected&&isPdf(selected)?<PdfDocumentViewer url={previewUrl} name={fileName(selected)} onClose={()=>{setSelected(null);setPreviewUrl('')}} onDownload={()=>void download(selected)}/>:selected&&<div className="fixed inset-0 z-50 bg-black/70 p-2 md:p-5" onClick={()=>{setSelected(null);setPreviewUrl('')}}><div className="h-full max-w-7xl mx-auto bg-[var(--surface)] rounded-2xl overflow-hidden flex flex-col" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3 p-3 border-b app-border shrink-0"><div className="w-9 h-9 rounded-lg bg-[var(--surface-2)] flex items-center justify-center"><FileIcon d={selected}/></div><div className="min-w-0 flex-1"><div className="font-bold break-all">{fileName(selected)}</div><div className="text-xs app-muted">{ext(fileName(selected))} · {sizeText(selected.size_bytes)||'—'} · {label(typed(selected))}</div></div><span className={`text-xs px-2 py-1 rounded-full ${statusClass(selected.status)}`}>{statusLabel(selected.status)}</span><button className="icon-btn" onClick={()=>void setDocStatus(selected,'approved')} title="تأیید"><Check size={17}/></button><button className="icon-btn" onClick={()=>void setDocStatus(selected,'rejected')} title="رد"><X size={17}/></button><button className="icon-btn" onClick={()=>void download(selected)} title="دانلود"><Download size={17}/></button><a className="icon-btn" href={previewUrl} target="_blank" rel="noreferrer" title="باز کردن فایل"><ExternalLink size={17}/></a><button className="icon-btn" onClick={()=>{setSelected(null);setPreviewUrl('')}} title="بستن"><X size={18}/></button></div><div className="flex-1 min-h-0 bg-neutral-900 overflow-auto">{isImage(selected)?<div className="w-full h-full overflow-auto flex items-center justify-center p-4"><img src={previewUrl} alt={fileName(selected)} className="max-w-none max-h-none"/></div>:<iframe title={fileName(selected)} src={previewUrl} className="w-full h-full border-0"/>}</div></div></div>}
 </div></main>;
};
export default CustomsDocumentManagerPage;