import React,{useEffect,useState} from 'react';
import {ArrowLeft,Check,Loader2} from 'lucide-react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../lib/supabase';

type Decl={id:string;shipment_id:string|null;kottaj_number:string;declaration_date:string;customs_path:string|null;payment_reference:string|null;total_duties_irr:number|null;declaration_file_name:string|null};
const ITEMS=[['declaration_review','کنترل اطلاعات اظهارنامه'],['document_review','کنترل اسناد و تطبیق با اظهار'],['payment_review','کنترل شناسه پرداخت و مبلغ گمرکی'],['customs_route_review','کنترل مسیر گمرکی'],['inspection_requirements','بررسی نیاز به ارزیابی / بازرسی'],['permit_review','کنترل مجوزها و الزامات'],['valuation_review','کنترل ارزش‌گذاری و محاسبات'],['release_preparation','آماده‌سازی ادامه عملیات ترخیص']] as const;
type ItemKey=typeof ITEMS[number][0];
const pathLabels:Record<string,string>={green:'سبز',yellow:'زرد',red:'قرمز'};
export const DeclarationOperationsChecklistPage:React.FC=()=>{const[params]=useSearchParams();const declarationId=params.get('declarationId')||'';const[decl,setDecl]=useState<Decl|null>(null);const[done,setDone]=useState<Record<string,boolean>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const load=async()=>{if(!declarationId)return;setBusy(true);setError('');try{const{data,error:e}=await supabase.from('customs_declarations').select('id,shipment_id,kottaj_number,declaration_date,customs_path,payment_reference,total_duties_irr,declaration_file_name').eq('id',declarationId).maybeSingle();if(e)throw e;if(!data)throw new Error('اظهارنامه پیدا نشد.');setDecl(data as Decl);const{data:rows,error:ce}=await supabase.from('declaration_checklist_items').select('item_key,completed').eq('declaration_id',declarationId);if(ce)throw ce;setDone(Object.fromEntries((rows||[]).map((x:any)=>[x.item_key,!!x.completed])))}catch(e:any){setError(e?.message||'دریافت چک‌لیست انجام نشد')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[declarationId]);
 const toggle=async(key:ItemKey)=>{if(!declarationId)return;const next=!done[key];setDone(p=>({...p,[key]:next}));const{error:e}=await supabase.from('declaration_checklist_items').update({completed:next,completed_at:next?new Date().toISOString():null,completed_by:next?(await supabase.auth.getUser()).data.user?.id||null:null,updated_at:new Date().toISOString()}).eq('declaration_id',declarationId).eq('item_key',key);if(e){setDone(p=>({...p,[key]:!next}));setError(e.message)}};
 const complete=async()=>{const completed=ITEMS.filter(([k])=>done[k]).length;if(completed!==ITEMS.length)return setError('همه موارد چک‌لیست گمرکی باید کنترل شوند.');setMessage('چک‌لیست گمرکی این اظهارنامه تکمیل شد و عملیات می‌تواند ادامه پیدا کند.');};
 if(!declarationId)return <main dir="rtl" className="min-h-screen p-6"><div className="max-w-xl mx-auto rounded-2xl border app-border bg-[var(--surface)] p-6"><h1 className="font-black text-xl">اظهارنامه انتخاب نشده</h1><p className="text-sm app-muted mt-2">ابتدا اظهارنامه را ثبت کنید.</p><Link to="/operations?tab=declaration" className="inline-block mt-4 rounded-xl bg-[var(--primary)] text-white px-4 py-2">ثبت اظهار</Link></div></main>;
 const completed=ITEMS.filter(([k])=>done[k]).length;
 return <main dir="rtl" className="min-h-screen bg-[var(--bg)] text-[var(--text)] p-4 md:p-8"><div className="max-w-5xl mx-auto space-y-5"><header className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="text-xs app-muted">مرحله ۴</div><h1 className="text-2xl md:text-3xl font-black mt-1">چک‌لیست گمرکی</h1><p className="text-sm app-muted mt-1">کنترل اظهارنامه ثبت‌شده قبل از ادامه عملیات ترخیص</p></div><Link to={`/operations?tab=declaration&shipmentId=${encodeURIComponent(decl?.shipment_id||'')}`} className="px-4 py-2 rounded-xl border app-border bg-[var(--surface)] text-sm"><ArrowLeft className="inline ml-1" size={15}/>بازگشت به ثبت اظهار</Link></header>
 {error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-500">{error}</div>}{message&&<div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-600">{message}</div>}
 {decl&&<section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="grid grid-cols-2 md:grid-cols-5 gap-3 text-sm"><div><span className="app-muted">کوتاژ</span><div className="font-black mt-1">{decl.kottaj_number}</div></div><div><span className="app-muted">تاریخ اظهار</span><div className="font-bold mt-1">{new Date(decl.declaration_date).toLocaleDateString('fa-IR')}</div></div><div><span className="app-muted">شناسه پرداخت</span><div className="font-bold mt-1">{decl.payment_reference||'—'}</div></div><div><span className="app-muted">مبلغ گمرکی</span><div className="font-bold mt-1">{decl.total_duties_irr==null?'—':new Intl.NumberFormat('fa-IR').format(decl.total_duties_irr)}</div></div><div><span className="app-muted">مسیر</span><div className="font-bold mt-1">{decl.customs_path?pathLabels[decl.customs_path]||decl.customs_path:'—'}</div></div></div><div className="mt-3 text-xs app-muted">فایل اظهارنامه: {decl.declaration_file_name||'ثبت نشده'}</div></section>}
 <section className="rounded-2xl border app-border bg-[var(--surface)] overflow-hidden"><div className="p-5 border-b app-border flex items-center justify-between"><h2 className="font-black">کنترل‌های اجباری</h2><span className="text-xs app-muted">{completed} از {ITEMS.length}</span></div><div>{ITEMS.map(([key,label],i)=><button key={key} onClick={()=>void toggle(key)} className="w-full flex items-center gap-3 p-4 border-b app-border text-right hover:bg-[var(--surface-2)]"><span className={`w-7 h-7 rounded-lg border grid place-items-center shrink-0 ${done[key]?'bg-emerald-500 border-emerald-500 text-white':'app-border'}`}>{done[key]&&<Check size={16}/>}</span><span className="text-sm font-semibold">{i+1}. {label}</span></button>)}</div><div className="p-5"><button disabled={busy||completed!==ITEMS.length} onClick={()=>void complete()} className="w-full md:w-auto rounded-xl bg-[var(--primary)] text-white px-6 py-3 font-bold disabled:opacity-40">{busy?<><Loader2 className="inline ml-2 animate-spin" size={16}/>در حال بررسی...</>:'تکمیل چک‌لیست گمرکی'}</button></div></section>
 </div></main>;
};
