import React, { useEffect, useState } from 'react';
import { ArrowRight, CheckCircle2, Loader2, RotateCcw, Save, ShieldCheck } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';

type CaseRow = { id: string; case_number: string | null; status: string };
type Decl = { id: string; kottaj_number: string | null; customs_path: string | null; declaration_date: string | null; assessed_value_irr: number | null; total_duties_irr: number | null };
type Office = { id: string; name: string | null; code: string | null };

const labels: Record<string, string> = { draft: 'پیش‌نویس', registration_order: 'ثبت سفارش', documents_ready: 'اسناد آماده', epl_submitted: 'اظهار ثبت شد', kottaj_received: 'کوتاژ دریافت شد', path_green: 'مسیر سبز', path_yellow: 'مسیر زرد', path_red: 'مسیر قرمز', valuation: 'ارزش‌گذاری', duties_calculation: 'محاسبه حقوق', exit_permit: 'مجوز خروج', completed: 'تکمیل‌شده', archived: 'بایگانی' };
const pathLabels: Record<string, string> = { green: 'سبز', yellow: 'زرد', red: 'قرمز' };
const nav = (tab: string, id: string) => `/operations?tab=${tab}${id ? `&caseId=${encodeURIComponent(id)}` : ''}`;
const num = (v: string) => { const x = Number(String(v).replace(/[۰-۹]/g, d => String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[,٬،]/g, '')); return Number.isFinite(x) ? x : null; };

const Field = ({ label, value, onChange, type = 'text', placeholder = '', inputMode }: { label: string; value: string; onChange: (v: string) => void; type?: string; placeholder?: string; inputMode?: 'numeric' | 'text' }) => <label><span className="block text-sm text-slate-300 mb-1">{label}</span><input type={type} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} inputMode={inputMode} className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3" /></label>;
const Info = ({ t, v }: { t: string; v: string }) => <div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="text-xs text-slate-500">{t}</div><div className="mt-1 text-sm break-all">{v}</div></div>;

export const DeclarationChecklistPage: React.FC = () => {
 const [params] = useSearchParams(); const requested = params.get('caseId') || '';
 const [cases, setCases] = useState<CaseRow[]>([]); const [selected, setSelected] = useState(requested); const [decl, setDecl] = useState<Decl | null>(null); const [offices, setOffices] = useState<Office[]>([]);
 const [kottaj, setKottaj] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 16)); const [office, setOffice] = useState(''); const [path, setPath] = useState(''); const [assessed, setAssessed] = useState(''); const [duties, setDuties] = useState('');
 const [checked, setChecked] = useState<boolean[]>(() => { try { const x = JSON.parse(localStorage.getItem('customs_os_declaration_checklist') || '[]'); return Array.from({ length: 14 }, (_, i) => Boolean(x?.[i])); } catch { return Array(14).fill(false); } });
 const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const current = cases.find(c => c.id === selected) || null;
 const load = async (id: string) => { setError(''); const [{ data: c, error: ce }, { data: o, error: oe }] = await Promise.all([supabase.from('cases').select('id,case_number,status').order('created_at', { ascending: false }), supabase.from('customs_offices').select('id,name,code').order('name')]); if (ce || oe) { setError((ce || oe)?.message || 'دریافت اطلاعات ناموفق بود'); return; } setCases((c || []) as CaseRow[]); setOffices((o || []) as Office[]); if (!id) { setDecl(null); return; } const { data: d, error: de } = await supabase.from('customs_declarations').select('id,kottaj_number,customs_path,declaration_date,assessed_value_irr,total_duties_irr').eq('case_id', id).order('created_at', { ascending: false }).limit(1); if (de) { setError(de.message); return; } const x = (d || [])[0] as Decl | undefined; setDecl(x || null); if (x) { setKottaj(x.kottaj_number || ''); setDate(x.declaration_date ? new Date(x.declaration_date).toISOString().slice(0, 16) : new Date().toISOString().slice(0, 16)); setPath(x.customs_path || ''); setAssessed(x.assessed_value_irr != null ? String(x.assessed_value_irr) : ''); setDuties(x.total_duties_irr != null ? String(x.total_duties_irr) : ''); } };
 useEffect(() => { void load(selected); }, [selected]);
 const choose = (id: string) => { setSelected(id); setDecl(null); setKottaj(''); setPath(''); setAssessed(''); setDuties(''); setError(''); setMessage(''); };
 const submitEpl = async () => { if (!selected) return setError('پرونده را انتخاب کنید.'); setBusy(true); setError(''); setMessage(''); try { const { error: e } = await supabase.rpc('submit_epl_workflow', { p_case_id: selected, p_declaration_date: new Date(date).toISOString() }); if (e) throw e; setMessage('اظهار EPL ثبت شد.'); await load(selected); } catch (e: any) { setError(e?.message || 'ثبت اظهار EPL انجام نشد'); } finally { setBusy(false); } };
 const registerKottaj = async () => { if (!selected) return setError('پرونده را انتخاب کنید.'); if (!kottaj.trim()) return setError('شماره کوتاژ را وارد کنید.'); if (current?.status !== 'epl_submitted') return setError(`ابتدا اظهار EPL را ثبت کنید. وضعیت فعلی: ${labels[current?.status || ''] || current?.status}`); setBusy(true); setError(''); setMessage(''); try { const { error: e } = await supabase.rpc('register_declaration_workflow', { p_case_id: selected, p_kottaj_number: kottaj.trim(), p_declaration_date: new Date(date).toISOString(), p_customs_office_id: office || null, p_customs_path: path || null, p_assessed_value_irr: num(assessed), p_total_duties_irr: num(duties) }); if (e) throw e; setMessage(path ? `کوتاژ ثبت شد؛ مسیر ${pathLabels[path]} ثبت شد.` : 'کوتاژ ثبت شد.'); await load(selected); } catch (e: any) { setError(e?.message || 'ثبت کوتاژ انجام نشد'); } finally { setBusy(false); } };
 const toggle = (i: number) => setChecked(p => { const n = p.map((v, j) => j === i ? !v : v); try { localStorage.setItem('customs_os_declaration_checklist', JSON.stringify(n)); } catch {} return n; });
 const reset = () => { const n = Array(14).fill(false); setChecked(n); try { localStorage.setItem('customs_os_declaration_checklist', JSON.stringify(n)); } catch {} };
 const items = ['در انتظار مبلغ ترخیصیه', 'پاس کشتی', 'اظهار', 'مالیات علی الحساب', 'درخواست ضمانتنامه حقوق ورودی و ارزش افزوده', 'ارزیابی', 'آزمایشگاه', 'مجوز استاندارد', 'نوبت کارشناسی', 'کد ساتا', 'تبصره دو منطقه آزاد', 'صورت‌حساب انبارداری اولیه', 'صورت‌حساب انبارداری متمم', 'وکالت حمل'];
 return <main dir="rtl" className="min-h-screen bg-slate-950 text-slate-100 p-4 sm:p-6 lg:p-8"><div className="max-w-6xl mx-auto space-y-5">
 <header className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs text-slate-500">CUSTOMS / DECLARATION / EPL</div><h1 className="text-2xl font-black mt-1">اظهار / EPL و ثبت کوتاژ</h1><p className="text-sm text-slate-400 mt-1">اطلاعات این بخش مستقیماً در پرونده و اظهار گمرکی ذخیره می‌شود.</p></div><Link to={selected ? `/stage?caseId=${encodeURIComponent(selected)}` : '/stage'} className="rounded-xl border border-slate-700 bg-slate-900 px-4 py-2"><ArrowRight className="inline ml-2" size={16} /> کنترل مراحل</Link></header>
 <nav className="grid grid-cols-1 md:grid-cols-3 gap-2"><Link to={nav('pre-declaration', selected)} className="rounded-xl px-4 py-3 text-center font-bold bg-slate-900 border border-slate-700">۱. ورود اطلاعات قبل اظهار</Link><div className="rounded-xl px-4 py-3 text-center font-bold bg-blue-600">۲. اظهار / EPL</div><Link to={nav('exit', selected)} className="rounded-xl px-4 py-3 text-center font-bold bg-slate-900 border border-slate-700">۳. صدور پروانه / درب خروج</Link></nav>
 {error && <div className="rounded-xl border border-red-900 bg-red-950/30 p-4 text-red-300">{error}</div>}{message && <div className="rounded-xl border border-emerald-900 bg-emerald-950/30 p-4 text-emerald-300">{message}</div>}
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><label className="text-sm text-slate-400">پرونده</label><select value={selected} onChange={e => choose(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">انتخاب پرونده</option>{cases.map(c => <option key={c.id} value={c.id}>{c.case_number || c.id.slice(0, 8)} — {labels[c.status] || c.status}</option>)}</select>{current && <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-3"><Info t="شماره پرونده" v={current.case_number || '—'} /><Info t="وضعیت" v={labels[current.status] || current.status} /><Info t="کوتاژ" v={decl?.kottaj_number || 'ثبت نشده'} /><Info t="مسیر" v={decl?.customs_path ? `مسیر ${pathLabels[decl.customs_path] || decl.customs_path}` : 'ثبت نشده'} /></div>}</section>
 {current && <><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-2 mb-4"><ShieldCheck className="text-cyan-400" size={20} /><h2 className="font-black">مرحله ۱ — ثبت اظهار EPL</h2></div><p className="text-sm text-slate-400 mb-4">ثبت این مرحله فقط با کنترل پیش‌نیازهای دیتابیس انجام می‌شود؛ شماره کوتاژ در این مرحله ساخته نمی‌شود.</p><button disabled={busy || current.status !== 'documents_ready'} onClick={() => void submitEpl()} className="rounded-xl bg-cyan-600 px-5 py-3 font-bold disabled:opacity-50">{busy ? <><Loader2 className="inline ml-2 animate-spin" size={17} />در حال ثبت...</> : <><ShieldCheck className="inline ml-2" size={17} />ثبت اظهار EPL</>}</button>{current.status === 'epl_submitted' && <div className="mt-3 text-sm text-emerald-400">اظهار EPL قبلاً ثبت شده است.</div>}</section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-2 mb-4"><Save className="text-cyan-400" size={20} /><h2 className="font-black">مرحله ۲ — کوتاژ و مسیر گمرکی</h2></div><div className="grid md:grid-cols-2 gap-4"><Field label="شماره کوتاژ" value={kottaj} onChange={setKottaj} placeholder="شماره واقعی کوتاژ" /><Field label="تاریخ اظهار" value={date} onChange={setDate} type="datetime-local" /><label><span className="block text-sm text-slate-300 mb-1">گمرک</span><select value={office} onChange={e => setOffice(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">انتخاب گمرک (اختیاری)</option>{offices.map(o => <option key={o.id} value={o.id}>{o.name || 'گمرک'}{o.code ? ` — ${o.code}` : ''}</option>)}</select></label><label><span className="block text-sm text-slate-300 mb-1">مسیر گمرکی</span><select value={path} onChange={e => setPath(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">هنوز مشخص نشده</option><option value="green">سبز</option><option value="yellow">زرد</option><option value="red">قرمز</option></select></label><Field label="ارزش ارزیابی‌شده (ریال)" value={assessed} onChange={setAssessed} inputMode="numeric" /><Field label="جمع حقوق و عوارض (ریال)" value={duties} onChange={setDuties} inputMode="numeric" /></div><button disabled={busy || current.status !== 'epl_submitted'} onClick={() => void registerKottaj()} className="mt-5 rounded-xl bg-emerald-600 px-5 py-3 font-bold disabled:opacity-50">{busy ? <><Loader2 className="inline ml-2 animate-spin" size={17} />در حال ثبت و کنترل...</> : <><Save className="inline ml-2" size={17} />ثبت کوتاژ و ادامه گردش</>}</button></section></>}
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-bold text-lg">چک‌لیست عملیاتی</h2><p className="text-xs text-slate-500 mt-1">{checked.filter(Boolean).length} از {items.length} مورد انجام شده</p></div><button onClick={reset} className="text-xs text-slate-400"><RotateCcw className="inline ml-1" size={14} />بازنشانی</button></div><div className="grid md:grid-cols-2 gap-2">{items.map((item, i) => <label key={item} className="flex items-center gap-3 rounded-xl border border-slate-800 p-3"><input type="checkbox" checked={checked[i]} onChange={() => toggle(i)} /><span>{item}</span>{checked[i] && <CheckCircle2 className="mr-auto text-emerald-400" size={17} />}</label>)}</div></section>
 </div></main>;
};
export default DeclarationChecklistPage;
