import React,{useEffect,useState} from 'react';
import {ArrowRight,CheckCircle2,Loader2,RotateCcw,ShieldCheck} from 'lucide-react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../lib/supabase';

const items=['در انتظار مبلغ ترخیصیه','پاس کشتی','اظهار','مالیات علی الحساب','درخواست ضمانتنامه حقوق ورودی و ارزش افزوده','ارزیابی','آزمایشگاه','مجوز استاندارد','نوبت کارشناسی','کد ساتا','تبصره دو منطقه آزاد','صورت‌حساب انبارداری اولیه','صورت‌حساب انبارداری متمم','وکالت حمل'];
const KEY='customs_os_declaration_checklist';
const nav=(tab:string,caseId:string)=>`/operations?tab=${tab}${caseId?`&caseId=${encodeURIComponent(caseId)}`:''}`;

type CaseRow={id:string;case_number:string|null;status:string;registration_order_no:string|null;warehouse_receipt_no:string|null};
type Decl={id:string;kottaj_number:string|null;customs_path:string|null;declaration_date:string|null};

export const DeclarationChecklistPage:React.FC=()=>{
 const[params]=useSearchParams();const requestedCase=params.get('caseId')||'';
 const[checked,setChecked]=useState<boolean[]>(()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return items.map((_,i)=>Boolean(x?.[i]))}catch{return items.map(()=>false)}});
 const[cases,setCases]=useState<CaseRow[]>([]),[caseId,setCaseId]=useState(requestedCase),[current,setCurrent]=useState<CaseRow|null>(null),[decl,setDecl]=useState<Decl|null>(null);
 const[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=async(id:string)=>{setError('');const{data,error:e}=await supabase.from('cases').select('id,case_number,status,registration_order_no,warehouse_receipt_no').order('created_at',{ascending:false});if(e){setError(e.message);return}const rows=(data||[]) as CaseRow[];setCases(rows);const chosen=id&&rows.some(x=>x.id===id)?id:(rows[0]?.id||'');setCaseId(chosen);setCurrent(rows.find(x=>x.id===chosen)||null);if(chosen){const{data:d,error:de}=await supabase.from('customs_declarations').select('id,kottaj_number,customs_path,declaration_date').eq('case_id',chosen).order('created_at',{ascending:false}).limit(1);if(de)setError(de.message);else setDecl(((d||[])[0]||null) as Decl|null)}else setDecl(null)};
 useEffect(()=>{void load(requestedCase)},[requestedCase]);
 const toggle=(i:number)=>setChecked(p=>{const n=p.map((v,j)=>j===i?!v:v);try{localStorage.setItem(KEY,JSON.stringify(n))}catch{}return n});
 const reset=()=>{const n=items.map(()=>false);setChecked(n);try{localStorage.setItem(KEY,JSON.stringify(n))}catch{}};
 const submitEpl=async()=>{if(!caseId)return setError('پرونده را انتخاب کنید.');setBusy(true);setError('');setMessage('');try{const{data,error:e}=await supabase.rpc('submit_epl_workflow',{p_case_id:caseId,p_declaration_date:new Date().toISOString()});if(e)throw e;setMessage('اظهار EPL ثبت شد و مرحله پرونده به «اظهار ثبت شد» منتقل شد.');const{data:d}=await supabase.from('customs_declarations').select('id,kottaj_number,customs_path,declaration_date').eq('id',data).maybeSingle();setDecl((d||null) as Decl|null);await load(caseId)}catch(e:any){setError(e?.message||'ثبت اظهار EPL انجام نشد')}finally{setBusy(false)}};
 const done=checked.filter(Boolean).length;const canSubmit=Boolean(current&&(current.status==='documents_ready'||current.status==='epl_submitted'));
 return <main dir="rtl" className="min-h-screen bg-slate-950 text-slate-100 p-4 sm:p-6 lg:p-8"><div className="max-w-6xl mx-auto space-y-5">
  <header><div className="text-xs text-slate-500">CUSTOMS / DECLARATION / EPL</div><h1 className="text-2xl font-black mt-1">۲- اظهار / EPL</h1><p className="text-sm text-slate-400 mt-2">این صفحه اکنون به پرونده و اظهار واقعی Supabase متصل است؛ چک‌لیست صرفاً کنترل عملیاتی کاربر است.</p></header>
  <nav className="grid grid-cols-1 md:grid-cols-3 gap-2"><Link to={nav('pre-declaration',caseId)} className="rounded-xl px-4 py-3 text-center font-bold bg-slate-900 border border-slate-700">۱. ورود اطلاعات قبل اظهار</Link><Link to={nav('declaration',caseId)} className="rounded-xl px-4 py-3 text-center font-bold bg-blue-600">۲. اظهار / EPL</Link><Link to={nav('exit',caseId)} className="rounded-xl px-4 py-3 text-center font-bold bg-slate-900 border border-slate-700">۳. صدور پروانه / درب خروج</Link></nav>
  {error&&<div className="rounded-xl border border-red-900 bg-red-950/30 p-4 text-red-300 whitespace-pre-wrap">{error}</div>}{message&&<div className="rounded-xl border border-emerald-900 bg-emerald-950/30 p-4 text-emerald-300">{message}</div>}
  <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><label className="text-sm text-slate-400">پرونده</label><select value={caseId} onChange={e=>{setCaseId(e.target.value);setCurrent(cases.find(x=>x.id===e.target.value)||null);void load(e.target.value)}} className="mt-2 w-full rounded-xl bg-slate-950 border border-slate-700 p-3"><option value="">انتخاب پرونده</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number||c.id.slice(0,8)} — {c.status}</option>)}</select>{current&&<div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-3"><Info t="شماره پرونده" v={current.case_number||'—'}/><Info t="وضعیت" v={current.status}/><Info t="ثبت سفارش" v={current.registration_order_no||'ثبت نشده'}/><Info t="قبض انبار" v={current.warehouse_receipt_no||'ثبت نشده'}/></div>}</section>
  {current&&<section className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><ShieldCheck className="text-cyan-400" size={20}/><h2 className="font-black">اظهار واقعی پرونده</h2></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Info t="شناسه اظهار" v={decl?.id||'هنوز ایجاد نشده'}/><Info t="کوتاژ" v={decl?.kottaj_number||'بعد از ثبت EPL'}/><Info t="مسیر گمرکی" v={decl?.customs_path||'بعد از کوتاژ'}/><Info t="تاریخ اظهار" v={decl?.declaration_date?new Date(decl.declaration_date).toLocaleDateString('fa-IR'):'—'}/></div><button disabled={busy||!canSubmit} onClick={()=>void submitEpl()} className="mt-5 px-5 py-3 rounded-xl bg-cyan-600 disabled:opacity-50 font-bold">{busy?<><Loader2 className="inline ml-2 animate-spin" size={17}/>در حال ثبت...</>:<><ShieldCheck className="inline ml-2" size={17}/>{current.status==='epl_submitted'?'اظهار قبلاً ثبت شده':'ثبت اظهار EPL'}</>}</button>{!canSubmit&&<p className="text-xs text-amber-400 mt-3">برای ثبت اظهار، وضعیت پرونده باید «اسناد آماده» باشد.</p>}</section>}
  <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-bold text-lg">چک‌لیست عملیاتی اظهار</h2><p className="text-xs text-slate-500 mt-1">{done} از {items.length} مورد انجام شده — این بخش دیگر وضعیت پرونده را جعل نمی‌کند.</p></div><button onClick={reset} className="px-3 py-2 rounded-xl border border-slate-700 text-sm"><RotateCcw className="inline ml-1" size={15}/>پاک کردن</button></div><div className="space-y-2">{items.map((item,i)=><button key={item} onClick={()=>toggle(i)} className={`w-full flex items-center justify-between gap-3 rounded-xl border px-4 py-3 text-right transition ${checked[i]?'border-emerald-700 bg-emerald-950/30':'border-slate-800 bg-slate-950'}`}><span>{i+1}. {item}</span>{checked[i]&&<CheckCircle2 className="text-emerald-400 shrink-0" size={20}/>}</button>)}</div></section>
  <Link to={caseId?`/stage?caseId=${encodeURIComponent(caseId)}`:'/stage'} className="inline-block px-4 py-2 rounded-xl border border-slate-700 bg-slate-900 text-sm"><ArrowRight className="inline ml-1" size={16}/> کنترل مراحل پرونده</Link>
 </div></main>;
};
const Info=({t,v}:{t:string;v:string})=><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="text-xs text-slate-500">{t}</div><div className="mt-1 text-sm break-all">{v}</div></div>;
export default DeclarationChecklistPage;
