import React,{useEffect,useState,useRef} from 'react';
import {ArrowLeft,CheckCircle2,FileUp,Loader2,Save} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {useAuth} from '../context/AuthContext';

type Shipment={id:string;bill_of_lading_no:string|null;cargo_count:number|null;cargo_count_unit:string|null;client_id:string|null;display_name:string|null;vessel_id:string|null};
type Declaration={id:string;shipment_id:string|null;kottaj_number:string;declaration_date:string;customs_path:string|null;payment_reference:string|null;total_duties_irr:number|null;declaration_file_name:string|null};
const pathLabels:Record<string,string>={green:'سبز',yellow:'زرد',red:'قرمز'};
const safeFile=(name:string)=>name.replace(/[^\w.\-]+/g,'_');
const parseAmount=(v:string)=>{const n=Number(v.replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٬,]/g,''));return Number.isFinite(n)?n:null};

export const DeclarationRegistrationPage:React.FC=()=>{
 const{profile}=useAuth();
 const[shipments,setShipments]=useState<Shipment[]>([]);const[selected,setSelected]=useState('');const[decl,setDecl]=useState<Declaration|null>(null);const[kottaj,setKottaj]=useState('');const[date,setDate]=useState(new Date().toISOString().slice(0,16));const[payment,setPayment]=useState('');const[amount,setAmount]=useState('');const[path,setPath]=useState('');const[file,setFile]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[fileRef]=useState(()=>React.createRef<HTMLInputElement>());
 const load=async(id:string)=>{setSelected(id);setError('');setMessage('');if(!id){setDecl(null);return}const{data,error:e}=await supabase.from('customs_declarations').select('id,shipment_id,kottaj_number,declaration_date,customs_path,payment_reference,total_duties_irr,declaration_file_name').eq('shipment_id',id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(e){setError(e.message);return}setDecl(data as Declaration|null);if(data){setKottaj(data.kottaj_number||'');setDate(data.declaration_date?new Date(data.declaration_date).toISOString().slice(0,16):new Date().toISOString().slice(0,16));setPayment(data.payment_reference||'');setAmount(data.total_duties_irr==null?'':String(data.total_duties_irr));setPath(data.customs_path||'')}};
 useEffect(()=>{const run=async()=>{const{data,error:e}=await supabase.from('shipments').select('id,bill_of_lading_no,cargo_count,cargo_count_unit,client_id,display_name,vessel_id').order('created_at',{ascending:false});if(e){setError(e.message);return}setShipments((data||[]) as Shipment[]);try{const raw=localStorage.getItem('customs_registered_shipment');const x=raw?JSON.parse(raw):null;if(x?.id)await load(x.id)}catch{}};void run()},[]);
 const register=async()=>{if(!selected)return setError('ابتدا محموله را انتخاب کنید.');if(!kottaj.trim())return setError('شماره پروانه / کوتاژ را وارد کنید.');if(!path)return setError('مسیر گمرکی را انتخاب کنید.');if(!profile?.organization_id)return setError('اطلاعات سازمان کاربر آماده نیست.');setBusy(true);setError('');setMessage('');try{const{data:declarationId,error:e}=await supabase.rpc('register_shipment_declaration',{p_shipment_id:selected,p_kottaj_number:kottaj.trim(),p_declaration_date:new Date(date).toISOString(),p_customs_path:path,p_payment_reference:payment.trim()||null,p_total_duties_irr:parseAmount(amount),p_case_id:null});if(e)throw e;const id=String(declarationId);let uploadedPath:string|null=null;if(file){if(!/^(application\/pdf|image\/(jpeg|png)|image\/jpg)$/i.test(file.type))throw new Error('فایل اظهارنامه باید PDF، JPG، JPEG یا PNG باشد.');const storagePath=`${profile.organization_id}/${selected}/${id}/${crypto.randomUUID()}-${safeFile(file.name)}`;const{error:up}=await supabase.storage.from('customs_documents').upload(storagePath,file,{upsert:false,contentType:file.type});if(up)throw up;uploadedPath=storagePath;const{error:fe}=await supabase.rpc('set_declaration_file',{p_declaration_id:id,p_storage_path:storagePath,p_file_name:file.name});if(fe)throw fe;const{error:docError}=await supabase.from('customs_documents').insert({organization_id:profile.organization_id,case_id:null,shipment_id:selected,document_type:'CUSTOMS_DECLARATION_PRINT',original_name:file.name,display_name:`اظهارنامه ${kottaj.trim()}`,storage_path:storagePath,mime_type:file.type,size_bytes:file.size,status:'uploaded',document_number:kottaj.trim(),issue_date:new Date(date).toISOString().slice(0,10),created_by:null});if(docError)throw docError}const{error:ci}=await supabase.rpc('initialize_declaration_checklist',{p_declaration_id:id});if(ci)throw ci;setMessage(uploadedPath?'اظهارنامه با فایل آن ثبت شد و چک‌لیست گمرکی آماده است.':'اظهارنامه ثبت شد. فایل اظهارنامه هنوز بارگذاری نشده است.');await load(selected);setDecl(await fetchDeclaration(id));}catch(e:any){setError(e?.message||'ثبت اظهارنامه انجام نشد')}finally{setBusy(false)}};
 const fetchDeclaration=async(id:string)=>{const{data,error:e}=await supabase.from('customs_declarations').select('id,shipment_id,kottaj_number,declaration_date,customs_path,payment_reference,total_duties_irr,declaration_file_name').eq('id',id).maybeSingle();if(e)throw e;return data as Declaration|null};
 const shipment=shipments.find(x=>x.id===selected);
 return <main dir="rtl" className="min-h-screen bg-[var(--bg)] text-[var(--text)] p-4 md:p-8"><div className="max-w-5xl mx-auto space-y-5"><header className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="text-xs app-muted">مرحله ۳</div><h1 className="text-2xl md:text-3xl font-black mt-1">ثبت اظهار</h1><p className="text-sm app-muted mt-1">اظهارنامه‌ای که همکار در EPL گمرک ثبت کرده را به محموله متصل کنید.</p></div><Link to="/operations?tab=pre-declaration" className="px-4 py-2 rounded-xl border app-border bg-[var(--surface)] text-sm"><ArrowLeft className="inline ml-1" size={15}/>اطلاعات گمرکی</Link></header>
 {error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-500">{error}</div>}{message&&<div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-600 flex items-center gap-2"><CheckCircle2 size={17}/>{message}</div>}
 <section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><label className="text-sm font-bold">محموله</label><select value={selected} onChange={e=>void load(e.target.value)} className="mt-2 w-full rounded-xl border app-border bg-[var(--surface-2)] p-3"><option value="">انتخاب محموله</option>{shipments.map(s=><option key={s.id} value={s.id}>{s.display_name||`${s.cargo_count||'—'} ${s.cargo_count_unit||''} · B/L ${s.bill_of_lading_no||'—'}`}</option>)}</select>{shipment&&<div className="mt-2 text-xs app-muted">B/L: {shipment.bill_of_lading_no||'—'}</div>}</section>
 {selected&&<section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="grid md:grid-cols-2 gap-4"><label><span className="block text-sm mb-1">شماره پروانه / کوتاژ *</span><input value={kottaj} onChange={e=>setKottaj(e.target.value)} className="w-full rounded-xl border app-border bg-[var(--surface-2)] p-3"/></label><label><span className="block text-sm mb-1">تاریخ اظهار *</span><input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} className="w-full rounded-xl border app-border bg-[var(--surface-2)] p-3"/></label><label><span className="block text-sm mb-1">شناسه پرداخت</span><input value={payment} onChange={e=>setPayment(e.target.value)} className="w-full rounded-xl border app-border bg-[var(--surface-2)] p-3"/></label><label><span className="block text-sm mb-1">مبلغ گمرکی (ریال)</span><input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} className="w-full rounded-xl border app-border bg-[var(--surface-2)] p-3"/></label><label><span className="block text-sm mb-1">مسیر گمرکی *</span><select value={path} onChange={e=>setPath(e.target.value)} className="w-full rounded-xl border app-border bg-[var(--surface-2)] p-3"><option value="">انتخاب مسیر</option><option value="green">سبز</option><option value="yellow">زرد</option><option value="red">قرمز</option></select></label><label><span className="block text-sm mb-1">فایل اظهارنامه</span><div className="flex gap-2"><input ref={fileRef} type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0]||null)} className="hidden"/><button type="button" onClick={()=>fileRef.current?.click()} className="flex-1 rounded-xl border app-border bg-[var(--surface-2)] p-3 text-sm text-right"><FileUp className="inline ml-2" size={16}/>{file?.name||decl?.declaration_file_name||'انتخاب فایل اظهارنامه'}</button></div></label></div>
 <div className="mt-5 flex flex-col md:flex-row gap-3"><button disabled={busy} onClick={()=>void register()} className="rounded-xl bg-[var(--primary)] text-white px-6 py-3 font-bold disabled:opacity-50">{busy?<><Loader2 className="inline ml-2 animate-spin" size={17}/>در حال ثبت...</>:<><Save className="inline ml-2" size={17}/>ثبت اظهار و اتصال به محموله</>}</button>{decl&&<Link to={`/operations?tab=stage5&declarationId=${encodeURIComponent(decl.id)}`} className="rounded-xl border app-border bg-[var(--surface-2)] px-6 py-3 font-bold text-center">رفتن به چک‌لیست گمرکی</Link>}</div></section>}
 {decl&&<section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><h2 className="font-black mb-3">اظهار ثبت‌شده</h2><div className="grid grid-cols-2 md:grid-cols-5 gap-3 text-sm"><div><span className="app-muted">کوتاژ</span><div className="font-bold mt-1">{decl.kottaj_number}</div></div><div><span className="app-muted">تاریخ</span><div className="font-bold mt-1">{new Date(decl.declaration_date).toLocaleDateString('fa-IR')}</div></div><div><span className="app-muted">شناسه پرداخت</span><div className="font-bold mt-1">{decl.payment_reference||'—'}</div></div><div><span className="app-muted">مبلغ گمرکی</span><div className="font-bold mt-1">{decl.total_duties_irr==null?'—':new Intl.NumberFormat('fa-IR').format(decl.total_duties_irr)}</div></div><div><span className="app-muted">مسیر</span><div className="font-bold mt-1">{decl.customs_path?pathLabels[decl.customs_path]||decl.customs_path:'—'}</div></div></div></section>}
 </div></main>;
};
