import React,{useEffect,useState} from 'react';
import {ArrowLeft,Loader2,Save} from 'lucide-react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../lib/supabase';

type CaseRow={id:string;case_number:string|null;status:string};
type Decl={id:string;kottaj_number:string|null;declaration_date:string|null;customs_path:string|null;payment_reference:string|null};
const pathLabels:Record<string,string>={green:'سبز',yellow:'زرد',red:'قرمز'};
const Info=({t,v}:{t:string;v:string})=><div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="text-xs text-slate-500">{t}</div><div className="mt-1 text-sm">{v}</div></div>;
const Field=({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string})=><label><span className="block text-sm text-slate-300 mb-1">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label>;

export const DeclarationChecklistPage:React.FC=()=>{
 const[params]=useSearchParams();const requested=params.get('caseId')||'';const[cases,setCases]=useState<CaseRow[]>([]);const[selected,setSelected]=useState(requested);const[decl,setDecl]=useState<Decl|null>(null);const[kottaj,setKottaj]=useState('');const[date,setDate]=useState(new Date().toISOString().slice(0,16));const[payment,setPayment]=useState('');const[path,setPath]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const load=async(id:string)=>{setError('');const{data,error:e}=await supabase.from('cases').select('id,case_number,status').order('created_at',{ascending:false});if(e){setError(e.message);return}setCases((data||[]) as CaseRow[]);if(!id)return;const{data:d,error:de}=await supabase.from('customs_declarations').select('id,kottaj_number,declaration_date,customs_path,payment_reference').eq('case_id',id).order('created_at',{ascending:false}).limit(1);if(de){setError(de.message);return}const x=(d||[])[0] as Decl|undefined;setDecl(x||null);if(x){setKottaj(x.kottaj_number||'');setDate(x.declaration_date?new Date(x.declaration_date).toISOString().slice(0,16):new Date().toISOString().slice(0,16));setPayment(x.payment_reference||'');setPath(x.customs_path||'')}};
 useEffect(()=>{void load(selected)},[selected]);
 const save=async()=>{if(!selected)return setError('پرونده را انتخاب کنید.');if(!kottaj.trim())return setError('شماره کوتاژ را وارد کنید.');setBusy(true);setError('');setMessage('');try{const{error:e}=await supabase.rpc('register_declaration_workflow',{p_case_id:selected,p_kottaj_number:kottaj.trim(),p_declaration_date:new Date(date).toISOString(),p_customs_office_id:null,p_customs_path:path||null,p_assessed_value_irr:null,p_total_duties_irr:null});if(e)throw e;if(payment){const{error:pe}=await supabase.from('customs_declarations').update({payment_reference:payment}).eq('case_id',selected).eq('kottaj_number',kottaj.trim());if(pe)throw pe}setMessage('اظهارنامه ثبت و اطلاعات کوتاژ، تاریخ کوتاژ، شناسه پرداخت و مسیر ذخیره شد.');await load(selected)}catch(e:any){setError(e?.message||'ثبت اظهارنامه انجام نشد')}finally{setBusy(false)}};
 return <main dir="rtl" className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8"><div className="max-w-5xl mx-auto space-y-5"><header className="flex items-center justify-between gap-3"><div><div className="text-xs text-slate-500">مرحله ۴</div><h1 className="text-2xl md:text-3xl font-black mt-1">اظهارنامه</h1><p className="text-sm text-slate-400 mt-1">آپلود و ثبت اطلاعات نهایی اظهارنامه</p></div><Link to={selected?`/stage?caseId=${encodeURIComponent(selected)}`:'/stage'} className="px-4 py-2 rounded-xl border border-slate-700 bg-slate-900 text-sm"><ArrowLeft className="inline ml-1" size={15}/>مرحله ۵</Link></header>{error&&<div className="rounded-xl border border-red-900 bg-red-950/30 p-4 text-red-300">{error}</div>}{message&&<div className="rounded-xl border border-emerald-900 bg-emerald-950/30 p-4 text-emerald-300">{message}</div>}<section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><label className="text-sm text-slate-400">محموله / پرونده</label><select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">انتخاب</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number||c.id.slice(0,8)}</option>)}</select></section>{selected&&<><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="grid md:grid-cols-2 gap-4"><Field label="شماره کوتاژ" value={kottaj} onChange={setKottaj}/><Field label="تاریخ کوتاژ" value={date} onChange={setDate} type="datetime-local"/><Field label="شناسه پرداخت" value={payment} onChange={setPayment}/><label><span className="block text-sm text-slate-300 mb-1">رنگ مسیر</span><select value={path} onChange={e=>setPath(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="">انتخاب مسیر</option><option value="green">سبز</option><option value="yellow">زرد</option><option value="red">قرمز</option></select></label></div><button onClick={()=>void save()} disabled={busy} className="mt-5 rounded-xl bg-cyan-600 px-5 py-3 font-bold disabled:opacity-50">{busy?<><Loader2 className="inline ml-2 animate-spin" size={17}/>در حال ثبت...</>:<><Save className="inline ml-2" size={17}/>ثبت اظهارنامه</>}</button></section>{decl&&<section className="rounded-2xl border border-slate-800 bg-slate-900 p-5 grid md:grid-cols-4 gap-3"><Info t="کوتاژ" v={decl.kottaj_number||'—'}/><Info t="تاریخ کوتاژ" v={decl.declaration_date?new Date(decl.declaration_date).toLocaleDateString('fa-IR'):'—'}/><Info t="شناسه پرداخت" v={decl.payment_reference||'—'}/><Info t="رنگ مسیر" v={decl.customs_path?pathLabels[decl.customs_path]||decl.customs_path:'—'}/></section>}</>}</div></main>;
};
