import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {Anchor,Bell,Briefcase,CalendarClock,CloudSun,Database,FolderKanban,MapPinned,Search,Settings,Ship,Truck,Wallet,Wind} from 'lucide-react';

const ports=[
 {name:'انزلی',lat:37.4727,lon:49.4587},{name:'آستارا',lat:38.429,lon:48.875},{name:'امیرآباد',lat:36.925,lon:53.420},{name:'نوشهر',lat:36.648,lon:51.496},{name:'فریدونکنار',lat:36.686,lon:52.523},{name:'ترکمن',lat:36.901,lon:54.071},{name:'بندر گز',lat:36.756,lon:53.947}
];
const apps=[['control','مرکز کنترل','/control',FolderKanban],['operations','عملیات گمرکی','/operations',Briefcase],['maritime','کشتیرانی و B/L','/maritime',Anchor],['vessel','کشتی‌ها','/vessel-tracking',MapPinned],['reminders','یادآورها','/reminders',Bell],['clients','صاحبان کالا','/clients',Database],['finance','مالی','/finance',Wallet],['exit','خروج و ترانزیت','/exit',Truck]] as const;
const faDate=new Intl.DateTimeFormat('fa-IR-u-ca-persian',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
const faTime=new Intl.DateTimeFormat('fa-IR',{hour:'2-digit',minute:'2-digit'});

export const DesktopHomePage:React.FC=()=>{
 const [now,setNow]=useState(new Date());const [port,setPort]=useState(ports[0]);const [weather,setWeather]=useState<any>(null);const [loading,setLoading]=useState(false);
 useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(id)},[]);
 useEffect(()=>{let cancelled=false;setLoading(true);fetch(`https://api.open-meteo.com/v1/forecast?latitude=${port.lat}&longitude=${port.lon}&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m,wind_direction_10m&timezone=auto`).then(r=>r.json()).then(j=>{if(!cancelled)setWeather(j.current)}).catch(()=>setWeather(null)).finally(()=>!cancelled&&setLoading(false));return()=>{cancelled=true}},[port]);
 const weatherText=useMemo(()=>{const c=weather?.weather_code;if(c===0)return'صاف';if([1,2,3].includes(c))return'ابری';if([45,48].includes(c))return'مه';if([51,53,55,61,63,65,80,81,82].includes(c))return'بارش';if([95,96,99].includes(c))return'رعدوبرق';return'—'},[weather]);
 return <main dir="rtl" className="min-h-screen bg-[#06101c] text-slate-100"><header className="h-14 border-b border-white/10 bg-[#091725]/95 flex items-center justify-between px-4 md:px-6 sticky top-0 z-20"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg bg-cyan-600 grid place-items-center"><Ship size={17}/></div><div><b className="text-sm">Customs OS</b><span className="hidden sm:inline text-[10px] text-slate-500 mr-2">Operations Control</span></div></div><div className="hidden md:flex items-center gap-2 text-xs text-slate-400"><Search size={14}/><span>جستجوی سریع</span><span className="mx-2 text-slate-700">|</span><span>{faTime.format(now)}</span></div><div className="flex gap-1"><Link className="p-2 rounded-lg hover:bg-white/5" to="/reminders"><Bell size={17}/></Link><Link className="p-2 rounded-lg hover:bg-white/5" to="/settings"><Settings size={17}/></Link></div></header>
 <div className="max-w-[1500px] mx-auto p-4 md:p-5 space-y-4"><section className="grid xl:grid-cols-[1.5fr_.75fr_.75fr] gap-3"><div className="rounded-2xl border border-white/10 bg-[#0b1928] p-5"><div className="text-[10px] text-cyan-400 mb-2">CONTROL DESK</div><h1 className="text-xl md:text-2xl font-black">میز کار عملیات گمرکی</h1><p className="text-xs text-slate-500 mt-2">پرونده، محموله، ترانزیت، مالی و کشتیرانی در یک صفحه.</p><div className="flex gap-2 mt-4"><Link to="/control" className="px-3 py-2 rounded-lg bg-cyan-600 text-xs font-bold">مرکز کنترل</Link><Link to="/operations" className="px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-xs">عملیات</Link></div></div><div className="rounded-2xl border border-white/10 bg-[#0b1928] p-4"><div className="text-[10px] text-slate-500">تاریخ</div><div className="font-bold mt-2">{faDate.format(now)}</div><div className="text-2xl font-black mt-3 tabular-nums">{faTime.format(now)}</div></div><div className="rounded-2xl border border-white/10 bg-[#0b1928] p-4"><div className="flex justify-between"><div><div className="text-[10px] text-slate-500">آب‌وهوای بندر</div><select value={port.name} onChange={e=>setPort(ports.find(p=>p.name===e.target.value)||ports[0])} className="mt-2 bg-transparent text-sm font-bold outline-none">{ports.map(p=><option key={p.name}>{p.name}</option>)}</select></div><CloudSun className="text-amber-300" size={20}/></div>{loading?<div className="mt-4 text-xs text-slate-500">در حال دریافت...</div>:<div className="mt-4"><span className="text-3xl font-black">{weather?.temperature_2m!=null?Math.round(weather.temperature_2m):'—'}°</span><span className="text-xs text-slate-500 mr-2">{weatherText}</span><div className="text-[11px] text-slate-500 mt-2"><Wind size={12} className="inline ml-1"/>{weather?.wind_speed_10m??'—'} km/h · {weather?.wind_direction_10m??'—'}°</div></div>}</div></section>
 <section className="grid xl:grid-cols-[1.5fr_.9fr] gap-3"><div className="rounded-2xl border border-white/10 bg-[#0b1928] p-4"><div className="flex items-center justify-between mb-3"><div><h2 className="font-bold text-sm">ابزارهای عملیاتی</h2><p className="text-[10px] text-slate-500 mt-1">دسترسی سریع</p></div><Briefcase size={17} className="text-cyan-400"/></div><div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-2">{apps.map(([key,label,to,Icon])=><Link key={key} to={to} className="rounded-xl border border-white/7 bg-[#08131f] hover:border-cyan-500/30 hover:bg-cyan-500/5 p-3 min-h-[78px] flex flex-col items-center justify-center gap-2"><Icon size={18} className="text-cyan-300"/><span className="text-[10px] font-semibold text-center">{label}</span></Link>)}</div></div><div className="rounded-2xl border border-white/10 bg-[#0b1928] p-4"><div className="flex items-center justify-between mb-3"><div><h2 className="font-bold text-sm">دسترسی‌های مهم</h2><p className="text-[10px] text-slate-500 mt-1">عملیات روزانه</p></div><CalendarClock size={17} className="text-violet-300"/></div><div className="space-y-2 text-xs"><Link to="/reminders" className="flex justify-between p-2.5 rounded-lg bg-white/[.03] hover:bg-white/[.06]"><span>یادآورهای امروز</span><b>→</b></Link><Link to="/vessel-tracking" className="flex justify-between p-2.5 rounded-lg bg-white/[.03] hover:bg-white/[.06]"><span>مسیر دریایی خزر</span><b>→</b></Link><Link to="/maritime" className="flex justify-between p-2.5 rounded-lg bg-white/[.03] hover:bg-white/[.06]"><span>کشتی و B/L</span><b>→</b></Link></div></div></section>
 <section className="grid sm:grid-cols-3 gap-3">{[['پرونده‌ها','/control','مدیریت و کنترل عملیات'],['محموله‌ها','/operations','ثبت و پیگیری مراحل'],['کشتیرانی','/maritime','B/L و اطلاعات کشتی']].map(([t,to,d])=><Link key={to} to={to} className="rounded-xl border border-white/10 bg-[#0b1928] p-4 hover:border-cyan-500/25"><div className="font-bold text-sm">{t}</div><div className="text-[10px] text-slate-500 mt-1">{d}</div></Link>)}</section></div><footer className="border-t border-white/10 mt-5 px-5 py-3 text-[10px] text-slate-600 flex justify-between"><span>Customs OS</span><span>{faDate.format(now)} · {port.name}</span></footer></main>;
};
