import React,{useEffect,useRef,useState} from 'react';
import {FileSearch,Upload,Check,AlertTriangle,Eye,RefreshCw,ArrowRight,Loader2} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import * as pdfjsLib from 'pdfjs-dist';
import {createWorker} from 'tesseract.js';
pdfjsLib.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.mjs',import.meta.url).toString();

type Field={id?:string;field_key:string;extracted_value:string|null;normalized_value:string|null;confidence:number|null;source_page:number|null;bbox:any;verification_status:string;extractor?:string};
const normalizeDigits=(v:string)=>v.replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d)));
const rules:{key:string;re:RegExp;confidence:number}[]=[
 {key:'registration_order_no',re:/(?:ثبت\s*سفارش|registration\s*order)[^\d\n]{0,40}([0-9۰-۹]{6,20})/i,confidence:.93},
 {key:'bill_of_lading_no',re:/(?:B\s*\/\s*L|BILL\s+OF\s+LADING)[^A-Z0-9۰-۹]{0,30}([A-Z0-9۰-۹-]{5,40})/i,confidence:.92},
 {key:'invoice_no',re:/(?:invoice\s*(?:no|number)|شماره\s*فاکتور)[^A-Z0-9۰-۹]{0,30}([A-Z0-9۰-۹-]{3,40})/i,confidence:.86},
 {key:'hs_code',re:/(?:HS\s*(?:CODE|NO)?|کد\s*تعرفه)[^0-9۰-۹]{0,15}([0-9۰-۹]{6,12})/i,confidence:.9},
 {key:'quantity',re:/(?:quantity|qty|مقدار|تعداد)[^0-9۰-۹]{0,20}([0-9۰-۹.,]+)/i,confidence:.8},
 {key:'gross_weight_kg',re:/(?:gross\s*weight|وزن\s*ناخالص)[^0-9۰-۹]{0,20}([0-9۰-۹.,]+)/i,confidence:.82},
 {key:'net_weight_kg',re:/(?:net\s*weight|وزن\s*خالص)[^0-9۰-۹]{0,20}([0-9۰-۹.,]+)/i,confidence:.82},
];
export const DocumentExtractionPage:React.FC=()=>{
 const [cases,setCases]=useState<any[]>([]),[documents,setDocuments]=useState<any[]>([]),[fields,setFields]=useState<Field[]>([]),[caseId,setCaseId]=useState(''),[selectedDoc,setSelectedDoc]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[message,setMessage]=useState('');
 const [preview,setPreview]=useState<{page:number;url:string}|null>(null);const canvasRef=useRef<HTMLCanvasElement|null>(null);
 const load=async()=>{const [{data:c,error:ce},{data:d,error:de}]=await Promise.all([supabase.from('cases').select('id,case_number').order('created_at',{ascending:false}),supabase.from('documents').select('id,case_id,file_name,doc_type,storage_path,created_at').order('created_at',{ascending:false})]);if(ce||de)setMessage((ce||de)?.message||'خطا');setCases(c||[]);setDocuments(d||[])};
 useEffect(()=>{load()},[]);
 useEffect(()=>{(async()=>{if(!preview||!canvasRef.current)return;try{const r=await fetch(preview.url);const b=await r.arrayBuffer();const pdf=await pdfjsLib.getDocument({data:b}).promise;const page=await pdf.getPage(preview.page);const viewport=page.getViewport({scale:1.35});const canvas=canvasRef.current;canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d')!,viewport}).promise}catch(e:any){setMessage(e?.message||'خطا در پیش‌نمایش سند')}})()},[preview]);
 const fileUrl=async(path:string)=>{const {data,error}=await supabase.storage.from('case-documents').createSignedUrl(path,600);if(error)throw error;return data.signedUrl};
 const findBox=(text:string,needle:string)=>{const i=text.toLowerCase().indexOf(needle.toLowerCase());return i>=0?{textIndex:i,needle}:null};
 const extractPdf=async(file:File)=>{const bytes=await file.arrayBuffer();const pdf=await pdfjsLib.getDocument({data:bytes}).promise;const out:Field[]=[];for(let pageNo=1;pageNo<=pdf.numPages;pageNo++){setProgress(`خواندن صفحه ${pageNo} از ${pdf.numPages}`);const page=await pdf.getPage(pageNo);const content=await page.getTextContent();const items=(content.items as any[]).filter(x=>typeof x.str==='string');const text=items.map(x=>x.str).join(' ');for(const rule of rules){if(out.some(x=>x.field_key===rule.key))continue;const m=text.match(rule.re);if(!m)continue;const value=normalizeDigits(m[1]);const token=items.find(x=>x.str&&x.str.includes(m[1]))||items.find(x=>x.str&&x.str.includes(value));let bbox=null;if(token){const tr=token.transform||[];bbox={x:tr[4]||0,y:tr[5]||0,width:token.width||0,height:token.height||Math.abs(tr[3]||12),page_width:page.view[2],page_height:page.view[3]};}out.push({field_key:rule.key,extracted_value:m[1],normalized_value:value,confidence:rule.confidence,source_page:pageNo,bbox,verification_status:rule.confidence>=.9?'needs_review':'needs_review',extractor:'pdf-text-regex'});}}return out};
 const extractImage=async(file:File)=>{setProgress('OCR تصویر در حال اجراست…');const worker=await createWorker('eng');try{const {data}=await worker.recognize(file);const text=data.text;const out:Field[]=[];for(const rule of rules){const m=text.match(rule.re);if(m)out.push({field_key:rule.key,extracted_value:m[1],normalized_value:normalizeDigits(m[1]),confidence:Math.min(.88,rule.confidence-.08),source_page:1,bbox:null,verification_status:'needs_review',extractor:'tesseract-ocr'});}return out}finally{await worker.terminate()}};
 const uploadAndExtract=async(file:File)=>{if(!caseId)return setMessage('ابتدا پرونده را انتخاب کنید.');setBusy(true);setMessage('');try{const id=crypto.randomUUID();const path=`${caseId}/${id}-${file.name.replace(/[^\w.\-]+/g,'_')}`;setProgress('در حال ذخیره سند…');const {error:up}=await supabase.storage.from('case-documents').upload(path,file,{upsert:false,contentType:file.type});if(up)throw up;const {data:{user}}=await supabase.auth.getUser();const {data:doc,error:de}=await supabase.from('documents').insert({id,case_id:caseId,uploaded_by:user?.id||null,file_name:file.name,storage_path:path,mime_type:file.type,file_size_bytes:file.size,doc_type:'other'}).select('id').single();if(de)throw de;const extracted=file.type==='application/pdf'?await extractPdf(file):file.type.startsWith('image/')?await extractImage(file):[];if(extracted.length){const {error:fe}=await supabase.from('document_extraction_fields').upsert(extracted.map(x=>({...x,document_id:doc.id,organization_id:undefined})),{onConflict:'document_id,field_key'});if(fe){const {data:{user:u}}=await supabase.auth.getUser();const {data:p}=await supabase.from('profiles').select('organization_id').eq('id',u?.id||'').maybeSingle();if(!p?.organization_id)throw fe;const {error:fe2}=await supabase.from('document_extraction_fields').upsert(extracted.map(x=>({...x,document_id:doc.id,organization_id:p.organization_id})),{onConflict:'document_id,field_key'});if(fe2)throw fe2;}}setSelectedDoc(doc.id);setProgress('');setMessage(extracted.length?`${extracted.length} فیلد استخراج شد؛ همه برای تأیید انسانی علامت‌گذاری شدند.`:'متن قابل استخراج/تشخیص پیدا نشد؛ سند ذخیره شد و نیاز به بررسی دستی دارد.');await load();const signed=await fileUrl(path);if(file.type==='application/pdf')setPreview({page:1,url:signed});}catch(e:any){setMessage(e?.message||'خطا در استخراج/ذخیره سند');setProgress('')}finally{setBusy(false)}};
 const loadFields=async(docId:string)=>{setSelectedDoc(docId);const {data,error}=await supabase.from('document_extraction_fields').select('*').eq('document_id',docId).order('field_key');if(error)setMessage(error.message);setFields(data||[])};
 const verify=async(f:Field,status:string)=>{if(!f.id)return;const {error}=await supabase.from('document_extraction_fields').update({verification_status:status}).eq('id',f.id);if(error)setMessage(error.message);else setFields(x=>x.map(y=>y.id===f.id?{...y,verification_status:status}:y))};
 const showSource=async(f:Field)=>{const d=documents.find(x=>x.id===selectedDoc);if(!d?.storage_path||!f.source_page)return;try{const url=await fileUrl(d.storage_path);setPreview({page:f.source_page,url})}catch(e:any){setMessage(e?.message||'پیش‌نمایش در دسترس نیست')}};
 useEffect(()=>{if(selectedDoc)loadFields(selectedDoc)},[selectedDoc]);
 return <main className="min-h-screen p-4 sm:p-6 lg:p-8" dir="rtl"><div className="max-w-[1500px] mx-auto"><div className="flex justify-between items-center mb-6"><div><div className="text-xs app-muted">Document Intelligence</div><h1 className="text-2xl font-black">استخراج و راستی‌آزمایی اسناد</h1><p className="text-sm app-muted mt-1">PDF متنی و تصویر را استخراج می‌کند؛ هیچ مقدار استخراج‌شده بدون تأیید شما قطعی نمی‌شود.</p></div><Link to="/" className="px-4 py-2 rounded-xl border app-border"><ArrowRight className="inline ml-2" size={16}/>صفحه اصلی</Link></div>
 <div className="grid lg:grid-cols-[360px_1fr] gap-5"><section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><h2 className="font-black mb-3">۱. سند جدید</h2><select value={caseId} onChange={e=>setCaseId(e.target.value)} className="w-full rounded-xl border app-border bg-[var(--surface-2)] p-3 mb-3"><option value="">انتخاب پرونده</option>{cases.map(c=><option key={c.id} value={c.id}>{c.case_number||c.id.slice(0,8)}</option>)}</select><label className="block rounded-xl border border-dashed app-border p-6 text-center cursor-pointer"><Upload className="mx-auto mb-2"/><span className="text-sm font-bold">انتخاب PDF یا تصویر</span><input type="file" accept="application/pdf,image/*" className="hidden" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)uploadAndExtract(f)}}/></label>{busy&&<div className="mt-4 text-xs app-muted flex items-center gap-2"><Loader2 className="animate-spin" size={15}/>{progress}</div>}{message&&<div className="mt-4 text-xs rounded-xl border app-border p-3">{message}</div>}<h2 className="font-black mt-6 mb-3">اسناد قبلی</h2><div className="space-y-2 max-h-[430px] overflow-auto">{documents.map(d=><button key={d.id} onClick={()=>loadFields(d.id)} className={`w-full text-right rounded-xl border p-3 ${selectedDoc===d.id?'border-cyan-500/50 bg-cyan-500/5':'app-border bg-[var(--surface-2)]'}`}><div className="font-bold text-sm">{d.file_name}</div><div className="text-[11px] app-muted mt-1">{d.doc_type} · {new Date(d.created_at).toLocaleDateString('fa-IR')}</div></button>)}</div></section>
 <section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="flex items-center gap-2 mb-4"><FileSearch size={19}/><h2 className="font-black">۲. فیلدهای استخراج‌شده</h2></div>{fields.length===0?<div className="py-20 text-center app-muted">یک سند را انتخاب یا آپلود کنید.</div>:<div className="space-y-3">{fields.map(f=><div key={f.id} className={`rounded-xl border p-4 ${f.verification_status==='verified'?'border-emerald-500/30 bg-emerald-500/5':f.verification_status==='rejected'?'border-red-500/30 bg-red-500/5':'border-amber-500/30 bg-amber-500/5'}`}><div className="flex items-start justify-between gap-3"><div><div className="font-bold">{f.field_key}</div><div className="text-lg font-black mt-1" dir="ltr">{f.normalized_value||f.extracted_value||'—'}</div><div className="text-[11px] app-muted mt-1">Confidence: {f.confidence!=null?`${Math.round(f.confidence*100)}%`:'—'} · صفحه {f.source_page||'—'} · {f.extractor||'—'}</div></div><div className="flex gap-2"><button onClick={()=>showSource(f)} className="icon-btn" title="نمایش منبع"><Eye size={15}/></button><button onClick={()=>verify(f,'verified')} className="icon-btn text-emerald-500" title="تأیید"><Check size={15}/></button><button onClick={()=>verify(f,'rejected')} className="icon-btn text-red-500" title="رد"><AlertTriangle size={15}/></button></div></div><div className="text-xs mt-3 p-2 rounded-lg bg-[var(--surface-2)]">وضعیت: <b>{f.verification_status==='verified'?'تأیید شده':f.verification_status==='rejected'?'رد شده':'نیازمند بررسی'}</b></div></div>)}</div>}</section></div>
 {preview&&<div className="fixed inset-0 z-50 bg-black/80 p-4 flex items-center justify-center" onClick={()=>setPreview(null)}><div className="max-w-5xl max-h-[90vh] overflow-auto bg-white p-3 rounded-xl" onClick={e=>e.stopPropagation()}><div className="text-black text-sm font-bold mb-2">پیش‌نمایش صفحه {preview.page} — برای بستن لمس کنید</div><canvas ref={canvasRef} className="max-w-full h-auto"/></div></div>}</div></main>;
};
