import React,{useEffect,useState} from 'react';
import {BookOpen,Check,Clock3,FileSearch,Loader2,MessageCircle,ShieldCheck,Upload,X} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Extraction={title:string;source_type:string;source_number:string|null;issued_at:string|null;effective_at:string|null;issuer:string|null;subject:string|null;keywords:string[];summary:string;extracted_text:string;chunks:{page_number:number|null;content:string}[]};
type Source={id:string;title:string;source_type:string;source_number:string|null;issued_at:string|null;effective_at:string|null;issuer:string|null;subject:string|null;status:string;metadata:any;ai_extraction:Extraction;storage_path:string|null;created_at:string};

const typeLabels:Record<string,string>={law:'قانون',circular:'بخشنامه',instruction:'دستورالعمل',notice:'اطلاعیه',tariff:'تعرفه',ruling:'رأی/نظر',guide:'راهنما',other:'سایر'};
const statusLabels:Record<string,string>={pending_review:'در انتظار تأیید',active:'فعال',rejected:'رد شده',superseded:'منسوخ/جایگزین شده',revoked:'لغو شده',draft:'پیش‌نویس'};
const sha256=async(file:File)=>{const b=await file.arrayBuffer();const h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')};
const fileToBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||'');const i=s.indexOf(',');resolve(i>=0?s.slice(i+1):s)};r.onerror=()=>reject(new Error('خواندن فایل ناموفق بود.'));r.readAsDataURL(file)});

export const KnowledgeCenterV2Page:React.FC=()=>{
 const[sources,setSources]=useState<Source[]>([]),[pending,setPending]=useState<Source[]>([]),[q,setQ]=useState(''),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[file,setFile]=useState<File|null>(null),[review,setReview]=useState<Extraction|null>(null),[reviewSourceId,setReviewSourceId]=useState(''),[selected,setSelected]=useState<Source|null>(null);
 const load=async()=>{const{data,error}=await supabase.from('knowledge_sources').select('id,title,source_type,source_number,issued_at,effective_at,issuer,subject,status,metadata,ai_extraction,storage_path,created_at').order('updated_at',{ascending:false}).limit(100);if(error){setErr(error.message);return}const rows=(data||[]) as Source[];setSources(rows.filter(x=>x.status==='active'));setPending(rows.filter(x=>x.status==='pending_review'))};
 useEffect(()=>{void load()},[]);
 const extract=async()=>{
  if(!file)return;setBusy(true);setErr('');setReview(null);setReviewSourceId('');
  try{
   const mime=file.type||'application/octet-stream';if(!(mime==='application/pdf'||mime==='text/plain'||mime==='text/markdown'||mime.startsWith('image/')))throw new Error('PDF، تصویر، TXT یا Markdown انتخاب کنید.');if(file.size>25*1024*1024)throw new Error('حداکثر حجم فایل ۲۵ مگابایت است.');
   const data=await fileToBase64(file);const{data:r,error}=await supabase.functions.invoke('knowledge-ai',{body:{action:'extract',filename:file.name,document_mime_type:mime,document_data:data}});if(error)throw error;
   const ex=r?.extraction as Extraction;if(!ex?.title||!Array.isArray(ex.chunks))throw new Error('استخراج AI ناقص بود.');
   const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('کاربر وارد نشده است.');
   const{data:p,error:pe}=await supabase.from('profiles').select('organization_id').eq('id',user.id).maybeSingle();if(pe||!p?.organization_id)throw new Error(pe?.message||'سازمان کاربر مشخص نیست.');
   const hash=await sha256(file);const safe=file.name.replace(/[^\w.\-\u0600-\u06ff]+/g,'_');const path=p.organization_id+'/'+crypto.randomUUID()+'-'+safe;
   const up=await supabase.storage.from('customs-knowledge').upload(path,file,{contentType:mime,cacheControl:'3600',upsert:false});if(up.error)throw up.error;
   const{data:s,error:se}=await supabase.from('knowledge_sources').insert({organization_id:p.organization_id,title:ex.title,source_type:typeLabels[ex.source_type]?ex.source_type:'other',source_number:ex.source_number||null,issued_at:ex.issued_at||null,effective_at:ex.effective_at||null,issuer:ex.issuer||null,subject:ex.subject||null,keywords:Array.isArray(ex.keywords)?ex.keywords:[],status:'pending_review',storage_path:path,mime_type:mime,created_by:user.id,extracted_text:ex.extracted_text||'',ai_extraction:ex,extraction_model:r?.model||'gemini-3.8-flash',metadata:{filename:file.name,size:file.size,sha256:hash,summary:ex.summary||''}}).select('id').single();
   if(se||!s){await supabase.storage.from('customs-knowledge').remove([path]);throw se||new Error('ثبت منبع ناموفق بود.')}setReview(ex);setReviewSourceId(s.id);setFile(null);await load();
  }catch(e:any){setErr(e?.message||'استخراج ناموفق بود.')}finally{setBusy(false)}
 };
 const reviewAction=async(action:'approve'|'reject')=>{if(!reviewSourceId)return;setBusy(true);setErr('');try{const{data,error}=await supabase.functions.invoke('knowledge-ai',{body:{action,source_id:reviewSourceId,note:action==='reject'?'رد شده در بررسی انسانی':'تأیید و انتشار پس از بررسی انسانی'}});if(error)throw error;if(data?.error)throw new Error(data.error);setReview(null);setReviewSourceId('');await load()}catch(e:any){setErr(e?.message||'عملیات بررسی ناموفق بود.')}finally{setBusy(false)}};
 const ask=async()=>{if(!q.trim())return;setBusy(true);setErr('');setAnswer('');try{const{data,error}=await supabase.functions.invoke('ai-core',{body:{query:q,mode:'chat'}});if(error)throw error;setAnswer(data?.answer||'پاسخی دریافت نشد.')}catch(e:any){setErr(e?.message||'پاسخ‌گویی ناموفق بود.')}finally{setBusy(false)}};
 return <main dir="rtl" className="min-h-screen p-4 md:p-8" style={{background:'var(--bg)',color:'var(--text)'}}><div className="max-w-6xl mx-auto space-y-5">
  <header><div className="flex items-center gap-2"><BookOpen/><h1 className="text-2xl font-black">دانشنامه گمرکی</h1></div><p className="text-xs app-muted mt-1">آپلود سند → استخراج هوش مصنوعی → بررسی انسانی → انتشار در دانش فعال</p></header>
  {err&&<div className="p-3 rounded-xl bg-red-500/10 border border-red-400/30 text-sm">{err}</div>}
  <section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="flex items-center gap-2 mb-3"><Upload size={18}/><h2 className="font-bold">افزودن قانون / بخشنامه</h2></div>
   <label className="block p-6 rounded-xl border border-dashed app-border text-center cursor-pointer"><FileSearch className="mx-auto mb-2" size={28}/><div className="font-bold">{file?file.name:'فایل را انتخاب کنید'}</div><div className="text-xs app-muted mt-1">PDF، تصویر، TXT یا Markdown — حداکثر ۲۵MB</div><input type="file" className="hidden" accept="application/pdf,image/*,.txt,.md" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>
   <button className="w-full mt-3 py-3 rounded-xl bg-[var(--primary)] text-white font-bold disabled:opacity-50" disabled={!file||busy} onClick={extract}>{busy?<span className="inline-flex items-center gap-2"><Loader2 className="animate-spin" size={17}/>در حال استخراج...</span>:'استخراج خودکار با AI'}</button>
  </section>
  {review&&<section className="rounded-2xl border-2 border-amber-400/40 bg-[var(--surface)] p-5"><div className="flex items-center gap-2"><Clock3/><h2 className="font-bold">بررسی قبل از انتشار</h2></div>
   <div className="grid md:grid-cols-2 gap-3 mt-4 text-sm"><div>عنوان: <b>{review.title||'—'}</b></div><div>نوع: <b>{typeLabels[review.source_type]||'سایر'}</b></div><div>شماره: {review.source_number||'—'}</div><div>مرجع: {review.issuer||'—'}</div><div>تاریخ صدور: {review.issued_at||'—'}</div><div>تاریخ اجرا: {review.effective_at||'—'}</div><div className="md:col-span-2">موضوع: {review.subject||'—'}</div><div className="md:col-span-2">خلاصه AI: {review.summary||'—'}</div></div>
   <div className="mt-4"><div className="font-bold text-sm mb-2">متن استخراج‌شده</div><div className="max-h-72 overflow-auto rounded-xl bg-[var(--surface-2)] p-4 whitespace-pre-wrap text-xs leading-6">{review.extracted_text||'متن استخراج نشد.'}</div></div>
   <div className="mt-4"><div className="font-bold text-sm mb-2">بخش‌های قابل استناد: {review.chunks.length}</div><div className="max-h-48 overflow-auto space-y-2">{review.chunks.slice(0,20).map((c,i)=><div key={i} className="rounded-lg bg-[var(--surface-2)] p-3 text-xs"><b>{c.page_number?'صفحه '+c.page_number:'بخش '+(i+1)}</b><div className="mt-1">{c.content}</div></div>)}</div></div>
   <div className="flex gap-2 mt-4"><button className="flex-1 py-3 rounded-xl bg-[var(--primary)] text-white font-bold disabled:opacity-50" disabled={busy} onClick={()=>reviewAction('approve')}><Check className="inline ml-1" size={17}/>تأیید و انتشار</button><button className="px-5 py-3 rounded-xl border app-border font-bold disabled:opacity-50" disabled={busy} onClick={()=>reviewAction('reject')}><X className="inline ml-1" size={17}/>رد</button></div>
  </section>}
  {pending.length>0&&<section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><h2 className="font-bold mb-3">در انتظار تأیید ({pending.length})</h2><div className="grid md:grid-cols-2 gap-2">{pending.map(s=><button key={s.id} onClick={()=>{setReview(s.ai_extraction);setReviewSourceId(s.id)}} className="text-right p-3 rounded-xl bg-[var(--surface-2)]"><b>{s.title}</b><div className="text-xs app-muted mt-1">{typeLabels[s.source_type]||'سایر'}{s.source_number?' · '+s.source_number:''}</div></button>)}</div></section>}
  <section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="flex items-center gap-2 mb-3"><MessageCircle size={18}/><h2 className="font-bold">پرسش از دانش فعال</h2></div><div className="flex gap-2"><input className="field flex-1" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="مثلاً: در این بخشنامه چه الزامی برای قبض انبار آمده؟"/><button className="px-5 rounded-xl bg-[var(--primary)] text-white font-bold disabled:opacity-50" onClick={ask} disabled={busy||!q.trim()}>{busy?<Loader2 className="animate-spin"/>:'پرسش'}</button></div>{answer&&<div className="mt-4 rounded-xl bg-[var(--surface-2)] p-4 whitespace-pre-wrap leading-7 text-sm">{answer}</div>}</section>
  <section className="rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="flex items-center gap-2 mb-3"><ShieldCheck size={18}/><h2 className="font-bold">منابع فعال ({sources.length})</h2></div>{!sources.length?<div className="text-sm app-muted">هنوز منبع تأییدشده‌ای ثبت نشده است.</div>:<div className="grid md:grid-cols-2 gap-2">{sources.map(s=><div key={s.id} className="p-3 rounded-xl bg-[var(--surface-2)]"><b>{s.title}</b><div className="text-xs app-muted mt-1">{typeLabels[s.source_type]||'سایر'}{s.source_number?' · '+s.source_number:''}{s.issuer?' · '+s.issuer:''} · {statusLabels[s.status]||s.status}</div></div>)}</div>}</section>
 </div></main>;
};