import React,{useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,FileText,Loader2,MessageCircle,Plus,Search,Trash2,Upload} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Source={id:string;title:string;source_type:string;source_number:string|null;issued_at:string|null;effective_at:string|null;issuer:string|null;subject:string|null;status:string;source_url:string|null;storage_path:string|null;created_at:string};
const types=[['law','قانون'],['circular','بخشنامه'],['instruction','دستورالعمل'],['notice','اطلاعیه'],['tariff','تعرفه'],['ruling','رأی/نظر'],['guide','راهنما'],['other','سایر']];
const chunk=(text:string,n=2200)=>{const a=[];for(let i=0;i<text.length;i+=n)a.push(text.slice(i,i+n));return a.filter(x=>x.trim())};
const file64=(f:File)=>new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||'');ok(s.includes(',')?s.split(',')[1]:s)};r.onerror=()=>no(new Error('خواندن فایل ناموفق بود'));r.readAsDataURL(f)});

export const KnowledgeCenterPage:React.FC=()=>{
 const[file,setFile]=useState<File|null>(null),[text,setText]=useState(''),[sources,setSources]=useState<Source[]>([]),[selected,setSelected]=useState<Source|null>(null),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[chatBusy,setChatBusy]=useState(false),[error,setError]=useState('');
 const[title,setTitle]=useState(''),[type,setType]=useState('circular'),[number,setNumber]=useState(''),[issued,setIssued]=useState(''),[effective,setEffective]=useState(''),[issuer,setIssuer]=useState(''),[subject,setSubject]=useState(''),[url,setUrl]=useState('');
 const ref=useRef<HTMLInputElement>(null);
 const load=async()=>{const{data,error}=await supabase.from('knowledge_sources').select('*').order('updated_at',{ascending:false}).limit(100);if(!error)setSources((data||[]) as Source[])};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>sources.filter(s=>[s.title,s.source_number,s.subject,s.issuer].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase())),[sources,search]);
 const save=async()=>{setError('');if(!title.trim()){setError('عنوان منبع الزامی است');return}if(!file&&!text.trim()){setError('فایل یا متن منبع را وارد کنید');return}setBusy(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('جلسه کاربر معتبر نیست');const{data:profile}=await supabase.from('profiles').select('organization_id').eq('id',user.id).single();if(!profile?.organization_id)throw new Error('سازمان کاربر پیدا نشد');let storage_path:string|null=null;let extracted=text.trim();if(file){const data=await file64(file);storage_path=`${profile.organization_id}/${crypto.randomUUID()}-${file.name.replace(/[^\w.\-]+/g,'_')}`;const up=await supabase.storage.from('customs-knowledge').upload(storage_path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(up.error)throw up.error;const ai=await supabase.functions.invoke('ai-assistant',{body:{knowledge_ingest:true,document_data:data,document_mime_type:file.type,query:title,page_context:'/knowledge'}});if(ai.error)throw ai.error;if(typeof ai.data?.answer==='string')extracted=ai.data.answer;if(!extracted.trim())throw new Error('متن قابل جستجوی منبع استخراج نشد')}const{data:src,error:se}=await supabase.from('knowledge_sources').insert({organization_id:profile.organization_id,title:title.trim(),source_type:type,source_number:number.trim()||null,issued_at:issued||null,effective_at:effective||null,issuer:issuer.trim()||null,subject:subject.trim()||null,status:'active',source_url:url.trim()||null,storage_path,mime_type:file?.type||'text/plain',created_by:user.id}).select().single();if(se)throw se;const chunks=chunk(extracted);const rows=chunks.map((content,i)=>({organization_id:profile.organization_id,source_id:src.id,chunk_index:i,content}));const{error:ce}=await supabase.from('knowledge_chunks').insert(rows);if(ce)throw ce;setTitle('');setNumber('');setIssued('');setEffective('');setIssuer('');setSubject('');setUrl('');setText('');setFile(null);if(ref.current)ref.current.value='';await load();setSelected(src as Source)}catch(e:any){setError(e?.message||'ثبت منبع ناموفق بود')}finally{setBusy(false)}};
 const remove=async(s:Source)=>{if(!confirm(`حذف «${s.title}»؟`))return;const{error}=await supabase.from('knowledge_sources').delete().eq('id',s.id);if(error)setError(error.message);else{setSelected(null);await load()}};
 const ask=async()=>{if(!question.trim())return;setChatBusy(true);setError('');try{const r=await supabase.functions.invoke('knowledge-assistant',{body:{query:question.trim()}});if(r.error)throw r.error;setAnswer(r.data?.answer||'پاسخی دریافت نشد.')}catch(e:any){setError(e?.message||'پاسخ‌گویی ناموفق بود')}finally{setChatBusy(false)}};
 return <main dir="rtl" className="min-h-screen p-4 md:p-7" style={{background:'var(--bg)',color:'var(--text)'}}><div className="max-w-[1500px] mx-auto"><div className="flex flex-wrap items-center justify-between gap-3 mb-5"><div><div className="flex items-center gap-2"><BookOpen size={22}/><h1 className="text-2xl font-black">مرکز دانش گمرکی</h1></div><p className="text-xs app-muted mt-1">منابع رسمی، بخشنامه‌ها و مقررات قابل استناد برای هوش مصنوعی</p></div><button onClick={()=>document.getElementById('knowledge-new')?.scrollIntoView({behavior:'smooth'})} className="px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white text-sm font-bold"><Plus size={16} className="inline ml-1"/> منبع جدید</button></div>
 {error&&<div className="mb-4 rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-sm">{error}</div>}
 <div className="grid xl:grid-cols-[1.1fr_.9fr] gap-5"><section className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex items-center justify-between gap-2 mb-3"><h2 className="font-bold">منابع ثبت‌شده</h2><div className="relative"><Search size={15} className="absolute right-3 top-2.5 app-muted"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جستجوی منبع..." className="pr-9 pl-3 py-2 rounded-xl bg-[var(--surface-2)] border app-border text-xs outline-none"/></div></div><div className="space-y-2 max-h-[560px] overflow-auto">{filtered.map(s=><button key={s.id} onClick={()=>setSelected(s)} className={`w-full text-right p-3 rounded-xl border app-border hover:bg-[var(--surface-2)] ${selected?.id===s.id?'ring-1 ring-[var(--primary)]':''}`}><div className="flex items-start gap-3"><FileText size={18}/><div className="min-w-0 flex-1"><b className="text-sm block truncate">{s.title}</b><span className="text-[10px] app-muted">{types.find(x=>x[0]===s.source_type)?.[1]||'سایر'}{s.source_number?` · ${s.source_number}`:''}{s.issued_at?` · ${s.issued_at}`:''}</span></div><span className="text-[10px] text-emerald-400">معتبر</span></div></button>)}{!filtered.length&&<div className="py-10 text-center app-muted text-sm">منبع ثبت نشده است.</div>}</div>{selected&&<div className="mt-4 p-4 rounded-xl bg-[var(--surface-2)]"><div className="flex justify-between gap-3"><div><b>{selected.title}</b><div className="text-xs app-muted mt-1">{selected.issuer||'مرجع نامشخص'} {selected.subject?`· ${selected.subject}`:''}</div></div><button onClick={()=>remove(selected)} className="text-red-400" title="حذف"><Trash2 size={17}/></button></div></div>}</section>
 <section className="rounded-2xl border app-border bg-[var(--surface)] p-4" id="knowledge-new"><h2 className="font-bold mb-3">افزودن منبع تخصصی</h2><div className="grid md:grid-cols-2 gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان منبع *" className="field"/><select value={type} onChange={e=>setType(e.target.value)} className="field">{types.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input value={number} onChange={e=>setNumber(e.target.value)} placeholder="شماره بخشنامه / قانون" className="field"/><input value={issuer} onChange={e=>setIssuer(e.target.value)} placeholder="مرجع صادرکننده" className="field"/><input type="date" value={issued} onChange={e=>setIssued(e.target.value)} className="field" title="تاریخ صدور"/><input type="date" value={effective} onChange={e=>setEffective(e.target.value)} className="field" title="تاریخ اجرا"/><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="موضوع" className="field md:col-span-2"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="لینک منبع رسمی (اختیاری)" className="field md:col-span-2"/></div><div className="mt-3 border border-dashed app-border rounded-xl p-4"><input ref={ref} type="file" accept="application/pdf,image/*,.txt,.md" onChange={e=>setFile(e.target.files?.[0]||null)} className="hidden"/><button onClick={()=>ref.current?.click()} className="w-full py-5 rounded-xl bg-[var(--surface-2)]"><Upload size={20} className="inline ml-2"/>{file?file.name:'PDF یا تصویر منبع را انتخاب کنید'}</button></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="یا متن بخشنامه/قانون را مستقیماً اینجا وارد کنید..." className="field w-full min-h-[150px] mt-3"/><button disabled={busy} onClick={save} className="w-full mt-3 py-3 rounded-xl bg-[var(--primary)] text-white font-bold disabled:opacity-50">{busy?<><Loader2 size={17} className="inline ml-2 animate-spin"/>در حال استخراج و ثبت...</>:<>ثبت در مرکز دانش</>}</button></section></div>
 <section className="mt-5 rounded-2xl border app-border bg-[var(--surface)] p-5"><div className="flex items-center gap-2 mb-3"><MessageCircle size={19}/><div><h2 className="font-bold">پرسش از منابع گمرکی</h2><p className="text-[10px] app-muted">پاسخ فقط بر اساس منابع فعال ثبت‌شده در این مرکز</p></div></div><div className="flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="مثلاً برای این نوع ترانزیت چه مدارکی طبق بخشنامه لازم است؟" className="field flex-1"/><button disabled={chatBusy} onClick={ask} className="px-5 rounded-xl bg-[var(--primary)] text-white font-bold">{chatBusy?<Loader2 className="animate-spin"/>:'پرسش'}</button></div>{answer&&<div className="mt-4 p-4 rounded-xl bg-[var(--surface-2)] whitespace-pre-wrap text-sm leading-7">{answer}</div>}</section></div></main>};