import React,{useEffect,useMemo,useState} from 'react';
import {Activity,Anchor,ArrowLeft,ArrowUpLeft,BarChart3,Building2,Calculator,CheckCircle2,ChevronLeft,FileCheck2,FileText,History,LayoutDashboard,Plus,RefreshCw,ShieldCheck,Ship,Truck,Wallet,AlertTriangle} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
const labels:Record<string,string>={draft:'پیش‌نویس',registration_order:'ثبت سفارش',documents_ready:'اسناد آماده',epl_submitted:'اظهار ثبت شد',kottaj_received:'کوتاژ دریافت شد',path_green:'مسیر سبز',path_yellow:'مسیر زرد',path_red:'مسیر قرمز',valuation:'ارزش‌گذاری',duties_calculation:'محاسبه حقوق',exit_permit:'مجوز خروج',completed:'تکمیل‌شده',archived:'بایگانی'};
const shipmentLabels:Record<string,string>={Draft:'پیش‌نویس','Booking Confirmed':'تأیید رزرو',Loading:'بارگیری',Loaded:'بارگیری کامل',Departed:'حرکت کرده','In Transit':'در مسیر','Approaching Destination':'نزدیک مقصد',Anchorage:'لنگرگاه',Berthing:'در اسکله',Discharging:'تخلیه',Discharged:'تخلیه کامل',Completed:'تکمیل‌شده',Delayed:'تأخیر',Cancelled:'لغو'};
const money=(n:number)=>new Intl.NumberFormat('fa-IR').format(Math.round(n));
const statusTone=(s:string)=>s.includes('red')||s==='Delayed'?'danger':s.includes('yellow')?'warning':s.includes('green')||s==='Completed'||s==='Discharged'?'success':'neutral';
export const MainMenuPage:React.FC=()=>{
 const[cases,setCases]=useState<any[]>([]),[shipments,setShipments]=useState<any[]>([]),[permits,setPermits]=useState<any[]>([]),[exits,setExits]=useState<any[]>([]),[finance,setFinance]=useState<any[]>([]),[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);try{const[{data:c},{data:s},{data:p},{data:e},{data:f}]=await Promise.all([supabase.from('cases').select('id,case_number,status,created_at').order('created_at',{ascending:false}),supabase.from('shipments').select('id,bill_of_lading_no,current_status,current_location,eta_destination').order('created_at',{ascending:false}),supabase.from('permits').select('id,case_id,permit_type,status,expires_at').order('created_at',{ascending:false}),supabase.from('case_exit_operations').select('id,case_id,exit_status,exit_permit_no,exit_at,vehicle_plate').order('updated_at',{ascending:false}),supabase.from('financial_transactions').select('id,case_id,transaction_type,base_amount_irr').order('transaction_date',{ascending:false})]);setCases(c||[]);setShipments(s||[]);setPermits(p||[]);setExits(e||[]);setFinance(f||[])}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);const openCases=cases.filter(x=>!['completed','archived'].includes(x.status));const pendingPermits=permits.filter(x=>x.status==='pending');const pendingExits=exits.filter(x=>!['exited','cancelled'].includes(x.exit_status));const financeTotal=useMemo(()=>finance.reduce((n,x)=>n+(Number(x.base_amount_irr)||0)*(x.transaction_type==='expense'||x.transaction_type==='withdrawal'?-1:1),0),[finance]);const stageCounts=useMemo(()=>openCases.reduce((a,c)=>(a[c.status]=(a[c.status]||0)+1,a),{} as Record<string,number>),[openCases]);
 return <main className="min-h-screen p-4 sm:p-6 lg:p-8" dir="rtl"><div className="max-w-[1720px] mx-auto">
  <header className="flex flex-col xl:flex-row xl:items-end xl:justify-between gap-5 mb-6"><div><div className="text-xs app-muted mb-2">داشبورد عملیاتی · Operations Dashboard</div><div className="flex items-center gap-3"><span className="app-brand-mark"><Ship size={23}/></span><div><h1 className="text-2xl sm:text-3xl font-black tracking-tight">مرکز مدیریت Customs OS</h1><p className="text-sm app-muted mt-1">نمای سریع عملیات، پرونده‌های فعال، حمل، مجوز، مالی و خروج کالا.</p></div></div></div><div className="flex flex-wrap gap-2"><Link to="/operations" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white px-4 py-2.5 text-sm font-bold"><Plus size={16}/> پرونده جدید</Link><Link to="/maritime" className="inline-flex items-center gap-2 rounded-xl border app-border bg-[var(--surface)] px-4 py-2.5 text-sm font-bold"><Anchor size={16}/> محموله</Link><button onClick={load} className="icon-btn" title="بروزرسانی"><RefreshCw size={17} className={loading?'animate-spin':''}/></button></div></header>
  <section className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-6"><Kpi icon={FileCheck2} title="پرونده باز" value={openCases.length} href="/operations"/><Kpi icon={Anchor} title="محموله" value={shipments.length} href="/maritime"/><Kpi icon={ShieldCheck} title="مجوز در انتظار" value={pendingPermits.length} href="/operations?tab=documents" alert={pendingPermits.length>0}/><Kpi icon={Truck} title="خروج باز" value={pendingExits.length} href="/exit" alert={pendingExits.length>0}/><Kpi icon={Wallet} title="خالص مالی IRR" value={money(financeTotal)}/></section>
  <section className="grid xl:grid-cols-[1.65fr_1fr] gap-5 mb-5"><Panel title="پرونده‌های فعال" subtitle="آخرین پرونده‌ها و مرحله جاری" icon={Activity} action="مشاهده همه" to="/operations"><div className="space-y-2">{openCases.slice(0,8).map(c=><div key={c.id} className="flex items-center gap-3 p-3 rounded-xl bg-[var(--surface-2)] border app-border"><div className="h-9 w-9 rounded-lg grid place-items-center bg-blue-500/10 text-blue-500"><FileCheck2 size={17}/></div><div className="min-w-0 flex-1"><div className="font-bold text-sm truncate">{c.case_number||`پرونده ${c.id.slice(0,8)}`}</div><div className="text-xs app-muted mt-1">{labels[c.status]||c.status}</div></div><span className={`status-pill ${statusTone(c.status)}`}>{labels[c.status]||c.status}</span><Link to={`/operations?caseId=${encodeURIComponent(c.id)}`} className="icon-btn !w-9 !h-9"><ChevronLeft size={16}/></Link></div>)}{openCases.length===0&&<Empty icon={CheckCircle2} text="پرونده فعال وجود ندارد." action="ایجاد پرونده" to="/operations"/>}</div></Panel><Panel title="توزیع مراحل" subtitle="وضعیت چرخه پرونده‌های باز" icon={BarChart3}><div className="space-y-3">{Object.entries(stageCounts).slice(0,7).map(([stage,count])=><div key={stage}><div className="flex justify-between text-xs mb-1"><span>{labels[stage]||stage}</span><b>{count}</b></div><div className="h-2 rounded-full bg-[var(--surface-3)] overflow-hidden"><div className="h-full rounded-full bg-[var(--primary)]" style={{width:`${Math.min(100,(Number(count)/Math.max(openCases.length,1))*100)}%`}}/></div></div>)}{openCases.length===0&&<p className="text-sm app-muted">پس از ایجاد پرونده، توزیع مراحل اینجا نمایش داده می‌شود.</p>}</div></Panel></section>
  <section className="grid lg:grid-cols-3 gap-5 mb-5"><Panel title="کشتیرانی و محموله" subtitle="آخرین وضعیت حمل" icon={Anchor} action="مدیریت حمل" to="/maritime"><div className="space-y-2">{shipments.slice(0,5).map(s=><div key={s.id} className="p-3 rounded-xl bg-[var(--surface-2)] border app-border"><div className="flex items-center justify-between gap-2"><b className="text-sm">{s.bill_of_lading_no||'Draft B/L'}</b><span className={`status-pill ${statusTone(s.current_status)}`}>{shipmentLabels[s.current_status]||s.current_status}</span></div><div className="text-xs app-muted mt-2">{s.current_location||'موقعیت ثبت نشده'}{s.eta_destination?` · ETA ${new Date(s.eta_destination).toLocaleDateString('fa-IR')}`:''}</div></div>)}{shipments.length===0&&<Empty icon={Anchor} text="محموله‌ای ثبت نشده." action="ثبت اطلاعات حمل" to="/maritime"/>}</div></Panel><Panel title="هشدارهای عملیاتی" subtitle="موارد نیازمند پیگیری" icon={AlertTriangle}><div className="space-y-2"><AlertRow label="مجوزهای در انتظار" value={pendingPermits.length} to="/operations?tab=documents"/><AlertRow label="خروج‌های نهایی‌نشده" value={pendingExits.length} to="/exit"/><AlertRow label="پرونده‌های فعال" value={openCases.length} to="/operations"/><AlertRow label="موجودی خالص ledger" value={`${money(financeTotal)} IRR`}/></div></Panel><Panel title="دسترسی سریع" subtitle="مسیرهای پرتکرار" icon={LayoutDashboard}><div className="grid grid-cols-2 gap-2"><Quick to="/operations" icon={FileCheck2} text="عملیات پرونده"/><Quick to="/maritime" icon={Anchor} text="کشتیرانی"/><Quick to="/clients" icon={Building2} text="صاحب کالا"/><Quick to="/operations?tab=registration" icon={FileText} text="ثبت سفارش"/><Quick to="/operations?tab=valuation" icon={Calculator} text="ارزش‌گذاری"/><Quick to="/finance" icon={Wallet} text="مالی"/><Quick to="/exit" icon={Truck} text="خروج کالا"/><Quick to="/history" icon={History} text="تاریخچه"/></div></Panel></section>
  <section className="rounded-2xl border app-border bg-[var(--surface)] p-4 sm:p-5"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><div className="font-black">ماژول‌های سامانه</div><div className="text-xs app-muted mt-1">تمام مسیرهای عملیاتی از منوی کناری نیز در دسترس هستند.</div></div><Link to="/control" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--primary)]">مرکز کنترل کامل <ArrowLeft size={15}/></Link></div><div className="mt-4 flex flex-wrap gap-2"><Module to="/control" text="مرکز کنترل"/><Module to="/operations" text="عملیات پرونده"/><Module to="/maritime" text="کشتیرانی"/><Module to="/permit-rules" text="قواعد مجوز"/><Module to="/finance" text="مالی"/><Module to="/exit" text="خروج"/><Module to="/stage" text="مراحل"/><Module to="/print-declaration" text="چاپ اظهار"/></div></section>
 </div></main>;
const Kpi=({icon:Icon,title,value,href,alert}:{icon:any;title:string;value:any;href?:string;alert?:boolean})=>{const body=<div className={`rounded-2xl border app-border bg-[var(--surface)] p-4 min-h-[112px] ${href?'hover:-translate-y-0.5 transition':''}`}><div className="flex items-center justify-between"><span className="h-9 w-9 rounded-xl bg-blue-500/10 text-blue-500 grid place-items-center"><Icon size={18}/></span>{alert&&<span className="h-2 w-2 rounded-full bg-amber-500"/>}</div><div className="text-xs app-muted mt-3">{title}</div><div className="text-xl font-black mt-1 truncate" title={String(value)}>{value}</div></div>;return href?<Link to={href}>{body}</Link>:body};
const Panel=({title,subtitle,icon:Icon,action,to,children}:{title:string;subtitle:string;icon:any;action?:string;to?:string;children:React.ReactNode})=><section className="rounded-2xl border app-border bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-start justify-between gap-3 mb-4"><div className="flex items-center gap-3"><span className="h-9 w-9 rounded-xl bg-[var(--surface-2)] grid place-items-center text-[var(--primary)]"><Icon size={18}/></span><div><h2 className="font-black">{title}</h2><p className="text-xs app-muted mt-1">{subtitle}</p></div></div>{to&&<Link to={to} className="text-xs font-bold text-[var(--primary)] whitespace-nowrap">{action||'مشاهده'} <ArrowLeft className="inline mr-1" size={13}/></Link>}</div>{children}</section>;
const Quick=({to,icon:Icon,text}:{to:string;icon:any;text:string})=><Link to={to} className="flex items-center gap-2 rounded-xl border app-border bg-[var(--surface-2)] p-3 text-xs font-bold hover:border-[var(--primary)] transition"><Icon size={16} className="text-[var(--primary)]"/>{text}</Link>;
const Module=({to,text}:{to:string;text:string})=><Link to={to} className="rounded-full border app-border bg-[var(--surface-2)] px-3 py-2 text-xs font-semibold hover:border-[var(--primary)] transition">{text}</Link>;
const AlertRow=({label,value,to}:{label:string;value:any;to?:string})=><div className="flex items-center justify-between gap-3 p-3 rounded-xl bg-[var(--surface-2)] border app-border"><span className="text-sm">{label}</span>{to?<Link to={to} className="font-black text-[var(--primary)]">{value}</Link>:<span className="font-black">{value}</span>}</div>;
const Empty=({icon:Icon,text,action,to}:{icon:any;text:string;action:string;to:string})=><div className="py-7 text-center"><Icon size={28} className="mx-auto app-muted"/><p className="text-sm app-muted mt-2">{text}</p><Link to={to} className="inline-flex items-center gap-1 mt-3 text-xs font-bold text-[var(--primary)]">{action}<ArrowUpLeft size={13}/></Link></div>;
