import React,{useCallback,useEffect,useState} from "react";
import {ArrowLeft,RefreshCw,Send,Plug,UploadCloud,CheckCircle2,ShieldAlert} from "lucide-react";
import {useNavigate} from "react-router-dom";
import {supabase} from "../lib/supabase";
type Conn={id:string;platform:string;display_name:string;external_account_id:string;enabled:boolean};
type Chat={id:string;connection_id:string;external_chat_id:string;display_name:string|null;purpose:string;enabled:boolean};
const names:Record<string,string>={telegram:"تلگرام",bale:"بله",rubika:"روبیکا",whatsapp:"واتساپ"};
const field="w-full rounded-xl border app-border bg-[var(--surface-2)] px-3 py-2.5 text-sm outline-none focus:border-[var(--primary)]";
export const MessengerIntegrationsPage:React.FC=()=>{
 const nav=useNavigate(),[connections,setConnections]=useState<Conn[]>([]),[chats,setChats]=useState<Chat[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState(""),[verifyToken,setVerifyToken]=useState("");
 const [platform,setPlatform]=useState("telegram"),[displayName,setDisplayName]=useState(""),[accessToken,setAccessToken]=useState(""),[phoneNumberId,setPhoneNumberId]=useState(""),[appSecret,setAppSecret]=useState(""),[webhookSecret,setWebhookSecret]=useState("");
 const [connectionId,setConnectionId]=useState(""),[externalChatId,setExternalChatId]=useState(""),[chatName,setChatName]=useState(""),[purpose,setPurpose]=useState("inbox"),[chatSelection,setChatSelection]=useState(""),[message,setMessage]=useState(""),[file,setFile]=useState<File|null>(null),[lastAssetId,setLastAssetId]=useState("");
 const api=useCallback(async(path:string,init:RequestInit={})=>{const {data}=await supabase.auth.getSession();const jwt=data.session?.access_token;if(!jwt)throw new Error("نشست معتبر نیست؛ دوباره وارد شوید.");const headers=new Headers(init.headers);headers.set("Authorization","Bearer "+jwt);headers.set("apikey",(import.meta as any).env.VITE_SUPABASE_ANON_KEY||"");if(typeof init.body==="string"&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");const res=await fetch(path,{...init,headers,cache:"no-store"});const ct=res.headers.get("content-type")||"",d=ct.includes("application/json")?await res.json():await res.text();if(!res.ok||d?.ok===false)throw new Error(d?.error||"درخواست ناموفق بود.");return d;},[]);
 const refresh=useCallback(async()=>{setBusy(true);try{const [a,b]=await Promise.all([api("/api/messenger/connections"),api("/api/messenger/chats")]);setConnections(a.connections||[]);setChats(b.chats||[]);if(!connectionId&&a.connections?.[0])setConnectionId(a.connections[0].id);}catch(e){setError(e instanceof Error?e.message:"دریافت اطلاعات ناموفق بود");}finally{setBusy(false);}},[api,connectionId]);
 useEffect(()=>{void refresh();},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const d=await api("/api/messenger/connections",{method:"POST",body:JSON.stringify({platform,displayName,accessToken,phoneNumberId,appSecret,webhookSecret})});setNotice((d.note||"اتصال ایجاد شد.")+(d.webhookUrl?" آدرس وب‌هوک: "+d.webhookUrl:""));if(d.verifyToken){setVerifyToken(d.verifyToken);setNotice("Callback URL: "+(d.webhookUrl||"")+". توکن تأیید را همین حالا در Meta وارد کنید.");}setAccessToken("");setAppSecret("");setWebhookSecret("");await refresh();if(d.connection?.id)setConnectionId(d.connection.id);}catch(e){setError(e instanceof Error?e.message:"ایجاد اتصال ناموفق بود");}finally{setBusy(false);}};
 const saveChat=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api("/api/messenger/chats",{method:"POST",body:JSON.stringify({connectionId,externalChatId,displayName:chatName,chatType:"unknown",purpose})});setNotice("مقصد مجاز ثبت شد.");setExternalChatId("");setChatName("");await refresh();}catch(e){setError(e instanceof Error?e.message:"ثبت مقصد ناموفق بود");}finally{setBusy(false);}};
 const activeChat=chats.find(c=>c.id===chatSelection);
 const send=async(e:React.FormEvent)=>{e.preventDefault();if(!activeChat)return;setBusy(true);setError("");try{await api("/api/messenger/messages",{method:"POST",body:JSON.stringify({connectionId:activeChat.connection_id,chatId:activeChat.external_chat_id,text:message})});setMessage("");setNotice("پیام ارسال شد.");}catch(e){setError(e instanceof Error?e.message:"ارسال پیام ناموفق بود");}finally{setBusy(false);}};
 const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!file||!activeChat)return;setBusy(true);setError("");try{const d=await api("/api/messenger/uploads/"+activeChat.connection_id+"?chatId="+encodeURIComponent(activeChat.external_chat_id),{method:"POST",headers:{"Content-Type":file.type||"application/octet-stream","X-File-Name":encodeURIComponent(file.name),"X-File-Size":String(file.size)},body:file});setLastAssetId(d.fileAssetId||"");setNotice("فایل استریم و ارسال شد؛ محتوای باینری در سامانه نگهداری نشد.");setFile(null);}catch(e){setError(e instanceof Error?e.message:"ارسال فایل ناموفق بود");}finally{setBusy(false);}};
 const transfer=async()=>{const dest=prompt("شناسهٔ اتصال مقصد را وارد کنید"),chat=prompt("شناسهٔ چت مقصد را وارد کنید");if(!dest||!chat||!lastAssetId)return;setBusy(true);try{await api("/api/messenger/transfers",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({fileAssetId:lastAssetId,destinationConnectionId:dest,destinationChatId:chat})});setNotice("انتقال فایل انجام شد.");}catch(e){setError(e instanceof Error?e.message:"انتقال ناموفق بود");}finally{setBusy(false);}};
 return <main dir="rtl" className="mx-auto w-full max-w-6xl space-y-5 p-4 md:p-6">
 <header className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button type="button" onClick={()=>nav("/settings")} className="rounded-xl border app-border p-2"><ArrowLeft size={18}/></button><div><h1 className="text-xl font-black">اتصال پیام‌رسان‌ها</h1><p className="mt-1 text-xs app-muted">اتصال، مقصدهای مجاز، ارسال و انتقال فایل</p></div></div><button type="button" onClick={()=>void refresh()} disabled={busy} className="flex items-center gap-2 rounded-xl border app-border px-3 py-2 text-sm"><RefreshCw size={16}/> تازه‌سازی</button></header>
 {notice&&<div role="status" className="rounded-xl border border-emerald-500/30 p-3 text-sm">{notice}{verifyToken&&<p className="mt-2 break-all font-mono">Verify Token: {verifyToken}<button className="mr-2 underline" onClick={()=>void navigator.clipboard.writeText(verifyToken)}>کپی</button></p>}</div>}{error&&<div role="alert" className="rounded-xl border border-red-500/30 p-3 text-sm text-red-500">{error}</div>}
 <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border app-border bg-[var(--surface)] p-4"><h2 className="flex items-center gap-2 font-bold"><Plug size={18}/> افزودن اتصال</h2><form onSubmit={create} className="mt-4 space-y-3">
 <label className="block text-xs font-bold">پیام‌رسان<select className={field+" mt-1"} value={platform} onChange={e=>setPlatform(e.target.value)}><option value="telegram">تلگرام</option><option value="bale">بله</option><option value="whatsapp">واتساپ تجاری</option><option value="rubika" disabled>روبیکا (API عمومی تأیید نشده)</option></select></label>
 <label className="block text-xs font-bold">نام اتصال<input className={field+" mt-1"} value={displayName} onChange={e=>setDisplayName(e.target.value)} required minLength={2}/></label><label className="block text-xs font-bold">توکن دسترسی<input className={field+" mt-1"} type="password" autoComplete="off" value={accessToken} onChange={e=>setAccessToken(e.target.value)} required/></label>
 {platform==="whatsapp"&&<><label className="block text-xs font-bold">Phone Number ID<input className={field+" mt-1"} value={phoneNumberId} onChange={e=>setPhoneNumberId(e.target.value)} required/></label><label className="block text-xs font-bold">Meta App Secret<input className={field+" mt-1"} type="password" autoComplete="off" value={appSecret} onChange={e=>setAppSecret(e.target.value)} required/></label></>}
 {platform!=="whatsapp"&&<label className="block text-xs font-bold">کلید وب‌هوک (اختیاری)<input className={field+" mt-1"} value={webhookSecret} onChange={e=>setWebhookSecret(e.target.value)} autoComplete="off" placeholder="خالی بماند تا تولید شود"/></label>}
 <button disabled={busy||platform==="rubika"} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary)] px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><CheckCircle2 size={17}/> اعتبارسنجی و ثبت</button><p className="text-xs app-muted">توکن در مرورگر ذخیره نمی‌شود و در Supabase Vault رمزنگاری می‌شود.</p></form></section>
 <section className="rounded-2xl border app-border bg-[var(--surface)] p-4"><h2 className="font-bold">اتصال‌های ثبت‌شده</h2><div className="mt-3 space-y-2">{connections.length===0&&<p className="text-sm app-muted">اتصالی ثبت نشده است.</p>}{connections.map(c=><div key={c.id} className="rounded-xl border app-border p-3"><div className="flex items-center justify-between gap-2"><div><b>{names[c.platform]||c.platform} · {c.display_name}</b><div className="mt-1 break-all text-xs app-muted">{c.external_account_id}</div></div><span className={c.enabled?"text-xs text-emerald-500":"text-xs text-amber-500"}>{c.enabled?"فعال":"غیرفعال"}</span></div><div className="mt-2 flex gap-2"><button onClick={async()=>{try{const d=await api("/api/messenger/connections/"+c.id+"/test",{method:"POST"});setNotice("اتصال سالم است: "+(d.account?.username||d.account?.displayPhoneNumber||d.account?.id||"تأیید شد"));setError("");}catch(e){setError(e instanceof Error?e.message:"آزمایش اتصال ناموفق بود");}}} className="rounded-lg border app-border px-3 py-1.5 text-xs">آزمایش</button>{c.platform!=="whatsapp"&&<button onClick={async()=>{try{const d=await api("/api/messenger/connections/"+c.id+"/register-webhook",{method:"POST"});setNotice("وب‌هوک ثبت شد: "+d.webhookUrl);setError("");}catch(e){setError(e instanceof Error?e.message:"ثبت وب‌هوک ناموفق بود");}}} className="rounded-lg border app-border px-3 py-1.5 text-xs">ثبت وب‌هوک</button>}</div></div>)}</div></section></div>
 <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border app-border bg-[var(--surface)] p-4"><h2 className="font-bold">ثبت مقصد مجاز</h2><form onSubmit={saveChat} className="mt-3 space-y-3"><label className="block text-xs font-bold">اتصال<select className={field+" mt-1"} value={connectionId} onChange={e=>setConnectionId(e.target.value)} required><option value="">انتخاب اتصال</option>{connections.map(c=><option key={c.id} value={c.id}>{names[c.platform]} · {c.display_name}</option>)}</select></label><label className="block text-xs font-bold">Chat ID یا شماره واتساپ<input className={field+" mt-1"} value={externalChatId} onChange={e=>setExternalChatId(e.target.value)} required/></label><label className="block text-xs font-bold">نام نمایشی<input className={field+" mt-1"} value={chatName} onChange={e=>setChatName(e.target.value)}/></label><label className="block text-xs font-bold">کاربرد<select className={field+" mt-1"} value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="inbox">دریافت پیام</option><option value="file_archive">آرشیو فایل</option><option value="daily_report">گزارش روزانه</option><option value="shipment_notifications">اعلان محموله</option><option value="shipment">محموله</option></select></label><button disabled={busy||!connectionId} className="w-full rounded-xl border app-border px-4 py-3 text-sm font-bold">ذخیرهٔ مقصد</button></form><div className="mt-4 space-y-2">{chats.map(c=><div key={c.id} className="rounded-lg border app-border p-2 text-xs"><b>{c.display_name||c.external_chat_id}</b><span className="mr-2 app-muted">{c.purpose}</span><div className="mt-1 break-all app-muted">{c.external_chat_id}</div></div>)}</div></section>
 <section className="space-y-4"><div className="rounded-2xl border app-border bg-[var(--surface)] p-4"><h2 className="flex items-center gap-2 font-bold"><Send size={18}/> ارسال پیام</h2><form onSubmit={send} className="mt-3 space-y-3"><label className="block text-xs font-bold">مقصد<select className={field+" mt-1"} value={chatSelection} onChange={e=>setChatSelection(e.target.value)}><option value="">انتخاب چت</option>{chats.map(c=><option key={c.id} value={c.id}>{c.display_name||c.external_chat_id} · {names[connections.find(x=>x.id===c.connection_id)?.platform||""]||""}</option>)}</select></label><textarea className={field+" min-h-24"} value={message} onChange={e=>setMessage(e.target.value)} maxLength={4000} required placeholder="متن پیام"/><button disabled={busy||!activeChat} className="w-full rounded-xl bg-[var(--primary)] px-4 py-3 text-sm font-bold text-white">ارسال پیام</button></form></div>
 <div className="rounded-2xl border app-border bg-[var(--surface)] p-4"><h2 className="flex items-center gap-2 font-bold"><UploadCloud size={18}/> ارسال / انتقال فایل</h2><form onSubmit={upload} className="mt-3 space-y-3"><label className="block text-xs font-bold">فایل<input className={field+" mt-1"} type="file" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label><p className="text-xs app-muted">فایل به چت انتخاب‌شده در بخش ارسال پیام می‌رود.</p><button disabled={busy||!file||!activeChat} className="w-full rounded-xl border app-border px-4 py-3 text-sm font-bold">استریم و ارسال</button></form>{lastAssetId&&<div className="mt-3 space-y-2 text-xs"><p className="break-all">شناسهٔ فایل: {lastAssetId}</p><button disabled={busy} onClick={()=>void transfer()} className="rounded-lg border app-border px-3 py-2">انتقال به پیام‌رسان دیگر</button></div>}</div></section></div>
 <div className="flex gap-2 rounded-xl border border-amber-500/30 p-3 text-xs app-muted"><ShieldAlert size={18} className="shrink-0 text-amber-500"/><p>روبیکا تا زمان تأیید API عمومی و مجاز فعال نمی‌شود. واتساپ نیازمند تنظیم callback در Meta Developer است. گزارش روزانه و استخراج سند هنوز به پردازش زمان‌بندی‌شده وصل نشده‌اند.</p></div></main>;
};