import React,{useMemo,useRef,useState} from 'react';
import {ArrowRight,Check,Copy,FileText,Loader2,Printer,RotateCcw,Save,Trash2,Upload,Sparkles} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';

type V=Record<string,string>;
const KEY='customs_os_single_pre_declaration';
const fields:[string,string][]=[
 ['vesselType','نوع کشتی'],['regNumber','شماره ثبت سفارش'],['regDate','تاریخ ثبت سفارش'],['packageCount','تعداد'],['warehouseReceiptNo','شماره قبض انبار'],['warehouseReceiptDate','تاریخ قبض انبار'],['cargoDescription','شرح کالا'],['originCountry','کشور مبدا'],['transactionCountry','کشور طرف معامله'],['deliveryTerm','شرایط تحویل'],['invoiceAmount','مبلغ کل فاکتور'],['invoiceCurrency','ارز'],['bankBranchCode','کد شعبه'],['bankName','نام بانک'],['bankBranch','شعبه'],['lcNumber','شماره اعتبار اسنادی'],['dutyRate','ماخذ حقوق ورودی'],['tariffCode','کد تعرفه کالا'],['netWeight','وزن خالص'],['grossWeight','وزن ناخالص'],['billOfLading','بارنامه'],['insuranceIrr','بیمه (ریال)']
];
const blank:V=Object.fromEntries(fields.map(([k])=>[k,'xxxx']));
const toBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||'');resolve(s.includes(',')?s.split(',')[1]:s)};r.onerror=()=>reject(new Error('خواندن فایل ناموفق بود'));r.readAsDataURL(file)});
const normalize=(x:any)=>String(x??'').trim()||'xxxx';
const nav=(tab:string)=>`/operations?tab=${tab}`;

export const PreDeclarationPage:React.FC=()=>{
 const[files,setFiles]=useState<File[]>([]);const[values,setValues]=useState<V>({...blank});const[needed,setNeeded]=useState('ندارد');const[busy,setBusy]=useState(false);const[registered,setRegistered]=useState(false);const[status,setStatus]=useState('');const[copied,setCopied]=useState(false);const inputRef=useRef<HTMLInputElement|null>(null);
 const addFiles=(list:FileList|null)=>{if(!list)return;setFiles(p=>[...p,...Array.from(list).filter(f=>/application\/pdf|image\//i.test(f.type)&&!p.some(x=>x.name===f.name&&x.size===f.size))])};
 const removeFile=(i:number)=>setFiles(p=>p.filter((_,j)=>j!==i));
 const set=(k:string,v:string)=>{setRegistered(false);setValues(p=>({...p,[k]:v}))};
 const runAI=async()=>{if(!files.length){setStatus('ابتدا حداقل یک سند را آپلود کنید.');return}setBusy(true);setRegistered(false);setStatus('در حال بررسی همه اسناد به صورت یکجا...');try{
   const documents=[] as any[];for(const file of files)documents.push({name:file.name,mime_type:file.type||'application/pdf',data:await toBase64(file)});
   const{data,error}=await supabase.functions.invoke('ai-assistant',{body:{query:'استخراج ورود اطلاعات قبل اظهار',documents,extract_fields:true,page_context:'/operations?tab=pre-declaration'}});if(error)throw error;
   const raw=data?.answer||data?.message||{};let parsed:any={};if(typeof raw==='object')parsed=raw;else{try{parsed=JSON.parse(raw)}catch{const m=String(raw).match(/\{[\s\S]*\}/);if(m)parsed=JSON.parse(m[0])}}
   const next:V={...blank};for(const[key]of fields)next[key]=normalize(parsed[key]);setValues(next);setNeeded(normalize(parsed.requiredDocuments||'ندارد'));setStatus('استخراج تمام شد. همه فیلدها باید مقدار داشته باشند؛ موارد ناموجود با xxxx مشخص شده‌اند. قبل از ثبت کنترل کنید.');
 }catch(e:any){setStatus(e?.message||'استخراج اطلاعات ناموفق بود.')}finally{setBusy(false)}};
 const output=useMemo(()=>{const v=(k:string)=>normalize(values[k]);return `نوع کشتی: ${v('vesselType')}\n\nشماره ثبت سفارش: ${v('regNumber')}\nتاریخ ثبت سفارش: ${v('regDate')}\n\nتعداد: ${v('packageCount')}\nشماره قبض انبار: ${v('warehouseReceiptNo')}\nتاریخ قبض انبار: ${v('warehouseReceiptDate')}\n\nشرح کالا: ${v('cargoDescription')}\n\n•••••••••••••••••••••••••\nکشور مبدا: ${v('originCountry')}\nکشور طرف معامله: ${v('transactionCountry')}\nشرایط تحویل: ${v('deliveryTerm')}\nمبلغ کل فاکتور: ${v('invoiceAmount')}\nارز: ${v('invoiceCurrency')}\n\n•••••••••••••••••••••••••\nاطلاعات بانکی:\nکد شعبه: ${v('bankBranchCode')}\nنام بانک: ${v('bankName')}\nشعبه: ${v('bankBranch')}\nشماره اعتبار اسنادی: ${v('lcNumber')}\n\n•••••••••••••••••••••••\nماخذ حقوق ورودی: ${v('dutyRate')}\nکد تعرفه کالا: ${v('tariffCode')}\nوزن: ${v('netWeight')}/${v('grossWeight')} کیلوگرم\n\nبارنامه:\n${v('billOfLading')}\n\n•••••••••••••••••••••••\nبیمه (ریال): ${v('insuranceIrr')}\n•••••••••••••••••••••••••\n\nاطلاعات مورد نیاز: ${normalize(needed||'ندارد')}`},[values,needed]);
 const register=()=>{try{localStorage.setItem(KEY,JSON.stringify({...values,requiredDocuments:needed,registeredAt:new Date().toISOString()}));setRegistered(true);setStatus('اطلاعات گمرکی ثبت شد. این تنها محل ثبت اطلاعات قبل اظهار است.')}catch{setStatus('ثبت اطلاعات ناموفق بود.')}};
 const reset=()=>{setValues({...blank});setNeeded('ندارد');setRegistered(false);setFiles([]);setStatus('')};
 const copy=async()=>{try{await navigator.clipboard.writeText(output);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setStatus('کپی متن در این مرورگر انجام نشد.')}};
 const print=()=>window.print();
 return <main dir="rtl" className="min-h-screen bg-slate-950 text-slate-100 p-4 sm:p-6 lg:p-8"><div className="max-w-6xl mx-auto space-y-5">
  <style>{`@media print{body *{visibility:hidden!important}.customs-print,.customs-print *{visibility:visible!important}.customs-print{position:absolute;left:0;top:0;width:100%;background:#fff!important;color:#000!important;padding:24px!important}.customs-print pre{white-space:pre-wrap;font-family:Tahoma,Arial,sans-serif;font-size:13pt;line-height:2;background:#fff!important;color:#000!important}}`}</style>
  <header className="flex flex-col md:flex-row md:items-center justify-between gap-3 no-print"><div><div className="text-xs text-slate-500">CUSTOMS / OPERATIONS</div><h1 className="text-2xl font-black mt-1">عملیات گمرکی</h1></div><Link to="/" className="px-4 py-2 rounded-xl border border-slate-700 bg-slate-900 text-sm"><ArrowRight className="inline ml-1" size={16}/> صفحه اصلی</Link></header>
  <nav className="grid grid-cols-1 md:grid-cols-3 gap-2 no-print"><Link to={nav('pre-declaration')} className="rounded-xl px-4 py-3 text-center font-bold bg-blue-600">۱. ورود اطلاعات قبل اظهار</Link><Link to={nav('declaration')} className="rounded-xl px-4 py-3 text-center font-bold bg-slate-900 border border-slate-700">۲. اظهار / EPL</Link><Link to={nav('exit')} className="rounded-xl px-4 py-3 text-center font-bold bg-slate-900 border border-slate-700">۳. صدور پروانه / درب خروج</Link></nav>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5 no-print"><div className="flex items-center justify-between"><div><h2 className="font-bold text-lg">آپلود اسناد برای استخراج خودکار</h2><p className="text-xs text-slate-500 mt-1">یک یا چند سند را با هم ارسال کنید؛ هوش مصنوعی همه اسناد را یکجا تطبیق می‌دهد.</p></div><FileText size={21}/></div><input ref={inputRef} type="file" multiple accept="application/pdf,image/*" className="hidden" onChange={e=>addFiles(e.target.files)}/><button type="button" onClick={()=>inputRef.current?.click()} className="mt-4 w-full min-h-28 rounded-xl border-2 border-dashed border-slate-700 bg-slate-950 flex flex-col items-center justify-center gap-2"><Upload size={24}/><span>انتخاب اسناد</span><span className="text-xs text-slate-500">PDF / تصویر</span></button>{files.length>0&&<div className="mt-3 space-y-2">{files.map((f,i)=><div key={`${f.name}-${i}`} className="flex items-center justify-between rounded-lg bg-slate-950 border border-slate-800 px-3 py-2 text-sm"><span className="truncate">{f.name}</span><button onClick={()=>removeFile(i)} className="text-red-400 p-1"><Trash2 size={16}/></button></div>)}</div>}<button disabled={busy||!files.length} onClick={runAI} className="mt-4 w-full rounded-xl bg-blue-600 disabled:opacity-50 py-3 font-bold flex items-center justify-center gap-2">{busy?<><Loader2 className="animate-spin" size={18}/>در حال بررسی همه اسناد...</>:<><Sparkles size={18}/>بررسی کن و اطلاعات را استخراج کن</>}</button>{status&&<div className="mt-3 text-sm text-slate-300">{status}</div>}</section>
  <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5 no-print"><h2 className="font-bold text-lg mb-4">اطلاعات قبل اظهار — تنها محل ثبت اطلاعات گمرکی</h2><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{fields.map(([key,label])=><label key={key} className="block"><span className="block text-sm text-slate-300 mb-1">{label}</span><input value={values[key]||'xxxx'} onChange={e=>set(key,e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 outline-none focus:border-blue-500" /></label>)}<label className="block md:col-span-2 lg:col-span-3"><span className="block text-sm text-slate-300 mb-1">اطلاعات مورد نیاز</span><input value={needed} onChange={e=>{setRegistered(false);setNeeded(e.target.value)}} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5" /></label></div><div className="flex flex-wrap items-center justify-between gap-3 mt-5 pt-4 border-t border-slate-800"><button onClick={reset} className="px-4 py-2.5 rounded-xl border border-slate-700"><RotateCcw className="inline ml-1" size={16}/> پاک کردن</button><button onClick={register} className="px-6 py-3 rounded-xl bg-emerald-600 font-bold"><Save className="inline ml-1" size={17}/> ثبت اطلاعات</button></div></section>
  {registered&&<section className="no-print rounded-2xl border border-emerald-700 bg-emerald-950/30 p-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-emerald-300"><Check size={19}/> اطلاعات با موفقیت ثبت شد</div><div className="flex gap-2"><button onClick={print} className="px-4 py-2.5 rounded-xl bg-slate-800"><Printer className="inline ml-1" size={16}/> پرینت</button><button onClick={copy} className="px-4 py-2.5 rounded-xl bg-slate-800"><Copy className="inline ml-1" size={16}/> {copied?'کپی شد':'کپی متن'}</button></div></section>}
  <section className="customs-print hidden print:block bg-white text-black rounded-2xl p-6"><pre className="whitespace-pre-wrap text-sm leading-8">{output}</pre></section>
 </div></main>;
};
export default PreDeclarationPage;
