import React,{useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {useAuth} from '../context/AuthContext';
import {useAppearance} from '../context/AppearanceContext';
import {Activity,Archive,ArrowDownToLine,ArrowRight,BarChart3,Bell,Box,Building2,Calendar,Check,ChevronDown,ChevronLeft,ChevronRight,ClipboardList,Cloud,Database,Download,FileCheck2,FileText,FlaskConical,FolderCog,Globe,HardDrive,History,KeyRound,LayoutDashboard,Lock,Map,Palette,Plug,RefreshCw,Save,Search,Server,Settings2,ShieldCheck,Ship,SlidersHorizontal,Trash2,Truck,Upload,User,UserCog,Users,Wallet,Webhook,X} from 'lucide-react';

type Role='owner'|'admin'|'broker'|'accountant'|'warehouse'|'client';
type Item={slug:string;label:string;en:string;group:string;icon:React.ComponentType<{size?:number;className?:string}>;roles?:Role[]};
type UserRow={id:string;full_name:string;phone:string|null;role:Role;is_active:boolean;created_at:string};
type AuditRow={id:string;action:string;table_name:string|null;record_id:string|null;created_at:string;user_id:string;old_data:unknown;new_data:unknown};

const roleLabel:Record<Role,string>={owner:'مالک',admin:'مدیر',broker:'کارگزار',accountant:'حسابدار',warehouse:'انبار',client:'صاحب کالا'};
const groups=[{id:'account',label:'حساب و کاربر'},{id:'org',label:'سازمان و دسترسی'},{id:'operations',label:'عملیات و ترخیص'},{id:'finance',label:'مالی و داده'},{id:'system',label:'سیستم و یکپارچه‌سازی'}];
const items:Item[]=[
 {slug:'',label:'نمای کلی تنظیمات',en:'Overview',group:'account',icon:LayoutDashboard},
 {slug:'account',label:'حساب کاربری',en:'Account',group:'account',icon:User},
 {slug:'profile',label:'پروفایل',en:'Profile',group:'account',icon:UserCog},
 {slug:'appearance',label:'ظاهر و شخصی‌سازی',en:'Appearance',group:'account',icon:Palette},
 {slug:'notifications',label:'اعلان‌ها',en:'Notifications',group:'account',icon:Bell},
 {slug:'security',label:'امنیت',en:'Security',group:'account',icon:Lock},
 {slug:'organization',label:'سازمان و شعب',en:'Organization',group:'org',icon:Building2,roles:['owner','admin']},
 {slug:'users',label:'کاربران و اعضا',en:'Users',group:'org',icon:Users,roles:['owner','admin']},
 {slug:'roles',label:'نقش‌ها و دسترسی‌ها',en:'Roles',group:'org',icon:ShieldCheck,roles:['owner','admin']},
 {slug:'customs',label:'عملیات گمرکی',en:'Customs',group:'operations',icon:FileCheck2,roles:['owner','admin','broker']},
 {slug:'clearance',label:'تنظیمات ترخیص',en:'Clearance',group:'operations',icon:ClipboardList,roles:['owner','admin','broker']},
 {slug:'transport',label:'حمل و نقل',en:'Transport',group:'operations',icon:Truck,roles:['owner','admin','broker']},
 {slug:'vessels',label:'کشتی و بار',en:'Vessels',group:'operations',icon:Ship,roles:['owner','admin','broker']},
 {slug:'warehouse',label:'انبار',en:'Warehouse',group:'operations',icon:Box,roles:['owner','admin','warehouse']},
 {slug:'documents',label:'اسناد',en:'Documents',group:'operations',icon:FileText},
 {slug:'permits',label:'مجوزها و Rules',en:'Permits',group:'operations',icon:ShieldCheck,roles:['owner','admin','broker']},
 {slug:'epl',label:'EPL و Workflow',en:'EPL',group:'operations',icon:Activity,roles:['owner','admin','broker']},
 {slug:'numbering',label:'شماره‌گذاری',en:'Numbering',group:'operations',icon:SlidersHorizontal},
 {slug:'statuses',label:'وضعیت‌ها و گردش‌کار',en:'Statuses',group:'operations',icon:ArrowRight},
 {slug:'client',label:'مشتریان',en:'Clients',group:'operations',icon:Users},
 {slug:'calendar',label:'تقویم و تاریخ',en:'Calendar',group:'finance',icon:Calendar},
 {slug:'units',label:'واحدها و اندازه‌گیری',en:'Units',group:'finance',icon:SlidersHorizontal},
 {slug:'currencies',label:'ارزها و نرخ ارز',en:'Currencies',group:'finance',icon:Wallet},
 {slug:'taxes',label:'مالیات و عوارض',en:'Taxes',group:'finance',icon:BarChart3},
 {slug:'finance',label:'تنظیمات مالی',en:'Finance',group:'finance',icon:Wallet},
 {slug:'printing',label:'چاپ و خروجی',en:'Printing',group:'finance',icon:Download},
 {slug:'templates',label:'Templateها',en:'Templates',group:'finance',icon:FolderCog},
 {slug:'integrations',label:'API و Integrations',en:'Integrations',group:'system',icon:Plug,roles:['owner','admin']},
 {slug:'webhooks',label:'Webhooks',en:'Webhooks',group:'system',icon:Webhook,roles:['owner','admin']},
 {slug:'storage',label:'Storage',en:'Storage',group:'system',icon:HardDrive,roles:['owner','admin']},
 {slug:'backup',label:'پشتیبان و Export',en:'Backup',group:'system',icon:Archive,roles:['owner','admin']},
 {slug:'audit',label:'Audit Log',en:'Audit',group:'system',icon:History,roles:['owner','admin']},
 {slug:'import-export',label:'Import / Export',en:'Data',group:'system',icon:ArrowDownToLine,roles:['owner','admin']},
 {slug:'advanced',label:'تنظیمات پیشرفته',en:'Advanced',group:'system',icon:FlaskConical,roles:['owner','admin']},
 {slug:'maintenance',label:'Maintenance',en:'Maintenance',group:'system',icon:Server,roles:['owner','admin']},
 {slug:'about',label:'درباره سیستم',en:'About',group:'system',icon:Globe}
];

const defaults={theme:'system',density:'comfortable',comfort:'normal',fontSize:'medium',animations:true,reducedMotion:false,stickyHeader:true,zebraRows:false,hoverRows:true,calendar:'jalali',timezone:'Asia/Tehran',timeFormat:'24',autoSave:false,sessionTimeout:60,numberingPrefix:'DB',numberingDigits:6,numberingYear:true,numberingMonth:false,duplicateClients:true,defaultPort:'بندر شهید رجایی',defaultCustomsOffice:'گمرک شهید رجایی',defaultWorkflow:'standard',currency:'IRR',exchangeMode:'manual',vatRate:10,documentMaxMb:25,retentionDays:3650,vesselAutoRefresh:15,quietHours:false,quietFrom:'22:00',quietTo:'07:00',casePrefix:'DB',shipmentPrefix:'SHP',documentPrefix:'DOC',transactionPrefix:'TRN',storageRetentionDays:3650};
const modules=['Dashboard','Clients','Cases','Shipments','Containers','Vessels','Customs','Declarations','Permits','Finance','Documents','Warehouse','Exit','Reports','Users','Settings','Audit'];
const actions=['View','Create','Edit','Delete','Approve','Export','Print','Manage'];
const roleDefaults:Record<Role,Record<string,boolean>>={
 owner:Object.fromEntries(modules.flatMap(m=>actions.map(a=>[`${m}:${a}`,true]))),
 admin:Object.fromEntries(modules.flatMap(m=>actions.map(a=>[`${m}:${a}`,m!=='Settings'||a!=='Manage']))),
 broker:Object.fromEntries(modules.flatMap(m=>actions.map(a=>[`${m}:${a}`,['Dashboard','Clients','Cases','Shipments','Containers','Vessels','Customs','Declarations','Permits','Documents','Exit'].includes(m)&&['View','Create','Edit','Approve','Print'].includes(a)]))),
 accountant:Object.fromEntries(modules.flatMap(m=>actions.map(a=>[`${m}:${a}`,['Dashboard','Cases','Finance','Reports'].includes(m)&&['View','Create','Edit','Export','Print'].includes(a)]))),
 warehouse:Object.fromEntries(modules.flatMap(m=>actions.map(a=>[`${m}:${a}`,['Dashboard','Cases','Shipments','Containers','Warehouse','Exit'].includes(m)&&['View','Create','Edit','Print'].includes(a)]))),
 client:Object.fromEntries(modules.flatMap(m=>actions.map(a=>[`${m}:${a}`,['Dashboard','Cases','Shipments','Documents','Finance'].includes(m)&&['View','Export','Print'].includes(a)])))
};

const Card:React.FC<{title:string;desc?:string;icon?:React.ComponentType<{size?:number}>;children:React.ReactNode}>=({title,desc,icon:Icon,children})=><section className="rounded-2xl border app-border bg-[var(--surface)] p-4 md:p-5"><div className="flex items-start gap-3 mb-5">{Icon&&<div className="h-10 w-10 rounded-xl grid place-items-center bg-[var(--surface-2)] text-[var(--primary)]"><Icon size={19}/></div>}<div><h3 className="font-bold">{title}</h3>{desc&&<p className="mt-1 text-xs app-muted">{desc}</p>}</div></div>{children}</section>;
const Input:React.FC<React.InputHTMLAttributes<HTMLInputElement>>=p=><input {...p} className={`w-full rounded-xl border app-border bg-[var(--surface-2)] text-[var(--text)] px-3 min-h-11 outline-none focus:border-[var(--primary)] ${p.className||''}`}/>;
const Select:React.FC<React.SelectHTMLAttributes<HTMLSelectElement>>=p=><select {...p} className={`w-full rounded-xl border app-border bg-[var(--surface-2)] text-[var(--text)] px-3 min-h-11 outline-none focus:border-[var(--primary)] ${p.className||''}`}/>;
const Toggle:React.FC<{checked:boolean;onChange:(v:boolean)=>void;label?:string;disabled?:boolean}>=({checked,onChange,label,disabled})=><button type="button" disabled={disabled} aria-pressed={checked} onClick={()=>onChange(!checked)} className={`inline-flex items-center gap-2 ${disabled?'opacity-50':''}`}><span className={`w-11 h-6 rounded-full p-1 transition ${checked?'bg-[var(--primary)]':'bg-[var(--surface-3)]'}`}><span className={`block w-4 h-4 rounded-full rounded-full bg-white transition ${checked?'translate-x-5':''}`}/></span>{label&&<span className="text-sm">{label}</span>}</button>;
const Field:React.FC<{label:string;help?:string;children:React.ReactNode}>=({label,help,children})=><label className="block"><span className="block text-sm font-semibold mb-1.5">{label}</span>{children}{help&&<span className="block mt-1 text-[11px] app-muted">{help}</span>}</label>;

export const SettingsEnterprisePage:React.FC=()=>{
 const location=useLocation();const navigate=useNavigate();const {user,profile,refreshProfile}=useAuth();const appearance=useAppearance();
 const slug=location.pathname.replace('/settings','').replace(/^\//,'');
 const [query,setQuery]=useState('');const [mobileOpen,setMobileOpen]=useState(false);const [toast,setToast]=useState('');
 const [settings,setSettings]=useState<Record<string,any>>(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem('customs-settings')||'{}')}}catch{return {...defaults}}});
 const [org,setOrg]=useState({name:'',economic_code:''});const [profileDraft,setProfileDraft]=useState({full_name:'',phone:''});
 const [users,setUsers]=useState<UserRow[]>([]);const [audit,setAudit]=useState<AuditRow[]>([]);const [loading,setLoading]=useState(false);const [userFilter,setUserFilter]=useState('');const [roleFilter,setRoleFilter]=useState<Role|''>('');
 const [selectedRole,setSelectedRole]=useState<Role>('admin');const [permissions,setPermissions]=useState<Record<string,boolean>>({});
 const [exportBusy,setExportBusy]=useState(false);
 const currentRole=(profile?.role||'client') as Role;const canAdmin=currentRole==='owner'||currentRole==='admin';
 const accessibleItems=useMemo(()=>items.filter(i=>!i.roles||i.roles.includes(currentRole)).filter(i=>!query||`${i.label} ${i.en}`.toLowerCase().includes(query.toLowerCase())),[currentRole,query]);
 const active=accessibleItems.find(i=>i.slug===slug)||items[0];
 const setSetting=(k:string,v:any)=>setSettings(s=>({...s,[k]:v}));
 useEffect(()=>{appearance.setTheme((settings.theme||'system'));appearance.setDensity(settings.density||'comfortable');appearance.setComfort(settings.comfort||'normal')},[settings.theme,settings.density,settings.comfort]);
 useEffect(()=>{const load=async()=>{if(!profile?.organization_id)return;setLoading(true);const [{data:o},{data:p},{data:u},{data:a}]=await Promise.all([
  supabase.from('organizations').select('name,economic_code').eq('id',profile.organization_id).maybeSingle(),
  supabase.from('profiles').select('full_name,phone').eq('id',profile.id).maybeSingle(),
  supabase.from('profiles').select('id,full_name,phone,role,is_active,created_at').eq('organization_id',profile.organization_id).order('full_name'),
  supabase.from('audit_logs').select('id,action,table_name,record_id,created_at,user_id,old_data,new_data').eq('organization_id',profile.organization_id).order('created_at',{ascending:false}).limit(100)
 ]);if(o) setOrg(o);if(p)setProfileDraft({full_name:p.full_name||'',phone:p.phone||''});setUsers((u||[]) as UserRow[]);setAudit((a||[]) as AuditRow[]);setLoading(false)};load()},[profile?.organization_id,profile?.id]);
 useEffect(()=>{setPermissions(JSON.parse(localStorage.getItem(`customs-permissions-${selectedRole}`)||JSON.stringify(roleDefaults[selectedRole])))},[selectedRole]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const persist=()=>{localStorage.setItem('customs-settings',JSON.stringify(settings));appearance.setTheme(settings.theme);appearance.setDensity(settings.density);appearance.setComfort(settings.comfort);notify('تنظیمات محلی ذخیره شد')};
 const auditWrite=async(action:string,tableName:string|null,newData:unknown)=>{if(!user?.id||!profile?.organization_id)return;await supabase.from('audit_logs').insert({organization_id:profile.organization_id,user_id:user.id,action,table_name:tableName,record_id:null,old_data:null,new_data:newData});};
 const saveOrg=async()=>{if(!profile?.organization_id||!canAdmin)return;setLoading(true);const{error}=await supabase.from('organizations').update({name:org.name.trim(),economic_code:org.economic_code.trim()}).eq('id',profile.organization_id);setLoading(false);if(error)notify(`خطا: ${error.message}`);else{await auditWrite('organization_update','organizations',{name:org.name,economic_code:org.economic_code});notify('اطلاعات سازمان ذخیره شد')}};
 const saveProfile=async()=>{if(!user?.id)return;setLoading(true);const{error}=await supabase.from('profiles').update({full_name:profileDraft.full_name.trim(),phone:profileDraft.phone.trim()}).eq('id',user.id);setLoading(false);if(error)notify(`خطا: ${error.message}`);else{await refreshProfile();await auditWrite('profile_update','profiles',{fields:['full_name','phone']});notify('پروفایل ذخیره شد')}};
 const updateUser=async(id:string,patch:Partial<UserRow>)=>{if(!canAdmin)return;const{error}=await supabase.from('profiles').update(patch).eq('id',id).eq('organization_id',profile?.organization_id||'');if(error)notify(`خطا: ${error.message}`);else{setUsers(u=>u.map(x=>x.id===id?{...x,...patch}:x));await auditWrite('user_update','profiles',{user_id:id,...patch});notify('کاربر به‌روزرسانی شد')}};
 const savePerms=()=>{localStorage.setItem(`customs-permissions-${selectedRole}`,JSON.stringify(permissions));notify(`دسترسی نقش ${roleLabel[selectedRole]} ذخیره شد`)};
 const download=async(name:string,data:unknown)=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
 const exportTable=async(table:'clients'|'cases')=>{if(!profile?.organization_id)return;setExportBusy(true);const q=table==='clients'?supabase.from('clients').select('*').eq('organization_id',profile.organization_id):supabase.from('cases').select('*').eq('organization_id',profile.organization_id);const{data,error}=await q;if(error)notify(`خطا: ${error.message}`);else await download(`${table}-backup-${new Date().toISOString().slice(0,10)}.json`,data||[]);setExportBusy(false);notify(error?'':'خروجی ایجاد شد')};
 const filteredUsers=users.filter(x=>(!userFilter||x.full_name.toLowerCase().includes(userFilter.toLowerCase())||x.phone?.includes(userFilter))&&(!roleFilter||x.role===roleFilter));
 const saveBar=<div className="sticky bottom-3 z-20 mt-5 flex items-center justify-between gap-3 rounded-2xl border app-border bg-[var(--surface)]/95 backdrop-blur-xl px-4 py-3 shadow-lg"><span className="text-xs app-muted">تغییرات این بخش را ذخیره کنید.</span><div className="flex gap-2"><button onClick={()=>{setSettings({...defaults});localStorage.setItem('customs-settings',JSON.stringify(defaults));notify('تنظیمات بازنشانی شد')}} className="px-3 py-2 rounded-xl border app-border text-sm">بازنشانی</button><button onClick={persist} className="px-4 py-2 rounded-xl bg-[var(--primary)] text-white text-sm font-bold inline-flex items-center gap-2"><Save size={15}/>ذخیره</button></div></div>;
 const render=()=>{
 switch(slug){
 case 'account':return <div className="space-y-4"><Card title="حساب کاربری" desc="تنظیمات عمومی جلسه و تجربه حساب" icon={User}><div className="grid md:grid-cols-2 gap-4"><Field label="ایمیل"><Input value={user?.email||''} disabled /></Field><Field label="نقش"><Input value={roleLabel[currentRole]} disabled /></Field><Field label="Timeout جلسه (دقیقه)"><Input type="number" min={5} value={settings.sessionTimeout} onChange={e=>setSetting('sessionTimeout',Number(e.target.value))}/></Field><Field label="فرمت ساعت"><Select value={settings.timeFormat} onChange={e=>setSetting('timeFormat',e.target.value)}><option value="24">۲۴ ساعته</option><option value="12">۱۲ ساعته</option></Select></Field></div></Card>{saveBar}</div>;
 case 'profile':return <div className="space-y-4"><Card title="پروفایل کاربر" desc="اطلاعات نمایشی شما در سامانه" icon={UserCog}><div className="grid md:grid-cols-2 gap-4"><Field label="نام و نام خانوادگی"><Input value={profileDraft.full_name} onChange={e=>setProfileDraft({...profileDraft,full_name:e.target.value})}/></Field><Field label="موبایل"><Input value={profileDraft.phone} onChange={e=>setProfileDraft({...profileDraft,phone:e.target.value})}/></Field><Field label="ایمیل"><Input value={user?.email||''} disabled/></Field></div><button onClick={saveProfile} disabled={loading} className="mt-5 px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white font-bold inline-flex items-center gap-2"><Save size={15}/>ذخیره پروفایل</button></Card></div>;
 case 'appearance':return <div className="space-y-4"><Card title="ظاهر و شخصی‌سازی" desc="تنظیمات از همان AppearanceContext فعلی سیستم استفاده می‌کنند." icon={Palette}><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4"><Field label="تم"><Select value={settings.theme} onChange={e=>setSetting('theme',e.target.value)}><option value="system">سیستم</option><option value="light">روشن</option><option value="dark">تیره</option></Select></Field><Field label="تراکم"><Select value={settings.density} onChange={e=>setSetting('density',e.target.value)}><option value="comfortable">راحت</option><option value="compact">فشرده</option></Select></Field><Field label="حالت مطالعه"><Select value={settings.comfort} onChange={e=>setSetting('comfort',e.target.value)}><option value="normal">عادی</option><option value="soft">ملایم</option><option value="warm">گرم</option><option value="reading">کتاب‌خوان</option></Select></Field><Field label="اندازه فونت"><Select value={settings.fontSize} onChange={e=>setSetting('fontSize',e.target.value)}><option value="small">کوچک</option><option value="medium">متوسط</option><option value="large">بزرگ</option></Select></Field></div><div className="mt-5 grid md:grid-cols-2 gap-4"><div className="flex justify-between rounded-xl border app-border p-3"><span>حرکت‌ها و Animation</span><Toggle checked={settings.animations} onChange={v=>setSetting('animations',v)}/></div><div className="flex justify-between rounded-xl border app-border p-3"><span>Reduced Motion</span><Toggle checked={settings.reducedMotion} onChange={v=>setSetting('reducedMotion',v)}/></div><div className="flex justify-between rounded-xl border app-border p-3"><span>Sticky Header جدول‌ها</span><Toggle checked={settings.stickyHeader} onChange={v=>setSetting('stickyHeader',v)}/></div><div className="flex justify-between rounded-xl border app-border p-3"><span>ردیف‌های راه‌راه</span><Toggle checked={settings.zebraRows} onChange={v=>setSetting('zebraRows',v)}/></div></div></Card>{saveBar}</div>;
 case 'organization':return <div className="space-y-4"><Card title="سازمان" desc="اطلاعات پایه Tenant فعلی" icon={Building2}><div className="grid md:grid-cols-2 gap-4"><Field label="نام سازمان"><Input value={org.name} onChange={e=>setOrg({...org,name:e.target.value})}/></Field><Field label="کد اقتصادی"><Input value={org.economic_code||''} onChange={e=>setOrg({...org,economic_code:e.target.value})}/></Field></div><button onClick={saveOrg} disabled={loading||!canAdmin} className="mt-5 px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white font-bold">ذخیره سازمان</button></Card><Card title="Branch / شعب" desc="مدل سازمانی فعلی هنوز جدول شعب مستقل ندارد؛ UI آماده اتصال است." icon={Map}><div className="rounded-xl border app-border p-4 app-muted text-sm">ساختار فعلی سازمان در Supabase با یک رکورد سازمان و پروفایل‌های اعضا کار می‌کند. ایجاد شعب مستقل نیازمند Schema جداگانه است.</div></Card></div>;
 case 'users':return <div className="space-y-4"><Card title="کاربران و اعضا" desc="لیست واقعی profiles سازمان فعلی" icon={Users}><div className="grid md:grid-cols-[1fr_180px] gap-3 mb-4"><Input placeholder="جستجوی نام یا موبایل..." value={userFilter} onChange={e=>setUserFilter(e.target.value)}/><Select value={roleFilter} onChange={e=>setRoleFilter(e.target.value as Role| '')}><option value="">همه نقش‌ها</option>{Object.keys(roleLabel).map(r=><option key={r} value={r}>{roleLabel[r as Role]}</option>)}</Select></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b app-border text-right"><th className="p-3">کاربر</th><th className="p-3">نقش</th><th className="p-3">وضعیت</th><th className="p-3">عضویت</th><th className="p-3">عملیات</th></tr></thead><tbody>{filteredUsers.map(u=><tr key={u.id} className="border-b app-border"><td className="p-3"><b>{u.full_name}</b><div className="text-[11px] app-muted">{u.phone||'—'}</div></td><td className="p-3"><Select disabled={!canAdmin||u.role==='owner'&&currentRole!=='owner'} value={u.role} onChange={e=>updateUser(u.id,{role:e.target.value as Role})}>{Object.keys(roleLabel).map(r=><option key={r} value={r}>{roleLabel[r as Role]}</option>)}</Select></td><td className="p-3"><span className={`status-pill ${u.is_active?'success':'danger'}`}>{u.is_active?'فعال':'غیرفعال'}</span></td><td className="p-3 text-xs">{new Date(u.created_at).toLocaleDateString('fa-IR')}</td><td className="p-3"><button onClick={()=>updateUser(u.id,{is_active:!u.is_active})} disabled={!canAdmin||u.id===user?.id} className="px-3 py-1.5 rounded-lg border app-border text-xs">{u.is_active?'غیرفعال‌سازی':'فعال‌سازی'}</button></td></tr>)}</tbody></table></div></Card></div>;
 case 'roles':return <div className="space-y-4"><Card title="نقش‌ها و دسترسی‌ها" desc="Permission Matrix قابل ذخیره برای هر Role" icon={ShieldCheck}><div className="mb-4 flex items-center gap-3"><Select className="max-w-xs" value={selectedRole} onChange={e=>setSelectedRole(e.target.value as Role)}>{Object.keys(roleLabel).map(r=><option key={r} value={r}>{roleLabel[r as Role]}</option>)}</Select><button onClick={savePerms} className="px-4 py-2 rounded-xl bg-[var(--primary)] text-white font-bold inline-flex gap-2 items-center"><Save size={15}/>ذخیره Role</button></div><div className="overflow-auto rounded-xl border app-border"><table className="min-w-[1100px] w-full text-xs"><thead><tr className="border-b app-border"><th className="p-2 text-right sticky right-0 bg-[var(--surface)]">ماژول</th>{actions.map(a=><th key={a} className="p-2">{a}</th>)}</tr></thead><tbody>{modules.map(m=><tr key={m} className="border-b app-border"><td className="p-2 font-bold sticky right-0 bg-[var(--surface)]">{m}</td>{actions.map(a=><td key={a} className="p-2 text-center"><input type="checkbox" checked={Boolean(permissions[`${m}:${a}`])} onChange={()=>setPermissions(p=>({...p,[`${m}:${a}`]:!p[`${m}:${a}`]}))}/></td>)}</tr>)}</tbody></table></div><div className="mt-3 text-xs app-muted">این Matrix در حال حاضر در localStorage نگه‌داری می‌شود؛ برای enforcement واقعی باید به جدول Permission در Supabase متصل شود.</div></Card></div>;
 case 'security':return <div className="space-y-4"><Card title="مرکز امنیت" desc="کنترل رمز عبور و نشست فعلی" icon={Lock}><div className="grid md:grid-cols-2 gap-4"><Field label="رمز عبور جدید" help="Supabase Auth هنگام ذخیره آن را تغییر می‌دهد."><Input id="new-password" type="password" placeholder="حداقل ۸ کاراکتر"/></Field><Field label="تکرار رمز"><Input id="confirm-password" type="password"/></Field></div><button onClick={async()=>{const p=(document.getElementById('new-password') as HTMLInputElement)?.value;const c=(document.getElementById('confirm-password') as HTMLInputElement)?.value;if(!p||p.length<8||p!==c){notify('رمزها معتبر یا یکسان نیستند');return}const{error}=await supabase.auth.updateUser({password:p});notify(error?`خطا: ${error.message}`:'رمز عبور تغییر کرد')}} className="mt-4 px-4 py-2.5 rounded-xl bg-[var(--primary)] text-white font-bold">تغییر رمز</button></Card><Card title="نشست فعلی" desc="اطلاعات نشست در اختیار Frontend است." icon={KeyRound}><div className="grid md:grid-cols-3 gap-3"><div className="rounded-xl border app-border p-3"><span className="text-xs app-muted">کاربر</span><b className="block mt-1 truncate">{user?.email||'—'}</b></div><div className="rounded-xl border app-border p-3"><span className="text-xs app-muted">Role</span><b className="block mt-1">{roleLabel[currentRole]}</b></div><div className="rounded-xl border app-border p-3"><span className="text-xs app-muted">Session</span><b className="block mt-1">{user?.id?.slice(0,8)||'—'}</b></div></div></Card></div>;
 case 'notifications':return <div className="space-y-4"><Card title="اعلان‌ها" desc="تنظیمات کانال و زمان سکوت" icon={Bell}><div className="grid md:grid-cols-2 gap-3">{[['اعلان داخل سامانه','inApp'],['ایمیل','email'],['SMS','sms'],['WhatsApp','whatsapp'],['Push','push']].map(([label,k])=><div key={k} className="flex justify-between rounded-xl border app-border p-3"><span>{label}</span><Toggle checked={settings[`notify_${k}`]!==false} onChange={v=>setSetting(`notify_${k}`,v)}/></div>)}</div><div className="mt-4 flex justify-between rounded-xl border app-border p-3"><span>ساعات سکوت</span><Toggle checked={settings.quietHours} onChange={v=>setSetting('quietHours',v)}/></div><div className="grid md:grid-cols-2 gap-4 mt-4"><Field label="شروع"><Input type="time" value={settings.quietFrom} onChange={e=>setSetting('quietFrom',e.target.value)}/></Field><Field label="پایان"><Input type="time" value={settings.quietTo} onChange={e=>setSetting('quietTo',e.target.value)}/></Field></div></Card>{saveBar}</div>;
 case 'customs':case 'clearance':case 'epl':case 'statuses':return <div className="space-y-4"><Card title={active.label} desc="تنظیمات عملیاتی متصل به تنظیمات مرکزی Customs OS" icon={active.icon}><div className="grid md:grid-cols-2 gap-4"><Field label="گمرک پیش‌فرض"><Input value={settings.defaultCustomsOffice} onChange={e=>setSetting('defaultCustomsOffice',e.target.value)}/></Field><Field label="بندر پیش‌فرض"><Input value={settings.defaultPort} onChange={e=>setSetting('defaultPort',e.target.value)}/></Field><Field label="Workflow پیش‌فرض"><Select value={settings.defaultWorkflow} onChange={e=>setSetting('defaultWorkflow',e.target.value)}><option value="standard">استاندارد</option><option value="fast">سریع</option><option value="custom">سفارشی</option></Select></Field><Field label="Statusهای مرجع"><Input value="draft → submitted_epl → green/yellow/red → cleared → archived" disabled/></Field></div></Card>{saveBar}</div>;
 case 'transport':case 'vessels':return <div className="space-y-4"><Card title={active.label} desc="تنظیمات حمل، کشتی و Tracking" icon={Ship}><div className="grid md:grid-cols-2 gap-4"><Field label="Refresh Tracking (ثانیه)"><Input type="number" min={5} value={settings.vesselAutoRefresh} onChange={e=>setSetting('vesselAutoRefresh',Number(e.target.value))}/></Field><Field label="واحد سرعت"><Select value={settings.speedUnit||'knots'} onChange={e=>setSetting('speedUnit',e.target.value)}><option value="knots">Knots</option><option value="kmh">km/h</option></Select></Field><Field label="حمل پیش‌فرض"><Select value={settings.transportMode||'sea'} onChange={e=>setSetting('transportMode',e.target.value)}><option value="sea">دریایی</option><option value="road">جاده‌ای</option><option value="rail">ریلی</option><option value="air">هوایی</option></Select></Field><Field label="Map Provider"><Select value={settings.mapProvider||'openstreetmap'} onChange={e=>setSetting('mapProvider',e.target.value)}><option value="openstreetmap">OpenStreetMap</option><option value="external">External API</option></Select></Field></div></Card>{saveBar}</div>;
 case 'warehouse':return <div className="space-y-4"><Card title="انبار" desc="تنظیمات نگهداری و هشدار" icon={Box}><div className="grid md:grid-cols-2 gap-4"><Field label="مدت نگهداری پیش‌فرض (روز)"><Input type="number" value={settings.storageRetentionDays} onChange={e=>setSetting('storageRetentionDays',Number(e.target.value))}/></Field><Field label="هشدار قبل از سررسید (روز)"><Input type="number" value={settings.storageAlertDays||7} onChange={e=>setSetting('storageAlertDays',Number(e.target.value))}/></Field></div></Card>{saveBar}</div>;
 case 'documents':return <div className="space-y-4"><Card title="اسناد" desc="قواعد پایه ذخیره و نگهداری" icon={FileText}><div className="grid md:grid-cols-2 gap-4"><Field label="حداکثر حجم فایل (MB)"><Input type="number" value={settings.documentMaxMb} onChange={e=>setSetting('documentMaxMb',Number(e.target.value))}/></Field><Field label="Retention (روز)"><Input type="number" value={settings.retentionDays} onChange={e=>setSetting('retentionDays',Number(e.target.value))}/></Field><Field label="OCR"><Select value={settings.ocrMode||'available'} onChange={e=>setSetting('ocrMode',e.target.value)}><option value="available">در دسترس</option><option value="off">خاموش</option></Select></Field><Field label="Versioning"><Toggle checked={settings.documentVersioning!==false} onChange={v=>setSetting('documentVersioning',v)}/></Field></div></Card>{saveBar}</div>;
 case 'numbering':return <div className="space-y-4"><Card title="شماره‌گذاری مرکزی" desc="پیش‌نمایش و فرمت شماره‌ها" icon={SlidersHorizontal}><div className="grid md:grid-cols-2 gap-4"><Field label="Prefix پرونده"><Input value={settings.casePrefix} onChange={e=>setSetting('casePrefix',e.target.value)}/></Field><Field label="Prefix محموله"><Input value={settings.shipmentPrefix} onChange={e=>setSetting('shipmentPrefix',e.target.value)}/></Field><Field label="Prefix سند"><Input value={settings.documentPrefix} onChange={e=>setSetting('documentPrefix',e.target.value)}/></Field><Field label="Prefix تراکنش"><Input value={settings.transactionPrefix} onChange={e=>setSetting('transactionPrefix',e.target.value)}/></Field><Field label="تعداد ارقام Sequence"><Input type="number" min={3} max={12} value={settings.numberingDigits} onChange={e=>setSetting('numberingDigits',Number(e.target.value))}/></Field><Field label="سال در شماره"><Toggle checked={settings.numberingYear} onChange={v=>setSetting('numberingYear',v)}/></Field></div><div className="mt-4 p-4 rounded-xl border app-border bg-[var(--surface-2)]"><span className="text-xs app-muted">نمونه:</span><div className="mt-1 text-xl font-black">{settings.casePrefix}-{settings.numberingYear?'1405-':''}{String(1).padStart(settings.numberingDigits,'0')}</div></div></Card>{saveBar}</div>;
 case 'calendar':case 'units':case 'currencies':case 'taxes':case 'finance':return <div className="space-y-4"><Card title={active.label} desc="تنظیمات مرجع برای محاسبات و نمایش" icon={Wallet}><div className="grid md:grid-cols-2 gap-4"><Field label="تقویم"><Select value={settings.calendar} onChange={e=>setSetting('calendar',e.target.value)}><option value="jalali">شمسی</option><option value="gregorian">میلادی</option></Select></Field><Field label="Time Zone"><Input value={settings.timezone} onChange={e=>setSetting('timezone',e.target.value)}/></Field><Field label="ارز پایه"><Select value={settings.currency} onChange={e=>setSetting('currency',e.target.value)}><option value="IRR">IRR</option><option value="USD">USD</option><option value="EUR">EUR</option></Select></Field><Field label="روش نرخ ارز"><Select value={settings.exchangeMode} onChange={e=>setSetting('exchangeMode',e.target.value)}><option value="manual">دستی</option><option value="api">API</option></Select></Field><Field label="VAT (%)"><Input type="number" value={settings.vatRate} onChange={e=>setSetting('vatRate',Number(e.target.value))}/></Field><Field label="واحد وزن"><Select value={settings.weightUnit||'kg'} onChange={e=>setSetting('weightUnit',e.target.value)}><option value="kg">کیلوگرم</option><option value="ton">تن</option></Select></Field></div></Card>{saveBar}</div>;
 case 'printing':case 'templates':return <div className="space-y-4"><Card title={active.label} desc="تنظیمات چاپ و Template" icon={Download}><div className="grid md:grid-cols-2 gap-4"><Field label="Paper"><Select value={settings.paper||'A4'} onChange={e=>setSetting('paper',e.target.value)}><option>A4</option><option>A5</option><option>Letter</option></Select></Field><Field label="Watermark"><Toggle checked={settings.watermark!==false} onChange={v=>setSetting('watermark',v)}/></Field><Field label="نمایش Logo"><Toggle checked={settings.printLogo!==false} onChange={v=>setSetting('printLogo',v)}/></Field><Field label="نمایش امضاء"><Toggle checked={settings.printSignature!==false} onChange={v=>setSetting('printSignature',v)}/></Field></div></Card>{saveBar}</div>;
 case 'integrations':return <div className="space-y-4"><Card title="Integration Center" desc="وضعیت سرویس‌ها و تنظیمات اتصال" icon={Plug}><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{[['Supabase','متصل','success'],['Cloud Storage','نیازمند بررسی','warning'],['Email','غیرمتصل','neutral'],['SMS','غیرمتصل','neutral'],['WhatsApp','غیرمتصل','neutral'],['Vessel Tracking','UI آماده','success']].map(([n,s,c])=><div key={n} className="rounded-xl border app-border p-4"><div className="flex items-center justify-between"><b>{n}</b><span className={`status-pill ${c}`}>{s}</span></div><button className="mt-3 w-full rounded-lg border app-border py-2 text-xs">پیکربندی</button></div>)}</div><div className="mt-4 rounded-xl border app-border p-4"><div className="flex items-center gap-2 text-amber-500"><KeyRound size={16}/><b>امنیت Secretها</b></div><p className="text-xs app-muted mt-2">هیچ API Secretی در localStorage یا کد Frontend ذخیره نشود. Secretهای واقعی باید از سمت Server/Edge Function مدیریت شوند.</p></div></Card></div>;
 case 'webhooks':return <div className="space-y-4"><Card title="Webhooks" desc="UI مدیریت endpointها" icon={Webhook}><div className="rounded-xl border app-border p-4 app-muted text-sm">ساختار UI آماده است؛ ثبت و ارسال واقعی Webhook به Edge Function نیاز دارد تا Secret و retry policy سمت Server بماند.</div><button disabled className="mt-4 px-4 py-2 rounded-xl border app-border opacity-60">+ افزودن Webhook</button></Card></div>;
 case 'storage':return <div className="space-y-4"><Card title="Storage" desc="نمایش وضعیت Storage بدون افشای Secret" icon={HardDrive}><div className="grid md:grid-cols-3 gap-3"><div className="rounded-xl border app-border p-4"><span className="text-xs app-muted">Documents bucket</span><b className="block mt-1">case-documents</b></div><div className="rounded-xl border app-border p-4"><span className="text-xs app-muted">Invoice bucket</span><b className="block mt-1">invoice-attachments</b></div><div className="rounded-xl border app-border p-4"><span className="text-xs app-muted">Vessel bucket</span><b className="block mt-1">vessel-documents</b></div></div><p className="text-xs app-muted mt-3">دسترسی واقعی Bucketها باید با Storage Policies کنترل شود.</p></Card></div>;
 case 'backup':return <div className="space-y-4"><Card title="Backup & Export" desc="خروجی واقعی از داده‌های قابل‌دسترسی Tenant" icon={Archive}><div className="grid md:grid-cols-2 gap-3"><button disabled={exportBusy} onClick={()=>exportTable('clients')} className="rounded-xl border app-border p-4 text-right hover:bg-[var(--surface-2)]"><b>پشتیبان مشتریان</b><span className="block text-xs app-muted mt-1">JSON از جدول clients همان سازمان</span></button><button disabled={exportBusy} onClick={()=>exportTable('cases')} className="rounded-xl border app-border p-4 text-right hover:bg-[var(--surface-2)]"><b>پشتیبان پرونده‌ها</b><span className="block text-xs app-muted mt-1">JSON از جدول cases همان سازمان</span></button></div><div className="mt-4 rounded-xl border app-border p-4 text-xs app-muted">این «export backup» است و Backup فیزیکی PostgreSQL محسوب نمی‌شود. Restore دیتابیس باید از مسیر مدیریت Supabase یا Backend امن انجام شود.</div></Card></div>;
 case 'audit':return <div className="space-y-4"><Card title="Audit Log" desc="رویدادهای واقعی ثبت‌شده برای سازمان" icon={History}><div className="overflow-auto"><table className="w-full min-w-[850px] text-xs"><thead><tr className="border-b app-border"><th className="p-3 text-right">زمان</th><th className="p-3 text-right">Action</th><th className="p-3 text-right">Table</th><th className="p-3 text-right">Record</th><th className="p-3 text-right">User</th></tr></thead><tbody>{audit.map(a=><tr key={a.id} className="border-b app-border"><td className="p-3">{new Date(a.created_at).toLocaleString('fa-IR')}</td><td className="p-3 font-semibold">{a.action}</td><td className="p-3">{a.table_name||'—'}</td><td className="p-3 font-mono">{a.record_id?.slice(0,8)||'—'}</td><td className="p-3 font-mono">{a.user_id?.slice(0,8)||'—'}</td></tr>)}</tbody></table></div></Card></div>;
 case 'import-export':return <div className="space-y-4"><Card title="Import / Export Data" desc="خروجی Tenant-scoped و امن" icon={ArrowDownToLine}><div className="grid md:grid-cols-2 gap-3"><button disabled={exportBusy} onClick={()=>exportTable('clients')} className="rounded-xl border app-border p-4 text-right"><Upload size={18}/><b className="block mt-2">Export Clients</b><span className="text-xs app-muted">JSON</span></button><button disabled={exportBusy} onClick={()=>exportTable('cases')} className="rounded-xl border app-border p-4 text-right"><Download size={18}/><b className="block mt-2">Export Cases</b><span className="text-xs app-muted">JSON</span></button></div></Card></div>;
 case 'advanced':return <div className="space-y-4"><Card title="تنظیمات پیشرفته" desc="فقط Owner/Admin" icon={FlaskConical}><div className="grid md:grid-cols-2 gap-3"><div className="rounded-xl border app-border p-4 flex justify-between"><span>Auto Save</span><Toggle checked={settings.autoSave} onChange={v=>setSetting('autoSave',v)}/></div><div className="rounded-xl border app-border p-4 flex justify-between"><span>Debug Mode</span><Toggle checked={Boolean(settings.debugMode)} onChange={v=>setSetting('debugMode',v)}/></div><div className="rounded-xl border app-border p-4 flex justify-between"><span>Experimental Features</span><Toggle checked={Boolean(settings.experimental)} onChange={v=>setSetting('experimental',v)}/></div></div></Card>{saveBar}</div>;
 case 'maintenance':return <div className="space-y-4"><Card title="Maintenance" desc="ابزارهای امن سمت کاربر" icon={Server}><div className="grid md:grid-cols-2 gap-3"><button onClick={()=>{localStorage.removeItem('customs-settings');setSettings({...defaults});notify('کش تنظیمات محلی پاک شد')}} className="rounded-xl border app-border p-4 text-right"><Trash2 size={18}/><b className="block mt-2">پاک‌سازی تنظیمات محلی</b></button><button onClick={()=>window.location.reload()} className="rounded-xl border app-border p-4 text-right"><RefreshCw size={18}/><b className="block mt-2">Reload برنامه</b></button></div></Card></div>;
 case 'about':return <div className="space-y-4"><Card title="Customs OS" desc="Customs & Logistics Operating System" icon={Settings2}><div className="grid md:grid-cols-3 gap-3"><div className="rounded-xl border app-border p-4"><span className="text-xs app-muted">Application</span><b className="block mt-1">Customs OS</b></div><div className="rounded-xl border app-border p-4"><span className="text-xs app-muted">Version</span><b className="block mt-1">0.1.0</b></div><div className="rounded-xl border app-border p-4"><span className="text-xs app-muted">Architecture</span><b className="block mt-1">React + Supabase</b></div></div></Card></div>;
 default:return <div className="space-y-4"><Card title="نمای کلی تنظیمات" desc="مرکز کنترل تنظیمات Customs OS" icon={LayoutDashboard}><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">{[{t:'کاربران',v:String(users.length),s:'profiles واقعی',i:Users},{t:'Audit',v:String(audit.length),s:'رویداد اخیر',i:History},{t:'Role',v:roleLabel[currentRole],s:'سطح دسترسی',i:ShieldCheck},{t:'Supabase',v:'متصل',s:profile?.organization_id?.slice(0,8)||'—',i:Database}].map(x=><div key={x.t} className="rounded-2xl border app-border bg-[var(--surface)] p-4"><x.i size={18}/><div className="mt-3 text-sm app-muted">{x.t}</div><div className="text-xl font-black mt-1">{x.v}</div><div className="text-[11px] app-muted mt-1">{x.s}</div></div>)}</div></Card><div className="grid lg:grid-cols-2 gap-4"><Card title="Quick Actions" icon={Activity}><div className="grid grid-cols-2 gap-3">{[['organization','سازمان',Building2],['users','کاربران',Users],['roles','دسترسی‌ها',ShieldCheck],['audit','Audit',History]].filter(x=>!items.find(i=>i.slug===x[0])?.roles||items.find(i=>i.slug===x[0])!.roles!.includes(currentRole)).map(([s,l,I])=><button key={String(s)} onClick={()=>navigate(`/settings/${s}`)} className="rounded-xl border app-border p-3 text-right hover:bg-[var(--surface-2)]"><I size={17}/><b className="block mt-2">{l}</b></button>)}</div></Card><Card title="وضعیت Configuration" icon={Settings2}><div className="space-y-2 text-sm">{[['Theme',settings.theme],['Calendar',settings.calendar],['Currency',settings.currency],['Port',settings.defaultPort],['Workflow',settings.defaultWorkflow]].map(([a,b])=><div key={a} className="flex justify-between border-b app-border py-2"><span className="app-muted">{a}</span><b>{String(b)}</b></div>)}</div></Card></div></div>;
 }
 };
 return <div dir="rtl" className="min-h-screen p-3 md:p-5"><div className="max-w-[1800px] mx-auto"><div className="flex items-center justify-between gap-3 mb-4"><div><div className="text-xs app-muted">Settings / {active.en}</div><h1 className="text-2xl md:text-3xl font-black mt-1">{active.label}</h1><p className="text-xs md:text-sm app-muted mt-1">مرکز تنظیمات یکپارچه Customs OS</p></div><button onClick={()=>setMobileOpen(v=>!v)} className="md:hidden icon-btn" aria-label="منوی تنظیمات"><SlidersHorizontal size={18}/></button></div><div className="grid md:grid-cols-[280px_minmax(0,1fr)] gap-4 items-start"><aside className={`${mobileOpen?'block':'hidden'} md:block rounded-2xl border app-border bg-[var(--surface)] p-3 md:sticky md:top-20`}><div className="relative mb-3"><Search size={15} className="absolute right-3 top-3.5 app-muted"/><Input className="pr-9" placeholder="جستجوی تنظیمات..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{groups.map(g=><div key={g.id} className="mb-4"><div className="px-2 pb-2 text-[11px] font-black app-muted">{g.label}</div>{accessibleItems.filter(i=>i.group===g.id).map(i=>{const I=i.icon;const is=active.slug===i.slug;return <button key={i.slug||'overview'} onClick={()=>{navigate(`/settings${i.slug?`/${i.slug}`:''}`);setMobileOpen(false)}} className={`w-full flex items-center gap-2 rounded-xl px-3 py-2.5 text-right text-sm mb-1 ${is?'bg-[color-mix(in_srgb,var(--primary)_16%,var(--surface))] text-[var(--primary)] font-bold':'hover:bg-[var(--surface-2)]'}`}><I size={16}/><span className="min-w-0"><span className="block truncate">{i.label}</span><span className="block text-[10px] app-muted">{i.en}</span></span>{is&&<ChevronLeft size={14} className="mr-auto"/>}</button>})}</div>)}</aside><main className="min-w-0">{loading&&<div className="mb-3 rounded-xl border app-border bg-[var(--surface)] px-4 py-3 text-xs app-muted flex items-center gap-2"><RefreshCw size={14} className="animate-spin"/>در حال همگام‌سازی...</div>}{render()}</main></div></div>{toast&&<div className="fixed bottom-5 left-1/2 -translate-x-1/2 z-[100] rounded-xl bg-slate-900 text-white px-4 py-3 text-sm shadow-xl flex items-center gap-2"><Check size={16}/>{toast}</div>}</div>;
};
