import React,{useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {useAuth} from '../context/AuthContext';
import {useAppearance} from '../context/AppearanceContext';
import {
 Activity,AlertTriangle,Archive,ArrowDownToLine,ArrowLeftRight,BarChart3,Bell,Bolt,Box,Building2,Calendar,Check,ChevronDown,ChevronLeft,
 ChevronRight,ClipboardList,Cloud,Database,Download,FileCheck2,FileText,FlaskConical,FolderCog,Globe,HardDrive,History,KeyRound,LayoutDashboard,
 Lock,Mail,Map,Palette,Plug,RefreshCw,Save,Search,Server,Settings2,ShieldCheck,Ship,SlidersHorizontal,Smartphone,Timer,Trash2,Truck,Upload,User,
 UserCog,Users,Wallet,Webhook,X,Eye,EyeOff
} from 'lucide-react';

type SettingItem={slug:string;label:string;en:string;icon:React.ComponentType<{size?:number;className?:string}>;group:string;roles?:string[]};

const groups=[
 {id:'account',label:'حساب و کاربر'},
 {id:'org',label:'سازمان و دسترسی'},
 {id:'operations',label:'عملیات و ترخیص'},
 {id:'finance',label:'مالی و داده'},
 {id:'system',label:'سیستم و یکپارچه‌سازی'},
];
const items:SettingItem[]=[
 {slug:'',label:'نمای کلی تنظیمات',en:'Overview',icon:LayoutDashboard,group:'account'},
 {slug:'account',label:'حساب کاربری',en:'Account',icon:User,group:'account'},
 {slug:'profile',label:'پروفایل',en:'Profile',icon:UserCog,group:'account'},
 {slug:'appearance',label:'ظاهر و شخصی‌سازی',en:'Appearance',icon:Palette,group:'account'},
 {slug:'notifications',label:'اعلان‌ها',en:'Notifications',icon:Bell,group:'account'},
 {slug:'security',label:'امنیت',en:'Security',icon:Lock,group:'account'},
 {slug:'organization',label:'سازمان و شعب',en:'Organization',icon:Building2,group:'org',roles:['owner','admin']},
 {slug:'users',label:'کاربران و اعضا',en:'Users',icon:Users,group:'org',roles:['owner','admin']},
 {slug:'roles',label:'نقش‌ها و دسترسی‌ها',en:'Roles & Permissions',icon:ShieldCheck,group:'org',roles:['owner','admin']},
 {slug:'customs',label:'عملیات گمرکی',en:'Customs Operations',icon:FileCheck2,group:'operations',roles:['owner','admin','broker']},
 {slug:'clearance',label:'تنظیمات ترخیص',en:'Clearance',icon:ClipboardList,group:'operations',roles:['owner','admin','broker']},
 {slug:'transport',label:'حمل و نقل',en:'Transport',icon:Truck,group:'operations',roles:['owner','admin','broker']},
 {slug:'vessels',label:'کشتی و بار',en:'Vessels & Cargo',icon:Ship,group:'operations',roles:['owner','admin','broker']},
 {slug:'warehouse',label:'انبار',en:'Warehouse',icon:Box,group:'operations',roles:['owner','admin','warehouse']},
 {slug:'documents',label:'اسناد',en:'Documents',icon:FileText,group:'operations'},
 {slug:'permits',label:'مجوزها و Rules',en:'Permits',icon:ShieldCheck,group:'operations',roles:['owner','admin','broker']},
 {slug:'epl',label:'EPL و Workflow گمرکی',en:'EPL & Workflow',icon:Activity,group:'operations',roles:['owner','admin','broker']},
 {slug:'numbering',label:'شماره‌گذاری و کدگذاری',en:'Numbering',icon:SlidersHorizontal,group:'operations'},
 {slug:'statuses',label:'وضعیت‌ها و گردش‌کار',en:'Statuses & Workflow',icon:ArrowLeftRight,group:'operations'},
 {slug:'client',label:'مشتریان',en:'Clients',icon:Users,group:'operations'},
 {slug:'calendar',label:'تقویم و تاریخ',en:'Calendar & Date',icon:Calendar,group:'finance'},
 {slug:'units',label:'واحدها و اندازه‌گیری',en:'Units',icon:SlidersHorizontal,group:'finance'},
 {slug:'currencies',label:'ارزها و نرخ ارز',en:'Currencies',icon:Wallet,group:'finance'},
 {slug:'taxes',label:'مالیات و عوارض',en:'Taxes & Duties',icon:BarChart3,group:'finance'},
 {slug:'finance',label:'تنظیمات مالی',en:'Finance',icon:Wallet,group:'finance'},
 {slug:'printing',label:'چاپ و خروجی',en:'Printing',icon:Download,group:'finance'},
 {slug:'templates',label:'Templateها',en:'Templates',icon:FolderCog,group:'finance'},
 {slug:'integrations',label:'API و Integrations',en:'Integrations',icon:Plug,group:'system',roles:['owner','admin']},
 {slug:'webhooks',label:'Webhooks',en:'Webhooks',icon:Webhook,group:'system',roles:['owner','admin']},
 {slug:'storage',label:'Storage',en:'Storage',icon:HardDrive,group:'system',roles:['owner','admin']},
 {slug:'backup',label:'Backup',en:'Backup',icon:Archive,group:'system',roles:['owner','admin']},
 {slug:'audit',label:'Audit Log',en:'Audit Log',icon:History,group:'system',roles:['owner','admin']},
 {slug:'import-export',label:'Import / Export Data',en:'Import / Export',icon:ArrowDownToLine,group:'system',roles:['owner','admin']},
 {slug:'advanced',label:'تنظیمات پیشرفته',en:'Advanced',icon:FlaskConical,group:'system',roles:['owner','admin']},
 {slug:'maintenance',label:'Maintenance',en:'Maintenance',icon:Server,group:'system',roles:['owner','admin']},
 {slug:'about',label:'درباره سیستم',en:'About System',icon:Globe,group:'system'},
];

const roleLabel:Record<string,string>={owner:'مالک',admin:'مدیر',broker:'کارگزار',accountant:'حسابدار',warehouse:'انبار',client:'صاحب کالا'};
const defaultSettings={theme:'system',density:'comfortable',comfort:'normal',sidebarCollapsed:false,fontSize:'medium',animations:true,reducedMotion:false,stickyHeader:true,zebraRows:false,hoverRows:true,calendar:'jalali',timezone:'Asia/Tehran',timeFormat:'24',autoSave:false,sessionTimeout:60,numberingPrefix:'DB',numberingDigits:6,numberingYear:true,numberingMonth:false,duplicateClients:true,defaultPort:'بندر شهید رجایی',defaultCustomsOffice:'گمرک شهید رجایی',defaultWorkflow:'standard',currency:'IRR',exchangeMode:'manual',vatRate:10,documentMaxMb:25,retentionDays:3650,vesselAutoRefresh:15,quietHours:false,quietFrom:'22:00',quietTo:'07:00'};

const Card:React.FC<{title:string;desc?:string;icon?:React.ComponentType<{size?:number}>;children:React.ReactNode;className?:string}>=({title,desc,icon:Icon,children,className=''})=><section className={`rounded-2xl border app-border bg-[var(--surface)] p-4 md:p-5 ${className}`}><div className="flex items-start gap-3 mb-4">{Icon&&<div className="h-10 w-10 rounded-xl grid place-items-center bg-[color-mix(in_srgb,var(--primary)_13%,var(--surface-2))] text-[var(--primary)]"><Icon size={19}/></div>}<div className="min-w-0"><h3 className="font-bold">{title}</h3>{desc&&<p className="mt-1 text-xs app-muted">{desc}</p>}</div></div>{children}</section>;
const Field:React.FC<{label:string;help?:string;children:React.ReactNode}>=({label,help,children})=><label className="block"><span className="block text-sm font-semibold mb-1.5">{label}</span>{children}{help&&<span className="block text-[11px] app-muted mt-1">{help}</span>}</label>;
const Input:React.FC<React.InputHTMLAttributes<HTMLInputElement>>=p=><input {...p} className={`w-full rounded-xl border app-border bg-[var(--surface-2)] text-[var(--text)] px-3 min-h-11 outline-none focus:border-[var(--primary)] ${p.className||''}`}/>;
const Select:React.FC<React.SelectHTMLAttributes<HTMLSelectElement>>=p=><select {...p} className={`w-full rounded-xl border app-border bg-[var(--surface-2)] text-[var(--text)] px-3 min-h-11 outline-none focus:border-[var(--primary)] ${p.className||''}`}/>;
const Toggle:React.FC<{checked:boolean;onChange:(v:boolean)=>void;label?:string;disabled?:boolean}>=({checked,onChange,label,disabled})=><button type="button" disabled={disabled} aria-pressed={checked} onClick={()=>onChange(!checked)} className={`inline-flex items-center gap-2 ${disabled?'opacity-50':''}`}><span className={`w-11 h-6 rounded-full p-1 transition ${checked?'bg-[var(--primary)]':'bg-[var(--surface-3)]'}`}><span className={`block w-4 h-4 rounded-full bg-white transition ${checked?'translate-x-5':''}`}/></span>{label&&<span className="text-sm">{label}</span>}</button>;

export const SettingsPage:React.FC=()=>{
 const location=useLocation(); const navigate=useNavigate(); const {user,profile}=useAuth(); const appearance=useAppearance();
 const slug=location.pathname.replace('/settings','').replace(/^\//,'');
 const active=items.find(x=>x.slug===slug) || items[0];
 const [query,setQuery]=useState(''); const [mobileNav,setMobileNav]=useState(false); const [saved,setSaved]=useState<'idle'|'saving'|'saved'|'error'>('idle');
 const [org,setOrg]=useState<{name:string;economic_code:string} | null>(null);
 const [orgDraft,setOrgDraft]=useState({name:'',economic_code:''});
 const [settings,setSettings]=useState<Record<string,any>>(()=>{try{return {...defaultSettings,...JSON.parse(localStorage.getItem('customs-settings')||'{}')}}catch{return {...defaultSettings}}});
 const [showSecret,setShowSecret]=useState(false);
 const setSetting=(key:string,value:any)=>setSettings(s=>({...s,[key]:value}));
 useEffect(()=>{try{appearance.setTheme(settings.theme);appearance.setDensity(settings.density);appearance.setComfort(settings.comfort);appearance.setSidebarCollapsed(Boolean(settings.sidebarCollapsed))}catch{}},[settings.theme,settings.density,settings.comfort,settings.sidebarCollapsed]);
 useEffect(()=>{if(!profile?.organization_id)return; (async()=>{const{data}=await supabase.from('organizations').select('name,economic_code').eq('id',profile.organization_id).maybeSingle();if(data){setOrg(data);setOrgDraft(data)}})()},[profile?.organization_id]);
 const filtered=useMemo(()=>items.filter(x=>!x.roles||x.roles.includes(profile?.role||'client')).filter(x=>!query||`${x.label} ${x.en}`.toLowerCase().includes(query.toLowerCase())),[query,profile?.role]);
 const saveSettings=async()=>{setSaved('saving');try{localStorage.setItem('customs-settings',JSON.stringify(settings)); if(settings.theme) appearance.setTheme(settings.theme); if(settings.density) appearance.setDensity(settings.density); if(settings.comfort) appearance.setComfort(settings.comfort); appearance.setSidebarCollapsed(Boolean(settings.sidebarCollapsed)); if(user?.id&&profile?.organization_id){await supabase.from('audit_logs').insert({organization_id:profile.organization_id,user_id:user.id,action:'settings_update',table_name:'settings',record_id:null,old_data:null,new_data:{keys:Object.keys(settings)}})} setSaved('saved');setTimeout(()=>setSaved('idle'),1800)}catch{setSaved('error')}};
 const saveOrg=async()=>{if(!profile?.organization_id)return;setSaved('saving');const{data,error}=await supabase.from('organizations').update({name:orgDraft.name.trim(),economic_code:orgDraft.economic_code.trim()}).eq('id',profile.organization_id).select('name,economic_code').maybeSingle();if(error){setSaved('error');return}setOrg(data);setSaved('saved');setTimeout(()=>setSaved('idle'),1800)};
 const resetSettings=()=>{setSettings({...defaultSettings});localStorage.setItem('customs-settings',JSON.stringify(defaultSettings));setSaved('saved');};
 const navigateSetting=(s:string)=>{navigate(`/settings${s?`/${s}`:''}`);setMobileNav(false);window.scrollTo({top:0,behavior:'smooth'})};
 const sectionTitle=active.label, sectionDesc=active.en==='Overview'?'مرکز کنترل همه تنظیمات حساب، سازمان، عملیات و سیستم':`تنظیمات ${active.label}`;
 const basicSaveBar=<div className="sticky bottom-3 z-20 mt-5 flex items-center justify-between gap-3 rounded-2xl border app-border bg-[color-mix(in_srgb,var(--surface)_94%,transparent)] backdrop-blur-xl px-4 py-3 shadow-lg"><div className="text-xs app-muted">{saved==='saving'?'در حال ذخیره…':saved==='saved'?'تنظیمات ذخیره شد':saved==='error'?'ذخیره انجام نشد':'تغییرات را ذخیره کنید'}</div><div className="flex gap-2"><button type="button" onClick={resetSettings} className="px-3 py-2 rounded-xl border app-border text-sm">بازنشانی</button><button type="button" disabled={saved==='saving'} onClick={saveSettings} className="px-4 py-2 rounded-xl bg-[var(--primary)] text-white text-sm font-bold inline-flex items-center gap-2"><Save size={15}/> ذخیره</button></div></div>;

 const renderOverview=()=>{const completion=org?.name?85:35;return <div className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">{[
  {t:'وضعیت سیستم',v:'فعال',s:'Frontend + Supabase',i:Activity,c:'success'},{t:'پروفایل سازمان',v:`${completion}%`,s:org?.name||'نیازمند تکمیل',i:Building2,c:'warning'},{t:'ظاهر',v:settings.theme==='dark'?'تیره':settings.theme==='light'?'روشن':'سیستم',s:`${settings.density==='compact'?'فشرده':'راحت'} / ${settings.calendar==='jalali'?'شمسی':'میلادی'}`,i:Palette,c:'neutral'},{t:'امنیت',v:profile?.role==='owner'?'مدیریت کامل':'استاندارد',s:`نقش: ${roleLabel[profile?.role||'']||'کاربر'}`,i:ShieldCheck,c:'success'}].map(x=><div key={x.t} className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex items-center justify-between"><div className="h-10 w-10 rounded-xl bg-[var(--surface-2)] grid place-items-center"><x.i size={18}/></div><span className={`status-pill ${x.c}`}>{x.c==='success'?'مناسب':x.c==='warning'?'تکمیل شود':'فعال'}</span></div><div className="mt-4 font-bold">{x.t}</div><div className="text-xl font-black mt-1">{x.v}</div><div className="text-xs app-muted mt-1">{x.s}</div></div>)}</div><Card title="دسترسی سریع" desc="متداول‌ترین تنظیمات را مستقیماً تغییر دهید" icon={Bolt}><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{[{s:'appearance',t:'ظاهر'},{s:'organization',t:'سازمان'},{s:'notifications',t:'اعلان‌ها'},{s:'security',t:'امنیت'}].map(x=><button key={x.s} onClick={()=>navigateSetting(x.s)} className="rounded-xl border app-border bg-[var(--surface-2)] p-3 text-right hover:border-[var(--primary)] transition"><div className="font-semibold text-sm">{x.t}</div><div className="text-[11px] app-muted mt-1">مشاهده و ویرایش</div></button>)}</div></Card><Card title="آخرین وضعیت تنظیمات" icon={History}><div className="grid md:grid-cols-3 gap-3"><div className="p-3 rounded-xl bg-[var(--surface-2)]"><div className="text-xs app-muted">تنظیمات سمت کاربر</div><div className="font-bold mt-1">Local Preferences</div></div><div className="p-3 rounded-xl bg-[var(--surface-2)]"><div className="text-xs app-muted">تنظیمات سازمان</div><div className="font-bold mt-1">Supabase</div></div><div className="p-3 rounded-xl bg-[var(--surface-2)]"><div className="text-xs app-muted">ثبت Audit</div><div className="font-bold mt-1">فعال در صورت مجوز RLS</div></div></div></Card></div>};
 const renderAccount=()=> <div className="space-y-4"><Card title="اطلاعات ورود" icon={KeyRound}><div className="grid md:grid-cols-2 gap-4"><Field label="ایمیل"><Input value={user?.email||''} disabled/></Field><Field label="شناسه کاربر"><Input value={user?.id||''} disabled/></Field><Field label="نقش"><Select value={profile?.role||''} disabled><option value={profile?.role||''}>{roleLabel[profile?.role||'']||profile?.role||'—'}</option></Select></Field><Field label="وضعیت"><div className="min-h-11 flex items-center"><span className="status-pill success">{profile?.is_active?'فعال':'غیرفعال'}</span></div></Field></div></Card><Card title="سیاست نشست" desc="مقادیر UI ذخیره می‌شوند؛ اعمال سمت Auth به تنظیمات پروژه Supabase وابسته است." icon={Timer}><div className="grid md:grid-cols-2 gap-4"><Field label="مدت نشست (دقیقه)"><Input type="number" min={5} max={1440} value={settings.sessionTimeout} onChange={e=>setSetting('sessionTimeout',Number(e.target.value))}/></Field><Field label="Auto-save"><div className="min-h-11 flex items-center"><Toggle checked={settings.autoSave} onChange={v=>setSetting('autoSave',v)}/></div></Field></div></Card>{basicSaveBar}</div>;
 const renderProfile=()=> <div className="space-y-4"><Card title="پروفایل فعلی" icon={User}><div className="flex items-center gap-4 mb-5"><div className="h-16 w-16 rounded-2xl grid place-items-center bg-[var(--primary)] text-white text-2xl font-black">{(profile?.full_name||'ک').slice(0,1)}</div><div><div className="font-black text-lg">{profile?.full_name||'کاربر'}</div><div className="text-xs app-muted">{roleLabel[profile?.role||'']||'کاربر'} · {profile?.phone||'شماره ثبت نشده'}</div></div></div><div className="grid md:grid-cols-2 gap-4"><Field label="نام و نام خانوادگی"><Input value={profile?.full_name||''} disabled/></Field><Field label="موبایل"><Input value={profile?.phone||''} disabled/></Field></div><div className="mt-4 p-3 rounded-xl bg-[var(--surface-2)] text-xs app-muted">ویرایش Profile باید با کنترل RLS جدول profiles انجام شود؛ این نسخه اطلاعات را از رکورد واقعی شما می‌خواند و از نمایش فرم جعلی خودداری می‌کند.</div></Card></div>;
 const renderAppearance=()=> <div className="space-y-4"><Card title="Theme Manager" desc="همین تنظیمات در AppearanceContext فعلی پروژه اعمال می‌شوند." icon={Palette}><div className="grid md:grid-cols-2 gap-4"><Field label="تم"><Select value={settings.theme} onChange={e=>setSetting('theme',e.target.value)}><option value="system">سیستم</option><option value="light">روشن</option><option value="dark">تیره</option></Select></Field><Field label="حالت مطالعه"><Select value={settings.comfort} onChange={e=>setSetting('comfort',e.target.value)}><option value="normal">عادی</option><option value="soft">ملایم</option><option value="warm">گرم</option><option value="reading">کتاب‌خوان</option></Select></Field><Field label="تراکم"><Select value={settings.density} onChange={e=>setSetting('density',e.target.value)}><option value="comfortable">راحت</option><option value="compact">فشرده</option></Select></Field><Field label="اندازه فونت"><Select value={settings.fontSize} onChange={e=>setSetting('fontSize',e.target.value)}><option value="small">کوچک</option><option value="medium">متوسط</option><option value="large">بزرگ</option></Select></Field></div><div className="mt-5 grid md:grid-cols-2 gap-4">{[['animations','انیمیشن‌ها'],['reducedMotion','کاهش حرکت'],['stickyHeader','Header چسبان جدول'],['zebraRows','ردیف‌های راه‌راه'],['hoverRows','Highlight ردیف'],['sidebarCollapsed','منوی کناری فشرده']].map(([k,l])=><div key={k} className="flex items-center justify-between p-3 rounded-xl bg-[var(--surface-2)]"><span className="text-sm font-semibold">{l}</span><Toggle checked={Boolean(settings[k])} onChange={v=>setSetting(k,v)}/></div>)}</div></Card>{basicSaveBar}</div>;
 const renderOrg=()=> <div className="space-y-4"><Card title="اطلاعات سازمان" desc="این بخش مستقیماً به جدول organizations فعلی متصل است." icon={Building2}><div className="grid md:grid-cols-2 gap-4"><Field label="نام سازمان"><Input value={orgDraft.name} onChange={e=>setOrgDraft(v=>({...v,name:e.target.value}))}/></Field><Field label="کد اقتصادی"><Input value={orgDraft.economic_code} onChange={e=>setOrgDraft(v=>({...v,economic_code:e.target.value}))}/></Field></div><div className="mt-4 flex justify-end"><button onClick={saveOrg} className="px-4 py-2 rounded-xl bg-[var(--primary)] text-white font-bold text-sm inline-flex items-center gap-2"><Save size={15}/> ذخیره سازمان</button></div></Card><Card title="پیش‌فرض‌های عملیاتی" icon={Map}><div className="grid md:grid-cols-2 gap-4"><Field label="گمرک پیش‌فرض"><Input value={settings.defaultCustomsOffice} onChange={e=>setSetting('defaultCustomsOffice',e.target.value)}/></Field><Field label="بندر پیش‌فرض"><Input value={settings.defaultPort} onChange={e=>setSetting('defaultPort',e.target.value)}/></Field></div></Card>{basicSaveBar}</div>;
 const renderNotifications=()=> <div className="space-y-4"><Card title="کانال‌های اعلان" icon={Bell}><div className="grid md:grid-cols-2 gap-3">{[['inApp','داخل سیستم'],['email','ایمیل'],['sms','SMS'],['whatsapp','WhatsApp'],['push','Push']].map(([k,l])=><div key={k} className="flex items-center justify-between p-3 rounded-xl bg-[var(--surface-2)]"><span className="text-sm font-semibold">{l}</span><Toggle checked={settings[`notify_${k}`]!==false} onChange={v=>setSetting(`notify_${k}`,v)}/></div>)}</div></Card><Card title="دسته‌بندی اعلان‌ها" icon={Activity}><div className="grid md:grid-cols-2 gap-3">{['تغییر وضعیت پرونده','ورود/رسیدن کشتی','وضعیت مجوز','پرداخت','انقضای سند','هشدار امنیتی','ارجاع کار','تأییدیه'].map((l,i)=><div key={l} className="flex items-center justify-between p-3 rounded-xl border app-border"><span className="text-sm">{l}</span><Toggle checked={settings[`cat_${i}`]!==false} onChange={v=>setSetting(`cat_${i}`,v)}/></div>)}</div><div className="mt-4 grid md:grid-cols-3 gap-4"><Field label="زمان ارسال"><Select value={settings.notifyFrequency||'instant'} onChange={e=>setSetting('notifyFrequency',e.target.value)}><option value="instant">فوری</option><option value="daily">روزانه</option><option value="weekly">هفتگی</option></Select></Field><Field label="ساعات سکوت"><div className="min-h-11 flex items-center"><Toggle checked={settings.quietHours} onChange={v=>setSetting('quietHours',v)}/></div></Field><Field label="بازه"><Input value={`${settings.quietFrom} تا ${settings.quietTo}`} onChange={()=>{}} disabled={!settings.quietHours}/></Field></div></Card>{basicSaveBar}</div>;
 const renderSecurity=()=> <div className="space-y-4"><Card title="مرکز امنیت" icon={Lock}><div className="grid md:grid-cols-3 gap-3"><div className="p-4 rounded-xl bg-[var(--surface-2)]"><div className="text-xs app-muted">2FA</div><div className="font-bold mt-1">مدیریت از Supabase Auth</div></div><div className="p-4 rounded-xl bg-[var(--surface-2)]"><div className="text-xs app-muted">Session</div><div className="font-bold mt-1">{settings.sessionTimeout} دقیقه</div></div><div className="p-4 rounded-xl bg-[var(--surface-2)]"><div className="text-xs app-muted">Security Score</div><div className="font-bold mt-1 text-[var(--success)]">قابل قبول</div></div></div><div className="mt-4 p-4 rounded-xl border border-[color-mix(in_srgb,var(--warning)_35%,var(--border))] bg-[color-mix(in_srgb,var(--warning)_7%,var(--surface))] flex gap-3"><AlertTriangle size={18} className="text-[var(--warning)] mt-0.5"/><div className="text-xs leading-6">عملیات‌هایی مثل Reset Password، مدیریت MFA و Session Revoke باید از API امن Auth انجام شوند و نباید با کلید Service Role در Browser پیاده‌سازی شوند.</div></div></Card></div>;
 const renderOperations=()=> <div className="space-y-4"><Card title="پیش‌فرض‌های عملیات گمرکی" icon={FileCheck2}><div className="grid md:grid-cols-2 gap-4"><Field label="Workflow پیش‌فرض"><Select value={settings.defaultWorkflow} onChange={e=>setSetting('defaultWorkflow',e.target.value)}><option value="standard">استاندارد</option><option value="fast">سریع</option><option value="manual">دستی</option></Select></Field><Field label="گمرک پیش‌فرض"><Input value={settings.defaultCustomsOffice} onChange={e=>setSetting('defaultCustomsOffice',e.target.value)}/></Field></div><div className="mt-5"><div className="text-sm font-bold mb-2">Statusهای فعلی</div><div className="flex flex-wrap gap-2">{['draft','submitted_epl','green','yellow','red','cleared','archived'].map(s=><span key={s} className="status-pill neutral">{s}</span>)}</div></div></Card><Card title="تنظیمات Vessel Tracking" icon={Ship}><div className="grid md:grid-cols-3 gap-4"><Field label="Auto Refresh (دقیقه)"><Input type="number" min={1} max={120} value={settings.vesselAutoRefresh} onChange={e=>setSetting('vesselAutoRefresh',Number(e.target.value))}/></Field><Field label="واحد سرعت"><Select value={settings.speedUnit||'knots'} onChange={e=>setSetting('speedUnit',e.target.value)}><option value="knots">گره دریایی</option><option value="kmh">km/h</option></Select></Field><Field label="واحد فاصله"><Select value={settings.distanceUnit||'nm'} onChange={e=>setSetting('distanceUnit',e.target.value)}><option value="nm">مایل دریایی</option><option value="km">کیلومتر</option></Select></Field></div></Card>{basicSaveBar}</div>;
 const renderFinance=()=> <div className="space-y-4"><Card title="ارز و نرخ‌ها" icon={Wallet}><div className="grid md:grid-cols-3 gap-4"><Field label="ارز پایه"><Select value={settings.currency} onChange={e=>setSetting('currency',e.target.value)}><option value="IRR">ریال ایران</option><option value="USD">دلار آمریکا</option><option value="EUR">یورو</option></Select></Field><Field label="روش نرخ ارز"><Select value={settings.exchangeMode} onChange={e=>setSetting('exchangeMode',e.target.value)}><option value="manual">دستی</option><option value="api">API</option></Select></Field><Field label="دقت اعشار"><Input type="number" min={0} max={6} value={settings.decimals??2} onChange={e=>setSetting('decimals',Number(e.target.value))}/></Field></div></Card><Card title="مالیات و هزینه‌ها" icon={BarChart3}><div className="grid md:grid-cols-3 gap-4"><Field label="VAT پیش‌فرض (%)"><Input type="number" min={0} max={100} value={settings.vatRate} onChange={e=>setSetting('vatRate',Number(e.target.value))}/></Field><Field label="هزینه‌های اصلی"><Input value={settings.costCategories||'گمرک، بندر، انبار، حمل، ترخیص، بازرسی، بیمه، بانک'} onChange={e=>setSetting('costCategories',e.target.value)}/></Field><Field label="شماره‌گذاری تراکنش"><Input value={settings.financePrefix||'FIN-1405-'} onChange={e=>setSetting('financePrefix',e.target.value)}/></Field></div></Card>{basicSaveBar}</div>;
 const renderDocuments=()=> <div className="space-y-4"><Card title="انواع اسناد" icon={FileText}><div className="grid md:grid-cols-2 gap-2">{['پروفورما','Invoice','Packing List','B/L','Certificate of Origin','Insurance','Inspection','Permit','اظهارنامه گمرکی','اسناد انبار'].map((x,i)=><div key={x} className="flex items-center justify-between p-3 rounded-xl bg-[var(--surface-2)]"><span className="text-sm font-semibold">{x}</span><Toggle checked={settings[`docRequired_${i}`]!==false} onChange={v=>setSetting(`docRequired_${i}`,v)} label="الزامی"/></div>)}</div><div className="mt-4 grid md:grid-cols-3 gap-4"><Field label="حداکثر حجم فایل (MB)"><Input type="number" value={settings.documentMaxMb} onChange={e=>setSetting('documentMaxMb',Number(e.target.value))}/></Field><Field label="Retention (روز)"><Input type="number" value={settings.retentionDays} onChange={e=>setSetting('retentionDays',Number(e.target.value))}/></Field><Field label="Versioning"><div className="min-h-11 flex items-center"><Toggle checked={settings.docVersioning!==false} onChange={v=>setSetting('docVersioning',v)}/></div></Field></div></Card>{basicSaveBar}</div>;
 const renderNumbering=()=> <div className="space-y-4"><Card title="مرکز شماره‌گذاری" icon={SlidersHorizontal}><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4"><Field label="Prefix پرونده"><Input value={settings.numberingPrefix} onChange={e=>setSetting('numberingPrefix',e.target.value.toUpperCase())}/></Field><Field label="تعداد ارقام"><Input type="number" min={4} max={10} value={settings.numberingDigits} onChange={e=>setSetting('numberingDigits',Number(e.target.value))}/></Field><Field label="سال"><div className="min-h-11 flex items-center"><Toggle checked={settings.numberingYear} onChange={v=>setSetting('numberingYear',v)} label="افزودن سال"/></div></Field><Field label="ماه"><div className="min-h-11 flex items-center"><Toggle checked={settings.numberingMonth} onChange={v=>setSetting('numberingMonth',v)} label="افزودن ماه"/></div></Field></div><div className="mt-5 rounded-xl border app-border bg-[var(--surface-2)] p-4"><div className="text-xs app-muted">Preview</div><div className="text-xl font-black tracking-wider mt-1">{settings.numberingPrefix}-{settings.numberingYear?'1405-':''}{String(1).padStart(Number(settings.numberingDigits), '0')}</div></div></Card>{basicSaveBar}</div>;
 const renderIntegrations=()=> <div className="space-y-4"><Card title="Integration Center" desc="وضعیت اتصالات موجود را بدون افشای Secret نمایش می‌دهد." icon={Plug}><div className="grid md:grid-cols-2 gap-3">{[
  ['Supabase','Backend / Auth / DB',true],['Storage','Document Storage',true],['Email','SMTP / Provider',false],['SMS','SMS Gateway',false],['WhatsApp','WhatsApp Business',false],['Maps','Map Provider',false],['Vessel Tracking','AIS / Tracking API',false],['Exchange Rate','FX API',false],['OCR','Document Extraction',false],['External API','Custom API',false]
 ].map(([n,d,connected])=><div key={String(n)} className="rounded-2xl border app-border p-4 bg-[var(--surface-2)]"><div className="flex items-start justify-between gap-3"><div><div className="font-bold">{n}</div><div className="text-xs app-muted mt-1">{d}</div></div><span className={`status-pill ${connected?'success':'neutral'}`}>{connected?'متصل':'پیکربندی نشده'}</span></div><div className="flex items-center justify-between mt-4"><span className="text-[11px] app-muted">Secret masked</span><button className="px-3 py-1.5 rounded-lg border app-border text-xs">Configure</button></div></div>)}</div></Card><Card title="API Key" icon={KeyRound}><div className="p-3 rounded-xl bg-[var(--surface-2)] text-xs app-muted">کلیدهای خصوصی باید در Secret / Edge Function نگهداری شوند؛ Browser فقط publishable configuration را دریافت کند.</div><div className="mt-3 flex items-center gap-2"><Input value={showSecret?'••••••••••••••••':'Secret hidden'} readOnly/><button onClick={()=>setShowSecret(v=>!v)} className="icon-btn">{showSecret?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></Card></div>;
 const renderSystem=()=> <div className="space-y-4"><Card title={active.label} desc="این بخش برای نسخه Enterprise آماده شده و قسمت‌های وابسته به Backend را به‌صورت صریح مشخص می‌کند." icon={active.icon}><div className="grid md:grid-cols-2 gap-3">{['کارکرد سیستم','پروتکل امنیت','تاریخچه تغییرات','وضعیت سرویس'].map((x,i)=><div key={x} className="p-4 rounded-xl bg-[var(--surface-2)]"><div className="text-xs app-muted">{x}</div><div className="font-bold mt-1">{i===0?'فعال':i===1?'RLS + Auth':i===2?'Audit Log':'در حال کار'}</div></div>)}</div><div className="mt-4 p-4 rounded-xl border app-border">{active.slug==='backup'?'Backup واقعی دیتابیس باید از زیرساخت Supabase/منبع امن اجرا شود؛ دکمه نمایشی بدون Backend ساخته نمی‌شود.':active.slug==='audit'?'Audit Log از جدول audit_logs فعلی خوانده می‌شود و قابلیت Diff Viewer می‌تواند در مرحله بعد روی همان داده فعال شود.':active.slug==='users'?'مدیریت کامل کاربران نیازمند Admin API امن است و نباید از Browser با service_role اجرا شود.':active.slug==='roles'?'Roleهای فعلی پروژه حفظ شده‌اند: owner, admin, broker, accountant, warehouse, client. برای Custom Role نیاز به مدل مجوز مستقل داریم.':'این ماژول در هسته Settings تعریف شده و برای قابلیت‌های Backend-specific بدون جعل اتصال نگه داشته شده است.'}</div></Card></div>;

 const renderContent=()=>{if(active.slug==='')return renderOverview();if(active.slug==='account')return renderAccount();if(active.slug==='profile')return renderProfile();if(active.slug==='appearance')return renderAppearance();if(active.slug==='organization')return renderOrg();if(active.slug==='notifications')return renderNotifications();if(active.slug==='security')return renderSecurity();if(['customs','clearance','transport','vessels','warehouse','permits','epl','statuses','client'].includes(active.slug))return renderOperations();if(active.slug==='finance'||active.slug==='currencies'||active.slug==='taxes'||active.slug==='units'||active.slug==='calendar'||active.slug==='printing'||active.slug==='templates')return renderFinance();if(active.slug==='documents')return renderDocuments();if(active.slug==='numbering')return renderNumbering();if(active.slug==='integrations'||active.slug==='webhooks')return renderIntegrations();return renderSystem();};
 return <div className="min-h-[calc(100vh-64px)] p-3 md:p-5 lg:p-6" dir="rtl"><div className="max-w-[1700px] mx-auto"><div className="flex items-center justify-between gap-3 mb-4"><div className="min-w-0"><div className="flex items-center gap-2 text-xs app-muted mb-1"><Settings2 size={14}/><span>Settings</span><ChevronLeft size={13}/><span>{active.en}</span></div><h1 className="text-2xl md:text-3xl font-black tracking-tight">تنظیمات</h1><p className="text-xs app-muted mt-1">مرکز کنترل تنظیمات Customs OS در سطح کاربر، سازمان، عملیات و زیرساخت</p></div><button onClick={()=>setMobileNav(v=>!v)} className="md:hidden icon-btn" aria-label="منوی تنظیمات"><Settings2 size={18}/></button></div><div className="grid md:grid-cols-[285px_minmax(0,1fr)] gap-4 lg:gap-5"><aside className={`${mobileNav?'block':'hidden'} md:block rounded-2xl border app-border bg-[var(--surface)] p-2 h-fit md:sticky md:top-[84px] max-h-[calc(100vh-100px)] overflow-y-auto`}><div className="p-2 pb-3"><div className="relative"><Search size={16} className="absolute right-3 top-1/2 -translate-y-1/2 app-muted"/><Input placeholder="جستجوی تنظیمات…" value={query} onChange={e=>setQuery(e.target.value)} className="pr-9"/></div></div>{groups.map(g=>{const its=filtered.filter(x=>x.group===g.id);if(!its.length)return null;return <div key={g.id} className="mb-3"><div className="px-3 py-2 text-[10px] font-bold app-muted">{g.label}</div>{its.map(x=>{const Icon=x.icon;const is=active.slug===x.slug;return <button key={x.slug} onClick={()=>navigateSetting(x.slug)} className={`w-full flex items-center gap-3 rounded-xl px-3 py-2.5 text-right transition ${is?'bg-[color-mix(in_srgb,var(--primary)_15%,var(--surface))] text-[var(--primary)]':'hover:bg-[var(--surface-2)]'}`}><Icon size={17}/><span className="min-w-0"><span className="block text-sm font-semibold truncate">{x.label}</span><span className="block text-[10px] app-muted truncate">{x.en}</span></span>{is&&<ChevronLeft size={15} className="mr-auto"/>}</button>})}</div>})}</aside><main className="min-w-0"><div className="rounded-2xl border app-border bg-[var(--surface)] p-4 md:p-5 mb-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-black">{sectionTitle}</h2><p className="text-xs app-muted mt-1">{sectionDesc}</p></div><span className="status-pill success">{profile?.role?roleLabel[profile.role]:'کاربر'}</span></div></div>{renderContent()}</main></div></div></div>;
};
