import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,FileText,FolderOpen,Loader2,Save,Sparkles,Trash2,Upload} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {useAuth} from '../context/AuthContext';
import {PreDeclarationPage} from './PreDeclarationPage';

type ShipmentForm={ownerId:string;ownerName:string;vesselName:string;imo:string;count:string;unit:string;net:string;gross:string;billOfLading:string};
type Vessel={id:string;name:string;imo_number?:string|null;shipping_line_id?:string|null};
type Extracted=Partial<Record<keyof ShipmentForm,string>>;
const KEY='customs_registered_shipment';
const empty:ShipmentForm={ownerId:'',ownerName:'',vesselName:'',imo:'',count:'',unit:'رول',net:'',gross:'',billOfLading:''};
const clean=(x:any)=>String(x??'').trim();
const num=(x:string)=>{const s=x.replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/,/g,'').trim();return s?Number(s):null};
const same=(a:string,b:string)=>clean(a).localeCompare(clean(b),'fa',{sensitivity:'base'})===0;
const pick=(o:any,...keys:string[])=>{for(const k of keys)if(o?.[k]!=null&&clean(o[k]))return clean(o[k]);return ''};
const toBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||'');resolve(s.includes(',')?s.split(',')[1]:s)};r.onerror=()=>reject(new Error('خواندن فایل ناموفق بود'));r.readAsDataURL(file)});

export const ShipmentFirstPage:React.FC=()=>{
 const{profile}=useAuth();const[input,setInput]=useState<ShipmentForm>({...empty});const[clients,setClients]=useState<any[]>([]);const[vessels,setVessels]=useState<Vessel[]>([]);const[vesselId,setVesselId]=useState('');const[files,setFiles]=useState<File[]>([]);const[extracted,setExtracted]=useState<Extracted>({});const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');const[registered,setRegistered]=useState<any|null>(null);const fileRef=useRef<HTMLInputElement|null>(null);
 const loadVessels=async()=>{if(!profile?.organization_id)return;const{data,error}=await supabase.from('vessels').select('id,name,imo_number,shipping_line_id').eq('organization_id',profile.organization_id).order('name');if(!error)setVessels((data||[]) as Vessel[])};
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setRegistered(JSON.parse(raw))}catch{};const load=async()=>{if(!profile?.organization_id)return;const[{data:c},{data:v}]=await Promise.all([supabase.from('clients').select('id,name,national_id').order('name'),supabase.from('vessels').select('id,name,imo_number,shipping_line_id').eq('organization_id',profile.organization_id).order('name')]);setClients(c||[]);setVessels((v||[]) as Vessel[])};load()},[profile?.organization_id]);
 const set=(k:keyof ShipmentForm,v:string)=>setInput(p=>({...p,[k]:v}));
 const selectVessel=(id:string)=>{const v=vessels.find(x=>x.id===id);setVesselId(id);if(v){set('vesselName',v.name);set('imo',v.imo_number||'')}};
 const addFiles=(list:FileList|null)=>{if(!list)return;setFiles(p=>[...p,...Array.from(list).filter(f=>/application\/pdf|image\//i.test(f.type)&&!p.some(x=>x.name===f.name&&x.size===f.size))])};
 const runAI=async()=>{if(!files.length)return setStatus('ابتدا سند کشتیرانی را آپلود کنید.');setBusy(true);setStatus('در حال استخراج اطلاعات محموله...');try{const documents=[] as any[];for(const f of files)documents.push({name:f.name,mime_type:f.type||'application/pdf',data:await toBase64(f)});const{data,error}=await supabase.functions.invoke('ai-assistant',{body:{query:'اطلاعات محموله را استخراج کن: نام صاحب کالا، نام کشتی، IMO، تعداد و واحد، وزن خالص، وزن ناخالص، شماره بارنامه. اگر کشتیرانی هم در سند وجود داشت در پاسخ بیاور اما فرم شروع عملیات فقط با نام کشتی کار می‌کند.',documents,shipment_extract:true,page_context:'/operations?tab=pre-declaration'}});if(error)throw error;const raw=data?.answer||data?.message||{};let p:any={};if(typeof raw==='object')p=raw;else{try{p=JSON.parse(raw)}catch{const m=String(raw).match(/\{[\s\S]*\}/);if(m)p=JSON.parse(m[0])}}const e:Extracted={ownerName:pick(p,'ownerName','clientName','cargoOwner','نام صاحب کالا'),vesselName:pick(p,'vesselName','vessel','shipName','نام کشتی'),imo:pick(p,'imo','imoNumber','IMO'),count:pick(p,'count','cargoCount','quantity','تعداد'),unit:pick(p,'unit','cargoCountUnit','quantityUnit','واحد'),net:pick(p,'netWeight','netWeightKg','وزن خالص','خالص'),gross:pick(p,'grossWeight','grossWeightKg','وزن ناخالص','ناخالص'),billOfLading:pick(p,'billOfLading','billOfLadingNo','bl','B/L','شماره بارنامه')};const owner=clients.find(c=>same(c.name,clean(e.ownerName)));const vessel=vessels.find(v=>same(v.name,clean(e.vesselName)));if(owner)e.ownerName=owner.name;if(vessel){setVesselId(vessel.id);e.vesselName=vessel.name;e.imo=vessel.imo_number||e.imo}setExtracted(e);setInput(prev=>({...prev,...Object.fromEntries(Object.entries(e).filter(([,v])=>clean(v))) as Partial<ShipmentForm>,ownerId:owner?.id||prev.ownerId}));setStatus(vessel?'اطلاعات استخراج شد؛ کشتی موجود انتخاب شد.':'اطلاعات استخراج شد؛ نام کشتی را بررسی کنید.')}catch(e:any){setStatus(e?.message||'استخراج ناموفق بود')}finally{setBusy(false)}};
 const ensureVessel=async()=>{const name=clean(input.vesselName);if(!name)throw new Error('نام کشتی الزامی است.');let v=vessels.find(x=>same(x.name,name));if(v){setVesselId(v.id);if(!input.imo&&v.imo_number)set('imo',v.imo_number);return v}const imo=clean(input.imo).replace(/\D/g,'');if(imo&&!/^\d{7}$/.test(imo))throw new Error('IMO باید ۷ رقم باشد.');const{data,error}=await supabase.from('vessels').insert({organization_id:profile?.organization_id,name,imo_number:imo||null,shipping_line_id:null}).select('id,name,imo_number,shipping_line_id').single();if(error)throw error;const row=data as Vessel;setVessels(p=>[...p,row].sort((a,b)=>a.name.localeCompare(b.name)));setVesselId(row.id);return row};
 const save=async()=>{if(!profile?.organization_id)return setStatus('اطلاعات سازمان کاربر آماده نیست.');if(!input.ownerId)return setStatus('نام صاحب کالا را انتخاب کنید.');if(!input.vesselName.trim())return setStatus('نام کشتی را وارد یا انتخاب کنید.');if(!/^\d{7}$/.test(input.imo.replace(/\D/g,'')))return setStatus('IMO باید ۷ رقم باشد.');if(!input.count.trim()||!input.net.trim()||!input.gross.trim())return setStatus('تعداد، وزن خالص و وزن ناخالص را وارد کنید.');setBusy(true);setStatus('در حال ثبت محموله...');try{const vessel=await ensureVessel();let shippingLine='';if(vessel.shipping_line_id){const{data:l}=await supabase.from('shipping_lines').select('name').eq('id',vessel.shipping_line_id).maybeSingle();shippingLine=l?.name||''}const{data:s,error}=await supabase.from('shipments').insert({organization_id:profile.organization_id,client_id:input.ownerId,vessel_id:vessel.id,transport_mode:'sea',shipping_line:shippingLine||null,bill_of_lading_no:input.billOfLading.trim()||null,bill_of_lading_year:new Date().getFullYear(),cargo_count:num(input.count),cargo_count_unit:input.unit.trim()||'رول',net_weight_kg:num(input.net),gross_weight_kg:num(input.gross),current_status:'draft'}).select('id').single();if(error)throw error;for(const file of files){const id=crypto.randomUUID();const path=`${profile.organization_id}/${s.id}/${id}-${file.name.replace(/[^\w.\-]+/g,'_')}`;const{error:up}=await supabase.storage.from('customs_documents').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(up)throw up;const name=window.prompt('نام نمایشی سند را وارد کنید:',file.name)?.trim()||file.name;const{error:de}=await supabase.from('shipment_documents').insert({id,organization_id:profile.organization_id,shipment_id:s.id,uploaded_by:null,document_name:name,original_file_name:file.name,storage_path:path,mime_type:file.type||'application/octet-stream',file_size_bytes:file.size});if(de)throw de}const saved={id:s.id,...input,vesselName:vessel.name,imo:vessel.imo_number||input.imo,shippingLine,registeredAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(saved));setRegistered(saved);setStatus(files.length?`محموله ثبت شد و ${files.length} سند ذخیره شد.`:'محموله ثبت شد. کشتی جدید در فهرست سازمان ذخیره شد.')}catch(e:any){setStatus(e?.message||'ثبت محموله ناموفق بود')}finally{setBusy(false)}};
 if(registered)return <div><section dir="rtl" className="max-w-6xl mx-auto p-4"><div className="rounded-xl border border-emerald-700 bg-emerald-950/30 p-4 flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs text-emerald-300">محموله ثبت شده</div><div className="font-black mt-1">{registered.count} {registered.unit||'رول'} · {registered.vesselName} · {registered.ownerName}</div><div className="text-xs text-slate-400 mt-1">IMO: {registered.imo} · B/L: {registered.billOfLading||'—'}</div></div><div className="flex gap-2"><Link to="/documents/extract" className="text-xs px-3 py-2 rounded-lg bg-blue-600 font-bold"><FolderOpen className="inline ml-1" size={14}/>اسناد</Link><button onClick={()=>{localStorage.removeItem(KEY);setRegistered(null)}} className="text-xs px-3 py-2 rounded-lg border border-slate-700">محموله دیگر</button></div></div></section><PreDeclarationPage/></div>;
 return <main dir="rtl" className="min-h-screen bg-slate-950 text-slate-100 p-4 sm:p-6 lg:p-8"><div className="max-w-5xl mx-auto space-y-4"><header className="flex items-center justify-between"><div><div className="text-xs text-slate-500">CUSTOMS / SHIPPING CARGO</div><h1 className="text-2xl font-black mt-1">۱. شروع عملیات</h1><p className="text-xs text-slate-400 mt-1">فقط کشتی را انتخاب کنید؛ اگر وجود نداشت نام آن را تایپ کنید تا هنگام ثبت خودکار ذخیره شود.</p></div><Link to="/" className="px-3 py-2 rounded-lg border border-slate-700 bg-slate-900 text-sm"><ArrowRight className="inline ml-1" size={16}/>صفحه اصلی</Link></header>
 <section className="bg-slate-900 border border-slate-800 rounded-xl p-4"><label className="block text-sm font-bold mb-2">نام کشتی</label><input list="shipment-vessels" value={input.vesselName} onChange={e=>{set('vesselName',e.target.value);const v=vessels.find(x=>same(x.name,e.target.value));if(v)selectVessel(v.id);else setVesselId('')}} placeholder="نام کشتی را انتخاب یا تایپ کنید..." className="w-full min-h-12 rounded-lg border border-slate-700 bg-slate-950 px-4 text-base" autoComplete="off"/><datalist id="shipment-vessels">{vessels.map(v=><option key={v.id} value={v.name}>{v.imo_number?`IMO ${v.imo_number}`:''}</option>)}</datalist>{vesselId&&<div className="mt-2 text-[11px] text-emerald-300">کشتی از فهرست سازمان انتخاب شد.</div>}{!vesselId&&input.vesselName&&<div className="mt-2 text-[11px] text-slate-400">کشتی جدید هنگام ثبت خودکار در فهرست ذخیره می‌شود.</div>}</section>
 <section className="bg-slate-900 border border-slate-800 rounded-xl p-4"><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><label><span className="block text-xs text-slate-400 mb-1">صاحب کالا</span><select value={input.ownerId} onChange={e=>{const c=clients.find(x=>x.id===e.target.value);set('ownerId',e.target.value);set('ownerName',c?.name||'')}} className="w-full min-h-10 rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm"><option value="">انتخاب صاحب کالا</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className="block text-xs text-slate-400 mb-1">IMO</span><input value={input.imo} onChange={e=>set('imo',e.target.value)} dir="ltr" className="w-full min-h-10 rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm"/></label><label><span className="block text-xs text-slate-400 mb-1">شماره B/L</span><input value={input.billOfLading} onChange={e=>set('billOfLading',e.target.value)} className="w-full min-h-10 rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm"/></label></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3"><label><span className="block text-xs text-slate-400 mb-1">تعداد</span><input value={input.count} onChange={e=>set('count',e.target.value)} dir="ltr" className="w-full min-h-10 rounded-lg border border-slate-700 bg-slate-950 px-3"/></label><label><span className="block text-xs text-slate-400 mb-1">واحد</span><input value={input.unit} onChange={e=>set('unit',e.target.value)} className="w-full min-h-10 rounded-lg border border-slate-700 bg-slate-950 px-3"/></label><label><span className="block text-xs text-slate-400 mb-1">وزن خالص</span><input value={input.net} onChange={e=>set('net',e.target.value)} dir="ltr" className="w-full min-h-10 rounded-lg border border-slate-700 bg-slate-950 px-3"/></label><label><span className="block text-xs text-slate-400 mb-1">وزن ناخالص</span><input value={input.gross} onChange={e=>set('gross',e.target.value)} dir="ltr" className="w-full min-h-10 rounded-lg border border-slate-700 bg-slate-950 px-3"/></label></div>{extracted.vesselName&&<div className="mt-3 text-[11px] text-blue-300">خوانش سند: {extracted.vesselName}{extracted.imo?` · IMO ${extracted.imo}`:''}</div>}</section>
 <section className="bg-slate-900 border border-slate-800 rounded-xl p-4"><div className="flex items-center justify-between gap-3"><div><b className="text-sm">سند محموله</b><p className="text-[11px] text-slate-500 mt-1">اختیاری؛ برای استخراج خودکار اطلاعات</p></div><input ref={fileRef} type="file" multiple accept="application/pdf,image/*" className="hidden" onChange={e=>addFiles(e.target.files)}/><button onClick={()=>fileRef.current?.click()} className="px-3 py-2 rounded-lg border border-slate-700 text-xs"><Upload className="inline ml-1" size={14}/>انتخاب سند</button></div>{files.length>0&&<div className="mt-3 space-y-1">{files.map((f,i)=><div key={`${f.name}-${i}`} className="flex items-center justify-between rounded-lg bg-slate-950 px-3 py-2 text-xs"><span className="truncate">{f.name}</span><button onClick={()=>setFiles(p=>p.filter((_,j)=>j!==i))} className="text-red-400"><Trash2 size={14}/></button></div>)}</div>}{files.length>0&&<button disabled={busy} onClick={runAI} className="mt-3 w-full min-h-10 rounded-lg bg-blue-600 text-xs font-bold">{busy?<><Loader2 className="inline ml-1 animate-spin" size={15}/>در حال استخراج...</>:<><Sparkles className="inline ml-1" size={15}/>استخراج اطلاعات سند</>}</button>}</section>
 {status&&<div className="rounded-lg border border-slate-800 bg-slate-900 px-3 py-2 text-xs">{status}</div>}<div className="flex justify-end"><button onClick={save} disabled={busy} className="min-h-11 px-5 rounded-lg bg-emerald-600 text-white font-bold text-sm"><Save className="inline ml-1" size={16}/>ثبت محموله</button></div>
 </div></main>;
};
export default ShipmentFirstPage;
