import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,Loader2,Save,Sparkles,Trash2,Upload,CheckCircle2} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {useAuth} from '../context/AuthContext';
import {PreDeclarationPage} from './PreDeclarationPage';

type ShipmentForm={ownerId:string;ownerName:string;vesselName:string;imo:string;count:string;unit:string;net:string;gross:string;billOfLading:string};
type Vessel={id:string;name:string;imo_number?:string|null;shipping_line_id?:string|null};
type Extracted=Partial<Record<keyof ShipmentForm,string>>;
const KEY='customs_registered_shipment';
const empty:ShipmentForm={ownerId:'',ownerName:'',vesselName:'',imo:'',count:'',unit:'رول',net:'',gross:'',billOfLading:''};
const clean=(x:any)=>String(x??'').trim();
const same=(a:string,b:string)=>clean(a).localeCompare(clean(b),'fa',{sensitivity:'base'})===0;
const pick=(o:any,...keys:string[])=>{for(const k of keys)if(o?.[k]!=null&&clean(o[k]))return clean(o[k]);return ''};
const toBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result||'');resolve(s.includes(',')?s.split(',')[1]:s)};r.onerror=()=>reject(new Error('خواندن فایل ناموفق بود'));r.readAsDataURL(file)});
const persianDigits=(s:string)=>s.replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d)));
const weightKg=(value:string)=>{let s=persianDigits(clean(value)).replace(/,/g,'').replace(/٬/g,'').replace(/،/g,'.').trim();const m=s.match(/(-?\d+(?:\.\d+)?)\s*(MT|M\/T|TONNES?|TON|T|تن|کیلوگرم|کیلو|KG|KGS|G|GRAMS?|گرم)?/i);if(!m)return '';const n=Number(m[1]);if(!Number.isFinite(n))return '';const unit=clean(m[2]).toUpperCase();let kg=n;if(/^(MT|M\/T|TONNES?|TON|T|تن)$/.test(unit))kg=n*1000;else if(/^(G|GRAMS?|گرم)$/.test(unit))kg=n/1000;return String(Math.round(kg));};
const integerNumber=(value:string)=>{const n=Number(persianDigits(clean(value)).replace(/,/g,'').replace(/٬/g,'').replace(/،/g,'.'));return Number.isFinite(n)?Math.round(n):null};
export const ShipmentFirstPage:React.FC=()=>{const{profile}=useAuth();const[input,setInput]=useState({...empty});const[clients,setClients]=useState<any[]>([]);const[vessels,setVessels]=useState<Vessel[]>([]);const[vesselId,setVesselId]=useState('');const[files,setFiles]=useState<File[]>([]);const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');const[registered,setRegistered]=useState<any|null>(null);const fileRef=useRef<HTMLInputElement|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setRegistered(JSON.parse(raw))}catch{};if(!profile?.organization_id)return;Promise.all([supabase.from('clients').select('id,name,national_id').order('name'),supabase.from('vessels').select('id,name,imo_number,shipping_line_id').eq('organization_id',profile.organization_id).order('name')]).then(([c,v])=>{setClients(c.data||[]);setVessels((v.data||[]) as Vessel[])})},[profile?.organization_id]);
 const set=(k:keyof ShipmentForm,v:string)=>setInput(prev=>({...prev,[k]:v}));
 const selectVessel=(id:string)=>{const v=vessels.find(x=>x.id===id);setVesselId(id);if(v){set('vesselName',v.name);set('imo',v.imo_number||'')}};
 const addFiles=(list:FileList|null)=>{if(!list)return;setFiles(p=>[...p,...Array.from(list).filter(f=>/application\/pdf|image\//i.test(f.type)&&!p.some(x=>x.name===f.name&&x.size===f.size))])};
 const runAI=async()=>{if(!files.length){setStatus('ابتدا سند حمل را بارگذاری کنید.');return}setBusy(true);setStatus('در حال استخراج اطلاعات و تبدیل وزن‌ها به کیلوگرم...');try{const documents=[] as any[];for(const f of files)documents.push({name:f.name,mime_type:f.type||'application/pdf',data:await toBase64(f)});const{data,error}=await supabase.functions.invoke('ai-assistant',{body:{query:'اطلاعات محموله را استخراج کن: نام صاحب کالا، نام کشتی، IMO، تعداد و واحد، وزن خالص، وزن ناخالص، شماره بارنامه. وزن خالص و ناخالص را دقیقاً از سند بخوان و مقدار عددی را همراه واحد اصلی برگردان. برای کالای ورق آهن با تعرفه 72083900 واحد تعداد را رول در نظر بگیر. نام کشتی را دقیقاً همان‌طور که در سند آمده برگردان.',documents,shipment_extract:true,page_context:'/operations?tab=pre-declaration'}});if(error)throw error;const raw=data?.answer||data?.message||{};let p:any={};if(typeof raw==='object')p=raw;else{try{p=JSON.parse(raw)}catch{const m=String(raw).match(/\{[\s\S]*\}/);if(m)p=JSON.parse(m[0])}}const e:Extracted={ownerName:pick(p,'ownerName','clientName','cargoOwner','نام صاحب کالا'),vesselName:pick(p,'vesselName','vessel','shipName','نام کشتی'),imo:pick(p,'imo','imoNumber','IMO'),count:pick(p,'count','cargoCount','quantity','تعداد'),unit:'رول',net:weightKg(pick(p,'netWeight','net','netWeightKg','وزن خالص','خالص')),gross:weightKg(pick(p,'grossWeight','gross','grossWeightKg','وزن ناخالص','ناخالص')),billOfLading:pick(p,'billOfLading','billOfLadingNo','bl','B/L','شماره بارنامه')};const owner=clients.find(c=>same(c.name,clean(e.ownerName))),vessel=vessels.find(v=>same(v.name,clean(e.vesselName)));if(owner)e.ownerName=owner.name;if(vessel){setVesselId(vessel.id);e.vesselName=vessel.name;e.imo=vessel.imo_number||e.imo}setInput(prev=>({...prev,...Object.fromEntries(Object.entries(e).filter(([,v])=>clean(v))),ownerId:owner?.id||prev.ownerId}));setStatus('استخراج انجام شد؛ وزن‌ها به صورت عدد صحیح کیلوگرم نمایش داده می‌شوند.')}catch(e:any){setStatus(e?.message||'استخراج ناموفق بود')}finally{setBusy(false)}};
 const ensureVessel=async()=>{const name=clean(input.vesselName);if(!name)throw new Error('نام کشتی الزامی است.');let v=vessels.find(x=>same(x.name,name));if(v)return v;const imo=clean(input.imo).replace(/\D/g,'');if(imo&&!/^\d{7}$/.test(imo))throw new Error('IMO باید ۷ رقم باشد.');const{data,error}=await supabase.from('vessels').insert({organization_id:profile?.organization_id,name,imo_number:imo||null,shipping_line_id:null}).select('id,name,imo_number,shipping_line_id').single();if(error)throw error;const row=data as Vessel;setVessels(p=>[...p,row]);return row};
 const save=async()=>{if(!profile?.organization_id)return setStatus('اطلاعات سازمان کاربر آماده نیست.');if(!input.ownerId)return setStatus('نام صاحب کالا را انتخاب کنید.');if(!input.vesselName.trim())return setStatus('نام کشتی را وارد یا انتخاب کنید.');if(!input.count.trim()||!input.net.trim()||!input.gross.trim())return setStatus('تعداد، وزن خالص و وزن ناخالص را تکمیل کنید.');const net=weightKg(input.net);const gross=weightKg(input.gross);if(!net||!gross)return setStatus('وزن خالص و ناخالص باید به صورت عدد وارد شوند.');setBusy(true);setStatus('در حال ثبت محموله...');try{const vessel=await ensureVessel();let shippingLine='';if(vessel.shipping_line_id){const{data:l}=await supabase.from('shipping_lines').select('name').eq('id',vessel.shipping_line_id).maybeSingle();shippingLine=l?.name||''}const{data:s,error}=await supabase.from('shipments').insert({organization_id:profile.organization_id,client_id:input.ownerId,vessel_id:vessel.id,transport_mode:'sea',shipping_line:shippingLine||null,bill_of_lading_no:input.billOfLading.trim()||null,bill_of_lading_year:new Date().getFullYear(),cargo_count:integerNumber(input.count),cargo_count_unit:'رول',net_weight_kg:integerNumber(net),gross_weight_kg:integerNumber(gross),current_status:'draft'}).select('id').single();if(error)throw error;for(const file of files){const id=crypto.randomUUID();const path=`${profile.organization_id}/${s.id}/${id}-${file.name.replace(/[^\w.\-]+/g,'_')}`;const{error:up}=await supabase.storage.from('customs_documents').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(up)throw up;const{error:de}=await supabase.from('shipment_documents').insert({id,organization_id:profile.organization_id,shipment_id:s.id,uploaded_by:null,document_name:file.name,original_file_name:file.name,storage_path:path,mime_type:file.type||'application/octet-stream',file_size_bytes:file.size});if(de)throw de}const saved={id:s.id,...input,unit:'رول',net,gross,vesselName:vessel.name,imo:vessel.imo_number||input.imo,shippingLine,registeredAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(saved));setRegistered(saved);setStatus('محموله با موفقیت ثبت شد.')}catch(e:any){setStatus(e?.message||'ثبت محموله ناموفق بود')}finally{setBusy(false)}};
 if(registered)return <div><section dir="rtl" className="max-w-6xl mx-auto p-4"><div className="rounded-2xl border border-emerald-700 bg-emerald-950/30 p-4 flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs text-emerald-300">محموله ثبت شده</div><div className="font-black mt-1">{registered.count} {registered.unit||'رول'} · {registered.vesselName} · {registered.ownerName}</div><div className="text-xs app-muted mt-1">وزن خالص: {registered.net||'—'} کیلوگرم · وزن ناخالص: {registered.gross||'—'} کیلوگرم · شماره بارنامه: {registered.billOfLading||'—'}</div></div><button onClick={()=>{localStorage.removeItem(KEY);setRegistered(null)}} className="text-xs px-3 py-2 rounded-lg border app-border">محموله دیگر</button></div></section><PreDeclarationPage/></div>;
 return <main dir="rtl" className="min-h-screen bg-slate-950 text-slate-100 p-4 sm:p-6 lg:p-8"><div className="max-w-6xl mx-auto space-y-4"><header className="flex items-center justify-between"><div><h1 className="text-2xl font-black mt-1">۱. شروع عملیات</h1><p className="text-xs text-slate-400 mt-1">نام کشتی را انتخاب یا تایپ کنید؛ کشتی جدید هنگام ثبت ذخیره می‌شود.</p></div><Link to="/" className="px-3 py-2 rounded-lg border border-slate-700 bg-slate-900 text-sm"><ArrowRight className="inline ml-1" size={16}/>صفحه اصلی</Link></header>
 <section className="bg-slate-900 border border-slate-800 rounded-2xl p-4"><label className="block text-sm font-bold mb-2">نام کشتی</label><input list="shipment-vessels" value={input.vesselName} onChange={e=>{set('vesselName',e.target.value);const v=vessels.find(x=>same(x.name,e.target.value));if(v)selectVessel(v.id);else setVesselId('')}} placeholder="نام کشتی را انتخاب یا تایپ کنید..." className="w-full min-h-12 rounded-xl border border-slate-700 bg-slate-950 px-4 text-base"/><datalist id="shipment-vessels">{vessels.map(v=><option key={v.id} value={v.name}/>)}</datalist>{vesselId&&<div className="mt-2 text-[11px] text-emerald-300">کشتی از فهرست سازمان انتخاب شد.</div>}</section>
 <section className="bg-slate-900 border border-slate-800 rounded-2xl p-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><label><span className="block text-xs text-slate-400 mb-1">صاحب کالا</span><select value={input.ownerId} onChange={e=>{const c=clients.find(x=>x.id===e.target.value);set('ownerId',e.target.value);set('ownerName',c?.name||'')}} className="w-full min-h-11 rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm"><option value="">انتخاب صاحب کالا</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className="block text-xs text-slate-400 mb-1">شماره بارنامه</span><input value={input.billOfLading} onChange={e=>set('billOfLading',e.target.value)} className="w-full min-h-11 rounded-xl border border-slate-700 bg-slate-950 px-3"/></label></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3"><label><span className="block text-xs text-slate-400 mb-1">تعداد</span><input value={input.count} onChange={e=>set('count',e.target.value)} dir="ltr" className="w-full min-h-11 rounded-xl border border-slate-700 bg-slate-950 px-3"/></label><label><span className="block text-xs text-slate-400 mb-1">واحد</span><input value="رول" readOnly className="w-full min-h-11 rounded-xl border border-slate-700 bg-slate-950 px-3"/></label><label><span className="block text-xs text-slate-400 mb-1">وزن خالص (کیلوگرم)</span><input value={input.net} onChange={e=>set('net',weightKg(e.target.value))} dir="ltr" inputMode="numeric" className="w-full min-h-11 rounded-xl border border-slate-700 bg-slate-950 px-3"/></label><label><span className="block text-xs text-slate-400 mb-1">وزن ناخالص (کیلوگرم)</span><input value={input.gross} onChange={e=>set('gross',weightKg(e.target.value))} dir="ltr" inputMode="numeric" className="w-full min-h-11 rounded-xl border border-slate-700 bg-slate-950 px-3"/></label></div></section>
 <section className="bg-slate-900 border border-slate-800 rounded-2xl p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-sm">استخراج هوشمند</h2><p className="text-xs text-slate-400 mt-1">سند را اضافه کنید؛ وزن‌ها به کیلوگرم صحیح تبدیل می‌شوند.</p></div><div className="flex gap-2"><button onClick={()=>fileRef.current?.click()} className="px-3 py-2 rounded-xl border border-slate-700 text-xs"><Upload size={14} className="inline ml-1"/>افزودن سند</button><button onClick={runAI} disabled={busy||!files.length} className="px-3 py-2 rounded-xl bg-cyan-600 text-white text-xs font-bold"><Sparkles size={14} className="inline ml-1"/>{busy?'در حال استخراج...':'استخراج با هوش مصنوعی'}</button></div></div><input ref={fileRef} type="file" accept="application/pdf,image/*" multiple className="hidden" onChange={e=>addFiles(e.target.files)}/>{files.length>0&&<div className="mt-3 space-y-1">{files.map(f=><div key={f.name+f.size} className="flex items-center justify-between rounded-lg bg-slate-950 px-3 py-2 text-xs"><span>{f.name}</span><button onClick={()=>setFiles(p=>p.filter(x=>x!==f))}><Trash2 size={14}/></button></div>)}</div>}</section>
 <div className="rounded-xl border border-slate-800 bg-slate-900 px-4 py-3 min-h-12 flex items-center gap-2 text-xs">{busy?<Loader2 className="animate-spin" size={16}/>:status.includes('موفقیت')?<CheckCircle2 size={16} className="text-emerald-400"/>:<Sparkles size={16} className="text-cyan-400"/>}<span>{status||'سند را بارگذاری و استخراج کنید؛ سپس اطلاعات را کنترل کنید.'}</span></div>
 <div className="flex justify-end pt-1 pb-10"><button onClick={save} disabled={busy} className="min-w-44 min-h-12 px-5 rounded-xl bg-[var(--primary)] text-white font-black text-sm shadow-lg hover:brightness-110 disabled:opacity-50"><Save size={17} className="inline ml-2"/>{busy?'در حال ثبت...':'ثبت محموله'}</button></div>
 </div></main>;
};