import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,Link2,RefreshCw,Unlink2} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';

type Shipment={id:string;case_id:string|null;client_id:string|null;bill_of_lading_no:string|null;cargo_count:number|null;cargo_count_unit:string|null;net_weight_kg:number|null;current_status:string|null;vessel_name?:string|null;client_name?:string|null};
type CaseRow={id:string;case_number:string|null;client_id:string|null;status:string|null};
const statusLabel:Record<string,string>={draft:'پیش‌نویس',registration_order:'ثبت سفارش',documents_ready:'اسناد آماده',epl_submitted:'اظهار ثبت شد',kottaj_received:'کوتاژ دریافت شد',path_green:'مسیر سبز',path_yellow:'مسیر زرد',path_red:'مسیر قرمز',valuation:'ارزش‌گذاری',duties_calculation:'محاسبه حقوق',exit_permit:'مجوز خروج',completed:'تکمیل‌شده',archived:'بایگانی'};
const shipmentStatus:Record<string,string>={draft:'پیش‌نویس',booking_confirmed:'تأیید رزرو',loading:'در حال بارگیری',loaded:'بارگیری کامل',departed:'حرکت',in_transit:'در مسیر',approaching_destination:'نزدیک مقصد',anchorage:'لنگرگاه',berthing:'پهلوگیری',discharging:'در حال تخلیه',discharged:'تخلیه کامل',completed:'تکمیل',delayed:'تأخیر',cancelled:'لغو'};
const num=(v:number|null)=>v==null?'—':new Intl.NumberFormat('fa-IR').format(Number(v));

export const ShipmentCaseLinkPage:React.FC=()=>{
 const[shipments,setShipments]=useState<Shipment[]>([]),[cases,setCases]=useState<CaseRow[]>([]),[selected,setSelected]=useState<Record<string,string>>({}),[loading,setLoading]=useState(false),[saving,setSaving]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const[sh,cs]=await Promise.all([
  supabase.rpc('get_control_center_shipments'),
  supabase.from('cases').select('id,case_number,client_id,status').order('created_at',{ascending:false})
 ]);if(sh.error)throw sh.error;if(cs.error)throw cs.error;setShipments((sh.data||[]) as Shipment[]);setCases((cs.data||[]) as CaseRow[]);}catch(e:any){setError(e?.message||'خطا در دریافت اطلاعات')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const unlinked=useMemo(()=>shipments.filter(s=>!s.case_id),[shipments]);
 const linked=useMemo(()=>shipments.filter(s=>s.case_id),[shipments]);
 const caseOptions=(s:Shipment)=>cases.filter(c=>!s.client_id||!c.client_id||c.client_id===s.client_id);
 const link=async(s:Shipment)=>{const caseId=selected[s.id];if(!caseId)return setError('ابتدا پرونده مقصد را انتخاب کنید.');setSaving(s.id);setError('');setSuccess('');try{const{error:e}=await supabase.rpc('link_shipment_to_case',{p_shipment_id:s.id,p_case_id:caseId});if(e)throw e;setSuccess(`محموله ${s.bill_of_lading_no||'بدون B/L'} به پرونده متصل شد و اسناد آن نیز به پرونده لینک شدند.`);setSelected(x=>{const n={...x};delete n[s.id];return n});await load();}catch(e:any){setError(e?.message||'اتصال محموله به پرونده انجام نشد.')}finally{setSaving('')}};
 return <main className="min-h-screen p-4 sm:p-6 lg:p-8" dir="rtl"><div className="max-w-[1500px] mx-auto">
  <header className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-6"><div><div className="text-xs app-muted mb-2">Shipment → Case</div><h1 className="text-2xl sm:text-3xl font-black">اتصال محموله به پرونده</h1><p className="text-sm app-muted mt-1">محموله‌های بدون پرونده را به پرونده صحیح متصل کنید. اتصال از سمت دیتابیس کنترل سازمان و صاحب کالا را انجام می‌دهد.</p></div><div className="flex gap-2"><button onClick={load} disabled={loading} className="icon-btn" title="بروزرسانی"><RefreshCw size={17} className={loading?'animate-spin':''}/></button><Link to="/control" className="inline-flex items-center gap-2 rounded-xl border app-border bg-[var(--surface)] px-4 py-2.5 text-sm font-bold"><ArrowRight size={16}/> مرکز کنترل</Link></div></header>
  {error&&<div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm">{error}</div>}{success&&<div className="mb-4 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm flex items-center gap-2"><CheckCircle2 size={17}/>{success}</div>}
  <div className="grid grid-cols-2 gap-3 mb-5"><div className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="text-xs app-muted">محموله بدون پرونده</div><div className="text-2xl font-black mt-1">{num(unlinked.length)}</div></div><div className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="text-xs app-muted">محموله دارای پرونده</div><div className="text-2xl font-black mt-1">{num(linked.length)}</div></div></div>
  <section className="rounded-2xl border app-border bg-[var(--surface)] overflow-hidden"><div className="p-4 border-b app-border flex items-center justify-between"><div><h2 className="font-black flex items-center gap-2"><Link2 size={18}/> نیازمند اتصال</h2><p className="text-xs app-muted mt-1">هیچ اتصال حدسی یا خودکاری انجام نمی‌شود.</p></div></div>
   {unlinked.length===0?<div className="p-10 text-center app-muted text-sm">همه محموله‌های قابل مشاهده به پرونده متصل هستند.</div>:<div className="divide-y app-border">{unlinked.map(s=>{const opts=caseOptions(s);return <div key={s.id} className="p-4"><div className="grid xl:grid-cols-[1.4fr_1fr_1fr_auto] gap-3 items-center"><div><div className="font-black">B/L: {s.bill_of_lading_no||'—'}</div><div className="text-xs app-muted mt-1">{num(s.cargo_count)} {s.cargo_count_unit||''} · {num(s.net_weight_kg)} kg · {s.client_name||'صاحب کالا نامشخص'}</div></div><div className="text-sm"><span className="app-muted">وضعیت محموله: </span>{shipmentStatus[s.current_status||'']||s.current_status||'—'}</div><div><select value={selected[s.id]||''} onChange={e=>setSelected(x=>({...x,[s.id]:e.target.value}))} className="w-full rounded-xl border app-border bg-[var(--surface-2)] px-3 py-2.5 text-sm"><option value="">انتخاب پرونده مقصد</option>{opts.map(c=><option key={c.id} value={c.id}>{c.case_number||c.id.slice(0,8)} · {statusLabel[c.status||'']||c.status||'—'}</option>)}</select>{opts.length===0&&<div className="text-[11px] text-amber-500 mt-1">پرونده سازگار با صاحب کالا پیدا نشد.</div>}</div><button disabled={!selected[s.id]||saving===s.id} onClick={()=>link(s)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--primary)] text-white px-4 py-2.5 text-sm font-bold disabled:opacity-40">{saving===s.id?<RefreshCw size={16} className="animate-spin"/>:<Link2 size={16}/>} اتصال</button></div></div>})}</div>}
  </section>
  <section className="mt-5 rounded-2xl border app-border bg-[var(--surface)] p-4 text-xs app-muted"><div className="font-bold text-[var(--text)] mb-1 flex items-center gap-2"><Unlink2 size={15}/> نکته</div>بعد از اتصال، shipment.case_id ثبت می‌شود و اسناد customs_documents همان محموله که هنوز پرونده نداشتند نیز به همان پرونده متصل می‌شوند. سندهای قدیمی shipment_documents بدون نوع/وضعیت، همچنان به‌صورت legacy باقی می‌مانند و بدون تأیید شما طبقه‌بندی نمی‌شوند.</section>
 </div></main>;
};
