import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Move,Plus,RefreshCw,Ship,Trash2} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {useAuth} from '../context/AuthContext';

type Line={id:string;name:string;name_fa?:string|null};
type Vessel={id:string;name:string;imo_number?:string|null;shipping_line_id?:string|null};
const clean=(v:any)=>String(v??'').trim();

export const ShippingManagementPage:React.FC=()=>{
 const{profile}=useAuth();const nav=useNavigate();
 const[lines,setLines]=useState<Line[]>([]);const[vessels,setVessels]=useState<Vessel[]>([]);const[lineId,setLineId]=useState('');
 const[newLine,setNewLine]=useState('');const[newLineFa,setNewLineFa]=useState('');const[newVessel,setNewVessel]=useState('');const[newIMO,setNewIMO]=useState('');const[moveTo,setMoveTo]=useState('');const[status,setStatus]=useState('');const[busy,setBusy]=useState(false);
 const selectedLine=useMemo(()=>lines.find(x=>x.id===lineId),[lines,lineId]);
 const loadLines=async()=>{if(!profile?.organization_id)return;const{data,error}=await supabase.from('shipping_lines').select('id,name,name_fa').eq('organization_id',profile.organization_id).order('name');if(!error)setLines((data||[]) as Line[])};
 const loadVessels=async(id='')=>{if(!profile?.organization_id)return;let q=supabase.from('vessels').select('id,name,imo_number,shipping_line_id').eq('organization_id',profile.organization_id).order('name');if(id)q=q.eq('shipping_line_id',id);const{data,error}=await q;if(!error)setVessels((data||[]) as Vessel[])};
 useEffect(()=>{loadLines();loadVessels()},[profile?.organization_id]);useEffect(()=>{loadVessels(lineId)},[lineId,profile?.organization_id]);
 const addLine=async()=>{const name=clean(newLine);if(!name)return setStatus('نام کشتیرانی را وارد کنید.');setBusy(true);const{data,error}=await supabase.from('shipping_lines').insert({organization_id:profile?.organization_id,name,name_fa:clean(newLineFa)||null}).select('id,name,name_fa').single();setBusy(false);if(error)return setStatus(error.message);setLines(p=>[...p,data as Line].sort((a,b)=>a.name.localeCompare(b.name)));setLineId(data.id);setNewLine('');setNewLineFa('');setStatus(`کشتیرانی «${data.name}» ثبت شد.`)};
 const addVessel=async()=>{const name=clean(newVessel);if(!name)return setStatus('نام کشتی را وارد کنید.');const imo=clean(newIMO).replace(/\D/g,'');if(imo&&!/^\d{7}$/.test(imo))return setStatus('IMO باید ۷ رقم باشد.');setBusy(true);const{data,error}=await supabase.from('vessels').insert({organization_id:profile?.organization_id,name,imo_number:imo||null,shipping_line_id:lineId||null}).select('id,name,imo_number,shipping_line_id').single();setBusy(false);if(error)return setStatus(error.message);setVessels(p=>[...p,data as Vessel].sort((a,b)=>a.name.localeCompare(b.name)));setNewVessel('');setNewIMO('');setStatus(`کشتی «${name}» ثبت شد.`)};
 const transfer=async(v:Vessel)=>{if(!moveTo||moveTo===v.shipping_line_id)return setStatus('کشتیرانی مقصد را انتخاب کنید.');const{error}=await supabase.from('vessels').update({shipping_line_id:moveTo}).eq('id',v.id).eq('organization_id',profile?.organization_id||'');if(error)return setStatus(error.message);setMoveTo('');setStatus(`کشتی «${v.name}» منتقل شد.`);await loadVessels(lineId)};
 const removeVessel=async(v:Vessel)=>{const{count,error:check}=await supabase.from('shipments').select('id',{count:'exact',head:true}).eq('organization_id',profile?.organization_id||'').eq('vessel_id',v.id);if(check)return setStatus(check.message);if((count||0)>0)return setStatus('این کشتی در محموله ثبت‌شده استفاده شده و قابل حذف نیست.');if(!window.confirm(`کشتی «${v.name}» حذف شود؟`))return;const{error}=await supabase.from('vessels').delete().eq('id',v.id).eq('organization_id',profile?.organization_id||'');if(error)return setStatus(error.message);setStatus(`کشتی «${v.name}» حذف شد.`);await loadVessels(lineId)};
 const removeLine=async(l:Line)=>{if(!window.confirm(`کشتیرانی «${l.name}» حذف شود؟ کشتی‌های آن بدون کشتیرانی باقی می‌مانند.`))return;const{error}=await supabase.from('shipping_lines').delete().eq('id',l.id).eq('organization_id',profile?.organization_id||'');if(error)return setStatus(error.message);if(lineId===l.id)setLineId('');setStatus(`کشتیرانی «${l.name}» حذف شد.`);await loadLines();await loadVessels(lineId===l.id?'':lineId)};
 return <main dir="rtl" className="p-3 md:p-5"><div className="max-w-6xl mx-auto space-y-4"><header className="flex items-center justify-between"><div><div className="text-[10px] app-muted">SETTINGS / SHIPPING</div><h1 className="text-xl font-black flex items-center gap-2"><Ship size={20}/>مدیریت کشتیرانی و کشتی‌ها</h1><p className="text-xs app-muted mt-1">تعریف، انتقال و حذف کشتیرانی‌ها و کشتی‌ها فقط از این بخش انجام می‌شود.</p></div><button onClick={()=>nav('/settings')} className="px-3 py-2 rounded-lg border app-border text-xs"><ArrowLeft size={14} className="inline ml-1"/>تنظیمات</button></header>
 <section className="grid lg:grid-cols-[300px_1fr] gap-3">
  <div className="rounded-xl border app-border bg-[var(--surface)] p-3"><div className="flex items-center justify-between mb-2"><b className="text-sm">کشتیرانی‌ها</b><button onClick={loadLines} className="p-2 rounded-lg border app-border"><RefreshCw size={14}/></button></div><select value={lineId} onChange={e=>setLineId(e.target.value)} className="w-full min-h-10 rounded-lg border app-border bg-[var(--surface-2)] px-3 text-sm"><option value="">همه کشتی‌ها / بدون کشتیرانی</option>{lines.map(l=><option key={l.id} value={l.id}>{l.name}{l.name_fa?` — ${l.name_fa}`:''}</option>)}</select><div className="mt-3 space-y-2"><input value={newLine} onChange={e=>setNewLine(e.target.value)} placeholder="نام کشتیرانی جدید" className="w-full min-h-10 rounded-lg border app-border bg-[var(--surface-2)] px-3 text-sm"/><input value={newLineFa} onChange={e=>setNewLineFa(e.target.value)} placeholder="نام فارسی اختیاری" className="w-full min-h-10 rounded-lg border app-border bg-[var(--surface-2)] px-3 text-sm"/><button disabled={busy} onClick={addLine} className="w-full min-h-10 rounded-lg bg-[var(--primary)] text-white text-xs font-bold"><Plus size={14} className="inline ml-1"/>ثبت کشتیرانی</button></div><div className="mt-4 space-y-1">{lines.map(l=><div key={l.id} className={`flex items-center justify-between px-2 py-2 rounded-lg text-xs ${lineId===l.id?'bg-[var(--surface-2)]':''}`}><button onClick={()=>setLineId(l.id)} className="text-right truncate flex-1">{l.name}</button><button onClick={()=>removeLine(l)} className="p-1 text-red-400"><Trash2 size={13}/></button></div>)}</div></div>
  <div className="rounded-xl border app-border bg-[var(--surface)] p-3"><div className="flex items-center justify-between mb-3"><div><b className="text-sm">{selectedLine?`کشتی‌های ${selectedLine.name}`:'کشتی‌های بدون کشتیرانی'}</b><div className="text-[11px] app-muted mt-1">{vessels.length} کشتی</div></div></div><div className="grid md:grid-cols-[1fr_160px_auto] gap-2 mb-3"><input value={newVessel} onChange={e=>setNewVessel(e.target.value)} placeholder="نام کشتی جدید" className="min-h-10 rounded-lg border app-border bg-[var(--surface-2)] px-3 text-sm"/><input value={newIMO} onChange={e=>setNewIMO(e.target.value)} placeholder="IMO اختیاری" dir="ltr" className="min-h-10 rounded-lg border app-border bg-[var(--surface-2)] px-3 text-sm"/><button disabled={busy} onClick={addVessel} className="min-h-10 px-4 rounded-lg bg-emerald-600 text-white text-xs font-bold"><Plus size={14} className="inline ml-1"/>ثبت کشتی</button></div><div className="space-y-1">{vessels.map(v=><div key={v.id} className="grid md:grid-cols-[1fr_170px_auto_auto] items-center gap-2 rounded-lg border app-border px-3 py-2"><div className="text-sm font-semibold truncate">{v.name}<span className="block text-[10px] app-muted" dir="ltr">{v.imo_number||'IMO ثبت نشده'}</span></div><select value={moveTo} onChange={e=>setMoveTo(e.target.value)} className="min-h-8 rounded-lg border app-border bg-[var(--surface-2)] px-2 text-[11px]"><option value="">انتقال به...</option>{lines.filter(l=>l.id!==v.shipping_line_id).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><button onClick={()=>transfer(v)} className="min-h-8 px-2 rounded-lg border app-border text-[11px]"><Move size={13} className="inline ml-1"/>انتقال</button><button onClick={()=>removeVessel(v)} className="p-2 text-red-400"><Trash2 size={14}/></button></div>)}{!vessels.length&&<div className="py-10 text-center text-xs app-muted">کشتی‌ای در این فهرست نیست.</div>}</div></div>
 </section>{status&&<div className="text-xs px-3 py-2 rounded-lg border app-border bg-[var(--surface)]">{status}</div>}</div></main>;
};
export default ShippingManagementPage;
