import React,{useState} from 'react';
import {MapContainer,TileLayer,Marker,Popup,useMap} from 'react-leaflet';
import L from 'leaflet';
import {Search,Ship,RefreshCw,MapPin,Database,CheckCircle2,AlertTriangle} from 'lucide-react';
import 'leaflet/dist/leaflet.css';
import {supabase} from '../lib/supabase';

type Source={source:string;url:string;ok:boolean;name?:string|null;mmsi?:string|null;imo?:string|null;lat?:number|null;lon?:number|null;positionAt?:string|null;speed?:number|null;course?:number|null;region?:string|null;error?:string};
type Result={imo:string;mmsi?:string|null;name?:string|null;sources:Source[];selected?:{lat:number;lon:number;sourceCount:number;sourceNames:string[];confidence:string}|null;checkedAt:string};
const icon=L.divIcon({className:'',html:'<div style="width:18px;height:18px;border-radius:50%;background:#22d3ee;border:3px solid white;box-shadow:0 0 0 4px rgba(34,211,238,.25),0 0 20px rgba(34,211,238,.9)"></div>',iconSize:[18,18],iconAnchor:[9,9]});
const Fly=({p}:{p:[number,number]})=>{const m=useMap();React.useEffect(()=>{m.flyTo(p,8,{duration:1.2})},[m,p]);return null};
const ago=(v?:string|null)=>{if(!v)return 'نامشخص';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('fa-IR')};

export const VesselMultiSourcePage:React.FC=()=>{
 const[imo,setImo]=useState('8860028');const[result,setResult]=useState<Result|null>(null);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 const search=async()=>{const x=imo.replace(/\D/g,'');setImo(x);if(!/^\d{7}$/.test(x)){setMsg('IMO باید دقیقاً ۷ رقم باشد.');return}setBusy(true);setMsg('در حال دریافت و تطبیق اطلاعات از چند منبع...');try{const{data,error}=await supabase.functions.invoke('vessel-multi-source',{body:{imo:x}});if(error)throw error;if(data?.error)throw new Error(data.error);setResult(data as Result);setMsg(`${data?.sources?.filter((s:Source)=>s.ok).length||0} منبع پاسخ دادند · ${data?.selected?.sourceCount||0} منبع مختصات قابل استفاده داشتند.`)}catch(e:any){setResult(null);setMsg(e?.message||'خطا در جستجو')}finally{setBusy(false)}};
 const pos=result?.selected?[result.selected.lat,result.selected.lon] as [number,number]:null;
 return <main dir="rtl" className="min-h-screen bg-[var(--background)] text-[var(--text)] p-4 md:p-6"><div className="max-w-7xl mx-auto">
  <header className="mb-5"><div className="text-[10px] app-muted">VESSEL INTELLIGENCE / MULTI-SOURCE</div><h1 className="text-2xl font-black mt-1">رهگیری کشتی با IMO</h1><p className="text-xs app-muted mt-1">جستجوی همزمان چند منبع عمومی AIS و نمایش آخرین موقعیت قابل اتکا، حتی اگر قدیمی باشد.</p></header>
  <section className="rounded-2xl border app-border bg-[var(--surface)] p-4 mb-3"><div className="flex flex-col sm:flex-row gap-2"><div className="flex-1"><label className="text-[10px] app-muted">IMO NUMBER</label><input dir="ltr" inputMode="numeric" maxLength={7} value={imo} onChange={e=>setImo(e.target.value.replace(/\D/g,'').slice(0,7))} onKeyDown={e=>{if(e.key==='Enter')search()}} className="w-full min-h-11 mt-1 rounded-xl border app-border bg-[var(--surface-2)] px-3 text-sm outline-none" placeholder="8860028"/></div><button onClick={search} disabled={busy||imo.length!==7} className="sm:mt-5 min-h-11 px-6 rounded-xl bg-cyan-400 text-slate-950 font-bold text-sm disabled:opacity-50"><Search size={15} className="inline ml-1"/>{busy?'در حال جستجو...':'جستجوی کشتی'}</button></div>{msg&&<div className="mt-3 text-xs app-muted">{msg}</div>}</section>
  {result&&<><section className="grid md:grid-cols-4 gap-2 mb-3">{[['نام کشتی',result.name||'—'],['IMO',result.imo],['MMSI',result.mmsi||'—'],['بررسی در',ago(result.checkedAt)]].map(([a,b])=><div key={a} className="rounded-xl border app-border bg-[var(--surface)] p-3"><div className="text-[10px] app-muted">{a}</div><b className="block mt-1 text-sm" dir={a==='IMO'||a==='MMSI'?'ltr':'rtl'}>{b}</b></div>)}</section>
  <section className="grid lg:grid-cols-[1.1fr_.9fr] gap-3 mb-3"><div className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex items-center justify-between mb-3"><div><div className="text-[10px] app-muted">POSITION RECONCILIATION</div><h2 className="font-bold mt-1">آخرین موقعیت قابل نمایش</h2></div><MapPin className="text-cyan-300"/></div>{pos?<><div className="rounded-xl bg-[var(--surface-2)] p-3 mb-3"><div className="text-xs">مختصات انتخاب‌شده</div><b dir="ltr" className="text-lg">{pos[0].toFixed(5)}, {pos[1].toFixed(5)}</b><div className="text-[10px] app-muted mt-1">{result.selected?.confidence==='cross-source'?`تطبیق‌شده از ${result.selected.sourceCount} منبع`:'فقط یک منبع مختصات دقیق قابل استخراج داشت؛ تاریخ را حتماً بررسی کنید.'}</div></div><div className="h-[390px] rounded-xl overflow-hidden border app-border"><MapContainer center={pos} zoom={8} className="h-full w-full"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Fly p={pos}/><Marker position={pos} icon={icon}><Popup><b>{result.name||'Vessel'}</b><br/>IMO {result.imo}<br/>{pos[0].toFixed(5)}, {pos[1].toFixed(5)}</Popup></Marker></MapContainer></div></>:<div className="py-12 text-center app-muted text-sm">هیچ مختصات قابل استخراج از منابع عمومی پیدا نشد.</div>}</div>
  <div className="rounded-2xl border app-border bg-[var(--surface)] p-4"><div className="flex items-center gap-2 mb-3"><Database size={18} className="text-cyan-300"/><div><div className="text-[10px] app-muted">SOURCE COMPARISON</div><h2 className="font-bold">تطبیق منابع</h2></div></div><div className="space-y-2">{result.sources.map(s=><div key={s.source} className="rounded-xl border app-border bg-[var(--surface-2)] p-3"><div className="flex items-center justify-between gap-2"><b className="text-sm">{s.source}</b>{s.ok?<CheckCircle2 size={16} className="text-emerald-400"/>:<AlertTriangle size={16} className="text-amber-400"/>}</div>{s.ok?<><div className="text-[10px] app-muted mt-2">نام: {s.name||result.name||'—'} · MMSI: {s.mmsi||result.mmsi||'—'}</div><div className="text-[10px] mt-1">{s.lat!=null&&s.lon!=null?<><span dir="ltr">{s.lat.toFixed(5)}, {s.lon.toFixed(5)}</span> · دریافت: {ago(s.positionAt)}</>:<>مختصات دقیق در خروجی عمومی این منبع در دسترس نبود{ s.region?` · ناحیه: ${s.region}`:''}</>}</div>{(s.speed!=null||s.course!=null)&&<div className="text-[10px] app-muted mt-1">سرعت: {s.speed??'—'} kn · کورس: {s.course??'—'}°</div>}</>:<div className="text-[10px] app-muted mt-2">منبع در این لحظه قابل دریافت نبود.</div>}<a href={s.url} target="_blank" rel="noreferrer" className="block text-[10px] text-cyan-300 mt-2 truncate">مشاهده منبع ↗</a></div>)}</div></div></section>
  <div className="rounded-xl border app-border bg-[var(--surface)] p-3 text-[10px] app-muted">⚠️ موقعیت AIS ممکن است قدیمی باشد. Customs OS تاریخ/زمان آخرین دریافت را کنار موقعیت نگه می‌دارد و هرگز موقعیت قدیمی را به‌عنوان «زنده» برچسب نمی‌زند.</div></>}
  {!result&&<div className="rounded-2xl border app-border bg-[var(--surface)] p-8 text-center app-muted"><Ship size={30} className="mx-auto mb-2 text-cyan-300"/><div className="font-bold">مثلاً IMO 8860028</div><div className="text-xs mt-1">برای RASHA 1 جستجو را اجرا کنید.</div></div>}
 </div></main>;
};
