import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,ExternalLink,MapPinned,RefreshCw,Ship} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';

type Vessel={id:string;name:string;imo_number:string|null;flag_code:string|null;last_latitude:number|null;last_longitude:number|null;last_position_at:string|null;last_position_source:string|null;last_speed_knots:number|null;last_course_deg:number|null};
const n=(v:any)=>v==null||v===''?'—':new Intl.NumberFormat('fa-IR').format(Number(v));
export const VesselTrackingPage:React.FC=()=>{
 const [rows,setRows]=useState<Vessel[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const {data,error}=await supabase.from('vessels').select('id,name,imo_number,flag_code,last_latitude,last_longitude,last_position_at,last_position_source,last_speed_knots,last_course_deg').order('last_position_at',{ascending:false}).order('name');if(error)throw error;setRows((data||[]) as Vessel[]);if(!selected&&data?.[0])setSelected(data[0].id)}catch(e:any){setError(e?.message||'دریافت اطلاعات کشتی ناموفق بود')}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const vessel=useMemo(()=>rows.find(x=>x.id===selected)||rows[0], [rows,selected]);
 const hasPos=Number.isFinite(vessel?.last_latitude)&&Number.isFinite(vessel?.last_longitude);
 const lat=Number(vessel?.last_latitude),lon=Number(vessel?.last_longitude);
 const bbox=hasPos?`${lon-0.8},${lat-0.5},${lon+0.8},${lat+0.5}`:'';
 const mapUrl=hasPos?`https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(bbox)}&layer=mapnik&marker=${lat},${lon}`:'';
 const external=hasPos?`https://www.google.com/maps/search/?api=1&query=${lat},${lon}`:'';
 return <main dir="rtl" className="min-h-screen bg-slate-950 text-slate-100 p-5 md:p-8"><div className="max-w-[1500px] mx-auto"><header className="flex flex-wrap items-center justify-between gap-3 mb-6"><div><div className="text-xs text-cyan-400 mb-2">CUSTOMS OS / AIS</div><h1 className="text-2xl md:text-3xl font-black flex items-center gap-2"><MapPinned className="text-cyan-400"/> موقعیت کشتی</h1><p className="text-sm text-slate-500 mt-2">نمایش مختصات آخرین موقعیت ذخیره‌شده؛ بدون iframe سرویس AIS خارجی که در Firefox محدود شود.</p></div><div className="flex gap-2"><button onClick={load} className="px-3 py-2 rounded-xl border border-slate-700 bg-slate-900"><RefreshCw size={16} className={busy?'animate-spin':''}/></button><Link to="/" className="px-4 py-2 rounded-xl border border-slate-700 bg-slate-900">صفحه اصلی <ArrowRight className="inline mr-2" size={16}/></Link></div></header>
 {error&&<div className="mb-5 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300">{error}</div>}
 <div className="grid lg:grid-cols-[360px_1fr] gap-5"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-bold mb-4 flex items-center gap-2"><Ship size={18} className="text-cyan-400"/> کشتی‌ها</h2><select value={vessel?.id||''} onChange={e=>setSelected(e.target.value)} className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 mb-5"><option value="">انتخاب کشتی</option>{rows.map(v=><option key={v.id} value={v.id}>{v.name}{v.imo_number?` — IMO ${v.imo_number}`:''}</option>)}</select>{vessel?<div className="space-y-3 text-sm"><div className="text-xl font-black">{vessel.name}</div><div className="grid grid-cols-2 gap-2"><div className="rounded-xl bg-slate-950 p-3"><span className="text-xs text-slate-500">IMO</span><div dir="ltr">{vessel.imo_number||'—'}</div></div><div className="rounded-xl bg-slate-950 p-3"><span className="text-xs text-slate-500">پرچم</span><div>{vessel.flag_code||'—'}</div></div><div className="rounded-xl bg-slate-950 p-3"><span className="text-xs text-slate-500">Latitude</span><div dir="ltr">{hasPos?lat:'—'}</div></div><div className="rounded-xl bg-slate-950 p-3"><span className="text-xs text-slate-500">Longitude</span><div dir="ltr">{hasPos?lon:'—'}</div></div><div className="rounded-xl bg-slate-950 p-3"><span className="text-xs text-slate-500">سرعت</span><div>{n(vessel.last_speed_knots)} kn</div></div><div className="rounded-xl bg-slate-950 p-3"><span className="text-xs text-slate-500">Course</span><div>{n(vessel.last_course_deg)}°</div></div></div>{vessel.last_position_at&&<div className="text-xs text-slate-500">آخرین موقعیت: {new Date(vessel.last_position_at).toLocaleString('fa-IR')} · منبع: {vessel.last_position_source||'—'}</div>}{hasPos&&<a href={external} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-cyan-600 hover:bg-cyan-500 font-bold text-sm">باز کردن مختصات در نقشه <ExternalLink size={15}/></a>}</div>:<div className="text-sm text-slate-500">هیچ کشتی‌ای ثبت نشده است.</div>}</section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-3 min-h-[600px]">{hasPos?<iframe title="OpenStreetMap vessel position" src={mapUrl} className="w-full h-[580px] rounded-xl border border-slate-800" loading="lazy"/>:<div className="h-[580px] flex flex-col items-center justify-center text-center text-slate-500"><MapPinned size={42} className="mb-3 text-slate-600"/><b className="text-slate-300">مختصات AIS موجود نیست</b><p className="text-sm mt-2 max-w-md">برای نمایش موقعیت واقعی باید latitude/longitude کشتی در Master Data یا منبع AIS وارد شود. این صفحه عمداً از سرویس خارجی AIS داخل iframe استفاده نمی‌کند.</p></div>}</section></div></div></main>;
};
