-- Customs OS AI Core v2
create extension if not exists pgcrypto;
create table if not exists public.ai_interactions (id uuid primary key default gen_random_uuid(),organization_id uuid not null,user_id uuid,shipment_id uuid,case_id uuid,session_id text,mode text not null default 'chat',query text not null,answer text,provider text,model text,latency_ms integer,status text not null default 'completed',created_at timestamptz not null default now());
create table if not exists public.ai_evidence (id uuid primary key default gen_random_uuid(),organization_id uuid not null,interaction_id uuid references public.ai_interactions(id) on delete cascade,shipment_id uuid,document_id uuid,field_key text,extracted_value text,source_text text,page_number integer,confidence numeric(5,4),verification_status text not null default 'unverified',extraction_method text,created_at timestamptz not null default now());
create table if not exists public.ai_knowledge_documents (id uuid primary key default gen_random_uuid(),organization_id uuid,title text not null,source_type text not null default 'internal',source_uri text,version text,content text,metadata jsonb not null default '{}'::jsonb,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ai_action_proposals (id uuid primary key default gen_random_uuid(),organization_id uuid not null,interaction_id uuid references public.ai_interactions(id) on delete set null,shipment_id uuid,case_id uuid,action_type text not null,payload jsonb not null default '{}'::jsonb,evidence_ids uuid[] not null default '{}',risk_level text not null default 'low',status text not null default 'proposed',created_by uuid,executed_by uuid,executed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.ai_risk_findings (id uuid primary key default gen_random_uuid(),organization_id uuid not null,interaction_id uuid references public.ai_interactions(id) on delete set null,shipment_id uuid,case_id uuid,risk_type text not null,severity text not null default 'medium',title text not null,details text,evidence jsonb not null default '[]'::jsonb,status text not null default 'open',created_at timestamptz not null default now());
create index if not exists ai_interactions_org_created_idx on public.ai_interactions(organization_id,created_at desc);
create index if not exists ai_evidence_shipment_field_idx on public.ai_evidence(shipment_id,field_key);
create index if not exists ai_knowledge_documents_org_idx on public.ai_knowledge_documents(organization_id,active);
create index if not exists ai_action_proposals_org_status_idx on public.ai_action_proposals(organization_id,status);
create index if not exists ai_risk_findings_shipment_status_idx on public.ai_risk_findings(shipment_id,status);
alter table public.ai_interactions enable row level security; alter table public.ai_evidence enable row level security; alter table public.ai_knowledge_documents enable row level security; alter table public.ai_action_proposals enable row level security; alter table public.ai_risk_findings enable row level security;
drop policy if exists ai_interactions_org on public.ai_interactions; create policy ai_interactions_org on public.ai_interactions for all using (organization_id=public.user_org_id()) with check (organization_id=public.user_org_id());
drop policy if exists ai_evidence_org on public.ai_evidence; create policy ai_evidence_org on public.ai_evidence for all using (organization_id=public.user_org_id()) with check (organization_id=public.user_org_id());
drop policy if exists ai_knowledge_documents_org on public.ai_knowledge_documents; create policy ai_knowledge_documents_org on public.ai_knowledge_documents for all using (organization_id=public.user_org_id()) with check (organization_id=public.user_org_id());
drop policy if exists ai_action_proposals_org on public.ai_action_proposals; create policy ai_action_proposals_org on public.ai_action_proposals for all using (organization_id=public.user_org_id()) with check (organization_id=public.user_org_id());
drop policy if exists ai_risk_findings_org on public.ai_risk_findings; create policy ai_risk_findings_org on public.ai_risk_findings for all using (organization_id=public.user_org_id()) with check (organization_id=public.user_org_id());
create or replace function public.ai_find_knowledge(search_text text,org_id uuid,max_rows integer default 6)
returns table(id uuid,title text,content text,metadata jsonb) language sql stable security invoker as $$
select d.id,d.title,d.content,d.metadata from public.ai_knowledge_documents d where d.active and d.organization_id=org_id and (coalesce(search_text,'')='' or d.title ilike '%'||search_text||'%' or coalesce(d.content,'') ilike '%'||search_text||'%') order by d.updated_at desc limit greatest(1,least(max_rows,20));
$$;