import React,{useEffect,useRef,useState} from 'react';
import {Download,ExternalLink,Loader2,X,ZoomIn,ZoomOut} from 'lucide-react';
import {getDocument,GlobalWorkerOptions,PDFDocumentProxy} from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
GlobalWorkerOptions.workerSrc=workerUrl;
// Multi-page PDF viewer; integrated into CustomsDocumentManagerPage by the temporary workflow.
export default function PdfDocumentViewer({url,name,onClose,onDownload}:{url:string;name:string;onClose:()=>void;onDownload:()=>void}){
 const host=useRef<HTMLDivElement>(null);const[pdf,setPdf]=useState<PDFDocumentProxy|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[scale,setScale]=useState(1.05);
 useEffect(()=>{let alive=true;let loaded:PDFDocumentProxy|undefined;setLoading(true);setError('');(async()=>{try{const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.arrayBuffer();loaded=await getDocument({data}).promise;if(alive)setPdf(loaded);else void loaded.destroy()}catch(e:any){if(alive)setError(e?.message||'خطا در خواندن PDF')}})();return()=>{alive=false;if(loaded)void loaded.destroy()};},[url]);
 useEffect(()=>{if(!pdf||!host.current)return;let cancelled=false;const render=async()=>{const root=host.current!;root.innerHTML='';for(let n=1;n<=pdf.numPages;n++){if(cancelled)break;const page=await pdf.getPage(n);const viewport=page.getViewport({scale});const wrap=document.createElement('div');wrap.className='relative mb-4 flex justify-center';const canvas=document.createElement('canvas');canvas.className='max-w-full h-auto shadow-lg bg-white';canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);wrap.appendChild(canvas);const badge=document.createElement('span');badge.className='absolute top-2 left-2 rounded-md bg-black/65 text-white text-[11px] px-2 py-1';badge.textContent=`صفحه ${n} از ${pdf.numPages}`;wrap.appendChild(badge);root.appendChild(wrap);await page.render({canvasContext:canvas.getContext('2d')!,viewport}).promise}};void render();return()=>{cancelled=true}},[pdf,scale]);
 return <div className="fixed inset-0 z-[100] bg-black/80 flex flex-col" dir="rtl"><header className="h-14 shrink-0 bg-[var(--surface)] border-b app-border flex items-center gap-2 px-3"><div className="min-w-0 flex-1"><b className="block truncate text-sm">{name}</b><span className="text-[10px] app-muted">{pdf?`${pdf.numPages} صفحه`:''}</span></div><button className="icon-btn" title="کوچک‌نمایی" onClick={()=>setScale(s=>Math.max(.65,s-.15))}><ZoomOut size={17}/></button><button className="icon-btn" title="بزرگ‌نمایی" onClick={()=>setScale(s=>Math.min(2.2,s+.15))}><ZoomIn size={17}/></button><button className="icon-btn" title="دانلود" onClick={onDownload}><Download size={17}/></button><a className="icon-btn" title="بازکردن در تب جدید" href={url} target="_blank" rel="noreferrer"><ExternalLink size={17}/></a><button className="icon-btn" title="بستن" onClick={onClose}><X size={18}/></button></header><div className="flex-1 overflow-auto p-4 bg-neutral-800"><div ref={host} className="mx-auto max-w-5xl"/>{loading&&!pdf&&!error&&<div className="h-32 grid place-items-center text-white"><Loader2 className="animate-spin"/></div>}{error&&<div className="max-w-xl mx-auto rounded-xl bg-red-500/15 border border-red-400/30 text-white p-4">پیش‌نمایش PDF ناموفق بود: {error}</div>}</div></div>;
}
