// Deployed Edge Function: send-chat-push (verify_jwt=false; protected by Vault cron secret).
// Runtime source is deployed to Supabase project bjngfgiecvihofemptub.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "jsr:@supabase/supabase-js@2";
import {sendPushNotification,rawPayload,WebPushError} from "npm:@mmmike/web-push@1.3.0/send";
const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json"}});
const secret=async(name:string)=>{const {data,error}=await admin.rpc("internal_get_reminder_secret",{p_name:name});if(error)throw error;return data as string|null};
async function main(){const {data,error}=await admin.rpc("claim_chat_notification_outbox",{p_limit:100});if(error)throw error;const rows:any[]=data??[];if(!rows.length)return{claimed:0,sent:0};const pub=await secret("reminder_vapid_public"),priv=await secret("reminder_vapid_private"),subject=await secret("reminder_vapid_subject")??"mailto:admin@darbandicommercial.ir";if(!pub||!priv)throw new Error("VAPID keys are not configured");let sent=0;const groups=new Map<string,any[]>();for(const r of rows){const k=r.user_id+":"+r.conversation_id;groups.set(k,[...(groups.get(k)??[]),r])}for(const [k,list] of groups){const [userId,conversationId]=k.split(":");const {data:member}=await admin.from("chat_conversation_members").select("muted_until").eq("user_id",userId).eq("conversation_id",conversationId).is("deleted_at",null).is("left_at",null).maybeSingle();if(member?.muted_until&&new Date(member.muted_until)>new Date()){await admin.from("notification_outbox").update({next_attempt_at:member.muted_until,last_error:"conversation_muted"}).in("id",list.map(x=>x.id));continue}const {data:pref}=await admin.from("notification_preferences").select("quiet_start,quiet_end,hide_content,timezone").eq("user_id",userId).maybeSingle();const {data:subs}=await admin.from("push_subscriptions").select("id,endpoint,p256dh,auth").eq("user_id",userId).eq("is_active",true);if(!subs?.length){await admin.from("notification_outbox").update({next_attempt_at:new Date(Date.now()+900000).toISOString(),last_error:"no_active_device"}).in("id",list.map(x=>x.id));continue}const latest=list[list.length-1]||list[0];const payload={title:pref?.hide_content?"پیام جدید":latest?.title||"پیام جدید",body:pref?.hide_content?"پیام جدیدی برای شما ثبت شده است.":latest?.body||"پیام جدید",tag:"chat-"+conversationId,url:latest?.url||"/chat?conversation="+conversationId,data:{conversationId,messageId:latest?.message_id,senderName:latest?.title||""},dir:"rtl",lang:"fa"};let ok=false;for(const sub of subs){try{await sendPushNotification({endpoint:sub.endpoint,keys:{p256dh:sub.p256dh,auth:sub.auth}},rawPayload(JSON.stringify(payload)),{publicKey:pub,privateKey:priv,subject},{ttl:86400,urgency:"high"});ok=true;sent++;await admin.from("push_subscriptions").update({last_success_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),failure_count:0}).eq("id",sub.id)}catch(e){if(e instanceof WebPushError&&(e.statusCode===404||e.statusCode===410))await admin.from("push_subscriptions").delete().eq("id",sub.id)}}if(ok)await admin.from("notification_outbox").update({sent_at:new Date().toISOString(),next_attempt_at:null,last_error:null}).in("id",list.map(x=>x.id))}return{claimed:rows.length,sent}}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const expected=await secret("chat_push_cron_secret");if(!expected||req.headers.get("x-chat-push-cron-secret")!==expected)return json({error:"unauthorized"},401);try{return json({ok:true,...await main()})}catch(e){return json({ok:false,error:e instanceof Error?e.message:"failed"},500)}});