begin;
drop policy if exists chat_files_delete on storage.objects;
drop policy if exists chat_files_update on storage.objects;
drop policy if exists chat_files_select on storage.objects;
drop policy if exists chat_files_insert on storage.objects;

drop trigger if exists trg_chat_messages_audit on public.chat_messages;
drop trigger if exists trg_chat_message_outbox on public.chat_messages;
drop trigger if exists trg_chat_receipts_status on public.chat_message_receipts;
drop trigger if exists trg_chat_messages_mutation on public.chat_messages;
drop trigger if exists trg_chat_messages_guest on public.chat_messages;
drop trigger if exists trg_chat_conversations_touch on public.chat_conversations;
drop trigger if exists trg_chat_members_touch on public.chat_conversation_members;
drop trigger if exists trg_chat_conversations_guest on public.chat_conversations;
drop trigger if exists trg_chat_members_guest on public.chat_conversation_members;
drop trigger if exists trg_chat_states_guest on public.chat_message_user_states;
drop trigger if exists trg_chat_reactions_guest on public.chat_message_reactions;
drop trigger if exists trg_chat_mentions_guest on public.chat_message_mentions;
drop trigger if exists trg_chat_pins_guest on public.chat_message_pins;
drop trigger if exists trg_chat_receipts_guest on public.chat_message_receipts;
drop trigger if exists trg_chat_attachments_guest on public.chat_attachments;
drop trigger if exists trg_file_scans_guest on public.file_scans;
drop trigger if exists trg_notification_outbox_guest on public.notification_outbox;
drop trigger if exists trg_chat_focus_guest on public.chat_user_focus;

drop table if exists public.notification_outbox;
drop table if exists public.file_scans;
drop table if exists public.chat_attachments;
drop table if exists public.chat_message_receipts;
drop table if exists public.chat_message_pins;
drop table if exists public.chat_message_mentions;
drop table if exists public.chat_message_reactions;
drop table if exists public.chat_message_user_states;
drop table if exists public.chat_messages;
drop table if exists public.chat_conversation_members;
drop table if exists public.chat_conversations;
drop table if exists public.chat_user_focus;

drop function if exists public.chat_storage_path_allowed(text,boolean);
drop function if exists public.chat_enqueue_message_notifications();
drop function if exists public.chat_sync_delivery_status();
drop function if exists public.chat_guard_message_mutation();
drop function if exists public.touch_chat_updated_at();
drop function if exists public.chat_toggle_pin(uuid);
drop function if exists public.chat_search(text,uuid,integer);
drop function if exists public.chat_conversation_list(integer);
drop function if exists public.chat_unread_count(uuid);
drop function if exists public.chat_first_unread(uuid);
drop function if exists public.chat_list_messages(uuid,timestamptz,uuid,integer);
drop function if exists public.chat_register_attachment(uuid,uuid,text,text,text,bigint,numeric,jsonb,text);
drop function if exists public.chat_clear_focus();
drop function if exists public.chat_mark_focus(uuid);
drop function if exists public.chat_toggle_reaction(uuid,text);
drop function if exists public.chat_toggle_star(uuid);
drop function if exists public.chat_delete_message_for_all(uuid);
drop function if exists public.chat_delete_message_for_me(uuid);
drop function if exists public.chat_mark_delivered(uuid);
drop function if exists public.chat_mark_read(uuid,uuid);
drop function if exists public.chat_insert_message(uuid,uuid,text,text,uuid,uuid,uuid);
drop function if exists public.chat_add_member(uuid,uuid,text);
drop function if exists public.chat_create_conversation(text,text,text,uuid,uuid,uuid);
drop function if exists public.chat_connection_allowed_for_conversation(uuid,uuid);
drop function if exists public.chat_can_manage(uuid);
drop function if exists public.chat_user_is_member(uuid,uuid);
drop function if exists public.chat_normalize_text(text);
commit;