import React from 'react';
import {BrowserRouter,Routes,Route,Navigate,useSearchParams,useLocation} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {AuthProvider,UserRole,useAuth} from './context/AuthContext';
import {AppearanceProvider} from './context/AppearanceContext';
import {ProtectedRoute} from './components/ProtectedRoute';
import {AppShell} from './components/AppShell';
import {SettingsPersistenceBridge} from './components/SettingsPersistenceBridge';
import {LoginPage} from './pages/LoginPage';import {OnboardingPage} from './pages/OnboardingPage';import {MainMenuPage} from './pages/MainMenuPage';import {DesktopHomePage} from './pages/DesktopHomePage';import {ClientRegistryPage} from './pages/ClientRegistryPage';import {MaritimePage} from './pages/MaritimePage';import {VesselSearchPage} from './pages/VesselSearchPage';import {DeclarationPrintPage} from './pages/DeclarationPrintPage';import {DeclarationChecklistPage} from './pages/DeclarationChecklistPage';import {ShipmentFirstPage} from './pages/ShipmentFirstPage';import {PreDeclarationPage} from './pages/PreDeclarationPage';import {PermitRulesPage} from './pages/PermitRulesPage';import {FinancePage} from './pages/FinancePage';import {ExitPage} from './pages/ExitPage';import {CaseHistoryPage} from './pages/CaseHistoryPage';import {CaseStagePage} from './pages/CaseStagePage';import {DocumentExtractionPage} from './pages/DocumentExtractionPage';import {SettingsEnterprisePage} from './pages/SettingsEnterprisePage';import {RemindersPage} from './pages/RemindersPage';import {KnowledgeCenterV2Page} from './pages/KnowledgeCenterV2Page';import {CustomsDocumentManagerPage} from './pages/CustomsDocumentManagerPage';import {ValuationPage} from './pages/ValuationPage';import {DutiesCalculationPage} from './pages/DutiesCalculationPage';import {CaseOperationsPage} from './pages/CaseOperationsPage';import {CaseAlertsPage} from './pages/CaseAlertsPage';import {ControlCenterWithAlertsPage} from './pages/ControlCenterWithAlertsPage';import {ShipmentCaseLinkPage} from './pages/ShipmentCaseLinkPage';import {CaseDocumentManagementPage} from './pages/CaseDocumentManagementPage';
const queryClient=new QueryClient({defaultOptions:{queries:{staleTime:30000,refetchOnWindowFocus:false,retry:1}}});
const operationalRoles:UserRole[]=['owner','admin','broker','warehouse','client'];const staffRoles:UserRole[]=['owner','admin','broker','accountant','warehouse'];const managementRoles:UserRole[]=['owner','admin','broker'];const financeRoles:UserRole[]=['owner','admin','accountant'];
const adminSettings=new Set(['organization','users','roles','integrations','webhooks','storage','backup','audit','advanced']);
function OperationsRoute(){const[params]=useSearchParams();const{profile}=useAuth();const tab=params.get('tab');if(profile?.role==='client'&&!['pre-declaration','case'].includes(tab||''))return <Navigate to="/operations?tab=pre-declaration" replace/>;if(tab==='case')return <CaseOperationsPage/>;if(tab==='pre-declaration')return <PreDeclarationPage/>;if(tab==='declaration')return <DeclarationChecklistPage/>;if(tab==='valuation')return <ValuationPage/>;if(tab==='duties')return <DutiesCalculationPage/>;if(tab==='exit')return <ExitPage/>;return <ShipmentFirstPage/>;}
function SettingsRoute(){const{profile}=useAuth();const loc=useLocation();const slug=loc.pathname.replace('/settings','').replace(/^\//,'').split('/')[0];if(adminSettings.has(slug)&&!['owner','admin'].includes(profile?.role||''))return <Navigate to="/settings" replace/>;if(slug==='shipping'&&!['owner','admin','broker'].includes(profile?.role||''))return <Navigate to="/settings" replace/>;return <SettingsEnterprisePage/>;}
function App(){return <QueryClientProvider client={queryClient}><AuthProvider><AppearanceProvider><SettingsPersistenceBridge/><BrowserRouter><AppShell><Routes><Route path="/login" element={<LoginPage/>}/><Route path="/onboarding" element={<OnboardingPage/>}/><Route path="/" element={<ProtectedRoute><DesktopHomePage/></ProtectedRoute>}/><Route path="/legacy-dashboard" element={<ProtectedRoute allowedRoles={managementRoles}><MainMenuPage/></ProtectedRoute>}/><Route path="/clients" element={<ProtectedRoute allowedRoles={managementRoles}><ClientRegistryPage/></ProtectedRoute>}/><Route path="/maritime" element={<ProtectedRoute allowedRoles={managementRoles}><MaritimePage/></ProtectedRoute>}/><Route path="/vessel-search" element={<ProtectedRoute allowedRoles={staffRoles}><VesselSearchPage/></ProtectedRoute>}/><Route path="/reminders" element={<ProtectedRoute><RemindersPage/></ProtectedRoute>}/><Route path="/alerts" element={<ProtectedRoute allowedRoles={operationalRoles}><CaseAlertsPage/></ProtectedRoute>}/><Route path="/operations" element={<ProtectedRoute allowedRoles={operationalRoles}><OperationsRoute/></ProtectedRoute>}/><Route path="/permit-rules" element={<ProtectedRoute allowedRoles={managementRoles}><PermitRulesPage/></ProtectedRoute>}/><Route path="/finance" element={<ProtectedRoute allowedRoles={financeRoles}><FinancePage/></ProtectedRoute>}/><Route path="/exit" element={<ProtectedRoute allowedRoles={['owner','admin','broker','warehouse']}><ExitPage/></ProtectedRoute>}/><Route path="/control" element={<ProtectedRoute allowedRoles={managementRoles}><ControlCenterWithAlertsPage/></ProtectedRoute>}/><Route path="/shipment-case-link" element={<ProtectedRoute allowedRoles={managementRoles}><ShipmentCaseLinkPage/></ProtectedRoute>}/><Route path="/case-documents" element={<ProtectedRoute allowedRoles={operationalRoles}><CaseDocumentManagementPage/></ProtectedRoute>}/><Route path="/history" element={<ProtectedRoute allowedRoles={staffRoles}><CaseHistoryPage/></ProtectedRoute>}/><Route path="/stage" element={<ProtectedRoute allowedRoles={managementRoles}><CaseStagePage/></ProtectedRoute>}/><Route path="/print-declaration" element={<ProtectedRoute allowedRoles={managementRoles}><DeclarationPrintPage/></ProtectedRoute>}/><Route path="/documents/extract" element={<ProtectedRoute allowedRoles={operationalRoles}><DocumentExtractionPage/></ProtectedRoute>}/><Route path="/documents" element={<ProtectedRoute allowedRoles={operationalRoles}><CustomsDocumentManagerPage/></ProtectedRoute>}/><Route path="/knowledge" element={<ProtectedRoute allowedRoles={managementRoles}><KnowledgeCenterV2Page/></ProtectedRoute>}/><Route path="/settings/*" element={<ProtectedRoute><SettingsRoute/></ProtectedRoute>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></AppShell></BrowserRouter></AppearanceProvider></AuthProvider></QueryClientProvider>}
export default App;
